#! /bin/sh
# --------------------------------------------------------------------------
# bootstrapping utility for autotools -> now just uses autreconf
# -------------------------------------------------------------------------- 

cmd="autoreconf -f -i"
echo "Bootstrapping using $cmd ..."

$cmd


