queso-0.50.0: QUESO::BaseTKGroup< V, M > Class Template Reference
QUESO::BaseTKGroup< V, M > Class Template Reference abstract
This base class allows the representation of a transition kernel.
#include <TKGroup.h>
Public Member Functions
Constructor/Destructor methods
BaseTKGroup ()
Default constructor.
BaseTKGroup (const char *prefix, const VectorSpace< V, M > &vectorSpace, const std::vector< double > &scales)
Constructor.
virtual ~BaseTKGroup ()
Destructor.
Statistical/Mathematical methods
virtual bool symmetric () const =0
Whether or not the matrix is symmetric. See template specialization.
virtual const GaussianVectorRV
< V, M > & rv (unsigned int stageId)=0
Gaussian increment property to construct a transition kernel. See template specialization.
virtual const GaussianVectorRV
< V, M > & rv (const std::vector< unsigned int > &stageIds)=0
Gaussian increment property to construct a transition kernel. See template specialization.
Misc methods
const BaseEnvironment & env () const
QUESO's environment.
const V & preComputingPosition (unsigned int stageId) const
Pre-computing position; access to protected attribute *m_preComputingPositions[stageId].
virtual bool setPreComputingPosition (const V &position, unsigned int stageId)
Sets the pre-computing positions m_preComputingPositions[stageId] with a new vector of size position.
virtual void clearPreComputingPositions ()
Clears the pre-computing positions m_preComputingPositions[stageId].
I/O methods
virtual void print (std::ostream &os) const
TODO: Prints the transition kernel.
Protected Attributes
const EmptyEnvironment * m_emptyEnv
const BaseEnvironment & m_env
std::string m_prefix
const VectorSpace< V, M > * m_vectorSpace
std::vector< double > m_scales
std::vector< const V * > m_preComputingPositions
std::vector< GaussianVectorRV
< V, M > * > m_rvs
Detailed Description
template<class V, class M>
class QUESO::BaseTKGroup< V, M >
This base class allows the representation of a transition kernel.
The transition kernel is a conditional distribution function that represents the probability of moving from a point to a point in the set , where is a Borel set over . Since it is a distribution function, , where it is permitted that the chain can make a transition from the point to , that is is not necessarily zero.
Definition at line 48 of file TKGroup.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::BaseTKGroup< V, M >::BaseTKGroup ()
Default constructor.
Definition at line 33 of file TKGroup.C.
   :
   m_emptyEnv             (new EmptyEnvironment()),
   m_env                  (*m_emptyEnv),
   m_prefix               (""),
   m_vectorSpace          (NULL),
   m_scales               (0),
   m_preComputingPositions(NULL),
   m_rvs                  (0)
 {
 }
template<class V, class M> QUESO::BaseTKGroup< V, M >::BaseTKGroup (const char * prefix, const VectorSpace< V, M > & vectorSpace, const std::vector< double > & scales)
Constructor.
Definition at line 46 of file TKGroup.C.
References QUESO::BaseTKGroup< V, M >::m_scales.
   :
   m_emptyEnv             (NULL),
   m_env                  (vectorSpace.env()),
   m_prefix               (prefix),
   m_vectorSpace          (&vectorSpace),
   m_scales               (scales.size(),1.),
   m_preComputingPositions(scales.size()+1,NULL), // Yes, +1
   m_rvs                  (scales.size(),NULL) // IMPORTANT: it stays like this for scaledTK, but it will be overwritten to '+1' by hessianTK constructor
 {
   for (unsigned int i = 0; i < m_scales.size(); ++i) {
     m_scales[i] = scales[i];
   }
 }
template<class V , class M > QUESO::BaseTKGroup< V, M >::~BaseTKGroup () virtual
Destructor.
Definition at line 65 of file TKGroup.C.
 {
   for (unsigned int i = 0; i < m_rvs.size(); ++i) {
     if (m_rvs[i]) delete m_rvs[i];
   }
   for (unsigned int i = 0; i < m_preComputingPositions.size(); ++i) {
     if (m_preComputingPositions[i]) delete m_preComputingPositions[i];
   }
   if (m_emptyEnv) delete m_emptyEnv;
 }
Member Function Documentation
template<class V , class M > void QUESO::BaseTKGroup< V, M >::clearPreComputingPositions () virtual
Clears the pre-computing positions m_preComputingPositions[stageId].
Reimplemented in QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
Definition at line 121 of file TKGroup.C.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::clearPreComputingPositions(), and QUESO::ScaledCovMatrixTKGroup< V, M >::clearPreComputingPositions().
 {
   for (unsigned int i = 0; i < m_preComputingPositions.size(); ++i) {
     if (m_preComputingPositions[i]) {
       delete m_preComputingPositions[i];
       m_preComputingPositions[i] = NULL;
     }
   }
   return;
 }
template<class V , class M > const BaseEnvironment & QUESO::BaseTKGroup< V, M >::env () const
QUESO's environment.
Definition at line 78 of file TKGroup.C.
 {
   return m_env;
 }
template<class V , class M > const V & QUESO::BaseTKGroup< V, M >::preComputingPosition (unsigned int stageId) const
Pre-computing position; access to protected attribute *m_preComputingPositions[stageId].
Definition at line 85 of file TKGroup.C.
References UQ_FATAL_TEST_MACRO.
 {
   UQ_FATAL_TEST_MACRO(m_preComputingPositions.size() <= stageId,
                       m_env.worldRank(),
                       "BaseTKGroup<V,M>::preComputingPosition()",
                       "m_preComputingPositions.size() <= stageId");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions[stageId] == NULL,
                       m_env.worldRank(),
                       "BaseTKGroup<V,M>::preComputingPosition()",
                       "m_preComputingPositions[stageId] == NULL");
   return *m_preComputingPositions[stageId];
 }
template<class V , class M > void QUESO::BaseTKGroup< V, M >::print (std::ostream & os) const virtual
TODO: Prints the transition kernel.
Todo:
: implement me!
Reimplemented in QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
Definition at line 135 of file TKGroup.C.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::print(), and QUESO::ScaledCovMatrixTKGroup< V, M >::print().
 {
   os << "In BaseTKGroup<V,M>::print()"
      << ": nothing to be printed" << std::endl;
   return;
 }
template<class V, class M> virtual const GaussianVectorRV<V,M>& QUESO::BaseTKGroup< V, M >::rv (unsigned int stageId) pure virtual
Gaussian increment property to construct a transition kernel. See template specialization.
Implemented in QUESO::HessianCovMatricesTKGroup< V, M >, and QUESO::ScaledCovMatrixTKGroup< V, M >.
template<class V, class M> virtual const GaussianVectorRV<V,M>& QUESO::BaseTKGroup< V, M >::rv (const std::vector< unsigned int > & stageIds) pure virtual
Gaussian increment property to construct a transition kernel. See template specialization.
Implemented in QUESO::HessianCovMatricesTKGroup< V, M >, and QUESO::ScaledCovMatrixTKGroup< V, M >.
template<class V, class M > bool QUESO::BaseTKGroup< V, M >::setPreComputingPosition (const V & position, unsigned int stageId) virtual
Sets the pre-computing positions m_preComputingPositions[stageId] with a new vector of size position.
Reimplemented in QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
Definition at line 102 of file TKGroup.C.
References UQ_FATAL_TEST_MACRO.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::setPreComputingPosition(), and QUESO::ScaledCovMatrixTKGroup< V, M >::setPreComputingPosition().
 {
   UQ_FATAL_TEST_MACRO(m_preComputingPositions.size() <= stageId,
                       m_env.worldRank(),
                       "BaseTKGroup<V,M>::setPreComputingPosition()",
                       "m_preComputingPositions.size() <= stageId");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions[stageId] != NULL,
                       m_env.worldRank(),
                       "BaseTKGroup<V,M>::setPreComputingPosition()",
                       "m_preComputingPositions[stageId] != NULL");
   m_preComputingPositions[stageId] = new V(position);
   return true;
 }
template<class V, class M> virtual bool QUESO::BaseTKGroup< V, M >::symmetric () const pure virtual
Whether or not the matrix is symmetric. See template specialization.
Implemented in QUESO::HessianCovMatricesTKGroup< V, M >, and QUESO::ScaledCovMatrixTKGroup< V, M >.
Member Data Documentation
template<class V, class M> const EmptyEnvironment* QUESO::BaseTKGroup< V, M >::m_emptyEnv protected
Definition at line 97 of file TKGroup.h.
template<class V, class M> const BaseEnvironment& QUESO::BaseTKGroup< V, M >::m_env protected
Definition at line 98 of file TKGroup.h.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), and QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup().
template<class V, class M> std::vector<const V*> QUESO::BaseTKGroup< V, M >::m_preComputingPositions protected
Definition at line 102 of file TKGroup.h.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), and QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup().
template<class V, class M> std::string QUESO::BaseTKGroup< V, M >::m_prefix protected
Definition at line 99 of file TKGroup.h.
template<class V, class M> std::vector<GaussianVectorRV<V,M>* > QUESO::BaseTKGroup< V, M >::m_rvs protected
Definition at line 103 of file TKGroup.h.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), and QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup().
template<class V, class M> std::vector<double> QUESO::BaseTKGroup< V, M >::m_scales protected
Definition at line 101 of file TKGroup.h.
Referenced by QUESO::BaseTKGroup< V, M >::BaseTKGroup(), QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), and QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup().
template<class V, class M> const VectorSpace<V,M>* QUESO::BaseTKGroup< V, M >::m_vectorSpace protected
Definition at line 100 of file TKGroup.h.
The documentation for this class was generated from the following files:
src/stats/inc/TKGroup.h
src/stats/src/TKGroup.C