queso-0.50.0: QUESO::WignerVectorRV< V, M > Class Template Reference
QUESO::WignerVectorRV< V, M > Class Template Reference
A class representing a vector RV constructed via Wigner distribution.
#include <WignerVectorRV.h>
Public Member Functions
Constructor/Destructor methods
WignerVectorRV (const char *prefix, const VectorSet< V, M > &imageSet, const V &centerPos, double radius)
Default Constructor.
virtual ~WignerVectorRV ()
Virtual destructor.
I/O methods
void print (std::ostream &os) const
TODO: Prints the vector RV.
Public Member Functions inherited from QUESO::BaseVectorRV< V, M >
BaseVectorRV (const char *prefix, const VectorSet< V, M > &imageSet)
Constructor.
virtual ~BaseVectorRV ()
Virtual destructor.
const BaseEnvironment & env () const
QUESO environment; access to private attribute m_env.
const VectorSet< V, M > & imageSet () const
Image set of the vector RV; access to private attribute m_imageSet.
const BaseJointPdf< V, M > & pdf () const
Posterior Density Function of the vector RV; access to private attribute m_pdf.
const BaseVectorRealizer< V, M > & realizer () const
Finds a realization (sample) of the PDF of this vector RV; access to private attribute m_realizer.
const BaseVectorCdf< V, M > & subCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering only the sub-sequence of data; access to private attribute m_subCdf.
const BaseVectorCdf< V, M > & unifiedCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering the unified sequence of data; access to private attribute m_unifiedCdf.
const BaseVectorMdf< V, M > & mdf () const
Finds the Mass Density Function of this vector RV; access to private attribute m_mdf.
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseVectorRV< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_imageSet
BaseJointPdf< V, M > * m_pdf
BaseVectorRealizer< V, M > * m_realizer
const BaseVectorCdf< V, M > * m_subCdf
const BaseVectorCdf< V, M > * m_unifiedCdf
const BaseVectorMdf< V, M > * m_mdf
Detailed Description
template<class V, class M>
class QUESO::WignerVectorRV< V, M >
A class representing a vector RV constructed via Wigner distribution.
This class allows the user to compute the value of a Wigner PDF and to generate realizations (samples) from it.
Todo:
: WignerVectorRealizer.realization() is not yet available, thus this class does nothing.
Definition at line 54 of file WignerVectorRV.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::WignerVectorRV< V, M >::WignerVectorRV (const char * prefix, const VectorSet< V, M > & imageSet, const V & centerPos, double radius)
Default Constructor.
Definition at line 33 of file WignerVectorRV.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRV< V, M >::m_env, QUESO::BaseVectorRV< V, M >::m_imageSet, QUESO::BaseVectorRV< V, M >::m_mdf, QUESO::BaseVectorRV< V, M >::m_pdf, QUESO::BaseVectorRV< V, M >::m_prefix, QUESO::BaseVectorRV< V, M >::m_realizer, QUESO::BaseVectorRV< V, M >::m_subCdf, QUESO::BaseVectorRV< V, M >::m_unifiedCdf, QUESO::BaseEnvironment::subDisplayFile(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   BaseVectorRV<V,M>(((std::string)(prefix)+"uni").c_str(),imageSet)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering WignerVectorRV<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   UQ_FATAL_TEST_MACRO(radius <= 0.,
                       m_env.worldRank(),
                       "WignerVectorRV<V,M>::constructor()",
                       "invalid radius");
   m_pdf        = new WignerJointPdf<V,M>(m_prefix.c_str(),
                                                 m_imageSet,
                                                 centerPos,
                                                 radius);
   m_realizer   = new WignerVectorRealizer<V,M>(m_prefix.c_str(),
                                                       m_imageSet,
                                                       centerPos,
                                                       radius);
   m_subCdf     = NULL; // FIX ME: complete code
   m_unifiedCdf = NULL; // FIX ME: complete code
   m_mdf        = NULL; // FIX ME: complete code
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving WignerVectorRV<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::WignerVectorRV< V, M >::~WignerVectorRV () virtual
Virtual destructor.
Definition at line 72 of file WignerVectorRV.C.
 {
   delete m_mdf;
   delete m_unifiedCdf;
   delete m_subCdf;
   delete m_realizer;
   delete m_pdf;
 }
Member Function Documentation
template<class V , class M > void QUESO::WignerVectorRV< V, M >::print (std::ostream & os) const virtual
TODO: Prints the vector RV.
Todo:
: implement me!
Implements QUESO::BaseVectorRV< V, M >.
Definition at line 83 of file WignerVectorRV.C.
 {
   os << "WignerVectorRV<V,M>::print() says, 'Please implement me.'" << std::endl;
   return;
 }
The documentation for this class was generated from the following files:
src/stats/inc/WignerVectorRV.h
src/stats/src/WignerVectorRV.C