queso-0.55.0: QUESO::OperatorBase Class Reference
QUESO::OperatorBase Class Reference abstract
Abstract base class for operator objects. Operators are assumed to be symmetric and positive-definite.
#include <OperatorBase.h>
Public Member Functions
virtual double get_eigenvalue (unsigned int i) const =0
Return eigenvalue i.
virtual double get_inverted_eigenvalue (unsigned int i) const =0
Return the reciprocal of eigenvalue i.
virtual unsigned int get_num_converged () const =0
Return the number of converged eigenpairs.
virtual boost::shared_ptr
< FunctionBase > inverse_kl_transform (std::vector< double > &xi, double alpha) const =0
Given coefficients xi, computes the Karhunen-Loeve transform.
Constructor/Destructor methods
OperatorBase ()
Constructor.
virtual ~OperatorBase ()
Destructor.
Detailed Description
Abstract base class for operator objects. Operators are assumed to be symmetric and positive-definite.
Definition at line 45 of file OperatorBase.h.
Constructor & Destructor Documentation
QUESO::OperatorBase::OperatorBase ()
Constructor.
Definition at line 30 of file OperatorBase.C.
 {
 }
QUESO::OperatorBase::~OperatorBase () virtual
Destructor.
Definition at line 34 of file OperatorBase.C.
 {
 }
Member Function Documentation
virtual double QUESO::OperatorBase::get_eigenvalue (unsigned int i) const pure virtual
Return eigenvalue i.
You can store them however you want, but having some kind of order to them is useful for InfiniteDimensionalMeasure
Referenced by QUESO::InfiniteDimensionalGaussian::get_kl_coefficient().
virtual double QUESO::OperatorBase::get_inverted_eigenvalue (unsigned int i) const pure virtual
Return the reciprocal of eigenvalue i.
virtual unsigned int QUESO::OperatorBase::get_num_converged () const pure virtual
Return the number of converged eigenpairs.
Referenced by QUESO::InfiniteDimensionalGaussian::draw(), and QUESO::InfiniteDimensionalGaussian::InfiniteDimensionalGaussian().
virtual boost::shared_ptr<FunctionBase> QUESO::OperatorBase::inverse_kl_transform (std::vector< double > & xi, double alpha) const pure virtual
Given coefficients xi, computes the Karhunen-Loeve transform.
This transform goes from coefficient space to physical space using this as the precision operator: / pow(, alpha / 2.0) (x) where the lambda are eigenvalues of the precision operator, this, and the (x) are eigenfunctions of the precision operator, this
Referenced by QUESO::InfiniteDimensionalGaussian::draw().
The documentation for this class was generated from the following files:
src/core/inc/OperatorBase.h
src/core/src/OperatorBase.C