queso-0.57.1: QUESO::ArrayOfSequences< V, M > Class Template Reference
QUESO::ArrayOfSequences< V, M > Class Template Reference
Class for handling array samples (arrays of scalar sequences).
#include <ArrayOfSequences.h>
Public Member Functions
Constructor/Destructor methods
ArrayOfSequences (const VectorSpace< V, M > &vectorSpace, unsigned int subSequenceSize, const std::string &name)
Default constructor.
~ArrayOfSequences ()
Destructor.
Sequence methods
unsigned int subSequenceSize () const
Size of the sub-sequence of arrays.
void resizeSequence (unsigned int newSubSequenceSize)
Resizes the sequence.
void resetValues (unsigned int initialPos, unsigned int numPos)
Resets a total of numPos values of the sequence starting at position initialPos.
void erasePositions (unsigned int initialPos, unsigned int numPos)
Erases numPos elements of the sequence starting at position initialPos.
void getPositionValues (unsigned int posId, V &vec) const
Gets the values of the sequence at position posId and stores them at vec.
void setPositionValues (unsigned int posId, const V &vec)
Set the values of vec at position posId of the sequence.
void setGaussian (const V &meanVec, const V &stdDevVec)
Sets the values of the sequence as a Gaussian distribution of mean given by meanVec and standard deviation by stdDevVec.
void setUniform (const V &aVec, const V &bVec)
Sets the values of the sequence as a uniform distribution between the values given by vectors aVec and bVec.
void mean (unsigned int initialPos, unsigned int numPos, V &meanVec) const
Finds the mean value of the sub-sequence, considering numPos positions starting at position initialPos.
void unifiedMean (unsigned int initialPos, unsigned int numPos, V &unifiedMeanVec) const
Finds the mean value of the unified sequence of numPos positions starting at position initialPos. See template specialization.
void sampleVariance (unsigned int initialPos, unsigned int numPos, const V &meanVec, V &samVec) const
Finds the sample variance of the sub-sequence, considering numPos positions starting at position initialPos and of mean meanVec.
void unifiedSampleVariance (unsigned int initialPos, unsigned int numPos, const V &meanVec, V &samVec) const
Finds the sample variance of the unified sequence, considering numPos positions starting at position initialPos and of mean meanVec.
void populationVariance (unsigned int initialPos, unsigned int numPos, const V &meanVec, V &popVec) const
Finds the population variance of the sub-sequence, considering numPos positions starting at position initialPos and of mean meanVec.
void autoCovariance (unsigned int initialPos, unsigned int numPos, const V &meanVec, unsigned int lag, V &covVec) const
Calculates the autocovariance.
void autoCorrViaDef (unsigned int initialPos, unsigned int numPos, unsigned int lag, V &corrVec) const
Calculates autocorrelation via definition.
void autoCorrViaFft (unsigned int initialPos, unsigned int numPos, const std::vector< unsigned int > &lags, std::vector< V * > &corrVecs) const
void autoCorrViaFft (unsigned int initialPos, unsigned int numPos, unsigned int numSum, V &autoCorrsSumVec) const
void minMax (unsigned int initialPos, V &minVec, V &maxVec) const
Given an initial position initialPos, finds the minimum and the maximum values of the sequence.
void histogram (unsigned int initialPos, const V &minVec, const V &maxVec, std::vector< V * > &centersForAllBins, std::vector< V * > &quanttsForAllBins) const
Calculates the histogram of the sequence.
void interQuantileRange (unsigned int initialPos, V &iqrs) const
Returns the interquartile range of the values in the sequence.
void scalesForKDE (unsigned int initialPos, const V &iqrs, unsigned int kdeDimension, V &scales) const
Selects the scales (bandwidth, scaleVec) for the kernel density estimation, of the sequence.
void gaussianKDE (const V &evaluationParamVec, V &densityVec) const
Gaussian kernel for the KDE estimate of the sequence.
void gaussianKDE (unsigned int initialPos, const V &scales, const std::vector< V * > &evaluationParamVecs, std::vector< V * > &densityVecs) const
TODO: Gaussian kernel for the KDE of the sequence.
void writeContents (std::ofstream &ofsvar) const
Write contents of the chain to a file.
void unifiedWriteContents (std::ofstream &ofsvar) const
Writes info of the unified sequence to a file.
void unifiedWriteContents (const std::string &fileName, const std::string &fileType) const
Writes info of the unified sequence to a file.
void unifiedReadContents (const std::string &fileName, const std::string &fileType, const unsigned int subSequenceSize)
Reads the unified sequence from a file.
void select (const std::vector< unsigned int > &idsOfUniquePositions)
Select positions in the sequence of vectors.
void filter (unsigned int initialPos, unsigned int spacing)
Filters positions in the sequence of vectors, starting at initialPos, and with spacing given by spacing.
void extractScalarSeq (unsigned int initialPos, unsigned int spacing, unsigned int numPos, unsigned int paramId, ScalarSequence< double > &scalarSeq) const
Extracts a sequence of scalars of size numPos, from position paramId of the array of sequences.
void uniformlySampledMdf (const V &numEvaluationPointsVec, ArrayOfOneDGrids< V, M > &mdfGrids, ArrayOfOneDTables< V, M > &mdfValues) const
void uniformlySampledCdf (const V &numEvaluationPointsVec, ArrayOfOneDGrids< V, M > &cdfGrids, ArrayOfOneDTables< V, M > &cdfValues) const
void bmm (unsigned int initialPos, unsigned int batchLength, V &bmmVec) const
void fftForward (unsigned int initialPos, unsigned int fftSize, unsigned int paramId, std::vector< std::complex< double > > &resultData) const
void psd (unsigned int initialPos, unsigned int numBlocks, double hopSizeRatio, unsigned int paramId, std::vector< double > &psdResult) const
void psdAtZero (unsigned int initialPos, unsigned int numBlocks, double hopSizeRatio, V &psdVec) const
void geweke (unsigned int initialPos, double ratioNa, double ratioNb, V &gewVec) const
Public Member Functions inherited from QUESO::BaseVectorSequence< V, M >
BaseVectorSequence (const VectorSpace< V, M > &vectorSpace, unsigned int subSequenceSize, const std::string &name)
Default constructor.
virtual ~BaseVectorSequence ()
Destructor.
unsigned int unifiedSequenceSize () const
Calculates the size of the unified sequence of vectors.
unsigned int vectorSizeLocal () const
Local dimension (size) of the vector space.
unsigned int vectorSizeGlobal () const
Global dimension (size) of the vector space.
const VectorSpace< V, M > & vectorSpace () const
Vector space; access to protected attribute VectorSpace<V,M>& m_vectorSpace.
const std::string & name () const
Access to protected attribute m_name: name of the sequence of vectors.
void setName (const std::string &newName)
Changes the name of the sequence of vectors.
void clear ()
Reset the values and the size of the sequence of vectors.
const V & subMinPlain () const
Finds the minimum value of the sub-sequence.
const V & unifiedMinPlain () const
Finds the minimum value of the unified sequence.
const V & subMaxPlain () const
Finds the maximum value of the sub-sequence.
const V & unifiedMaxPlain () const
Finds the maximum value of the unified sequence.
const V & subMeanPlain () const
Finds the mean value of the sub-sequence.
const V & unifiedMeanPlain () const
Finds the mean value of the unified sequence.
const V & subMedianPlain () const
Finds the median value of the sub-sequence.
const V & unifiedMedianPlain () const
Finds the median value of the unified sequence.
const V & subSampleVariancePlain () const
Finds the variance of a sample of the sub-sequence.
const V & unifiedSampleVariancePlain () const
Finds the variance of a sample of the unified sequence.
const BoxSubset< V, M > & subBoxPlain () const
Finds a box subset of the sub-sequence (given by its min and max values calculated via subMinPlain and subMaxPlain).
const BoxSubset< V, M > & unifiedBoxPlain () const
Finds a box subset of the unified-sequence (given by the min and max values of the unified sequence calculated via unifiedMinPlain and unifiedMaxPlain).
void deleteStoredVectors ()
Deletes all the stored vectors.
void append (const BaseVectorSequence< V, M > &src, unsigned int initialPos, unsigned int numPos)
Appends the vector src to this vector.
double subPositionsOfMaximum (const ScalarSequence< double > &subCorrespondingScalarValues, BaseVectorSequence< V, M > &subPositionsOfMaximum)
Finds the positions where the maximum element occurs in the sub-sequence.
double unifiedPositionsOfMaximum (const ScalarSequence< double > &subCorrespondingScalarValues, BaseVectorSequence< V, M > &unifiedPositionsOfMaximum)
Finds the positions where the maximum element occurs in the unified sequence.
void setGaussian (const V &meanVec, const V &stdDevVec)
Sets the values of the sequence as a Gaussian distribution of mean given by meanVec and standard deviation by stdDevVec.
void setUniform (const V &aVec, const V &bVec)
Sets the values of the sequence as a uniform distribution between the values given by vectors aVec and bVec.
virtual void subMeanExtra (unsigned int initialPos, unsigned int numPos, V &meanVec) const =0
Finds the mean value of the sub-sequence, considering numPos positions starting at position initialPos. See template specialization.
virtual void unifiedMeanExtra (unsigned int initialPos, unsigned int numPos, V &unifiedMeanVec) const =0
Finds the mean value of the unified sequence of numPos positions starting at position initialPos. See template specialization.
virtual void subMedianExtra (unsigned int initialPos, unsigned int numPos, V &medianVec) const =0
Finds the median value of the sub-sequence, considering numPos positions starting at position initialPos. See template specialization.
virtual void unifiedMedianExtra (unsigned int initialPos, unsigned int localNumPos, V &unifiedMedianVec) const =0
Finds the median value of the unified sequence, considering numPos positions starting at position initialPos. See template specialization.
virtual void subSampleVarianceExtra (unsigned int initialPos, unsigned int numPos, const V &meanVec, V &samVec) const =0
Finds the sample variance of the sub-sequence, considering numPos positions starting at position initialPos and of mean meanVec. See template specialization.
virtual void unifiedSampleVarianceExtra (unsigned int initialPos, unsigned int numPos, const V &unifiedMeanVec, V &unifiedSamVec) const =0
Finds the sample variance of the unified sequence, considering numPos positions starting at position initialPos and of mean meanVec. See template specialization.
virtual void subPopulationVariance (unsigned int initialPos, unsigned int numPos, const V &meanVec, V &popVec) const =0
Finds the population variance of the sub-sequence, considering numPos positions starting at position initialPos and of mean meanVec. See template specialization.
virtual void unifiedPopulationVariance (unsigned int initialPos, unsigned int numPos, const V &unifiedMeanVec, V &unifiedPopVec) const =0
Finds the population variance of the unified-sequence, considering numPos positions starting at position initialPos and of mean meanVec. See template specialization.
virtual void subMinMaxExtra (unsigned int initialPos, unsigned int numPos, V &minVec, V &maxVec) const =0
Finds the minimum and the maximum values of the sub-sequence, considering numPos positions starting at position initialPos. See template specialization.
virtual void unifiedMinMaxExtra (unsigned int initialPos, unsigned int numPos, V &unifiedMinVec, V &unifiedMaxVec) const =0
Finds the minimum and the maximum values of the unified sequence, considering numPos positions starting at position initialPos. See template specialization.
virtual void subHistogram (unsigned int initialPos, const V &minVec, const V &maxVec, std::vector< V * > &centersForAllBins, std::vector< V * > &quanttsForAllBins) const =0
Calculates the histogram of the sub-sequence. See template specialization.
virtual void unifiedHistogram (unsigned int initialPos, const V &unifiedMinVec, const V &unifiedMaxVec, std::vector< V * > &unifiedCentersForAllBins, std::vector< V * > &unifiedQuanttsForAllBins) const =0
Calculates the histogram of the unified sequence. See template specialization.
virtual void subInterQuantileRange (unsigned int initialPos, V &iqrVec) const =0
Returns the interquartile range of the values in the sub-sequence. See template specialization.
virtual void unifiedInterQuantileRange (unsigned int initialPos, V &unifiedIqrVec) const =0
Returns the interquartile range of the values in the unified sequence. See template specialization.
virtual void subScalesForKde (unsigned int initialPos, const V &iqrVec, unsigned int kdeDimension, V &scaleVec) const =0
Selects the scales (bandwidth, scaleVec) for the kernel density estimation, considering only the sub-sequence. See template specialization.
virtual void unifiedScalesForKde (unsigned int initialPos, const V &unifiedIqrVec, unsigned int kdeDimension, V &unifiedScaleVec) const =0
Selects the scales (bandwidth) for the kernel density estimation, considering the unified sequence. See template specialization.
virtual void subGaussian1dKde (unsigned int initialPos, const V &scaleVec, const std::vector< V * > &evaluationParamVecs, std::vector< V * > &densityVecs) const =0
Gaussian kernel for the KDE estimate of the sub-sequence. See template specialization.
virtual void unifiedGaussian1dKde (unsigned int initialPos, const V &unifiedScaleVec, const std::vector< V * > &unifiedEvaluationParamVecs, std::vector< V * > &unifiedDensityVecs) const =0
Gaussian kernel for the KDE estimate of the unified sequence. See template specialization.
virtual void subWriteContents (unsigned int initialPos, unsigned int numPos, const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds) const =0
Writes info of the sub-sequence to a file. See template specialization.
virtual void subWriteContents (unsigned int initialPos, unsigned int numPos, std::ofstream &ofsvar, const std::string &fileType) const =0
Writes info of the sub-sequence to a file. See template specialization.
void computeFilterParams (std::ofstream *passedOfs, unsigned int &initialPos, unsigned int &spacing)
Computes the filtering parameters spacing for the sequence of vectors.
virtual double estimateConvBrooksGelman (unsigned int initialPos, unsigned int numPos) const =0
Estimates convergence rate using Brooks & Gelman method. See template specialization.
virtual void subUniformlySampledCdf (const V &numEvaluationPointsVec, ArrayOfOneDGrids< V, M > &cdfGrids, ArrayOfOneDTables< V, M > &cdfValues) const =0
virtual void unifiedUniformlySampledCdf (const V &numEvaluationPointsVec, ArrayOfOneDGrids< V, M > &unifiedCdfGrids, ArrayOfOneDTables< V, M > &unifieddfValues) const =0
virtual void meanStacc (unsigned int initialPos, V &meanStaccVec) const =0
virtual void subCdfStacc (unsigned int initialPos, const std::vector< V * > &evalPositionsVecs, std::vector< V * > &cdfStaccVecs) const =0
void computeHistCdfstaccKde (const SequenceStatisticalOptions &statisticalOptions, std::ofstream *passedOfs)
void computeStatistics (const SequenceStatisticalOptions &statisticalOptions, std::ofstream *passedOfs)
void computeHistCdfstaccKde (const SsOptionsValues &statisticalOptions, std::ofstream *passedOfs)
void computeStatistics (const SsOptionsValues &statisticalOptions, std::ofstream *passedOfs)
virtual void subUniformlySampledMdf (const V &numEvaluationPointsVec, ArrayOfOneDGrids< V, M > &mdfGrids, ArrayOfOneDTables< V, M > &mdfValues) const =0
Private Member Functions
void extractRawData (unsigned int initialPos, unsigned int spacing, unsigned int numPos, unsigned int paramId, std::vector< double > &rawData) const
Extracts the raw data.
Private Attributes
DistArray< ScalarSequence
< double > * > m_scalarSequences
Sequence of scalars.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseVectorSequence< V, M >
void copy (const BaseVectorSequence< V, M > &src)
Copies vector sequence src to this.
virtual void subMeanMonitorAlloc (unsigned int numberOfMonitorPositions)=0
virtual void subMeanInter0MonitorAlloc (unsigned int numberOfMonitorPositions)=0
virtual void unifiedMeanMonitorAlloc (unsigned int numberOfMonitorPositions)=0
virtual void subMeanMonitorRun (unsigned int monitorPosition, V &subMeanVec, V &subMeanCltStd)=0
virtual void subMeanInter0MonitorRun (unsigned int monitorPosition, V &subMeanInter0Mean, V &subMeanInter0Clt95, V &subMeanInter0Empirical90, V &subMeanInter0Min, V &subMeanInter0Max)=0
virtual void unifiedMeanMonitorRun (unsigned int monitorPosition, V &unifiedMeanVec, V &unifiedMeanCltStd)=0
virtual void subMeanMonitorStore (unsigned int i, unsigned int monitorPosition, const V &subMeanVec, const V &subMeanCltStd)=0
virtual void subMeanInter0MonitorStore (unsigned int i, unsigned int monitorPosition, const V &subMeanInter0Mean, const V &subMeanInter0Clt95, const V &subMeanInter0Empirical90, const V &subMeanInter0Min, const V &subMeanInter0Max)=0
virtual void unifiedMeanMonitorStore (unsigned int i, unsigned int monitorPosition, V &unifiedMeanVec, V &unifiedMeanCltStd)=0
virtual void subMeanMonitorWrite (std::ofstream &ofs)=0
virtual void subMeanInter0MonitorWrite (std::ofstream &ofs)=0
virtual void unifiedMeanMonitorWrite (std::ofstream &ofs)=0
virtual void subMeanMonitorFree ()=0
virtual void subMeanInter0MonitorFree ()=0
virtual void unifiedMeanMonitorFree ()=0
void computeMeanEvolution (const SequenceStatisticalOptions &statisticalOptions, std::ofstream *passedOfs)
void computeMeanEvolution (const SsOptionsValues &statisticalOptions, std::ofstream *passedOfs)
void computeBMM (const SequenceStatisticalOptions &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computeFFT (const SequenceStatisticalOptions &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computePSD (const SequenceStatisticalOptions &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computePSDAtZero (const SequenceStatisticalOptions &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computeGeweke (const SequenceStatisticalOptions &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computeMeanStacc (const SequenceStatisticalOptions &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computeBMM (const SsOptionsValues &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computeFFT (const SsOptionsValues &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computePSD (const SsOptionsValues &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computePSDAtZero (const SsOptionsValues &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computeGeweke (const SsOptionsValues &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computeMeanStacc (const SsOptionsValues &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, std::ofstream *passedOfs)
void computeMeanVars (const SequenceStatisticalOptions &statisticalOptions, std::ofstream *passedOfs, V *subMeanPtr, V *subMedianPtr, V *subSampleVarPtr, V *subPopulVarPtr)
void computeAutoCorrViaDef (const SequenceStatisticalOptions &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, const std::vector< unsigned int > &lagsForCorrs, std::ofstream *passedOfs)
void computeAutoCorrViaFFT (const SequenceStatisticalOptions &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, const std::vector< unsigned int > &lagsForCorrs, std::ofstream *passedOfs)
void computeCovCorrMatrices (const SequenceStatisticalOptions &statisticalOptions, std::ofstream *passedOfs)
void computeMeanVars (const SsOptionsValues &statisticalOptions, std::ofstream *passedOfs, V *subMeanPtr, V *subMedianPtr, V *subSampleVarPtr, V *subPopulVarPtr)
void computeAutoCorrViaDef (const SsOptionsValues &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, const std::vector< unsigned int > &lagsForCorrs, std::ofstream *passedOfs)
void computeAutoCorrViaFFT (const SsOptionsValues &statisticalOptions, const std::vector< unsigned int > &initialPosForStatistics, const std::vector< unsigned int > &lagsForCorrs, std::ofstream *passedOfs)
void computeCovCorrMatrices (const SsOptionsValues &statisticalOptions, std::ofstream *passedOfs)
Protected Attributes inherited from QUESO::BaseVectorSequence< V, M >
const BaseEnvironment & m_env
const VectorSpace< V, M > & m_vectorSpace
std::string m_name
Fft< double > * m_fftObj
V * m_subMinPlain
V * m_unifiedMinPlain
V * m_subMaxPlain
V * m_unifiedMaxPlain
V * m_subMeanPlain
V * m_unifiedMeanPlain
V * m_subMedianPlain
V * m_unifiedMedianPlain
V * m_subSampleVariancePlain
V * m_unifiedSampleVariancePlain
BoxSubset< V, M > * m_subBoxPlain
BoxSubset< V, M > * m_unifiedBoxPlain
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::ArrayOfSequences< V, M >
Class for handling array samples (arrays of scalar sequences).
This class handles array of sequences (samples) generated by an algorithm, as well as operations that can be carried over them, e.g., calculation of means, correlation and covariance matrices. It is derived from and implements BaseVectorSequence<V,M>.
Definition at line 47 of file ArrayOfSequences.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::ArrayOfSequences< V, M >::ArrayOfSequences (const VectorSpace< V, M > & vectorSpace, unsigned int subSequenceSize, const std::string & name)
Default constructor.
Definition at line 32 of file ArrayOfSequences.C.
References QUESO::BaseVectorSequence< V, M >::m_env, QUESO::ArrayOfSequences< V, M >::m_scalarSequences, and QUESO::ArrayOfSequences< V, M >::subSequenceSize().
     : BaseVectorSequence<V,M>(vectorSpace,subSequenceSize,name),
       m_scalarSequences(m_vectorSpace.map(),1)
 {
   //if (m_env.subDisplayFile()) {
   //  *m_env.subDisplayFile() << "Entering ArrayOfSequences<V,M>::constructor()"
   //                         << std::endl;
   //}
   //if (m_env.subDisplayFile()) {
   //  *m_env.subDisplayFile() << "In ArrayOfSequences<V,M>::constructor()"
   //                         << "\n subSequenceSize = "              << subSequenceSize
   //                         << "\n m_scalarSequences.MyLength() = " << m_scalarSequences.MyLength()
   //                         << std::endl;
   //}
   for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
     m_scalarSequences(i,0) = new ScalarSequence<double>(m_env,subSequenceSize);
   }
   //if (m_env.subDisplayFile()) {
   //  *m_env.subDisplayFile() << "Leaving ArrayOfSequences<V,M>::constructor()"
   //                         << std::endl;
   //}
 }
template<class V , class M > QUESO::ArrayOfSequences< V, M >::~ArrayOfSequences ()
Destructor.
Definition at line 63 of file ArrayOfSequences.C.
 {
   for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
     if (m_scalarSequences(i,0)) delete m_scalarSequences(i,0);
   }
 }
Member Function Documentation
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::autoCorrViaDef (unsigned int initialPos, unsigned int numPos, unsigned int lag, V & corrVec) const virtual
Calculates autocorrelation via definition.
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 310 of file ArrayOfSequences.C.
 {
   V subChainMean              (m_vectorSpace.zeroVector());
   V subChainAutoCovarianceLag0(m_vectorSpace.zeroVector());
   this->mean(initialPos,
              numPos,
              subChainMean);
   this->autoCovariance(initialPos,
                        numPos,
                        subChainMean,
                        0, // lag
                        subChainAutoCovarianceLag0);
   this->autoCovariance(initialPos,
                        numPos,
                        subChainMean,
                        lag,
                        corrVec);
   corrVec /= subChainAutoCovarianceLag0;
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::autoCorrViaFft (unsigned int initialPos, unsigned int numPos, const std::vector< unsigned int > & lags, std::vector< V * > & corrVecs) const virtual
Calculates autocorrelation via Fast Fourier transforms (FFT). TODO: Implement me!
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 338 of file ArrayOfSequences.C.
 {
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::autoCorrViaFft (unsigned int initialPos, unsigned int numPos, unsigned int numSum, V & autoCorrsSumVec) const virtual
Calculates autocorrelation via Fast Fourier transforms (FFT). TODO: Implement me!
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 347 of file ArrayOfSequences.C.
References QUESO::ScalarSequence< T >::autoCorrViaFft().
 {
 #if 0
   bool bRC = ((initialPos             <  this->subSequenceSize()) &&
               (0                      <  numPos                 ) &&
               ((initialPos+numPos)    <= this->subSequenceSize()) &&
               (autoCorrsSumVec.size() == this->vectorSize()     ));
   queso_require_msg(bRC, "invalid input data");
   ScalarSequence<double> data(m_env,0);
   unsigned int numParams = this->vectorSize();
   for (unsigned int i = 0; i < numParams; ++i) {
     this->extractScalarSeq(initialPos,
                            1, // spacing
                            numPos,
                            i,
                            data);
     data.autoCorrViaFft(0,
                         numPos,
                         autoCorrsSumVec[i]);
   }
 #endif
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::autoCovariance (unsigned int initialPos, unsigned int numPos, const V & meanVec, unsigned int lag, V & covVec) const virtual
Calculates the autocovariance.
The autocovariance is the covariance of a variable with itself at some other time. It is calculated over a sequence of arrays with initial position initialPos, considering numPos positions, a lag of lag, with mean given by meanVec. The results are saved in the output vector covVec/
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 268 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences.
 {
   bool bRC = ((0                     <= initialPos                 ) &&
               (0                     <  numPos                     ) &&
               ((initialPos+numPos-1) <= (this->subSequenceSize()-1)));
   queso_require_msg(bRC, "invalid initial position or number of positions");
   bRC = (numPos > lag);
   queso_require_msg(bRC, "lag is too large");
   bRC = (this->vectorSize() == covVec.size());
   queso_require_msg(bRC, "incompatible sizes between covVec vector and vectors in sequence");
   bRC = (this->vectorSize() == meanVec.size());
   queso_require_msg(bRC, "incompatible sizes between meanVec vector and vectors in sequence");
   unsigned int loopSize      = numPos - lag;
   unsigned int finalPosPlus1 = initialPos + loopSize;
   double doubleLoopSize = (double) loopSize;
   covVec.cwSet(0.);
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   for (unsigned int i = 0; i < covVec.size(); ++i) {
     const ScalarSequence<double>& seq = *(tmp->m_scalarSequences(i,0));
     double meanValue = meanVec[i];
     double result = 0;
     for (unsigned int j = initialPos; j < finalPosPlus1; ++j) {
       double diff1 = seq[j]     - meanValue;
       double diff2 = seq[j+lag] - meanValue;
       result += diff1*diff2;
     }
     covVec[i] = result/doubleLoopSize;
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::bmm (unsigned int initialPos, unsigned int batchLength, V & bmmVec) const virtual
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 678 of file ArrayOfSequences.C.
 {
 #if 0
   V meanOfBatchMeans   (*(sequence[0]));
   V covLag0OfBatchMeans(*(sequence[0]));
   V covLag1OfBatchMeans(*(sequence[0]));
   V tmpVector(m_vectorSpace.zeroVector()); // In order to contour the fact that 'batchMeans' is a vector of 'const V*', but needs to be set first
   for (unsigned int initialPosId = 0; initialPosId < initialPositions.size(); initialPosId++) {
     for (unsigned int batchLengthId = 0; batchLengthId < batchLengths.size(); batchLengthId++) {
       unsigned int batchLength = batchLengths[batchLengthId];
       unsigned int numberOfBatches = (sequence.size() - initialPositions[initialPosId])/batchLength;
       std::vector<const V* > batchMeans(numberOfBatches,NULL);
       for (unsigned int batchId = 0; batchId < numberOfBatches; batchId++) {
         VectorSequenceMean(sequence,
                              initialPositions[initialPosId] + batchId*batchLength,
                              batchLength,
                              tmpVector);
         batchMeans[batchId] = new V(tmpVector);
       }
       VectorSequenceMean(batchMeans,
                            0,
                            batchMeans.size(),
                            meanOfBatchMeans);
       VectorSequenceAutoCovariance(batchMeans,
                                      0,
                                      batchMeans.size(),
                                      meanOfBatchMeans,
                                      0, // lag
                                      covLag0OfBatchMeans);
       VectorSequenceAutoCovariance(batchMeans,
                                      0,
                                      batchMeans.size(),
                                      meanOfBatchMeans,
                                      1, // lag
                                      covLag0OfBatchMeans);
       VectorSequenceSampleVariance(batchMeans,
                                      0,
                                      batchMeans.size(),
                                      meanOfBatchMeans,
                                      _2dArrayOfBMM(initialPosId,batchLengthId));
       //_2dArrayOfBMM(initialPosId,batchLengthId) /= (double) batchMeans.size(); // CHECK
       _2dArrayOfBMM(initialPosId,batchLengthId) *= (double) (sequence.size() - initialPositions[initialPosId]); // CHECK
       for (unsigned int batchId = 0; batchId < numberOfBatches; batchId++) {
         if (batchMeans[batchId] != NULL) delete batchMeans[batchId];
       }
     }
   }
 #endif
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::erasePositions (unsigned int initialPos, unsigned int numPos) virtual
Erases numPos elements of the sequence starting at position initialPos.
This routine deletes all stored computed vectors
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 106 of file ArrayOfSequences.C.
References QUESO::BaseVectorSequence< V, M >::deleteStoredVectors(), and QUESO::ScalarSequence< T >::erasePositions().
 {
   if (initialPos < this->subSequenceSize()) {
     for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
       ScalarSequence<double>& seq = *(m_scalarSequences(i,0));
       seq.erasePositions(initialPos,numPos);
     }
   }
   BaseVectorSequence<V,M>::deleteStoredVectors();
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::extractRawData (unsigned int initialPos, unsigned int spacing, unsigned int numPos, unsigned int paramId, std::vector< double > & rawData) const private virtual
Extracts the raw data.
Extracts the data from sequence of array at position paramId, with spacing spacing, and saves is in rawData. The vector rawData will have size numPos. Note that, in fact, spacing = 1.
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 622 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences.
 {
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   ScalarSequence<double>& seq = *(tmp->m_scalarSequences(paramId,0));
   rawData.resize(numPos);
   if (spacing == 1) {
     for (unsigned int j = 0; j < numPos; ++j) {
       rawData[j] = seq[paramId];
     }
   }
   else {
     for (unsigned int j = 0; j < numPos; ++j) {
       rawData[j] = seq[paramId];
     }
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::extractScalarSeq (unsigned int initialPos, unsigned int spacing, unsigned int numPos, unsigned int paramId, ScalarSequence< double > & scalarSeq) const virtual
Extracts a sequence of scalars of size numPos, from position paramId of the array of sequences.
In this method, the parameter initialPos is unused and the parameter spacing is always equal to one
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 596 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences, and QUESO::ScalarSequence< T >::resizeSequence().
 {
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   ScalarSequence<double>& seq = *(tmp->m_scalarSequences(paramId,0));
   scalarSeq.resizeSequence(numPos);
   if (spacing == 1) {
     for (unsigned int j = 0; j < numPos; ++j) {
       scalarSeq[j] = seq[paramId];
     }
   }
   else {
     for (unsigned int j = 0; j < numPos; ++j) {
       scalarSeq[j] = seq[paramId];
     }
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::fftForward (unsigned int initialPos, unsigned int fftSize, unsigned int paramId, std::vector< std::complex< double > > & resultData) const virtual
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 739 of file ArrayOfSequences.C.
 {
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::filter (unsigned int initialPos, unsigned int spacing) virtual
Filters positions in the sequence of vectors, starting at initialPos, and with spacing given by spacing.
TODO: implement me!
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 589 of file ArrayOfSequences.C.
 {
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::gaussianKDE (const V & evaluationParamVec, V & densityVec) const
Gaussian kernel for the KDE estimate of the sequence.
TODO: implement me!
Definition at line 497 of file ArrayOfSequences.C.
 {
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::gaussianKDE (unsigned int initialPos, const V & scales, const std::vector< V * > & evaluationParamVecs, std::vector< V * > & densityVecs) const
TODO: Gaussian kernel for the KDE of the sequence.
Todo:
: implement me! The density estimator will be:
\[ \hat{f}(x) = \frac{1}{nh} \sum_{j=1}^n K\Big(\frac{x-x_j}{h}\Big),\]
where \(K \) is a Gaussian kernel.
Definition at line 504 of file ArrayOfSequences.C.
References QUESO::MiscGaussianDensity().
 {
 #if 0
   unsigned int dataSize = sequence.size() - initialPos;
   unsigned int numEstimationsPerParam = evaluationParamVecs.size();
   for (unsigned int j = 0; j < numEstimationsPerParam; ++j) {
     densityVecs[j] = new V(*(sequence[0]));
   }
   unsigned int numParams = sequence[0]->size();
   for (unsigned int i = 0; i < numParams; ++i) {
     double scaleInv = 1./scales[i];
     for (unsigned int j = 0; j < numEstimationsPerParam; ++j) {
       double x = (*(evaluationParamVecs[j]))[i];
       double value = 0.;
       for (unsigned int k = 0; k < dataSize; ++k) {
         double xk = (*(sequence[initialPos+k]))[i];
         value += MiscGaussianDensity((x-xk)*scaleInv,0.,1.);
       }
       (*(densityVecs[j]))[i] = scaleInv * (value/(double) numEstimationsPerParam);
     }
   }
 #endif
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::getPositionValues (unsigned int posId, V & vec) const virtual
Gets the values of the sequence at position posId and stores them at vec.
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 122 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences.
 {
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
     vec[i] = (*(tmp->m_scalarSequences(i,0)))[posId];
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::geweke (unsigned int initialPos, double ratioNa, double ratioNb, V & gewVec) const virtual
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 791 of file ArrayOfSequences.C.
References QUESO::ScalarSequence< T >::psd().
 {
 #if 0
   for (unsigned int initialPosId = 0; initialPosId < initialPositions.size(); initialPosId++) {
     unsigned int fullDataSize = sequence.size() - initialPositions[initialPosId];
     unsigned int dataSizeA    = (unsigned int) (((double) fullDataSize) * ratioNa);
     unsigned int dataSizeB    = (unsigned int) (((double) fullDataSize) * ratioNb);
     unsigned int initialPosA  = initialPositions[initialPosId];
     unsigned int initialPosB  = sequence.size() - dataSizeB;
     V meanA(*(sequence[0]));
     VectorSequenceMean(sequence,
                          initialPosA,
                          dataSizeA,
                          meanA);
     V meanB(*(sequence[0]));
     VectorSequenceMean(sequence,
                          initialPosB,
                          dataSizeB,
                          meanB);
     unsigned int numParams = sequence[0]->size();
     V psdVecA(*(sequence[0]));
     ScalarSequence<double> dataA(dataSizeA,0.);
     for (unsigned int i = 0; i < numParams; ++i) {
       for (unsigned int j = 0; j < dataSizeA; ++j) {
   dataA[j] = (*(sequence[initialPosA+j]))[i];
       }
       std::vector<double> psdSequence(0,0.);
       dataA.psd(8,  // numBlocks
                 .5, // hopSizeRatio
                 psdSequence);
       psdVecA[i] = psdSequence[0];
     } // for 'i'
     V psdVecB(*(sequence[0]));
     ScalarSequence<double> dataB(dataSizeB,0.);
     for (unsigned int i = 0; i < numParams; ++i) {
       for (unsigned int j = 0; j < dataSizeB; ++j) {
   dataB[j] = (*(sequence[initialPosB+j]))[i];
       }
       std::vector<double> psdSequence(0,0.);
       dataB.psd(8,  // numBlocks
                 .5, // hopSizeRatio
                 psdSequence);
       psdVecB[i] = psdSequence[0];
     } // for 'i'
     vectorOfGeweke[initialPosId] = new V(*(sequence[0]));
     double doubleDataSizeA = (double) dataSizeA;
     double doubleDataSizeB = (double) dataSizeB;
     for (unsigned int i = 0; i < numParams; ++i) {
       (*(vectorOfGeweke[initialPosId]))[i] = (meanA[i] - meanB[i])/std::sqrt(psdVecA[i]/doubleDataSizeA + psdVecB[i]/doubleDataSizeB);
     }
   }
 #endif
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::histogram (unsigned int initialPos, const V & minVec, const V & maxVec, std::vector< V * > & centersForAllBins, std::vector< V * > & quanttsForAllBins) const
Calculates the histogram of the sequence.
TODO: implement me!
Definition at line 393 of file ArrayOfSequences.C.
References QUESO::queso_require_equal_to_msg.
 {
 #if 0
   queso_require_equal_to_msg(centersForAllBins.size(), quanttsForAllBins.size(), "vectors 'centers' and 'quantts' have different sizes");
   for (unsigned int j = 0; j < quanttsForAllBins.size(); ++j) {
     centersForAllBins[j] = new V(*(sequence[0]));
     quanttsForAllBins [j] = new V(*(sequence[0]));
   }
   unsigned int dataSize = sequence.size() - initialPos;
   unsigned int numParams = sequence[0]->size();
   for (unsigned int i = 0; i < numParams; ++i) {
     ScalarSequence<double> data(dataSize,0.);
     for (unsigned int j = 0; j < dataSize; ++j) {
       data[j] = (*(sequence[initialPos+j]))[i];
     }
     std::vector<double> centers(centersForAllBins.size(),0.);
     std::vector<double> quantts(quanttsForAllBins.size(),0.);
     data.histogram(minVec[i],
                    maxVec[i],
                    centers,
                    quantts);
     for (unsigned int j = 0; j < quantts.size(); ++j) {
       (*(centersForAllBins[j]))[i] = centers[j];
       (*(quanttsForAllBins[j]))[i] = quantts[j];
     }
   }
 #endif
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::interQuantileRange (unsigned int initialPos, V & iqrs) const
Returns the interquartile range of the values in the sequence.
TODO: implement me!
Definition at line 433 of file ArrayOfSequences.C.
 {
 #if 0
   unsigned int dataSize = sequence.size() - initialPos;
   ArrayOfSequences sortedSequence(dataSize,m_vectorSpace.zeroVector());
   this->sort(initialPos,
              sortedSequence);
   unsigned int pos1 = (unsigned int) ( (((double) dataSize) + 1.)*1./4. - 1. );
   unsigned int pos3 = (unsigned int) ( (((double) dataSize) + 1.)*3./4. - 1. );
   double fraction1 = (((double) dataSize) + 1.)*1./4. - 1. - ((double) pos1);
   double fraction3 = (((double) dataSize) + 1.)*3./4. - 1. - ((double) pos3);
   unsigned int numParams = sequence[0]->size();
   for (unsigned int i = 0; i < numParams; ++i) {
     double value1 = (1.-fraction1) * (*sortedSequence[pos1])[i] + fraction1 * (*sortedSequence[pos1+1])[i];
     double value3 = (1.-fraction3) * (*sortedSequence[pos3])[i] + fraction3 * (*sortedSequence[pos3+1])[i];
     iqrs[i] = value3 - value1;
   }
 #endif
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::mean (unsigned int initialPos, unsigned int numPos, V & meanVec) const
Finds the mean value of the sub-sequence, considering numPos positions starting at position initialPos.
Definition at line 172 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences, and QUESO::ScalarSequence< T >::subMeanExtra().
 {
   bool bRC = ((0                     <= initialPos                 ) &&
               (0                     <  numPos                     ) &&
               ((initialPos+numPos-1) <= (this->subSequenceSize()-1)));
   queso_require_msg(bRC, "invalid initial position or number of positions");
   bRC = (this->vectorSize() == meanVec.size());
   queso_require_msg(bRC, "incompatible sizes between meanVec vector and vectors in sequence");
   meanVec.cwSet(0.);
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   for (unsigned int i = 0; i < meanVec.size(); ++i) {
     const ScalarSequence<double>& seq = *(tmp->m_scalarSequences(i,0));
     meanVec[i] = seq.subMeanExtra(initialPos, numPos);
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::minMax (unsigned int initialPos, V & minVec, V & maxVec) const
Given an initial position initialPos, finds the minimum and the maximum values of the sequence.
Definition at line 378 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences, and QUESO::ScalarSequence< T >::subMinMaxExtra().
 {
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   unsigned int numParams = this->vectorSize();
   for (unsigned int i = 0; i < numParams; ++i) {
     ScalarSequence<double>& seq = *(tmp->m_scalarSequences(i,0));
     seq.subMinMaxExtra(initialPos,minVec[i],maxVec[i]);
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::populationVariance (unsigned int initialPos, unsigned int numPos, const V & meanVec, V & popVec) const
Finds the population variance of the sub-sequence, considering numPos positions starting at position initialPos and of mean meanVec.
Definition at line 231 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences.
 {
   bool bRC = ((0                     <= initialPos                 ) &&
               (0                     <  numPos                     ) &&
               ((initialPos+numPos-1) <= (this->subSequenceSize()-1)));
   queso_require_msg(bRC, "invalid initial position or number of positions");
   bRC = (this->vectorSize() == popVec.size());
   queso_require_msg(bRC, "incompatible sizes between popVec vector and vectors in sequence");
   bRC = (this->vectorSize() == meanVec.size());
   queso_require_msg(bRC, "incompatible sizes between meanVec vector and vectors in sequence");
   unsigned int loopSize      = numPos;
   unsigned int finalPosPlus1 = initialPos + loopSize;
   double doubleLoopSize = (double) loopSize;
   popVec.cwSet(0.);
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   for (unsigned int i = 0; i < popVec.size(); ++i) {
     const ScalarSequence<double>& seq = *(tmp->m_scalarSequences(i,0));
     double                               tmpMean = meanVec[i];
     double                               result = 0.;
     for (unsigned int j = initialPos; j < finalPosPlus1; ++j) {
       double diff = seq[j] - tmpMean;
       result += diff*diff;
     }
     popVec[i] = result/doubleLoopSize;
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::psd (unsigned int initialPos, unsigned int numBlocks, double hopSizeRatio, unsigned int paramId, std::vector< double > & psdResult) const virtual
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 748 of file ArrayOfSequences.C.
 {
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::psdAtZero (unsigned int initialPos, unsigned int numBlocks, double hopSizeRatio, V & psdVec) const virtual
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 758 of file ArrayOfSequences.C.
References QUESO::ScalarSequence< T >::psd().
 {
 #if 0
   for (unsigned int initialPosId = 0; initialPosId < initialPositions.size(); initialPosId++) {
     unsigned int dataSize = sequence.size() - initialPositions[initialPosId];
     ScalarSequence<double> data(dataSize,0.);
     unsigned int numParams = sequence[0]->size();
     for (unsigned int i = 0; i < numParams; ++i) {
       for (unsigned int j = 0; j < dataSize; ++j) {
   data[j] = (*(sequence[initialPositions[initialPosId]+j]))[i];
       }
       for (unsigned int numsOfBlocksId = 0; numsOfBlocksId < numsOfBlocks.size(); numsOfBlocksId++) {
         unsigned int numBlocks = numsOfBlocks[numsOfBlocksId];
         std::vector<double> psdSequence(0,0.); // size will be determined by 'ScalarSequencePSD()'
         data.psd(numBlocks,
                  hopSizeRatio,
                  psdSequence);
         _2dArrayOfPSDAtZero(initialPosId,numsOfBlocksId)[i] = psdSequence[0];
         //if (m_env.subDisplayFile()) {
   //  *m_env.subDisplayFile() << "psdSequence[0] = " << psdSequence[0] << std::endl;
         //}
       } // for 'numsOfBlocksId'
     } // for 'i'
   }
 #endif
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::resetValues (unsigned int initialPos, unsigned int numPos) virtual
Resets a total of numPos values of the sequence starting at position initialPos.
This routine deletes all stored computed vectors
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 93 of file ArrayOfSequences.C.
References QUESO::BaseVectorSequence< V, M >::deleteStoredVectors().
 {
   for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
     m_scalarSequences(i,0)->resetValues(initialPos,numPos);
   }
   BaseVectorSequence<V,M>::deleteStoredVectors();
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::resizeSequence (unsigned int newSubSequenceSize) virtual
Resizes the sequence.
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 80 of file ArrayOfSequences.C.
References QUESO::BaseVectorSequence< V, M >::deleteStoredVectors().
 {
   if (newSubSequenceSize != this->subSequenceSize()) {
     for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
       m_scalarSequences(i,0)->resizeSequence(newSubSequenceSize);
     }
   }
   BaseVectorSequence<V,M>::deleteStoredVectors();
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::sampleVariance (unsigned int initialPos, unsigned int numPos, const V & meanVec, V & samVec) const
Finds the sample variance of the sub-sequence, considering numPos positions starting at position initialPos and of mean meanVec.
Definition at line 194 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences.
 {
   bool bRC = ((0                     <= initialPos                 ) &&
               (0                     <  numPos                     ) &&
               ((initialPos+numPos-1) <= (this->subSequenceSize()-1)));
   queso_require_msg(bRC, "invalid initial position or number of positions");
   bRC = (this->vectorSize() == samVec.size());
   queso_require_msg(bRC, "incompatible sizes between samVec vector and vectors in sequence");
   bRC = (this->vectorSize() == meanVec.size());
   queso_require_msg(bRC, "incompatible sizes between meanVec vector and vectors in sequence");
   unsigned int loopSize      = numPos;
   unsigned int finalPosPlus1 = initialPos + loopSize;
   double doubleLoopSize = (double) loopSize;
   samVec.cwSet(0.);
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   for (unsigned int i = 0; i < samVec.size(); ++i) {
     const ScalarSequence<double>& seq = *(tmp->m_scalarSequences(i,0));
     double                               tmpMean = meanVec[i];
     double                               result = 0.;
     for (unsigned int j = initialPos; j < finalPosPlus1; ++j) {
       double diff = seq[j] - tmpMean;
       result += diff*diff;
     }
     samVec[i] = result/(doubleLoopSize - 1.);
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::scalesForKDE (unsigned int initialPos, const V & iqrs, unsigned int kdeDimension, V & scales) const
Selects the scales (bandwidth, scaleVec) for the kernel density estimation, of the sequence.
TODO: implement me!
Definition at line 461 of file ArrayOfSequences.C.
 {
 #if 0
   unsigned int dataSize = sequence.size() - initialPos;
   V mean(*(sequence[0]));
   VectorSequenceMean(sequence,
                        initialPos,
                        dataSize,
                        mean);
   V samVec(*(sequence[0]));
   VectorSequenceSampleVariance(sequence,
                                  initialPos,
                                  dataSize,
                                  mean,
                                  samVec);
   unsigned int numParams = sequence[0]->size();
   for (unsigned int i = 0; i < numParams; ++i) {
     if (iqrs[i] <= 0.) {
       scales[i] = 1.06*std::sqrt(samVec[i])/std::pow(dataSize,1./5.);
     }
     else {
       scales[i] = 1.06*std::min(std::sqrt(samVec[i]),iqrs[i]/1.34)/std::pow(dataSize,1./5.);
     }
   }
 #endif
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::select (const std::vector< unsigned int > & idsOfUniquePositions) virtual
Select positions in the sequence of vectors.
TODO: implement me!
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 582 of file ArrayOfSequences.C.
 {
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::setGaussian (const V & meanVec, const V & stdDevVec)
Sets the values of the sequence as a Gaussian distribution of mean given by meanVec and standard deviation by stdDevVec.
This routine deletes all stored computed vectors
Definition at line 146 of file ArrayOfSequences.C.
References QUESO::BaseVectorSequence< V, M >::deleteStoredVectors(), and QUESO::ScalarSequence< T >::setGaussian().
 {
   for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
     ScalarSequence<double>& seq = *(m_scalarSequences(i,0));
     seq.setGaussian(meanVec[i],stdDevVec[i]);
   }
   BaseVectorSequence<V,M>::deleteStoredVectors();
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::setPositionValues (unsigned int posId, const V & vec) virtual
Set the values of vec at position posId of the sequence.
This routine deletes all stored computed vectors
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 133 of file ArrayOfSequences.C.
References QUESO::BaseVectorSequence< V, M >::deleteStoredVectors().
 {
   for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
     ScalarSequence<double>& seq = *(m_scalarSequences(i,0));
     seq[posId] = vec[i];
   }
   BaseVectorSequence<V,M>::deleteStoredVectors();
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::setUniform (const V & aVec, const V & bVec)
Sets the values of the sequence as a uniform distribution between the values given by vectors aVec and bVec.
This routine deletes all stored computed vectors
Definition at line 159 of file ArrayOfSequences.C.
References QUESO::BaseVectorSequence< V, M >::deleteStoredVectors(), and QUESO::ScalarSequence< T >::setUniform().
 {
   for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
     ScalarSequence<double>& seq = *(m_scalarSequences(i,0));
     seq.setUniform(aVec[i],bVec[i]);
   }
   BaseVectorSequence<V,M>::deleteStoredVectors();
   return;
 }
template<class V , class M > unsigned int QUESO::ArrayOfSequences< V, M >::subSequenceSize () const virtual
Size of the sub-sequence of arrays.
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 72 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences.
Referenced by QUESO::ArrayOfSequences< V, M >::ArrayOfSequences().
 {
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   return tmp->m_scalarSequences(0,0)->subSequenceSize();
 }
template<class V = GslVector, class M = GslMatrix> void QUESO::ArrayOfSequences< V, M >::unifiedMean (unsigned int initialPos, unsigned int numPos, V & unifiedMeanVec) const
Finds the mean value of the unified sequence of numPos positions starting at position initialPos. See template specialization.
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::unifiedReadContents (const std::string & fileName, const std::string & fileType, const unsigned int subSequenceSize) virtual
Reads the unified sequence from a file.
TODO: implement me!
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 573 of file ArrayOfSequences.C.
 {
   queso_not_implemented();
   return;
 }
template<class V = GslVector, class M = GslMatrix> void QUESO::ArrayOfSequences< V, M >::unifiedSampleVariance (unsigned int initialPos, unsigned int numPos, const V & meanVec, V & samVec) const
Finds the sample variance of the unified sequence, considering numPos positions starting at position initialPos and of mean meanVec.
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::unifiedWriteContents (std::ofstream & ofsvar) const
Writes info of the unified sequence to a file.
TODO: implement me!
Definition at line 558 of file ArrayOfSequences.C.
 {
   queso_not_implemented();
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::unifiedWriteContents (const std::string & fileName, const std::string & fileType) const virtual
Writes info of the unified sequence to a file.
TODO: implement me!
Implements QUESO::BaseVectorSequence< V, M >.
Definition at line 565 of file ArrayOfSequences.C.
 {
   queso_not_implemented();
   return;
 }
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::uniformlySampledCdf (const V & numEvaluationPointsVec, ArrayOfOneDGrids< V, M > & cdfGrids, ArrayOfOneDTables< V, M > & cdfValues) const
Definition at line 649 of file ArrayOfSequences.C.
References QUESO::ArrayOfSequences< V, M >::m_scalarSequences, QUESO::ArrayOfOneDTables< V, M >::setOneDTable(), QUESO::ArrayOfOneDGrids< V, M >::setUniformGrids(), and QUESO::ScalarSequence< T >::subUniformlySampledCdf().
 {
   ArrayOfSequences<V,M>* tmp = const_cast<ArrayOfSequences<V,M>*>(this);
   V minCdfValues(m_vectorSpace.zeroVector());
   V maxCdfValues(m_vectorSpace.zeroVector());
   for (unsigned int i = 0; i < (unsigned int) m_scalarSequences.MyLength(); ++i) {
     const ScalarSequence<double>& seq = *(tmp->m_scalarSequences(i,0));
     unsigned int numEvaluationPoints = (unsigned int) numEvaluationPointsVec[i];
     std::vector<double> aCdf(0);
     seq.subUniformlySampledCdf(numEvaluationPoints,
                             minCdfValues[i],
                             maxCdfValues[i],
                             aCdf);
     cdfValues.setOneDTable(i,aCdf);
   }
   cdfGrids.setUniformGrids(numEvaluationPointsVec,
                            minCdfValues,
                            maxCdfValues);
   return;
 }
template<class V = GslVector, class M = GslMatrix> void QUESO::ArrayOfSequences< V, M >::uniformlySampledMdf (const V & numEvaluationPointsVec, ArrayOfOneDGrids< V, M > & mdfGrids, ArrayOfOneDTables< V, M > & mdfValues) const
template<class V , class M > void QUESO::ArrayOfSequences< V, M >::writeContents (std::ofstream & ofsvar) const
Write contents of the chain to a file.
Definition at line 536 of file ArrayOfSequences.C.
 {
   // Write chain
   ofsvar << m_name << "_sub" << m_env.subIdString() << " = zeros(" << this->subSequenceSize()
          << ","                                                    << this->vectorSize()
          << ");"
          << std::endl;
   ofsvar << m_name << "_sub" << m_env.subIdString() << " = [";
   V tmpVec(m_vectorSpace.zeroVector());
   unsigned int chainSize = this->subSequenceSize();
   for (unsigned int j = 0; j < chainSize; ++j) {
     this->getPositionValues(j,tmpVec);
     ofsvar << tmpVec
            << std::endl;
   }
   ofsvar << "];\n";
   return;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> DistArray<ScalarSequence<double>*> QUESO::ArrayOfSequences< V, M >::m_scalarSequences private
Sequence of scalars.
Definition at line 264 of file ArrayOfSequences.h.
Referenced by QUESO::ArrayOfSequences< V, M >::ArrayOfSequences(), QUESO::ArrayOfSequences< V, M >::autoCovariance(), QUESO::ArrayOfSequences< V, M >::extractRawData(), QUESO::ArrayOfSequences< V, M >::extractScalarSeq(), QUESO::ArrayOfSequences< V, M >::getPositionValues(), QUESO::ArrayOfSequences< V, M >::mean(), QUESO::ArrayOfSequences< V, M >::minMax(), QUESO::ArrayOfSequences< V, M >::populationVariance(), QUESO::ArrayOfSequences< V, M >::sampleVariance(), QUESO::ArrayOfSequences< V, M >::subSequenceSize(), and QUESO::ArrayOfSequences< V, M >::uniformlySampledCdf().
The documentation for this class was generated from the following files:
src/basic/inc/ArrayOfSequences.h
src/basic/src/ArrayOfSequences.C