queso-0.57.1: QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M > Class Template Reference
QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M > Class Template Reference
A class representing a Gaussian likelihood with block-diagonal covariance matrix.
#include <GaussianLikelihoodBlockDiagonalCovariance.h>
Public Member Functions
double & blockCoefficient (unsigned int i)
Get (non-const) multiplicative coefficient for block i.
const double & getBlockCoefficient (unsigned int i) const
Get (const) multiplicative coefficient for block i.
virtual double lnValue (const V &domainVector) const
Logarithm of the value of the scalar function.
Constructor/Destructor methods.
GaussianLikelihoodBlockDiagonalCovariance (const char *prefix, const VectorSet< V, M > &domainSet, const V &observations, const GslBlockMatrix &covariance)
Default constructor.
virtual ~GaussianLikelihoodBlockDiagonalCovariance ()
Destructor.
Public Member Functions inherited from QUESO::LikelihoodBase< V, M >
virtual void evaluateModel (const V &domainVector, const V *domainDirection, V &modelOutput, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Deprecated. Evaluates the user's model at the point domainVector.
virtual void evaluateModel (const V &domainVector, V &modelOutput) const
Evaluates the user's model at the point domainVector.
virtual double actualValue (const V &domainVector, const V *, V *, M *, V *) const
Actual value of the scalar function.
LikelihoodBase (const char *prefix, const VectorSet< V, M > &domainSet, const V &observations)
Default constructor.
virtual ~LikelihoodBase ()=0
Destructor, pure to make this class abstract.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
void setFiniteDifferenceStepSize (double fdStepSize)
Sets the step size for finite differencing gradients.
void setFiniteDifferenceStepSize (unsigned int i, double fdStepSize)
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
virtual double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Logarithm of the value of the scalar function. Deprecated.
virtual double lnValue (const V &domainVector, V &gradVector) const
Returns the logarithm of the function and its gradient at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector, const V &domainDirection, V &hessianEffect) const
Private Attributes
std::vector< double > m_covarianceCoefficients
const GslBlockMatrix & m_covariance
Additional Inherited Members
Protected Attributes inherited from QUESO::LikelihoodBase< V, M >
const V & m_observations
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >
A class representing a Gaussian likelihood with block-diagonal covariance matrix.
Definition at line 45 of file GaussianLikelihoodBlockDiagonalCovariance.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::GaussianLikelihoodBlockDiagonalCovariance (const char * prefix, const VectorSet< V, M > & domainSet, const V & observations, const GslBlockMatrix & covariance)
Default constructor.
Instantiates a Gaussian likelihood function, given a prefix, its domain, a vector of observations and a block diagonal covariance matrix. The diagonal covariance matrix is of type GslBlockMatrix. Each block in the block diagonal matrix is an object of type GslMatrix.
Furthermore, each block comes with a multiplicative coefficient which defaults to 1.0.
Definition at line 35 of file GaussianLikelihoodBlockDiagonalCovariance.C.
References QUESO::GslBlockMatrix::getBlock(), QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::m_covariance, QUESO::GslBlockMatrix::numBlocks(), and QUESO::GslMatrix::numRowsLocal().
   : LikelihoodBase<V, M>(prefix, domainSet, observations),
     m_covarianceCoefficients(covariance.numBlocks(), 1.0),
     m_covariance(covariance)
 {
   unsigned int totalDim = 0;
   for (unsigned int i = 0; i < this->m_covariance.numBlocks(); i++) {
     totalDim += this->m_covariance.getBlock(i).numRowsLocal();
   }
   if (totalDim != observations.sizeLocal()) {
     queso_error_msg("Covariance matrix not same dimension as observation vector");
   }
 }
template<class V , class M > QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::~GaussianLikelihoodBlockDiagonalCovariance () virtual
Destructor.
Definition at line 54 of file GaussianLikelihoodBlockDiagonalCovariance.C.
 {
 }
Member Function Documentation
template<class V , class M > double & QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::blockCoefficient (unsigned int i)
Get (non-const) multiplicative coefficient for block i.
Definition at line 60 of file GaussianLikelihoodBlockDiagonalCovariance.C.
 {
   return this->m_covarianceCoefficients[i];
 }
template<class V , class M > const double & QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::getBlockCoefficient (unsigned int i) const
Get (const) multiplicative coefficient for block i.
Definition at line 68 of file GaussianLikelihoodBlockDiagonalCovariance.C.
 {
   return this->m_covarianceCoefficients[i];
 }
template<class V , class M > double QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::lnValue (const V & domainVector) const virtual
Logarithm of the value of the scalar function.
Reimplemented from QUESO::BaseScalarFunction< V, M >.
Definition at line 76 of file GaussianLikelihoodBlockDiagonalCovariance.C.
 {
   V modelOutput(this->m_observations, 0, 0);  // At least it's not a copy
   V weightedMisfit(this->m_observations, 0, 0);  // At least it's not a copy
   this->evaluateModel(domainVector, modelOutput);
   // Compute misfit G(x) - y
   modelOutput -= this->m_observations;
   // Solve \Sigma u = G(x) - y for u
   this->m_covariance.invertMultiply(modelOutput, weightedMisfit);
   // Deal with the multiplicative coefficients for each of the blocks
   unsigned int offset = 0;
   // For each block...
   for (unsigned int i = 0; i < this->m_covariance.numBlocks(); i++) {
     // ...divide the appropriate parts of the solution by the coefficient
     unsigned int blockDim = this->m_covariance.getBlock(i).numRowsLocal();
     for (unsigned int j = 0; j < blockDim; j++) {
       // coefficient is a variance, so we divide by it
       modelOutput[offset+j] /= this->m_covarianceCoefficients[i];
     }
     offset += blockDim;
   }
   // Compute (G(x) - y)^T \Sigma^{-1} (G(x) - y)
   modelOutput *= weightedMisfit;
   double norm2_squared = modelOutput.sumOfComponents();  // This is square of 2-norm
   return -0.5 * norm2_squared;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> const GslBlockMatrix& QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::m_covariance private
Definition at line 78 of file GaussianLikelihoodBlockDiagonalCovariance.h.
Referenced by QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::GaussianLikelihoodBlockDiagonalCovariance().
template<class V = GslVector, class M = GslMatrix> std::vector<double> QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::m_covarianceCoefficients private
Definition at line 77 of file GaussianLikelihoodBlockDiagonalCovariance.h.
The documentation for this class was generated from the following files:
src/stats/inc/GaussianLikelihoodBlockDiagonalCovariance.h
src/stats/src/GaussianLikelihoodBlockDiagonalCovariance.C