queso-0.57.1: QUESO::InfiniteDimensionalGaussian Class Reference
QUESO::InfiniteDimensionalGaussian Class Reference
Class defining infinite dimensional Gaussian measures.
#include <InfiniteDimensionalGaussian.h>
Public Member Functions
virtual SharedPtr
< FunctionBase >::Type draw ()
Draw from the measure, and then return a shared pointer to the draw.
virtual double get_kl_coefficient (unsigned int i) const
Return coefficient i of the KL expansion of the current draw. Must be called after draw()
Constructor/Destructor methods
InfiniteDimensionalGaussian (const FullEnvironment &env, const FunctionBase &mean, const OperatorBase &precision, double alpha, double beta)
Construct a Gaussian with mean mean, precision operator precision. alpha controls regularity of draws and beta^2 is a multiplicative coefficient of precision.
~InfiniteDimensionalGaussian ()
Destructor.
Public Member Functions inherited from QUESO::InfiniteDimensionalMeasureBase
InfiniteDimensionalMeasureBase ()
Default constructor.
virtual ~InfiniteDimensionalMeasureBase ()
Destructor.
Private Attributes
const FunctionBase & mean
const OperatorBase & precision
const FullEnvironment & env
double alpha
double beta
std::vector< double > coeffs
Detailed Description
Class defining infinite dimensional Gaussian measures.
Definition at line 45 of file InfiniteDimensionalGaussian.h.
Constructor & Destructor Documentation
QUESO::InfiniteDimensionalGaussian::InfiniteDimensionalGaussian (const FullEnvironment & env, const FunctionBase & mean, const OperatorBase & precision, double alpha, double beta)
Construct a Gaussian with mean mean, precision operator precision. alpha controls regularity of draws and beta^2 is a multiplicative coefficient of precision.
The argument alpha refers to the power to which the precision will be taken. And beta is the multiplicative coefficient of preicision. The complete measure is therefore:
N(mean, beta^2 * pow(precision, alpha))
It is expected that mean and precision will live longer than this
Definition at line 38 of file InfiniteDimensionalGaussian.C.
References coeffs, and QUESO::OperatorBase::get_num_converged().
   : InfiniteDimensionalMeasureBase(),
     mean(mean),
     precision(precision),
     env(env),
     alpha(alpha),
     beta(beta)
 {
   this->coeffs.resize(this->precision.get_num_converged(), 0.0);
 }
QUESO::InfiniteDimensionalGaussian::~InfiniteDimensionalGaussian ()
Destructor.
Definition at line 54 of file InfiniteDimensionalGaussian.C.
 {
 }
Member Function Documentation
SharedPtr< FunctionBase >::Type QUESO::InfiniteDimensionalGaussian::draw () virtual
Draw from the measure, and then return a shared pointer to the draw.
Implements QUESO::InfiniteDimensionalMeasureBase.
Definition at line 58 of file InfiniteDimensionalGaussian.C.
References beta, coeffs, env, QUESO::RngBase::gaussianSample(), QUESO::OperatorBase::get_num_converged(), QUESO::OperatorBase::inverse_kl_transform(), mean, precision, and QUESO::BaseEnvironment::rngObject().
 {
   unsigned int i;
   for (i = 0; i < this->precision.get_num_converged(); i++) {
     (this->coeffs)[i] = env.rngObject()->gaussianSample(this->beta);
   }
   SharedPtr<FunctionBase>::Type f(this->precision.inverse_kl_transform(this->coeffs, this->alpha));
   // Add on the mean
   f->add(1.0, mean);
   return f;
 }
double QUESO::InfiniteDimensionalGaussian::get_kl_coefficient (unsigned int i) const virtual
Return coefficient i of the KL expansion of the current draw. Must be called after draw()
Implements QUESO::InfiniteDimensionalMeasureBase.
Definition at line 74 of file InfiniteDimensionalGaussian.C.
References alpha, coeffs, QUESO::OperatorBase::get_eigenvalue(), and precision.
 {
   // This is code repetition, but I'm not quite sure this belongs
   // in the operator class, because it's useful in the measure
   return (this->coeffs)[i] / std::pow(this->precision.get_eigenvalue(i), this->alpha / 2.0);
 }
Member Data Documentation
double QUESO::InfiniteDimensionalGaussian::alpha private
Definition at line 84 of file InfiniteDimensionalGaussian.h.
Referenced by get_kl_coefficient().
double QUESO::InfiniteDimensionalGaussian::beta private
Definition at line 87 of file InfiniteDimensionalGaussian.h.
Referenced by draw().
std::vector<double> QUESO::InfiniteDimensionalGaussian::coeffs private
Definition at line 91 of file InfiniteDimensionalGaussian.h.
Referenced by draw(), get_kl_coefficient(), and InfiniteDimensionalGaussian().
const FullEnvironment& QUESO::InfiniteDimensionalGaussian::env private
Definition at line 81 of file InfiniteDimensionalGaussian.h.
Referenced by draw().
const FunctionBase& QUESO::InfiniteDimensionalGaussian::mean private
Definition at line 75 of file InfiniteDimensionalGaussian.h.
Referenced by draw().
const OperatorBase& QUESO::InfiniteDimensionalGaussian::precision private
Definition at line 78 of file InfiniteDimensionalGaussian.h.
Referenced by draw(), and get_kl_coefficient().
The documentation for this class was generated from the following files:
src/core/inc/InfiniteDimensionalGaussian.h
src/core/src/InfiniteDimensionalGaussian.C