queso-0.57.1: QUESO::GenericVectorRV< V, M > Class Template Reference
QUESO::GenericVectorRV< V, M > Class Template Reference
A templated class for handling generic vector RVs.
#include <GenericVectorRV.h>
Public Member Functions
Constructor/Destructor methods
GenericVectorRV (const char *prefix, const VectorSet< V, M > &imageSet)
Default constructor.
GenericVectorRV (const char *prefix, const VectorSet< V, M > &imageSet, BaseJointPdf< V, M > &pdf, BaseVectorRealizer< V, M > &realizer, const BaseVectorCdf< V, M > &subCdf, const BaseVectorCdf< V, M > &unifiedCdf, const BaseVectorMdf< V, M > &mdf)
Constructor.
virtual ~GenericVectorRV ()
Virtual destructor.
Random variable-handling methods
void setPdf (BaseJointPdf< V, M > &pdf)
Sets the PDF of this vector RV to pdf.
void setRealizer (BaseVectorRealizer< V, M > &realizer)
Sets the realizer of this vector RV to realizer.
void setSubCdf (BaseVectorCdf< V, M > &subCdf)
Sets the CDF of the sub-sequence of this vector RV to subCdf.
void setUnifiedCdf (BaseVectorCdf< V, M > &unifiedCdf)
Sets the CDF of the unified sequence of this vector RV to unifiedCdf.
void setMdf (BaseVectorMdf< V, M > &mdf)
Sets the MDF of this vector RV to Mdf.
I/O methods
void print (std::ostream &os) const
TODO: Prints the vector RV.
Public Member Functions inherited from QUESO::BaseVectorRV< V, M >
virtual double estimateENT_ANN () const
BaseVectorRV (const char *prefix, const VectorSet< V, M > &imageSet)
Constructor.
virtual ~BaseVectorRV ()
Virtual destructor.
const BaseEnvironment & env () const
QUESO environment; access to private attribute m_env.
const VectorSet< V, M > & imageSet () const
Image set of the vector RV; access to private attribute m_imageSet.
const BaseJointPdf< V, M > & pdf () const
Posterior Density Function of the vector RV; access to private attribute m_pdf.
bool has_realizer () const
Returns true iff this RV has the ability to produce realizations (samples)
const BaseVectorRealizer< V, M > & realizer () const
Finds a realization (sample) of the PDF of this vector RV; access to private attribute m_realizer.
const BaseVectorCdf< V, M > & subCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering only the sub-sequence of data; access to private attribute m_subCdf.
const BaseVectorCdf< V, M > & unifiedCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering the unified sequence of data; access to private attribute m_unifiedCdf.
const BaseVectorMdf< V, M > & mdf () const
Finds the Marginal Density Function of this vector RV; access to private attribute m_mdf.
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseVectorRV< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_imageSet
BaseJointPdf< V, M > * m_pdf
BaseVectorRealizer< V, M > * m_realizer
const BaseVectorCdf< V, M > * m_subCdf
const BaseVectorCdf< V, M > * m_unifiedCdf
const BaseVectorMdf< V, M > * m_mdf
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::GenericVectorRV< V, M >
A templated class for handling generic vector RVs.
This class allows the user to compute the value of the PDF of a generic random variable (RV) and to generate realizations (samples) from such PDF. This is the class used by QUESO to store the solution of an statistical inverse problem.
Definition at line 52 of file GenericVectorRV.h.
Constructor & Destructor Documentation
template<class V, class M> QUESO::GenericVectorRV< V, M >::GenericVectorRV (const char * prefix, const VectorSet< V, M > & imageSet)
Default constructor.
Constructs a new instance, given a prefix and the image set of the vector RV.
Definition at line 33 of file GenericVectorRV.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRV< V, M >::m_env, QUESO::BaseVectorRV< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRV<V,M>(((std::string)(prefix)+"gen").c_str(),imageSet)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering GenericVectorRV<V,M>::constructor() [1]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving GenericVectorRV<V,M>::constructor() [1]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V, class M> QUESO::GenericVectorRV< V, M >::GenericVectorRV (const char * prefix, const VectorSet< V, M > & imageSet, BaseJointPdf< V, M > & pdf, BaseVectorRealizer< V, M > & realizer, const BaseVectorCdf< V, M > & subCdf, const BaseVectorCdf< V, M > & unifiedCdf, const BaseVectorMdf< V, M > & mdf)
Constructor.
Constructs a new instance, given all the attributes that characterize the vector RV: prefix, image set, pdf, etc.
Definition at line 53 of file GenericVectorRV.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRV< V, M >::m_env, QUESO::BaseVectorRV< V, M >::m_mdf, QUESO::BaseVectorRV< V, M >::m_pdf, QUESO::BaseVectorRV< V, M >::m_prefix, QUESO::BaseVectorRV< V, M >::m_realizer, QUESO::BaseVectorRV< V, M >::m_subCdf, QUESO::BaseVectorRV< V, M >::m_unifiedCdf, QUESO::BaseVectorRV< V, M >::mdf(), QUESO::BaseVectorRV< V, M >::pdf(), QUESO::BaseVectorRV< V, M >::realizer(), QUESO::BaseVectorRV< V, M >::subCdf(), QUESO::BaseEnvironment::subDisplayFile(), and QUESO::BaseVectorRV< V, M >::unifiedCdf().
   :
   BaseVectorRV<V,M>(((std::string)(prefix)+"gen").c_str(),imageSet)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering GenericVectorRV<V,M>::constructor() [2]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   m_pdf        = &pdf;
   m_realizer   = &realizer;
   m_subCdf     = &subCdf;
   m_unifiedCdf = &unifiedCdf;
   m_mdf        = &mdf;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving GenericVectorRV<V,M>::constructor() [2]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::GenericVectorRV< V, M >::~GenericVectorRV () virtual
Virtual destructor.
Definition at line 84 of file GenericVectorRV.C.
 {
 }
Member Function Documentation
template<class V , class M > void QUESO::GenericVectorRV< V, M >::print (std::ostream & os) const virtual
TODO: Prints the vector RV.
Todo:
: implement me!
Implements QUESO::BaseVectorRV< V, M >.
Definition at line 130 of file GenericVectorRV.C.
 {
   os << "GenericVectorRV<V,M>::print() says, 'Please implement me.'" << std::endl;
   return;
 }
template<class V, class M> void QUESO::GenericVectorRV< V, M >::setMdf (BaseVectorMdf< V, M > & mdf)
Sets the MDF of this vector RV to Mdf.
Definition at line 122 of file GenericVectorRV.C.
 {
   m_mdf = &mdf;
   return;
 }
template<class V, class M> void QUESO::GenericVectorRV< V, M >::setPdf (BaseJointPdf< V, M > & pdf)
Sets the PDF of this vector RV to pdf.
Definition at line 90 of file GenericVectorRV.C.
Referenced by QUESO::MLSampling< P_V, P_M >::generateSequence_Step08_all().
 {
   m_pdf = &pdf;
   return;
 }
template<class V, class M> void QUESO::GenericVectorRV< V, M >::setRealizer (BaseVectorRealizer< V, M > & realizer)
Sets the realizer of this vector RV to realizer.
Definition at line 98 of file GenericVectorRV.C.
 {
   m_realizer = &realizer;
   return;
 }
template<class V, class M> void QUESO::GenericVectorRV< V, M >::setSubCdf (BaseVectorCdf< V, M > & subCdf)
Sets the CDF of the sub-sequence of this vector RV to subCdf.
Definition at line 106 of file GenericVectorRV.C.
 {
   m_subCdf = &subCdf;
   return;
 }
template<class V, class M> void QUESO::GenericVectorRV< V, M >::setUnifiedCdf (BaseVectorCdf< V, M > & unifiedCdf)
Sets the CDF of the unified sequence of this vector RV to unifiedCdf.
Definition at line 114 of file GenericVectorRV.C.
 {
   m_unifiedCdf = &unifiedCdf;
   return;
 }
The documentation for this class was generated from the following files:
src/stats/inc/GenericVectorRV.h
src/stats/src/GenericVectorRV.C