queso-0.57.1: QUESO::LogNormalVectorRealizer< V, M > Class Template Reference
QUESO::LogNormalVectorRealizer< V, M > Class Template Reference
A class for handling sampling from a Log-Normal probability density distribution.
#include <LogNormalVectorRealizer.h>
Public Member Functions
Constructor/Destructor methods
LogNormalVectorRealizer (const char *prefix, const VectorSet< V, M > &unifiedImageSet, const V &lawExpVector, const M &lowerCholLawCovMatrix)
Constructor.
LogNormalVectorRealizer (const char *prefix, const VectorSet< V, M > &unifiedImageSet, const V &lawExpVector, const M &matU, const V &vecSsqrt, const M &matVt)
Constructor.
~LogNormalVectorRealizer ()
Destructor.
Realization-related methods
const V & unifiedLawExpVector () const
Access to the vector of mean values and private attribute: m_unifiedLawExpVector.
const V & unifiedLawVarVector () const
Access to the vector of variance values and private attribute: m_unifiedLawVarVector.
void realization (V &nextValues) const
Draws a realization.
Public Member Functions inherited from QUESO::BaseVectorRealizer< V, M >
BaseVectorRealizer (const char *prefix, const VectorSet< V, M > &unifiedImageSet, unsigned int subPeriod)
Default constructor.
virtual ~BaseVectorRealizer ()
Virtual destructor.
const VectorSet< V, M > & unifiedImageSet () const
Image set where the realizations lie. Access to protected attribute m_unifiedImageSet.
unsigned int subPeriod () const
Sub-period of the realization. Access to protected attribute m_subPeriod.
Private Attributes
V * m_unifiedLawExpVector
V * m_unifiedLawVarVector
M * m_lowerCholLawCovMatrix
M * m_matU
V * m_vecSsqrt
M * m_matVt
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseVectorRealizer< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_unifiedImageSet
unsigned int m_subPeriod
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::LogNormalVectorRealizer< V, M >
A class for handling sampling from a Log-Normal probability density distribution.
This class handles sampling from a Log-Normal probability density distribution, of mean and variance given.
Definition at line 49 of file LogNormalVectorRealizer.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::LogNormalVectorRealizer< V, M >::LogNormalVectorRealizer (const char * prefix, const VectorSet< V, M > & unifiedImageSet, const V & lawExpVector, const M & lowerCholLawCovMatrix)
Constructor.
Constructs a new object of the class, given a prefix and the image set, a vector of mean values, lawExpVector, and a lower triangular matrix resulting from Cholesky decomposition of the covariance matrix, lowerCholLawCovMatrix.
Definition at line 34 of file LogNormalVectorRealizer.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRealizer< V, M >::m_env, QUESO::BaseVectorRealizer< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRealizer<V,M>( ((std::string)(prefix)+"gau").c_str(), unifiedImageSet, std::numeric_limits<unsigned int>::max()), // 2011/Oct/02 - Correction thanks to Corey
   m_unifiedLawExpVector  (new V(lawExpVector)),
   m_unifiedLawVarVector  (unifiedImageSet.vectorSpace().newVector( INFINITY)), // FIX ME
   m_lowerCholLawCovMatrix(new M(lowerCholLawCovMatrix)),
   m_matU                 (NULL),
   m_vecSsqrt             (NULL),
   m_matVt                (NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering LogNormalVectorRealizer<V,M>::constructor() [1]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving LogNormalVectorRealizer<V,M>::constructor() [1]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::LogNormalVectorRealizer< V, M >::LogNormalVectorRealizer (const char * prefix, const VectorSet< V, M > & unifiedImageSet, const V & lawExpVector, const M & matU, const V & vecSsqrt, const M & matVt)
Constructor.
Constructs a new object of the class, given a prefix and the image set, a vector of mean values, lawExpVector, and a set of two matrices and one vector resulting from the Single Value Decomposition of the covariance matrix, matU, vecSsqrt and matVt.
Definition at line 61 of file LogNormalVectorRealizer.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRealizer< V, M >::m_env, QUESO::BaseVectorRealizer< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRealizer<V,M>( ((std::string)(prefix)+"gau").c_str(), unifiedImageSet, std::numeric_limits<unsigned int>::max()), // 2011/Oct/02 - Correction thanks to Corey
   m_unifiedLawExpVector  (new V(lawExpVector)),
   m_unifiedLawVarVector  (unifiedImageSet.vectorSpace().newVector( INFINITY)), // FIX ME
   m_lowerCholLawCovMatrix(NULL),
   m_matU                 (new M(matU)),
   m_vecSsqrt             (new V(vecSsqrt)),
   m_matVt                (new M(matVt))
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering LogNormalVectorRealizer<V,M>::constructor() [2]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving LogNormalVectorRealizer<V,M>::constructor() [2]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::LogNormalVectorRealizer< V, M >::~LogNormalVectorRealizer ()
Destructor.
Definition at line 90 of file LogNormalVectorRealizer.C.
 {
   delete m_matVt;
   delete m_vecSsqrt;
   delete m_matU;
   delete m_lowerCholLawCovMatrix;
   delete m_unifiedLawVarVector;
   delete m_unifiedLawExpVector;
 }
Member Function Documentation
template<class V , class M > void QUESO::LogNormalVectorRealizer< V, M >::realization (V & nextValues) const virtual
Draws a realization.
This function draws a realization of a LogNormal distribution and saves it in nextValues.
Implements QUESO::BaseVectorRealizer< V, M >.
Definition at line 116 of file LogNormalVectorRealizer.C.
 {
   V iidGaussianVector(m_unifiedImageSet.vectorSpace().zeroVector());
   bool outOfSupport = true;
   do {
     iidGaussianVector.cwSetGaussian(0.0, 1.0);
     if (m_lowerCholLawCovMatrix) {
       nextValues = (*m_unifiedLawExpVector) + (*m_lowerCholLawCovMatrix)*iidGaussianVector;
     }
     else if (m_matU && m_vecSsqrt && m_matVt) {
       nextValues = (*m_unifiedLawExpVector) + (*m_matU)*( (*m_vecSsqrt) * ((*m_matVt)*iidGaussianVector) );
     }
     else {
       queso_error_msg("inconsistent internal state");
     }
     for (unsigned int i = 0; i < nextValues.sizeLocal(); ++i) {
       nextValues[i] = std::exp(nextValues[i]);
     }
     outOfSupport = !(this->m_unifiedImageSet.contains(nextValues));
   } while (outOfSupport); // prudenci 2011-Oct-04
   return;
 }
template<class V , class M > const V & QUESO::LogNormalVectorRealizer< V, M >::unifiedLawExpVector () const
Access to the vector of mean values and private attribute: m_unifiedLawExpVector.
Definition at line 102 of file LogNormalVectorRealizer.C.
 {
   return *m_unifiedLawExpVector;
 }
template<class V , class M > const V & QUESO::LogNormalVectorRealizer< V, M >::unifiedLawVarVector () const
Access to the vector of variance values and private attribute: m_unifiedLawVarVector.
Definition at line 109 of file LogNormalVectorRealizer.C.
 {
   return *m_unifiedLawVarVector;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> M* QUESO::LogNormalVectorRealizer< V, M >::m_lowerCholLawCovMatrix private
Definition at line 92 of file LogNormalVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> M* QUESO::LogNormalVectorRealizer< V, M >::m_matU private
Definition at line 93 of file LogNormalVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> M* QUESO::LogNormalVectorRealizer< V, M >::m_matVt private
Definition at line 95 of file LogNormalVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> V* QUESO::LogNormalVectorRealizer< V, M >::m_unifiedLawExpVector private
Definition at line 90 of file LogNormalVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> V* QUESO::LogNormalVectorRealizer< V, M >::m_unifiedLawVarVector private
Definition at line 91 of file LogNormalVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> V* QUESO::LogNormalVectorRealizer< V, M >::m_vecSsqrt private
Definition at line 94 of file LogNormalVectorRealizer.h.
The documentation for this class was generated from the following files:
src/stats/inc/LogNormalVectorRealizer.h
src/stats/src/LogNormalVectorRealizer.C