queso-0.57.1: QUESO::SampledVectorCdf< V, M > Class Template Reference
QUESO::SampledVectorCdf< V, M > Class Template Reference
A class for handling sampled vector CDFs.
#include <SampledVectorCdf.h>
Public Member Functions
Constructor/Destructor methods
SampledVectorCdf (const char *prefix, const ArrayOfOneDGrids< V, M > &oneDGrids, const ArrayOfOneDTables< V, M > &cdfValues)
Default constructor.
~SampledVectorCdf ()
Destructor.
Mathematical methods
void values (const V &paramValues, V &cdfVec) const
TODO: Returns the values of the vector CDF at each element of paramValues.
const BaseScalarCdf< double > & cdf (unsigned int rowId) const
Returns a scalar CDF stored at row rowId of the vector CDF.
I/O methods
void print (std::ostream &os) const
Prints the vector CDF (values of the grid points and of the CDF at such grid points).
void subWriteContents (const std::string &varNamePrefix, const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds) const
Writes the CDF of an allowed sub-environment to a file.
Public Member Functions inherited from QUESO::BaseVectorCdf< V, M >
BaseVectorCdf (const char *prefix, const VectorSet< V, M > &pdfSupport)
Default constructor.
virtual ~BaseVectorCdf ()
Virtual destructor.
const VectorSet< V, M > & pdfSupport () const
Returns the image set (support) of the PDF; access to protected attribute m_pdfSupport.
Protected Attributes
DistArray< SampledScalarCdf
< double > * > m_cdfs
Protected Attributes inherited from QUESO::BaseVectorCdf< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_pdfSupport
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::SampledVectorCdf< V, M >
A class for handling sampled vector CDFs.
This class implements a sampled vector cumulative distribution function (CDF), given the grid points where it will be sampled and it returns its values.
Definition at line 51 of file SampledVectorCdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::SampledVectorCdf< V, M >::SampledVectorCdf (const char * prefix, const ArrayOfOneDGrids< V, M > & oneDGrids, const ArrayOfOneDTables< V, M > & cdfValues)
Default constructor.
Instantiates an object of the class given a prefix and the grid points where it will be sampled/evaluated.
Definition at line 31 of file SampledVectorCdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::ArrayOfOneDGrids< V, M >::grid(), QUESO::SampledVectorCdf< V, M >::m_cdfs, QUESO::BaseVectorCdf< V, M >::m_env, QUESO::BaseVectorCdf< V, M >::m_prefix, QUESO::ArrayOfOneDTables< V, M >::oneDTable(), and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorCdf<V,M>(prefix,oneDGrids.rowSpace()),
   m_cdfs(m_pdfSupport.vectorSpace().map(),1)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering SampledVectorCdf<V,M>::constructor()"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
   char strI[65];
   for (unsigned int i = 0; i < (unsigned int) m_cdfs.MyLength(); ++i) {
     sprintf(strI,"%u_",i);
     m_cdfs(i,0) = new SampledScalarCdf<double>(m_env,
                                                       ((std::string)(m_prefix)+strI).c_str(),
                                                       oneDGrids.grid(i),
                                                       cdfValues.oneDTable(i));
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving SampledVectorCdf<V,M>::constructor()"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
 }
template<class V , class M > QUESO::SampledVectorCdf< V, M >::~SampledVectorCdf ()
Destructor.
Definition at line 62 of file SampledVectorCdf.C.
 {
   for (unsigned int i = 0; i < (unsigned int) m_cdfs.MyLength(); ++i) {
     if (m_cdfs(i,0)) delete m_cdfs(i,0);
   }
 }
Member Function Documentation
template<class V , class M > const BaseScalarCdf< double > & QUESO::SampledVectorCdf< V, M >::cdf (unsigned int rowId) const virtual
Returns a scalar CDF stored at row rowId of the vector CDF.
Implements QUESO::BaseVectorCdf< V, M >.
Definition at line 81 of file SampledVectorCdf.C.
 {
   queso_require_less_msg(rowId, m_pdfSupport.vectorSpace().dimLocal(), "rowId is out of range");
   SampledVectorCdf<V,M>* tmp = const_cast<SampledVectorCdf<V,M>*>(this);
   return *(tmp->m_cdfs(rowId,0));
 }
template<class V , class M > void QUESO::SampledVectorCdf< V, M >::print (std::ostream & os) const virtual
Prints the vector CDF (values of the grid points and of the CDF at such grid points).
Implements QUESO::BaseVectorCdf< V, M >.
Definition at line 92 of file SampledVectorCdf.C.
References QUESO::SampledVectorCdf< V, M >::m_cdfs.
 {
   SampledVectorCdf<V,M>* tmp = const_cast<SampledVectorCdf<V,M>*>(this);
   for (unsigned int i = 0; i < (unsigned int) m_cdfs.MyLength(); ++i) {
     os << (*tmp->m_cdfs(i,0))
        << std::endl;
   }
   return;
 }
template<class V , class M > void QUESO::SampledVectorCdf< V, M >::subWriteContents (const std::string & varNamePrefix, const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds) const virtual
Writes the CDF of an allowed sub-environment to a file.
Reimplemented from QUESO::BaseVectorCdf< V, M >.
Definition at line 105 of file SampledVectorCdf.C.
 {
   queso_require_greater_equal_msg(m_env.subRank(), 0, "unexpected subRank");
   SampledVectorCdf<V,M>* tmp = const_cast<SampledVectorCdf<V,M>*>(this);
   char compId[16+1];
   for (unsigned int i = 0; i < (unsigned int) m_cdfs.MyLength(); ++i) {
     sprintf(compId,"%d",i);
     tmp->m_cdfs(i,0)->subWriteContents(varNamePrefix+"comp"+compId,fileName,fileType,allowedSubEnvIds);
   }
   return;
 }
template<class V , class M > void QUESO::SampledVectorCdf< V, M >::values (const V & paramValues, V & cdfVec) const virtual
TODO: Returns the values of the vector CDF at each element of paramValues.
Todo:
: implement me!
Implements QUESO::BaseVectorCdf< V, M >.
Definition at line 71 of file SampledVectorCdf.C.
 {
   queso_error_msg("incomplete code");
   return;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> DistArray<SampledScalarCdf<double>*> QUESO::SampledVectorCdf< V, M >::m_cdfs protected
Definition at line 91 of file SampledVectorCdf.h.
Referenced by QUESO::SampledVectorCdf< V, M >::print(), and QUESO::SampledVectorCdf< V, M >::SampledVectorCdf().
The documentation for this class was generated from the following files:
src/stats/inc/SampledVectorCdf.h
src/stats/src/SampledVectorCdf.C