queso-0.57.0: QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M > Class Template Reference
QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M > Class Template Reference
A class representing a Gaussian likelihood with block-diagonal covariance matrix.
#include <GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients.h>
Public Member Functions
virtual double lnValue (const V &domainVector) const
Logarithm of the value of the scalar function.
Constructor/Destructor methods.
GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients (const char *prefix, const VectorSet< V, M > &domainSet, const V &observations, const GslBlockMatrix &covariance)
Default constructor.
virtual ~GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients ()
Destructor.
Public Member Functions inherited from QUESO::LikelihoodBase< V, M >
virtual void evaluateModel (const V &domainVector, const V *domainDirection, V &modelOutput, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Deprecated. Evaluates the user's model at the point domainVector.
virtual void evaluateModel (const V &domainVector, V &modelOutput) const
Evaluates the user's model at the point domainVector.
virtual double actualValue (const V &domainVector, const V *, V *, M *, V *) const
Actual value of the scalar function.
LikelihoodBase (const char *prefix, const VectorSet< V, M > &domainSet, const V &observations)
Default constructor.
virtual ~LikelihoodBase ()=0
Destructor, pure to make this class abstract.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
void setFiniteDifferenceStepSize (double fdStepSize)
Sets the step size for finite differencing gradients.
void setFiniteDifferenceStepSize (unsigned int i, double fdStepSize)
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
virtual double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Logarithm of the value of the scalar function. Deprecated.
virtual double lnValue (const V &domainVector, V &gradVector) const
Returns the logarithm of the function and its gradient at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector, const V &domainDirection, V &hessianEffect) const
Private Attributes
const GslBlockMatrix & m_covariance
Additional Inherited Members
Protected Attributes inherited from QUESO::LikelihoodBase< V, M >
const V & m_observations
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >
A class representing a Gaussian likelihood with block-diagonal covariance matrix.
Each block diagonal matrix has a multiplicative coefficient that is treated as a hyperparameter to be inferred during the sampling procedure.
Definition at line 47 of file GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients (const char * prefix, const VectorSet< V, M > & domainSet, const V & observations, const GslBlockMatrix & covariance)
Default constructor.
Instantiates a Gaussian likelihood function, given a prefix, its domain, a vector of observations and a block diagonal covariance matrix. The diagonal covariance matrix is of type GslBlockMatrix. Each block in the block diagonal matrix is an object of type GslMatrix.
Each block diagonal matrix has a multiplicative coefficient that is treated as a hyperparameter to be inferred during the sampling procedure.
Definition at line 33 of file GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients.C.
References QUESO::GslBlockMatrix::getBlock(), QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >::m_covariance, QUESO::GslBlockMatrix::numBlocks(), and QUESO::GslMatrix::numRowsLocal().
   : LikelihoodBase<V, M>(prefix, domainSet, observations),
     m_covariance(covariance)
 {
   unsigned int totalDim = 0;
   for (unsigned int i = 0; i < this->m_covariance.numBlocks(); i++) {
     totalDim += this->m_covariance.getBlock(i).numRowsLocal();
   }
   if (totalDim != observations.sizeLocal()) {
     queso_error_msg("Covariance matrix not same dimension as observation vector");
   }
 }
template<class V , class M > QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >::~GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients () virtual
Destructor.
Definition at line 51 of file GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >::lnValue (const V & domainVector) const virtual
Logarithm of the value of the scalar function.
The last n elements of domainVector, where n is the number of blocks in the block diagonal covariance matrix, are treated as hyperparameters and will be sample in a statistical inversion.
The user need not concern themselves with handling these in the model evaluation routine, since they are handled by the likelihood evaluation routine.
Reimplemented from QUESO::BaseScalarFunction< V, M >.
Definition at line 57 of file GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients.C.
 {
   V modelOutput(this->m_observations, 0, 0);  // At least it's not a copy
   V weightedMisfit(this->m_observations, 0, 0);  // At least it's not a copy
   this->evaluateModel(domainVector, modelOutput);
   // Compute misfit G(x) - y
   modelOutput -= this->m_observations;
   // Solve \Sigma u = G(x) - y for u
   this->m_covariance.invertMultiply(modelOutput, weightedMisfit);
   // Deal with the multiplicative coefficients for each of the blocks
   unsigned int numBlocks = this->m_covariance.numBlocks();
   unsigned int offset = 0;
   // For each block...
   double cov_norm_factor = 0.0;
   for (unsigned int i = 0; i < this->m_covariance.numBlocks(); i++) {
     // ...find the right hyperparameter
     unsigned int index = domainVector.sizeLocal() + (i - numBlocks);
     double coefficient = domainVector[index];
     // ...divide the appropriate parts of the solution by the coefficient
     unsigned int blockDim = this->m_covariance.getBlock(i).numRowsLocal();
     for (unsigned int j = 0; j < blockDim; j++) {
       // 'coefficient' is a variance, so we divide by it
       modelOutput[offset+j] /= coefficient;
     }
     // Keep track of the part of the covariance matrix that appears in the
     // normalising constant because of the hyperparameter
     double cov_determinant = this->m_covariance.getBlock(i).determinant();
     cov_determinant = std::sqrt(cov_determinant);
     coefficient = std::sqrt(coefficient);
     cov_norm_factor += std::log(std::pow(coefficient, blockDim) * cov_determinant);
     offset += blockDim;
   }
   // Compute (G(x) - y)^T \Sigma^{-1} (G(x) - y)
   modelOutput *= weightedMisfit;
   double norm2_squared = modelOutput.sumOfComponents();  // This is square of 2-norm
   return -0.5 * norm2_squared - cov_norm_factor;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> const GslBlockMatrix& QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >::m_covariance private
Definition at line 82 of file GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients.h.
Referenced by QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients().
The documentation for this class was generated from the following files:
src/stats/inc/GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients.h
src/stats/src/GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients.C