queso-0.56.2: QUESO::BetaJointPdf< V, M > Class Template Reference
QUESO::BetaJointPdf< V, M > Class Template Reference
A class for handling Beta joint PDFs.
#include <BetaJointPdf.h>
Public Member Functions
Constructor/Destructor methods
BetaJointPdf (const char *prefix, const VectorSet< V, M > &domainSet, const V &alpha, const V &beta)
Constructor.
~BetaJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Actual value of the Beta PDF.
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Logarithm of the value of the Beta PDF.
virtual void distributionMean (V &meanVector) const
Mean value of the underlying random variable.
virtual void distributionVariance (M &covMatrix) const
Covariance matrix of the underlying random variable.
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
virtual void setNormalizationStyle (unsigned int value) const
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
virtual void print (std::ostream &os) const
Print method. Non-pure for backwards compatibility.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
void setFiniteDifferenceStepSize (double fdStepSize)
Sets the step size for finite differencing gradients.
void setFiniteDifferenceStepSize (unsigned int i, double fdStepSize)
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
virtual double lnValue (const V &domainVector) const
Returns the logarithm of the function at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector) const
Returns the logarithm of the function and its gradient at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector, const V &domainDirection, V &hessianEffect) const
Protected Attributes
V m_alpha
V m_beta
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::BetaJointPdf< V, M >
A class for handling Beta joint PDFs.
This class allows the mathematical definition of a Beta Joint PDF.
Definition at line 47 of file BetaJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::BetaJointPdf< V, M >::BetaJointPdf (const char * prefix, const VectorSet< V, M > & domainSet, const V & alpha, const V & beta)
Constructor.
Constructs a new object of the class, given a prefix, the domain set, and the parameters alpha and beta of the Beta PDF.
Definition at line 34 of file BetaJointPdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarFunction< V, M >::m_env, QUESO::BaseScalarFunction< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"uni").c_str(),domainSet),
   m_alpha(alpha),
   m_beta (beta)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering BetaJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving BetaJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::BetaJointPdf< V, M >::~BetaJointPdf ()
Destructor.
Definition at line 58 of file BetaJointPdf.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::BetaJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Actual value of the Beta PDF.
This routine calls method lnValue() and returns the exponent of the returning value of such method.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 64 of file BetaJointPdf.C.
References QUESO::queso_require_equal_to_msg.
 {
   queso_require_equal_to_msg(domainVector.sizeLocal(), this->m_domainSet.vectorSpace().dimLocal(), "invalid input");
   queso_require_msg(!(domainDirection || hessianMatrix || hessianEffect), "incomplete code for hessianMatrix and hessianEffect calculations");
   // No need to multiply by exp(m_logOfNormalizationFactor) because 'lnValue()' is called
   double value = std::exp(this->lnValue(domainVector,domainDirection,gradVector,hessianMatrix,hessianEffect));
   if (gradVector) {
     // DM: This transformation may have issues near the boundary.  I haven't
     // fully explored this yet.
     //
     // This evaluation is also normalised (if m_normalizationStyle is zero) and
     // so the gradient in physical space contains the normalisation constant.
     (*gradVector) *= value;
   }
   return value;
 }
template<class V , class M > double QUESO::BetaJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
Computes the logarithm of the normalization factor.
This routine calls BaseJointPdf::commonComputeLogOfNormalizationFactor().
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 170 of file BetaJointPdf.C.
References QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor().
 {
   double value = 0.;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering BetaJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << std::endl;
   }
   value = BaseJointPdf<V,M>::commonComputeLogOfNormalizationFactor(numSamples, updateFactorInternally);
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving BetaJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << ", m_logOfNormalizationFactor = " << m_logOfNormalizationFactor
                             << std::endl;
   }
   return value;
 }
template<class V , class M > void QUESO::BetaJointPdf< V, M >::distributionMean (V & meanVector) const virtual
Mean value of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 138 of file BetaJointPdf.C.
 {
   unsigned int n_params = meanVector.sizeLocal();
   queso_assert_equal_to (n_params, m_alpha.sizeLocal());
   for (unsigned int i = 0; i < n_params; ++i) {
     meanVector[i] = m_alpha[i] / (m_alpha[i] + m_beta[i]);
   }
 }
template<class V , class M > void QUESO::BetaJointPdf< V, M >::distributionVariance (M & covMatrix) const virtual
Covariance matrix of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 150 of file BetaJointPdf.C.
 {
   unsigned int n_params = m_alpha.sizeLocal();
   queso_assert_equal_to (n_params, m_beta.sizeLocal());
   queso_assert_equal_to (n_params, covMatrix.numCols());
   queso_assert_equal_to (covMatrix.numCols(), covMatrix.numRowsGlobal());
   covMatrix.zeroLower();
   covMatrix.zeroUpper();
   for (unsigned int i = 0; i < n_params; ++i) {
     covMatrix(i,i) = (m_alpha[i] * m_beta[i]) /
       ((m_alpha[i] + m_beta[i]) *
        (m_alpha[i] + m_beta[i]) *
        (m_alpha[i] + m_beta[i] + 1));
   }
 }
template<class V , class M > double QUESO::BetaJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Logarithm of the value of the Beta PDF.
If the normalization style (m_normalizationStyle) is zero, then this routine calls a environment method which handles basic PDFs, e.g. basicPdfs()->betaPdfActualValue() and adds the log of the normalization factor (m_logOfNormalizationFactor) to it; otherwise the method uses the formula: .
Reimplemented from QUESO::BaseScalarFunction< V, M >.
Definition at line 91 of file BetaJointPdf.C.
 {
   queso_require_msg(!(domainDirection || hessianMatrix || hessianEffect), "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   double aux = 0.;
   double result = 0.;
   for (unsigned int i = 0; i < domainVector.sizeLocal(); ++i) {
     if (m_normalizationStyle == 0) {
       aux = log(m_env.basicPdfs()->betaPdfActualValue(domainVector[i],m_alpha[i],m_beta[i]));
     }
     else {
       aux = (m_alpha[i]-1.)*log(domainVector[i]) + (m_beta[i]-1.)*log(1.-domainVector[i]);
     }
     // The log of the beta pdf is
     // f(x) = (alpha - 1) * log(x) + (beta - 1) * log(1 - x)
     // Therefore
     // df/dx (x) = ((alpha - 1) / x) + ((1 - beta) / (1 - x))
     if (gradVector) {
       // We're computing grad of log of p which is p' / p
       (*gradVector)[i] = (m_alpha[i] - 1.0) / domainVector[i] +
         (1.0 - m_beta[i]) / (1.0 - domainVector[i]);
     }
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99)) {
       *m_env.subDisplayFile() << "In BetaJointPdf<V,M>::lnValue()"
                               << ", m_normalizationStyle = "      << m_normalizationStyle
                               << ": domainVector[" << i << "] = " << domainVector[i]
                               << ", m_alpha[" << i << "] = "      << m_alpha[i]
                               << ", m_beta[" << i << "] = "       << m_beta[i]
                               << ", log(pdf)= "                   << aux
                               << std::endl;
     }
     result += aux;
   }
   result += m_logOfNormalizationFactor;
   return result;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> V QUESO::BetaJointPdf< V, M >::m_alpha protected
Definition at line 92 of file BetaJointPdf.h.
template<class V = GslVector, class M = GslMatrix> V QUESO::BetaJointPdf< V, M >::m_beta protected
Definition at line 93 of file BetaJointPdf.h.
The documentation for this class was generated from the following files:
src/stats/inc/BetaJointPdf.h
src/stats/src/BetaJointPdf.C