queso-0.57.0: QUESO::GammaJointPdf< V, M > Class Template Reference
QUESO::GammaJointPdf< V, M > Class Template Reference
A class for handling Gamma joint PDFs.
#include <GammaJointPdf.h>
Public Member Functions
Constructor/Destructor methods
GammaJointPdf (const char *prefix, const VectorSet< V, M > &domainSet, const V &a, const V &b)
~GammaJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Actual value of the Gamma PDF.
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Logarithm of the value of the Gamma PDF.
virtual void distributionMean (V &meanVector) const
Mean value of the underlying random variable.
virtual void distributionVariance (M &covMatrix) const
Covariance matrix of the underlying random variable.
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
virtual void setNormalizationStyle (unsigned int value) const
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
virtual void print (std::ostream &os) const
Print method. Non-pure for backwards compatibility.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
void setFiniteDifferenceStepSize (double fdStepSize)
Sets the step size for finite differencing gradients.
void setFiniteDifferenceStepSize (unsigned int i, double fdStepSize)
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
virtual double lnValue (const V &domainVector) const
Returns the logarithm of the function at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector) const
Returns the logarithm of the function and its gradient at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector, const V &domainDirection, V &hessianEffect) const
Protected Attributes
V m_a
V m_b
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::GammaJointPdf< V, M >
A class for handling Gamma joint PDFs.
This class allows the mathematical definition of a Gamma Joint PDF.
Definition at line 47 of file GammaJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::GammaJointPdf< V, M >::GammaJointPdf (const char * prefix, const VectorSet< V, M > & domainSet, const V & a, const V & b)
Constructor for a shape-scale parameterisation of a Gamma(a,b) pdf defined on domainSet.
Constructs a new object of the class, given a prefix, the domain set, and the parameters a and b of the Gamma PDF.
The parameters a and b are the shape and scale parameters, respectively. That is, the pdf is
where C is a normalising constant.
Indeed, a and b are vectors and in multiple dimensions the pdf is just the product of Gamma(a_i, b_i) pdfs distributions in each dimension. That is, they are independent.
Note: the parameters a and b correspond to the shape and scale parameters k and in the Wikipedia entry for the Gamma distribution.
Definition at line 34 of file GammaJointPdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarFunction< V, M >::m_env, QUESO::BaseScalarFunction< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"uni").c_str(),domainSet),
   m_a(a),
   m_b(b)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering GammaJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving GammaJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::GammaJointPdf< V, M >::~GammaJointPdf ()
Destructor.
Definition at line 58 of file GammaJointPdf.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::GammaJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Actual value of the Gamma PDF.
This routine calls method lnValue() and returns the exponent of the returning value of such method.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 64 of file GammaJointPdf.C.
References QUESO::queso_require_equal_to_msg.
 {
   queso_require_equal_to_msg(domainVector.sizeLocal(), this->m_domainSet.vectorSpace().dimLocal(), "invalid input");
   queso_require_msg(!(domainDirection || gradVector || hessianMatrix || hessianEffect), "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   // No need to multiply by exp(m_logOfNormalizationFactor) because 'lnValue()' is called [PDF-06]
   return exp(this->lnValue(domainVector,domainDirection,gradVector,hessianMatrix,hessianEffect));
 }
template<class V , class M > double QUESO::GammaJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
Computes the logarithm of the normalization factor.
This routine calls BaseJointPdf::commonComputeLogOfNormalizationFactor().
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 145 of file GammaJointPdf.C.
References QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor().
 {
   double value = 0.;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering GammaJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << std::endl;
   }
   value = BaseJointPdf<V,M>::commonComputeLogOfNormalizationFactor(numSamples, updateFactorInternally);
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving GammaJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << ", m_logOfNormalizationFactor = " << m_logOfNormalizationFactor
                             << std::endl;
   }
   return value;
 }
template<class V , class M > void QUESO::GammaJointPdf< V, M >::distributionMean (V & meanVector) const virtual
Mean value of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 117 of file GammaJointPdf.C.
 {
   queso_assert_equal_to(m_a.sizeLocal(), m_b.sizeLocal());
   queso_assert_equal_to(m_a.sizeLocal(), meanVector.sizeLocal());
   for (unsigned int i = 0; i < m_a.sizeLocal(); ++i) {
     meanVector[i] = m_a[i] * m_b[i];
   }
 }
template<class V , class M > void QUESO::GammaJointPdf< V, M >::distributionVariance (M & covMatrix) const virtual
Covariance matrix of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 129 of file GammaJointPdf.C.
 {
   queso_assert_equal_to(m_a.sizeLocal(), m_b.sizeLocal());
   queso_assert_equal_to(m_a.sizeLocal(), covMatrix.numRowsGlobal());
   queso_assert_equal_to(covMatrix.numCols(), covMatrix.numRowsGlobal());
   covMatrix.zeroLower();
   covMatrix.zeroUpper();
   for (unsigned int i = 0; i < m_a.sizeLocal(); ++i) {
     covMatrix(i,i) = m_a[i] * m_b[i] * m_b[i];
   }
 }
template<class V , class M > double QUESO::GammaJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Logarithm of the value of the Gamma PDF.
If the normalization style (m_normalizationStyle) is zero, then this routine calls a environment method which handles basic PDFs, e.g. basicPdfs()->gammaPdfActualValue() and adds the log of the normalization factor (m_logOfNormalizationFactor) to it; otherwise the method uses the formula: , where a and b are the parameters of the Gamma PDF.
Reimplemented from QUESO::BaseScalarFunction< V, M >.
Definition at line 81 of file GammaJointPdf.C.
 {
   queso_require_msg(!(domainDirection || gradVector || hessianMatrix || hessianEffect), "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   double aux = 0.;
   double result = 0.;
   for (unsigned int i = 0; i < domainVector.sizeLocal(); ++i) {
     if (m_normalizationStyle == 0) {
       aux = log(m_env.basicPdfs()->gammaPdfActualValue(domainVector[i],m_a[i],m_b[i]));
     }
     else {
       aux = (m_a[i]-1.)*log(domainVector[i]) - domainVector[i]/m_b[i];
     }
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99)) {
       *m_env.subDisplayFile() << "In GammaJointPdf<V,M>::lnValue()"
                               << ", m_normalizationStyle = "      << m_normalizationStyle
                               << ": domainVector[" << i << "] = " << domainVector[i]
                               << ", m_a[" << i << "] = "          << m_a[i]
                               << ", m_b[" << i << "] = "          << m_b[i]
                               << ", log(pdf)= "                   << aux
                               << std::endl;
     }
     result += aux;
   }
   result += m_logOfNormalizationFactor; // [PDF-06]
   return result;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> V QUESO::GammaJointPdf< V, M >::m_a protected
Definition at line 113 of file GammaJointPdf.h.
template<class V = GslVector, class M = GslMatrix> V QUESO::GammaJointPdf< V, M >::m_b protected
Definition at line 114 of file GammaJointPdf.h.
The documentation for this class was generated from the following files:
src/stats/inc/GammaJointPdf.h
src/stats/src/GammaJointPdf.C