queso-0.56.2: QUESO::Map Class Reference
QUESO::Map Class Reference
A class for partitioning vectors and matrices.
#include <Map.h>
Public Member Functions
Constructor/Destructor methods
Map (int numGlobalElements, int indexBase, const MpiComm &comm)
Constructor for a uniform linear distribution of elements.
Map (const Map &src)
Copy constructor.
~Map ()
Destructor.
Set methods
Map & operator= (const Map &rhs)
Assignment operator.
Size, dimension and local ID accessor methods
int NumGlobalElements () const
Returns the total number of elements across all processors.
int IndexBase () const
int NumMyElements () const
Returns the number of elements owned by the calling processor.
int MinMyGID () const
The minimum global index value on the calling processor.
Miscellaneous methods
const MpiComm & Comm () const
Access function for MpiComm communicator.
const Epetra_Map & epetraMap () const
Trilinos Epetra_Map: A class for partitioning vectors and matrices.
Private Member Functions
Map ()
Default constructor. Do not call this directly.
void copy (const Map &src)
Copies the map.
Private Attributes
MpiComm m_MpiComm
This communicator can be queried for processor rank and size information.
Epetra_Map * m_epetraMap
Epetra_Map.
int m_numGlobalElements
Total number of elements across all processors.
int m_indexBase
Base integer value for indexed array references.
int m_numMyElements
Number of elements owned by the calling processor.
Detailed Description
A class for partitioning vectors and matrices.
It is often the case that multiple matrix and vector objects have an identical distribution of elements on a parallel machine. The Map keeps information that describes this distribution for matrices and vectors. Inspired by Trilinos Epetra_Map class.
Definition at line 49 of file Map.h.
Constructor & Destructor Documentation
QUESO::Map::Map (int numGlobalElements, int indexBase, const MpiComm & comm)
Constructor for a uniform linear distribution of elements.
QUESO::Map::Map (const Map & src)
Copy constructor.
QUESO::Map::~Map ()
Destructor.
QUESO::Map::Map () private
Default constructor. Do not call this directly.
Definition at line 63 of file Map.C.
References m_epetraMap.
 {
 #ifdef QUESO_HAS_TRILINOS
   delete m_epetraMap;
   m_epetraMap = NULL;
 #else
   // Nothing to do
 #endif
 }
Member Function Documentation
const MpiComm & QUESO::Map::Comm () const
Access function for MpiComm communicator.
Definition at line 131 of file Map.C.
References m_MpiComm.
Referenced by QUESO::Matrix::numOfProcsForStorage(), QUESO::Vector::numOfProcsForStorage(), QUESO::GPMSAFactory< V, M >::setUpEmulator(), and QUESO::GslMatrix::transpose().
 {
   return m_MpiComm;
 }
void QUESO::Map::copy (const Map & src) private
Copies the map.
Definition at line 146 of file Map.C.
References m_epetraMap, m_indexBase, m_MpiComm, m_numGlobalElements, and m_numMyElements.
Referenced by operator=().
 {
   m_MpiComm         = src.m_MpiComm;
 #ifdef QUESO_HAS_TRILINOS
   delete m_epetraMap;
   m_epetraMap         = new Epetra_Map(*src.m_epetraMap);
 #else
   m_numGlobalElements = src.m_numGlobalElements;
   m_indexBase         = src.m_indexBase;
   m_numMyElements     = src.m_numMyElements;
 #endif
   return;
 }
const Epetra_Map & QUESO::Map::epetraMap () const
Trilinos Epetra_Map: A class for partitioning vectors and matrices.
Definition at line 138 of file Map.C.
References m_epetraMap.
 {
   return *m_epetraMap;
 }
int QUESO::Map::IndexBase () const
Returns the base integer value for indexed array references. The first position in the global processor in my processors.
Definition at line 96 of file Map.C.
References m_epetraMap, and m_indexBase.
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraMap->IndexBase();
 #else
   return m_indexBase;
 #endif
 }
int QUESO::Map::MinMyGID () const
The minimum global index value on the calling processor.
Definition at line 118 of file Map.C.
References m_epetraMap.
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraMap->MinMyGID();
 #else
   return 0;
 #endif
 }
int QUESO::Map::NumGlobalElements () const
Returns the total number of elements across all processors.
Definition at line 85 of file Map.C.
References m_epetraMap, and m_numGlobalElements.
Referenced by QUESO::ConcatenatedJointPdf< V, M >::distributionVariance(), QUESO::GslVector::GslVector(), QUESO::ConcatenationSubset< V, M >::moments(), QUESO::GslVector::sizeGlobal(), QUESO::TeuchosVector::sizeGlobal(), QUESO::TeuchosMatrix::TeuchosMatrix(), QUESO::TeuchosVector::TeuchosVector(), and QUESO::VectorSpace< V, M >::VectorSpace().
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraMap->NumGlobalElements();
 #else
   return m_numGlobalElements;
 #endif
 }
int QUESO::Map::NumMyElements () const
Returns the number of elements owned by the calling processor.
Definition at line 107 of file Map.C.
References m_epetraMap, and m_numMyElements.
Referenced by QUESO::GslVector::GslVector(), QUESO::GslVector::sizeLocal(), QUESO::TeuchosVector::sizeLocal(), and QUESO::TeuchosVector::TeuchosVector().
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraMap->NumMyElements();
 #else
   return m_numMyElements;
 #endif
 }
Map & QUESO::Map::operator= (const Map & rhs)
Assignment operator.
Definition at line 76 of file Map.C.
References copy().
 {
   this->copy(rhs);
   return *this;
 }
Member Data Documentation
Epetra_Map* QUESO::Map::m_epetraMap private
Epetra_Map.
Definition at line 113 of file Map.h.
Referenced by copy(), epetraMap(), IndexBase(), Map(), MinMyGID(), NumGlobalElements(), and NumMyElements().
int QUESO::Map::m_indexBase private
Base integer value for indexed array references.
Definition at line 119 of file Map.h.
Referenced by copy(), and IndexBase().
MpiComm QUESO::Map::m_MpiComm private
This communicator can be queried for processor rank and size information.
Definition at line 109 of file Map.h.
Referenced by Comm(), and copy().
int QUESO::Map::m_numGlobalElements private
Total number of elements across all processors.
Definition at line 116 of file Map.h.
Referenced by copy(), and NumGlobalElements().
int QUESO::Map::m_numMyElements private
Number of elements owned by the calling processor.
Definition at line 122 of file Map.h.
Referenced by copy(), and NumMyElements().
The documentation for this class was generated from the following files:
src/core/inc/Map.h
src/core/src/Map.C