queso-0.57.0: QUESO::GaussianVectorRealizer< V, M > Class Template Reference
QUESO::GaussianVectorRealizer< V, M > Class Template Reference
A class for handling sampling from Gaussian probability density distributions.
#include <GaussianVectorRealizer.h>
Public Member Functions
Constructor/Destructor methods
GaussianVectorRealizer (const char *prefix, const VectorSet< V, M > &unifiedImageSet, const V &lawExpVector, const M &lowerCholLawCovMatrix)
Constructor.
GaussianVectorRealizer (const char *prefix, const VectorSet< V, M > &unifiedImageSet, const V &lawExpVector, const M &matU, const V &vecSsqrt, const M &matVt)
Constructor.
~GaussianVectorRealizer ()
Destructor.
Realization-related methods
const V & unifiedLawExpVector () const
Access to the vector of mean values and private attribute: m_unifiedLawExpVector.
const V & unifiedLawVarVector () const
Access to the vector of variance values and private attribute: m_unifiedLawVarVector.
void realization (V &nextValues) const
Draws a realization.
void updateLawExpVector (const V &newLawExpVector)
Updates the mean with the new value newLawExpVector.
void updateLowerCholLawCovMatrix (const M &newLowerCholLawCovMatrix)
Updates the lower triangular matrix from Cholesky decomposition of the covariance matrix to the new value newLowerCholLawCovMatrix.
void updateLowerCholLawCovMatrix (const M &matU, const V &vecSsqrt, const M &matVt)
Updates the SVD matrices from SVD decomposition of the covariance matrix to the new values: matU, vecSsqrt, and matVt.
Public Member Functions inherited from QUESO::BaseVectorRealizer< V, M >
BaseVectorRealizer (const char *prefix, const VectorSet< V, M > &unifiedImageSet, unsigned int subPeriod)
Default constructor.
virtual ~BaseVectorRealizer ()
Virtual destructor.
const VectorSet< V, M > & unifiedImageSet () const
Image set where the realizations lie. Access to protected attribute m_unifiedImageSet.
unsigned int subPeriod () const
Sub-period of the realization. Access to protected attribute m_subPeriod.
Private Attributes
V * m_unifiedLawExpVector
V * m_unifiedLawVarVector
M * m_lowerCholLawCovMatrix
M * m_matU
V * m_vecSsqrt
M * m_matVt
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseVectorRealizer< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_unifiedImageSet
unsigned int m_subPeriod
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::GaussianVectorRealizer< V, M >
A class for handling sampling from Gaussian probability density distributions.
This class handles sampling from a Gaussian probability density distribution.
Definition at line 48 of file GaussianVectorRealizer.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::GaussianVectorRealizer< V, M >::GaussianVectorRealizer (const char * prefix, const VectorSet< V, M > & unifiedImageSet, const V & lawExpVector, const M & lowerCholLawCovMatrix)
Constructor.
Constructs a new object, given a prefix and the image set of the vector realizer, a vector of mean values, lawExpVector, and a lower triangular matrix resulting from Cholesky decomposition of the covariance matrix, lowerCholLawCovMatrix.
Definition at line 34 of file GaussianVectorRealizer.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRealizer< V, M >::m_env, QUESO::BaseVectorRealizer< V, M >::m_prefix, QUESO::GaussianVectorRealizer< V, M >::m_unifiedLawExpVector, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRealizer<V,M>( ((std::string)(prefix)+"gau").c_str(), unifiedImageSet, std::numeric_limits<unsigned int>::max()), // 2011/Oct/02 - Correction thanks to Corey
   m_unifiedLawExpVector  (new V(lawExpVector)),
   m_unifiedLawVarVector  (unifiedImageSet.vectorSpace().newVector( INFINITY)), // FIX ME
   m_lowerCholLawCovMatrix(new M(lowerCholLawCovMatrix)),
   m_matU                 (NULL),
   m_vecSsqrt             (NULL),
   m_matVt                (NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering GaussianVectorRealizer<V,M>::constructor() [1]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   *m_unifiedLawExpVector = lawExpVector; // ????
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving GaussianVectorRealizer<V,M>::constructor() [1]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::GaussianVectorRealizer< V, M >::GaussianVectorRealizer (const char * prefix, const VectorSet< V, M > & unifiedImageSet, const V & lawExpVector, const M & matU, const V & vecSsqrt, const M & matVt)
Constructor.
Constructs a new object, given a prefix and the image set of the vector realizer, a vector of mean values, lawExpVector, and a set of two matrices and one vector resulting from the Single Value Decomposition of the covariance matrix, matU, vecSsqrt and matVt.
Definition at line 63 of file GaussianVectorRealizer.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRealizer< V, M >::m_env, QUESO::BaseVectorRealizer< V, M >::m_prefix, QUESO::GaussianVectorRealizer< V, M >::m_unifiedLawExpVector, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRealizer<V,M>( ((std::string)(prefix)+"gau").c_str(), unifiedImageSet, std::numeric_limits<unsigned int>::max()), // 2011/Oct/02 - Correction thanks to Corey
   m_unifiedLawExpVector  (new V(lawExpVector)),
   m_unifiedLawVarVector  (unifiedImageSet.vectorSpace().newVector( INFINITY)), // FIX ME
   m_lowerCholLawCovMatrix(NULL),
   m_matU                 (new M(matU)),
   m_vecSsqrt             (new V(vecSsqrt)),
   m_matVt                (new M(matVt))
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering GaussianVectorRealizer<V,M>::constructor() [2]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   *m_unifiedLawExpVector = lawExpVector; // ????
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving GaussianVectorRealizer<V,M>::constructor() [2]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::GaussianVectorRealizer< V, M >::~GaussianVectorRealizer ()
Destructor.
Definition at line 94 of file GaussianVectorRealizer.C.
 {
   delete m_matVt;
   delete m_vecSsqrt;
   delete m_matU;
   delete m_lowerCholLawCovMatrix;
   delete m_unifiedLawVarVector;
   delete m_unifiedLawExpVector;
 }
Member Function Documentation
template<class V , class M > void QUESO::GaussianVectorRealizer< V, M >::realization (V & nextValues) const virtual
Draws a realization.
This function draws a realization of a Gaussian distribution of mean m_unifiedLawExpVector and variance m_unifiedLawVarVector and saves it in nextValues.
Implements QUESO::BaseVectorRealizer< V, M >.
Definition at line 120 of file GaussianVectorRealizer.C.
 {
   V iidGaussianVector(m_unifiedImageSet.vectorSpace().zeroVector());
   bool outOfSupport = true;
   do {
     iidGaussianVector.cwSetGaussian(0.0, 1.0);
     if (m_lowerCholLawCovMatrix) {
       nextValues = (*m_unifiedLawExpVector) + (*m_lowerCholLawCovMatrix)*iidGaussianVector;
     }
     else if (m_matU && m_vecSsqrt && m_matVt) {
       nextValues = (*m_unifiedLawExpVector) + (*m_matU)*( (*m_vecSsqrt) * ((*m_matVt)*iidGaussianVector) );
     }
     else {
       queso_error_msg("inconsistent internal state");
     }
     outOfSupport = !(this->m_unifiedImageSet.contains(nextValues));
   } while (outOfSupport); // prudenci 2011-Oct-04
   return;
 }
template<class V , class M > const V & QUESO::GaussianVectorRealizer< V, M >::unifiedLawExpVector () const
Access to the vector of mean values and private attribute: m_unifiedLawExpVector.
Definition at line 106 of file GaussianVectorRealizer.C.
 {
   return *m_unifiedLawExpVector;
 }
template<class V , class M > const V & QUESO::GaussianVectorRealizer< V, M >::unifiedLawVarVector () const
Access to the vector of variance values and private attribute: m_unifiedLawVarVector.
Definition at line 113 of file GaussianVectorRealizer.C.
 {
   return *m_unifiedLawVarVector;
 }
template<class V , class M > void QUESO::GaussianVectorRealizer< V, M >::updateLawExpVector (const V & newLawExpVector)
Updates the mean with the new value newLawExpVector.
Definition at line 146 of file GaussianVectorRealizer.C.
 {
   // delete old expected values (allocated at construction or last call to this function)
   delete m_unifiedLawExpVector;
   m_unifiedLawExpVector = new V(newLawExpVector);
   return;
 }
template<class V , class M > void QUESO::GaussianVectorRealizer< V, M >::updateLowerCholLawCovMatrix (const M & newLowerCholLawCovMatrix)
Updates the lower triangular matrix from Cholesky decomposition of the covariance matrix to the new value newLowerCholLawCovMatrix.
The lower triangular matrix results resulting from a Cholesky decomposition of the covariance matrix. This routine deletes old expected values: m_lowerCholLawCovMatrix; m_matU, m_vecSsqrt, m_matVt.
Definition at line 158 of file GaussianVectorRealizer.C.
 {
   // delete old expected values (allocated at construction or last call to this function)
   delete m_lowerCholLawCovMatrix;
   delete m_matU;
   delete m_vecSsqrt;
   delete m_matVt;
   m_lowerCholLawCovMatrix = new M(newLowerCholLawCovMatrix);
   m_matU                  = NULL;
   m_vecSsqrt              = NULL;
   m_matVt                 = NULL;
   return;
 }
template<class V , class M > void QUESO::GaussianVectorRealizer< V, M >::updateLowerCholLawCovMatrix (const M & matU, const V & vecSsqrt, const M & matVt)
Updates the SVD matrices from SVD decomposition of the covariance matrix to the new values: matU, vecSsqrt, and matVt.
The lower triangular matrix results resulting from a Cholesky decomposition of the covariance matrix. This routine deletes old expected values: m_lowerCholLawCovMatrix; m_matU, m_vecSsqrt, m_matVt.
Definition at line 176 of file GaussianVectorRealizer.C.
 {
   // delete old expected values (allocated at construction or last call to this function)
   delete m_lowerCholLawCovMatrix;
   delete m_matU;
   delete m_vecSsqrt;
   delete m_matVt;
   m_lowerCholLawCovMatrix = NULL;
   m_matU                  = new M(matU);
   m_vecSsqrt              = new V(vecSsqrt);
   m_matVt                 = new M(matVt);
   return;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> M* QUESO::GaussianVectorRealizer< V, M >::m_lowerCholLawCovMatrix private
Definition at line 111 of file GaussianVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> M* QUESO::GaussianVectorRealizer< V, M >::m_matU private
Definition at line 112 of file GaussianVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> M* QUESO::GaussianVectorRealizer< V, M >::m_matVt private
Definition at line 114 of file GaussianVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> V* QUESO::GaussianVectorRealizer< V, M >::m_unifiedLawExpVector private
Definition at line 109 of file GaussianVectorRealizer.h.
Referenced by QUESO::GaussianVectorRealizer< V, M >::GaussianVectorRealizer().
template<class V = GslVector, class M = GslMatrix> V* QUESO::GaussianVectorRealizer< V, M >::m_unifiedLawVarVector private
Definition at line 110 of file GaussianVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> V* QUESO::GaussianVectorRealizer< V, M >::m_vecSsqrt private
Definition at line 113 of file GaussianVectorRealizer.h.
The documentation for this class was generated from the following files:
src/stats/inc/GaussianVectorRealizer.h
src/stats/src/GaussianVectorRealizer.C