queso-0.57.0: QUESO::WignerJointPdf< V, M > Class Template Reference
QUESO::WignerJointPdf< V, M > Class Template Reference
A class for handling Wigner joint PDFs.
#include <WignerJointPdf.h>
Public Member Functions
Constructor/Destructor methods
WignerJointPdf (const char *prefix, const VectorSet< V, M > &domainSet, const V &centerPos, double radius)
Constructor.
~WignerJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Actual value of the PDF (scalar function).
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Computes the logarithm of the value of the function.
virtual void distributionMean (V &meanVector) const
Mean value of the underlying random variable.
virtual void distributionVariance (M &covMatrix) const
Covariance matrix of the underlying random variable.
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
virtual void setNormalizationStyle (unsigned int value) const
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
virtual void print (std::ostream &os) const
Print method. Non-pure for backwards compatibility.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
void setFiniteDifferenceStepSize (double fdStepSize)
Sets the step size for finite differencing gradients.
void setFiniteDifferenceStepSize (unsigned int i, double fdStepSize)
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
virtual double lnValue (const V &domainVector) const
Returns the logarithm of the function at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector) const
Returns the logarithm of the function and its gradient at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector, const V &domainDirection, V &hessianEffect) const
Protected Attributes
V * m_centerPos
double m_radius
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::WignerJointPdf< V, M >
A class for handling Wigner joint PDFs.
This class allows the mathematical definition of a Wigner Joint PDF.
Definition at line 47 of file WignerJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::WignerJointPdf< V, M >::WignerJointPdf (const char * prefix, const VectorSet< V, M > & domainSet, const V & centerPos, double radius)
Constructor.
Constructs a new object of the class, given a prefix, the domain set of the PDF, the center position centerPos, and a radius radius.
Definition at line 33 of file WignerJointPdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarFunction< V, M >::m_env, QUESO::BaseScalarFunction< V, M >::m_prefix, QUESO::WignerJointPdf< V, M >::m_radius, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"uni").c_str(),
          domainSet),
   m_centerPos(new V(centerPos)),
   m_radius   (radius)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering WignerJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   queso_require_greater_msg(m_radius, 0., "invalid radius");
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving WignerJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::WignerJointPdf< V, M >::~WignerJointPdf ()
Destructor.
Definition at line 60 of file WignerJointPdf.C.
 {
   delete m_centerPos;
 }
Member Function Documentation
template<class V , class M > double QUESO::WignerJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Actual value of the PDF (scalar function).
It depends on the distance of the center position to the domain and on the radius.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 67 of file WignerJointPdf.C.
References QUESO::queso_require_equal_to_msg.
 {
   queso_require_equal_to_msg(domainVector.sizeLocal(), this->m_domainSet.vectorSpace().dimLocal(), "invalid input");
   if (gradVector   ) *gradVector     = m_domainSet.vectorSpace().zeroVector();
   if (hessianMatrix) *hessianMatrix *= 0.;
   if (hessianEffect) *hessianEffect  = m_domainSet.vectorSpace().zeroVector();
   double returnValue = 0.;
   double distanceRatio = (domainVector - *m_centerPos).norm2()/m_radius;
   if (distanceRatio < 1.) {
     returnValue = 2.*m_radius*m_radius*sqrt(1. - distanceRatio*distanceRatio)/M_PI;
   }
   returnValue *= exp(m_logOfNormalizationFactor); // [PDF-09]
   return returnValue;
 }
template<class V , class M > double QUESO::WignerJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
Computes the logarithm of the normalization factor.
This routine calls BaseJointPdf::commonComputeLogOfNormalizationFactor().
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 126 of file WignerJointPdf.C.
References QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor().
 {
   double value = 0.;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering WignerJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << std::endl;
   }
   value = BaseJointPdf<V,M>::commonComputeLogOfNormalizationFactor(numSamples, updateFactorInternally);
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving WignerJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << ", m_logOfNormalizationFactor = " << m_logOfNormalizationFactor
                             << std::endl;
   }
   return value;
 }
template<class V , class M > void QUESO::WignerJointPdf< V, M >::distributionMean (V & meanVector) const virtual
Mean value of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 109 of file WignerJointPdf.C.
 {
   meanVector = *m_centerPos;
 }
template<class V , class M > void QUESO::WignerJointPdf< V, M >::distributionVariance (M & covMatrix) const virtual
Covariance matrix of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 117 of file WignerJointPdf.C.
 {
   queso_not_implemented();
 }
template<class V , class M > double QUESO::WignerJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Computes the logarithm of the value of the function.
This method calls actualValue() and applies the logarithm to its result.
Reimplemented from QUESO::BaseScalarFunction< V, M >.
Definition at line 92 of file WignerJointPdf.C.
 {
   if (gradVector   ) *gradVector     = m_domainSet.vectorSpace().zeroVector();
   if (hessianMatrix) *hessianMatrix *= 0.;
   if (hessianEffect) *hessianEffect  = m_domainSet.vectorSpace().zeroVector();
   // No need to add m_logOfNormalizationFactor because 'actualValue()' is called [PDF-09]
   return log(this->actualValue(domainVector,domainDirection,gradVector,hessianMatrix,hessianEffect));
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> V* QUESO::WignerJointPdf< V, M >::m_centerPos protected
Definition at line 87 of file WignerJointPdf.h.
template<class V = GslVector, class M = GslMatrix> double QUESO::WignerJointPdf< V, M >::m_radius protected
Definition at line 88 of file WignerJointPdf.h.
Referenced by QUESO::WignerJointPdf< V, M >::WignerJointPdf().
The documentation for this class was generated from the following files:
src/stats/inc/WignerJointPdf.h
src/stats/src/WignerJointPdf.C