queso-0.56.2: src/contrib/ANN/include/ANN/ANN.h File Reference
ANN.h File Reference
Classes
class ANNpointSet
class ANNbruteForce
class ANNkd_tree
class ANNbd_tree
Typedefs
typedef double ANNcoord
typedef double ANNdist
typedef int ANNidx
typedef ANNcoord * ANNpoint
typedef ANNpoint * ANNpointArray
typedef ANNdist * ANNdistArray
typedef ANNidx * ANNidxArray
typedef ANNkd_node * ANNkd_ptr
Enumerations
enum ANNbool { ANNfalse = 0, ANNtrue = 1 }
enum ANNsplitRule {
ANN_KD_STD = 0, ANN_KD_MIDPT = 1, ANN_KD_FAIR = 2, ANN_KD_SL_MIDPT = 3,
ANN_KD_SL_FAIR = 4, ANN_KD_SUGGEST = 5
}
enum ANNshrinkRule { ANN_BD_NONE = 0, ANN_BD_SIMPLE = 1, ANN_BD_CENTROID = 2, ANN_BD_SUGGEST = 3 }
Functions
DLL_API ANNdist annDist (int dim, ANNpoint p, ANNpoint q)
DLL_API ANNpoint annAllocPt (int dim, ANNcoord c=0)
DLL_API ANNpointArray annAllocPts (int n, int dim)
DLL_API void annDeallocPt (ANNpoint &p)
DLL_API void annDeallocPts (ANNpointArray &pa)
DLL_API ANNpoint annCopyPt (int dim, ANNpoint source)
DLL_API void annMaxPtsVisit (int maxPts)
DLL_API void annClose ()
Variables
const double ANN_DBL_MAX = MAXDOUBLE
const ANNidx ANN_NULL_IDX = -1
const ANNdist ANN_DIST_INF = ANN_DBL_MAX
const int ANNcoordPrec = DBL_DIG
const ANNbool ANN_ALLOW_SELF_MATCH = ANNtrue
const int ANN_N_SPLIT_RULES = 6
const int ANN_N_SHRINK_RULES = 4
Typedef Documentation
typedef double ANNcoord
Definition at line 158 of file ANN.h.
typedef double ANNdist
Definition at line 159 of file ANN.h.
typedef ANNdist* ANNdistArray
Definition at line 377 of file ANN.h.
typedef int ANNidx
Definition at line 175 of file ANN.h.
typedef ANNidx* ANNidxArray
Definition at line 378 of file ANN.h.
typedef ANNkd_node* ANNkd_ptr
Definition at line 702 of file ANN.h.
typedef ANNcoord* ANNpoint
Definition at line 375 of file ANN.h.
typedef ANNpoint* ANNpointArray
Definition at line 376 of file ANN.h.
Enumeration Type Documentation
enum ANNbool
Enumerator
ANNfalse
ANNtrue
Definition at line 132 of file ANN.h.
 {ANNfalse = 0, ANNtrue = 1}; // ANN boolean type (non ANSI C++)
enum ANNshrinkRule
Enumerator
ANN_BD_NONE
ANN_BD_SIMPLE
ANN_BD_CENTROID
ANN_BD_SUGGEST
Definition at line 605 of file ANN.h.
                    {
                 ANN_BD_NONE                             = 0,    // no shrinking at all (just kd-tree)
                 ANN_BD_SIMPLE                   = 1,    // simple splitting
                 ANN_BD_CENTROID                 = 2,    // centroid splitting
                 ANN_BD_SUGGEST                  = 3};   // the authors' suggested choice
enum ANNsplitRule
Enumerator
ANN_KD_STD
ANN_KD_MIDPT
ANN_KD_FAIR
ANN_KD_SL_MIDPT
ANN_KD_SL_FAIR
ANN_KD_SUGGEST
Definition at line 596 of file ANN.h.
                   {
                 ANN_KD_STD                              = 0,    // the optimized kd-splitting rule
                 ANN_KD_MIDPT                    = 1,    // midpoint split
                 ANN_KD_FAIR                             = 2,    // fair split
                 ANN_KD_SL_MIDPT                 = 3,    // sliding midpoint splitting method
                 ANN_KD_SL_FAIR                  = 4,    // sliding fair split method
                 ANN_KD_SUGGEST                  = 5};   // the authors' suggestion for best
Function Documentation
DLL_API ANNpoint annAllocPt (int dim, ANNcoord c = 0)
Definition at line 110 of file ANN.cpp.
References dim.
Referenced by ANNorthRect::ANNorthRect(), annReadDump(), main(), and QUESO::normalizeANN_XY().
 {
         ANNpoint p = new ANNcoord[dim];
         for (int i = 0; i < dim; i++) p[i] = c;
         return p;
 }
DLL_API ANNpointArray annAllocPts (int n, int dim)
Definition at line 117 of file ANN.cpp.
References dim.
Referenced by annClusEllipsoids(), annClusGaussPts(), annClusOrthFlats(), annReadDump(), QUESO::computeMI_ANN(), QUESO::estimateCE_ANN(), QUESO::BaseVectorRV< V, M >::estimateENT_ANN(), QUESO::estimateKL_ANN(), QUESO::estimateMI_ANN(), generatePts(), main(), readANN(), and readPts().
 {
         ANNpointArray pa = new ANNpoint[n];                     // allocate points
         ANNpoint          p  = new ANNcoord[n*dim];             // allocate space for coords
         for (int i = 0; i < n; i++) {
                 pa[i] = &(p[i*dim]);
         }
         return pa;
 }
DLL_API void annClose ()
Definition at line 221 of file kd_tree.cpp.
References KD_TRIVIAL.
Referenced by QUESO::distANN_XY(), and main().
 {
         if (KD_TRIVIAL != NULL) {
                 delete KD_TRIVIAL;
                 KD_TRIVIAL = NULL;
         }
 }
DLL_API ANNpoint annCopyPt (int dim, ANNpoint source)
Definition at line 140 of file ANN.cpp.
References dim.
Referenced by ANNbd_tree::ANNbd_tree(), ANNkd_tree::ANNkd_tree(), and ANNorthRect::ANNorthRect().
 {
         ANNpoint p = new ANNcoord[dim];
         for (int i = 0; i < dim; i++) p[i] = source[i];
         return p;
 }
DLL_API void annDeallocPt (ANNpoint & p)
Definition at line 127 of file ANN.cpp.
Referenced by ANNkd_tree::~ANNkd_tree(), and ANNorthRect::~ANNorthRect().
 {
         delete [] p;
         p = NULL;
 }
DLL_API void annDeallocPts (ANNpointArray & pa)
Definition at line 133 of file ANN.cpp.
Referenced by annClusEllipsoids(), annClusGaussPts(), annClusOrthFlats(), QUESO::computeMI_ANN(), QUESO::estimateCE_ANN(), QUESO::BaseVectorRV< V, M >::estimateENT_ANN(), QUESO::estimateKL_ANN(), QUESO::estimateMI_ANN(), generatePts(), main(), and readPts().
 {
         delete [] pa[0];                                                        // dealloc coordinate storage
         delete [] pa;                                                           // dealloc points
         pa = NULL;
 }
DLL_API ANNdist annDist (int dim, ANNpoint p, ANNpoint q)
Definition at line 46 of file ANN.cpp.
References dim.
Referenced by ANNbruteForce::annkFRSearch(), and ANNbruteForce::annkSearch().
 {
         register int d;
         register ANNcoord diff;
         register ANNcoord dist;
         dist = 0;
         for (d = 0; d < dim; d++) {
                 diff = p[d] - q[d];
                 dist = ANN_SUM(dist, ANN_POW(diff));
         }
         ANN_FLOP(3*dim)                                 // performance counts
         ANN_PTS(1)
         ANN_COORD(dim)
         return dist;
 }
DLL_API void annMaxPtsVisit (int maxPts)
Definition at line 197 of file ANN.cpp.
References ANNmaxPtsVisited, and maxPts.
Referenced by main().
 {
         ANNmaxPtsVisited = maxPts;
 }
Variable Documentation
const ANNbool ANN_ALLOW_SELF_MATCH = ANNtrue
Definition at line 235 of file ANN.h.
Referenced by ANNkd_leaf::ann_FR_search(), ANNkd_leaf::ann_pri_search(), ANNkd_leaf::ann_search(), ANNbruteForce::annkFRSearch(), and ANNbruteForce::annkSearch().
const double ANN_DBL_MAX = MAXDOUBLE
Definition at line 114 of file ANN.h.
Referenced by doValidation(), and ANNsampStat::reset().
const ANNdist ANN_DIST_INF = ANN_DBL_MAX
Definition at line 199 of file ANN.h.
const int ANN_N_SHRINK_RULES = 4
Definition at line 610 of file ANN.h.
const int ANN_N_SPLIT_RULES = 6
Definition at line 603 of file ANN.h.
const ANNidx ANN_NULL_IDX = -1
Definition at line 176 of file ANN.h.
Referenced by doValidation(), and main().
const int ANNcoordPrec = DBL_DIG
Definition at line 220 of file ANN.h.
Referenced by ANNkd_tree::Dump().