queso-0.50.1: QUESO::ConcatenatedVectorRV< V, M > Class Template Reference
QUESO::ConcatenatedVectorRV< V, M > Class Template Reference
A class representing concatenated vector RVs.
#include <ConcatenatedVectorRV.h>
Public Member Functions
Constructor/Destructor methods
ConcatenatedVectorRV (const char *prefix, const BaseVectorRV< V, M > &rv1, const BaseVectorRV< V, M > &rv2, const VectorSet< V, M > &imageSet)
Constructor.
ConcatenatedVectorRV (const char *prefix, const std::vector< const BaseVectorRV< V, M > * > &rvs, const VectorSet< V, M > &imageSet)
Constructor.
virtual ~ConcatenatedVectorRV ()
Virtual destructor.
I/O methods
void print (std::ostream &os) const
TODO: Prints the vector RV.
Public Member Functions inherited from QUESO::BaseVectorRV< V, M >
BaseVectorRV (const char *prefix, const VectorSet< V, M > &imageSet)
Constructor.
virtual ~BaseVectorRV ()
Virtual destructor.
const BaseEnvironment & env () const
QUESO environment; access to private attribute m_env.
const VectorSet< V, M > & imageSet () const
Image set of the vector RV; access to private attribute m_imageSet.
const BaseJointPdf< V, M > & pdf () const
Posterior Density Function of the vector RV; access to private attribute m_pdf.
const BaseVectorRealizer< V, M > & realizer () const
Finds a realization (sample) of the PDF of this vector RV; access to private attribute m_realizer.
const BaseVectorCdf< V, M > & subCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering only the sub-sequence of data; access to private attribute m_subCdf.
const BaseVectorCdf< V, M > & unifiedCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering the unified sequence of data; access to private attribute m_unifiedCdf.
const BaseVectorMdf< V, M > & mdf () const
Finds the Mass Density Function of this vector RV; access to private attribute m_mdf.
Private Attributes
std::vector< const
BaseVectorRV< V, M > * > m_rvs
std::vector< const
BaseJointPdf< V, M > * > m_pdfs
std::vector< const
BaseVectorRealizer< V, M > * > m_realizers
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseVectorRV< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_imageSet
BaseJointPdf< V, M > * m_pdf
BaseVectorRealizer< V, M > * m_realizer
const BaseVectorCdf< V, M > * m_subCdf
const BaseVectorCdf< V, M > * m_unifiedCdf
const BaseVectorMdf< V, M > * m_mdf
Detailed Description
template<class V, class M>
class QUESO::ConcatenatedVectorRV< V, M >
A class representing concatenated vector RVs.
This class allows the user to concatenate two vector RV of different types and to generate realizations (samples) from this concatenated vector RV. It is used, for instance, to concatenate priors from two or more RVs, where one of them has a uniform distribution whereas the other one(s) has a Gaussian distribution.
Definition at line 52 of file ConcatenatedVectorRV.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::ConcatenatedVectorRV< V, M >::ConcatenatedVectorRV (const char * prefix, const BaseVectorRV< V, M > & rv1, const BaseVectorRV< V, M > & rv2, const VectorSet< V, M > & imageSet)
Constructor.
Concatenates two RVs: rv1 and rv2 into one vector RV, given a prefix and the image set of the vector RV.
Definition at line 33 of file ConcatenatedVectorRV.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRV< V, M >::m_env, QUESO::BaseVectorRV< V, M >::m_imageSet, QUESO::BaseVectorRV< V, M >::m_mdf, QUESO::BaseVectorRV< V, M >::m_pdf, QUESO::ConcatenatedVectorRV< V, M >::m_pdfs, QUESO::BaseVectorRV< V, M >::m_prefix, QUESO::BaseVectorRV< V, M >::m_realizer, QUESO::ConcatenatedVectorRV< V, M >::m_realizers, QUESO::ConcatenatedVectorRV< V, M >::m_rvs, QUESO::BaseVectorRV< V, M >::m_subCdf, QUESO::BaseVectorRV< V, M >::m_unifiedCdf, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRV<V,M>(((std::string)(prefix)+"concat").c_str(),imageSet),
   m_rvs                   (2,(const BaseVectorRV      <V,M>*) NULL),
   m_pdfs                  (2,(const BaseJointPdf      <V,M>*) NULL),
   m_realizers             (2,(const BaseVectorRealizer<V,M>*) NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ConcatenatedVectorRV<V,M>::constructor(1)"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   m_rvs[0]       = &rv1;
   m_rvs[1]       = &rv2;
   m_pdfs[0]      = &(m_rvs[0]->pdf());
   m_pdfs[1]      = &(m_rvs[1]->pdf());
   m_realizers[0] = &(m_rvs[0]->realizer());
   m_realizers[1] = &(m_rvs[1]->realizer());
   m_pdf          = new ConcatenatedJointPdf<V,M>(m_prefix.c_str(),
                                                         *(m_pdfs[0]),
                                                         *(m_pdfs[1]),
                                                         m_imageSet);
   m_realizer     = new ConcatenatedVectorRealizer<V,M>(m_prefix.c_str(),
                                                               *(m_realizers[0]),
                                                               *(m_realizers[1]),
                                                               m_imageSet);
   m_subCdf     = NULL; // FIX ME: complete code
   m_unifiedCdf = NULL; // FIX ME: complete code
   m_mdf        = NULL; // FIX ME: complete code
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ConcatenatedVectorRV<V,M>::constructor(1)"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::ConcatenatedVectorRV< V, M >::ConcatenatedVectorRV (const char * prefix, const std::vector< const BaseVectorRV< V, M > * > & rvs, const VectorSet< V, M > & imageSet)
Constructor.
Concatenates a sequence of RVs, given by: std::vector<const BaseVectorRV<V,M>* >& rvs into one single vector RV, given a prefix and the image set of the resulting vector RV.
Definition at line 78 of file ConcatenatedVectorRV.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRV< V, M >::m_env, QUESO::BaseVectorRV< V, M >::m_imageSet, QUESO::BaseVectorRV< V, M >::m_mdf, QUESO::BaseVectorRV< V, M >::m_pdf, QUESO::ConcatenatedVectorRV< V, M >::m_pdfs, QUESO::BaseVectorRV< V, M >::m_prefix, QUESO::BaseVectorRV< V, M >::m_realizer, QUESO::ConcatenatedVectorRV< V, M >::m_realizers, QUESO::ConcatenatedVectorRV< V, M >::m_rvs, QUESO::BaseVectorRV< V, M >::m_subCdf, QUESO::BaseVectorRV< V, M >::m_unifiedCdf, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRV<V,M>(((std::string)(prefix)+"concat").c_str(),imageSet),
   m_rvs                   (rvs.size(),(const BaseVectorRV      <V,M>*) NULL),
   m_pdfs                  (rvs.size(),(const BaseJointPdf      <V,M>*) NULL),
   m_realizers             (rvs.size(),(const BaseVectorRealizer<V,M>*) NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ConcatenatedVectorRV<V,M>::constructor(2)"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   for (unsigned int i = 0; i < m_rvs.size(); ++i) {
     m_rvs [i]      = rvs[i];
     m_pdfs[i]      = &(m_rvs[i]->pdf());
     m_realizers[i] = &(m_rvs[i]->realizer());
   }
   m_pdf        = new ConcatenatedJointPdf<V,M>(m_prefix.c_str(),
                                                       m_pdfs,
                                                       m_imageSet);
   unsigned int minPeriod = m_realizers[0]->subPeriod();
   for (unsigned int i = 0; i < m_realizers.size(); ++i) {
     if (minPeriod > m_realizers[i]->subPeriod()) {
       minPeriod = m_realizers[i]->subPeriod();
     }
   }
   m_realizer   = new ConcatenatedVectorRealizer<V,M>(m_prefix.c_str(),
                                                             m_realizers,
                                                             minPeriod,
                                                             m_imageSet);
   m_subCdf     = NULL; // FIX ME: complete code
   m_unifiedCdf = NULL; // FIX ME: complete code
   m_mdf        = NULL; // FIX ME: complete code
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ConcatenatedVectorRV<V,M>::constructor(2)"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::ConcatenatedVectorRV< V, M >::~ConcatenatedVectorRV () virtual
Virtual destructor.
Definition at line 127 of file ConcatenatedVectorRV.C.
 {
   delete m_mdf;
   delete m_unifiedCdf;
   delete m_subCdf;
   delete m_realizer;
   delete m_pdf;
 }
Member Function Documentation
template<class V , class M > void QUESO::ConcatenatedVectorRV< V, M >::print (std::ostream & os) const virtual
TODO: Prints the vector RV.
Todo:
: implement me!
Implements QUESO::BaseVectorRV< V, M >.
Definition at line 138 of file ConcatenatedVectorRV.C.
 {
   os << "ConcatenatedVectorRV<V,M>::print() says, 'Please implement me.'" << std::endl;
   return;
 }
Member Data Documentation
template<class V , class M > std::vector<const BaseJointPdf <V,M>* > QUESO::ConcatenatedVectorRV< V, M >::m_pdfs private
Definition at line 93 of file ConcatenatedVectorRV.h.
Referenced by QUESO::ConcatenatedVectorRV< V, M >::ConcatenatedVectorRV().
template<class V , class M > std::vector<const BaseVectorRealizer<V,M>* > QUESO::ConcatenatedVectorRV< V, M >::m_realizers private
Definition at line 94 of file ConcatenatedVectorRV.h.
Referenced by QUESO::ConcatenatedVectorRV< V, M >::ConcatenatedVectorRV().
template<class V , class M > std::vector<const BaseVectorRV <V,M>* > QUESO::ConcatenatedVectorRV< V, M >::m_rvs private
Definition at line 92 of file ConcatenatedVectorRV.h.
Referenced by QUESO::ConcatenatedVectorRV< V, M >::ConcatenatedVectorRV().
The documentation for this class was generated from the following files:
src/stats/inc/ConcatenatedVectorRV.h
src/stats/src/ConcatenatedVectorRV.C