queso-0.50.1: QUESO::BaseVectorCdf< V, M > Class Template Reference
QUESO::BaseVectorCdf< V, M > Class Template Reference abstract
A templated (base) class for handling CDFs of vector functions.
#include <VectorCdf.h>
Public Member Functions
Constructor/Destructor methods
BaseVectorCdf (const char *prefix, const VectorSet< V, M > &pdfSupport)
Default constructor.
virtual ~BaseVectorCdf ()
Virtual destructor.
Mathematical methods
const VectorSet< V, M > & pdfSupport () const
Returns the image set (support) of the PDF; access to protected attribute m_pdfSupport.
virtual void values (const V &paramValues, V &cdfVec) const =0
Finds the value of the vector CDF at each element of paramValue, and saves it in cdfVec. See template specialization.
virtual const BaseScalarCdf
< double > & cdf (unsigned int rowId) const =0
Protected Attributes
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_pdfSupport
I/O methods
virtual void print (std::ostream &os) const =0
Prints the vector CDF. See template specialization.
virtual void subWriteContents (const std::string &varNamePrefix, const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds) const
Writes the CDF of an allowed sub-environment to a file.
std::ostream & operator<< (std::ostream &os, const BaseVectorCdf< V, M > &obj)
Detailed Description
template<class V, class M>
class QUESO::BaseVectorCdf< V, M >
A templated (base) class for handling CDFs of vector functions.
In many applications is necessary to consider the properties of two or more RVs simultaneously (represented within QUESO as Random Vectors, via BaseVectorRV and derived classes). When dealing simultaneously with more than one RV, ie, a vector RV, the joint cumulative distribution function must also be defined. This class handles the CDFs of vector RV, which are referred to as multivariate/vector/joint CDFs.
Definition at line 56 of file VectorCdf.h.
Constructor & Destructor Documentation
template<class V, class M> QUESO::BaseVectorCdf< V, M >::BaseVectorCdf (const char * prefix, const VectorSet< V, M > & pdfSupport)
Default constructor.
Instantiates an object of the class given a prefix and the support (image set) of the PDF that is related to this CDF (recall that the CDF of a continuous RV is the integral of the PDF of that RV).
Definition at line 31 of file VectorCdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorCdf< V, M >::m_env, QUESO::BaseVectorCdf< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_env       (pdfSupport.env()),
   m_prefix    ((std::string)(prefix)+"Cdf_"),
   m_pdfSupport(pdfSupport)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering BaseVectorCdf<V,M>::constructor()"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving BaseVectorCdf<V,M>::constructor()"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
 }
template<class V , class M > QUESO::BaseVectorCdf< V, M >::~BaseVectorCdf () virtual
Virtual destructor.
Definition at line 53 of file VectorCdf.C.
 {
 }
Member Function Documentation
template<class V, class M> virtual const BaseScalarCdf<double>& QUESO::BaseVectorCdf< V, M >::cdf (unsigned int rowId) const pure virtual
Implemented in QUESO::SampledVectorCdf< V, M >.
Referenced by QUESO::horizontalDistances().
template<class V , class M > const VectorSet< V, M > & QUESO::BaseVectorCdf< V, M >::pdfSupport () const
Returns the image set (support) of the PDF; access to protected attribute m_pdfSupport.
Definition at line 59 of file VectorCdf.C.
Referenced by QUESO::horizontalDistances().
 {
   return m_pdfSupport;
 }
template<class V, class M> virtual void QUESO::BaseVectorCdf< V, M >::print (std::ostream & os) const pure virtual
Prints the vector CDF. See template specialization.
Implemented in QUESO::GaussianVectorCdf< V, M >, QUESO::SampledVectorCdf< V, M >, and QUESO::GenericVectorCdf< V, M >.
template<class V , class M > void QUESO::BaseVectorCdf< V, M >::subWriteContents (const std::string & varNamePrefix, const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds) const virtual
Writes the CDF of an allowed sub-environment to a file.
This function does nothing and should
not be called by the user.
Reimplemented in QUESO::SampledVectorCdf< V, M >.
Definition at line 66 of file VectorCdf.C.
 {
   std::cerr << "WARNING: BaseVectorCdf<V,M>::subWriteContents() being used..."
             << std::endl;
   if (&varNamePrefix)    {}; // just to remove compiler warning
   if (&fileName)         {}; // just to remove compiler warning
   if (&fileType)         {}; // just to remove compiler warning
   if (&allowedSubEnvIds) {}; // just to remove compiler warning
   return;
 }
template<class V, class M> virtual void QUESO::BaseVectorCdf< V, M >::values (const V & paramValues, V & cdfVec) const pure virtual
Finds the value of the vector CDF at each element of paramValue, and saves it in cdfVec. See template specialization.
Implemented in QUESO::GaussianVectorCdf< V, M >, QUESO::SampledVectorCdf< V, M >, and QUESO::GenericVectorCdf< V, M >.
Friends And Related Function Documentation
template<class V, class M> std::ostream& operator<< (std::ostream & os, const BaseVectorCdf< V, M > & obj) friend
Definition at line 86 of file VectorCdf.h.
{
     obj.print(os);
     return os;
   }
Member Data Documentation
template<class V, class M> const BaseEnvironment& QUESO::BaseVectorCdf< V, M >::m_env protected
Definition at line 101 of file VectorCdf.h.
Referenced by QUESO::BaseVectorCdf< V, M >::BaseVectorCdf(), QUESO::GaussianVectorCdf< V, M >::GaussianVectorCdf(), and QUESO::SampledVectorCdf< V, M >::SampledVectorCdf().
template<class V, class M> const VectorSet<V,M>& QUESO::BaseVectorCdf< V, M >::m_pdfSupport protected
Definition at line 103 of file VectorCdf.h.
template<class V, class M> std::string QUESO::BaseVectorCdf< V, M >::m_prefix protected
Definition at line 102 of file VectorCdf.h.
Referenced by QUESO::BaseVectorCdf< V, M >::BaseVectorCdf(), QUESO::GaussianVectorCdf< V, M >::GaussianVectorCdf(), QUESO::SampledVectorCdf< V, M >::SampledVectorCdf(), and QUESO::StatisticalForwardProblem< P_V, P_M, Q_V, Q_M >::solveWithMonteCarlo().
The documentation for this class was generated from the following files:
src/stats/inc/VectorCdf.h
src/stats/src/VectorCdf.C