queso-0.50.1: QUESO::BaseScalarCdf< T > Class Template Reference
QUESO::BaseScalarCdf< T > Class Template Reference abstract
A templated (base) class for handling CDFs.
#include <ScalarCdf.h>
Public Member Functions
Constructor/Destructor methods
BaseScalarCdf (const BaseEnvironment &env, const char *prefix)
Default constructor.
virtual ~BaseScalarCdf ()
Virtual destructor.
Environment methods
const BaseEnvironment & env () const
Environment. Access to private attribute m_env.
const std::string & prefix () const
Access to private attribute m_prefix.
Mathematical methods
virtual double value (T paramValue) const =0
Returns the value of the CDF at paramValue. See template specialization.
virtual T inverse (double cdfValue) const =0
Returns the position of a given value of CDF. See template specialization.
virtual void getSupport (T &minHorizontal, T &maxHorizontal) const =0
Returns the support (image) of the CDF between two horizontal values (domain). See template specialization.
Protected Attributes
const BaseEnvironment & m_env
std::string m_prefix
T m_minHorizontal
T m_maxHorizontal
I/O methods
virtual void print (std::ostream &os) const =0
Prints the CDF. See template specialization.
virtual void subWriteContents (const std::string &varNamePrefix, const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds) const
Writes the CDF of an allowed sub-environment to a file.
std::ostream & operator<< (std::ostream &os, const BaseScalarCdf< T > &obj)
Detailed Description
template<class T>
class QUESO::BaseScalarCdf< T >
A templated (base) class for handling CDFs.
This class allows the mathematical definition of a cumulative distribution function (CDF), which is a scalar function such as * ; ie a function of one or more variables that has always one-dimensional range, which for the specific CDF case, the image set . The CDF describes the probability that a real-valued random variable X with a given probability distribution will be found at a value less than or equal to x. In the case of a continuous distribution, it gives the area under the probability density function (PDF) from minus infinity to x.
Definition at line 56 of file ScalarCdf.h.
Constructor & Destructor Documentation
template<class T > QUESO::BaseScalarCdf< T >::BaseScalarCdf (const BaseEnvironment & env, const char * prefix)
Default constructor.
Instantiates an object of the class given a prefix and the environment.
Definition at line 31 of file ScalarCdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarCdf< T >::m_env, QUESO::BaseScalarCdf< T >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_env          (env),
   m_prefix       ((std::string)(prefix)+""),
   m_minHorizontal(-INFINITY),
   m_maxHorizontal( INFINITY)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering BaseScalarCdf<T>::constructor()"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving BaseScalarCdf<T>::constructor()"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
 }
template<class T > QUESO::BaseScalarCdf< T >::~BaseScalarCdf () virtual
Virtual destructor.
Definition at line 54 of file ScalarCdf.C.
 {
 }
Member Function Documentation
template<class T > const BaseEnvironment & QUESO::BaseScalarCdf< T >::env () const
Environment. Access to private attribute m_env.
Definition at line 60 of file ScalarCdf.C.
Referenced by QUESO::horizontalDistance(), and QUESO::StdScalarCdf< T >::StdScalarCdf().
 {
   return m_env;
 }
template<class T> virtual void QUESO::BaseScalarCdf< T >::getSupport (T & minHorizontal, T & maxHorizontal) const pure virtual
Returns the support (image) of the CDF between two horizontal values (domain). See template specialization.
Implemented in QUESO::StdScalarCdf< T >, and QUESO::SampledScalarCdf< T >.
template<class T> virtual T QUESO::BaseScalarCdf< T >::inverse (double cdfValue) const pure virtual
Returns the position of a given value of CDF. See template specialization.
Implemented in QUESO::StdScalarCdf< T >, and QUESO::SampledScalarCdf< T >.
Referenced by QUESO::horizontalDistance().
template<class T > const std::string & QUESO::BaseScalarCdf< T >::prefix () const
Access to private attribute m_prefix.
Definition at line 67 of file ScalarCdf.C.
Referenced by QUESO::horizontalDistance(), and QUESO::StdScalarCdf< T >::StdScalarCdf().
 {
   return m_prefix;
 }
template<class T> virtual void QUESO::BaseScalarCdf< T >::print (std::ostream & os) const pure virtual
Prints the CDF. See template specialization.
Implemented in QUESO::StdScalarCdf< T >, and QUESO::SampledScalarCdf< T >.
template<class T > void QUESO::BaseScalarCdf< T >::subWriteContents (const std::string & varNamePrefix, const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds) const virtual
Writes the CDF of an allowed sub-environment to a file.
This function does nothing and should
not be called by the user.
Reimplemented in QUESO::StdScalarCdf< T >, and QUESO::SampledScalarCdf< T >.
Definition at line 74 of file ScalarCdf.C.
 {
   std::cerr << "WARNING: BaseScalarCdf<T>::subWriteContents() being used..."
             << std::endl;
   return;
 }
template<class T> virtual double QUESO::BaseScalarCdf< T >::value (T paramValue) const pure virtual
Returns the value of the CDF at paramValue. See template specialization.
Implemented in QUESO::StdScalarCdf< T >, and QUESO::SampledScalarCdf< T >.
Referenced by QUESO::horizontalDistance().
Friends And Related Function Documentation
template<class T> std::ostream& operator<< (std::ostream & os, const BaseScalarCdf< T > & obj) friend
Definition at line 92 of file ScalarCdf.h.
{
     obj.print(os);
     return os;
   }
Member Data Documentation
template<class T> const BaseEnvironment& QUESO::BaseScalarCdf< T >::m_env protected
Definition at line 106 of file ScalarCdf.h.
Referenced by QUESO::BaseScalarCdf< T >::BaseScalarCdf(), QUESO::SampledScalarCdf< T >::SampledScalarCdf(), and QUESO::StdScalarCdf< T >::StdScalarCdf().
template<class T> T QUESO::BaseScalarCdf< T >::m_maxHorizontal mutable protected
Definition at line 109 of file ScalarCdf.h.
template<class T> T QUESO::BaseScalarCdf< T >::m_minHorizontal mutable protected
Definition at line 108 of file ScalarCdf.h.
template<class T> std::string QUESO::BaseScalarCdf< T >::m_prefix protected
Definition at line 107 of file ScalarCdf.h.
Referenced by QUESO::BaseScalarCdf< T >::BaseScalarCdf(), QUESO::SampledScalarCdf< T >::SampledScalarCdf(), and QUESO::StdScalarCdf< T >::StdScalarCdf().
The documentation for this class was generated from the following files:
src/stats/inc/ScalarCdf.h
src/stats/src/ScalarCdf.C