queso-0.50.1: QUESO::StatisticalInverseProblemOptions Class Reference
QUESO::StatisticalInverseProblemOptions Class Reference
This class reads option values for a Statistical Inverse Problem from an input file.
#include <StatisticalInverseProblemOptions.h>
Public Member Functions
Constructor/Destructor methods
StatisticalInverseProblemOptions (const BaseEnvironment &env, const char *prefix)
Constructor: reads options from the input file.
StatisticalInverseProblemOptions (const BaseEnvironment &env, const char *prefix, const SipOptionsValues &alternativeOptionsValues)
Constructor: with alternative option values.
~StatisticalInverseProblemOptions ()
Destructor.
I/O methods
void scanOptionsValues ()
It scans the option values from the options input file.
void print (std::ostream &os) const
It prints the option values.
Public Attributes
SipOptionsValues m_ov
std::string m_prefix
Private Member Functions
void defineMyOptions (po::options_description &optionsDesc) const
Define my SIP options as the default options.
void getMyOptionValues (po::options_description &optionsDesc)
Gets the option values of the SIP.
Private Attributes
const BaseEnvironment & m_env
po::options_description * m_optionsDesc
std::string m_option_help
std::string m_option_computeSolution
std::string m_option_dataOutputFileName
std::string m_option_dataOutputAllowedSet
Detailed Description
This class reads option values for a Statistical Inverse Problem from an input file.
This class reads the option values for the Statistical Inverse Problem (SIP) from an input file provided by the user. The class expects the prefix '<prefix>_ip_'. For instance, if 'prefix' is 'foo_775_', then the constructor will read all options that begin with 'foo_775_ip_'. If the options request data to be written in the output file (MATLAB .m format only, for now), the user can run 'grep zeros <OUTPUT FILE NAME>' after the solution procedure ends in order to check which MATLAB variables are defined and set. The names of the variables are self explanatory.
Definition at line 106 of file StatisticalInverseProblemOptions.h.
Constructor & Destructor Documentation
QUESO::StatisticalInverseProblemOptions::StatisticalInverseProblemOptions (const BaseEnvironment & env, const char * prefix)
Constructor: reads options from the input file.
Definition at line 82 of file StatisticalInverseProblemOptions.C.
References m_env, QUESO::BaseEnvironment::optionsInputFileName(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   m_ov                         (),
   m_prefix                     ((std::string)(prefix) + "ip_"),
   m_env                        (env),
   m_optionsDesc                (new po::options_description("Statistical Inverse Problem options")),
   m_option_help                (m_prefix + "help"                ),
   m_option_computeSolution     (m_prefix + "computeSolution"     ),
   m_option_dataOutputFileName  (m_prefix + "dataOutputFileName"  ),
   m_option_dataOutputAllowedSet(m_prefix + "dataOutputAllowedSet")
 #ifdef UQ_SIP_READS_SOLVER_OPTION
   m_option_solver              (m_prefix + "solver"              )
 #endif
 {
   UQ_FATAL_TEST_MACRO(m_env.optionsInputFileName() == "",
                       m_env.worldRank(),
                       "StatisticalInverseProblemOptions::constructor(1)",
                       "this constructor is incompatible with the absence of an options input file");
 }
QUESO::StatisticalInverseProblemOptions::StatisticalInverseProblemOptions (const BaseEnvironment & env, const char * prefix, const SipOptionsValues & alternativeOptionsValues)
Constructor: with alternative option values.
In this constructor, the input options are given by alternativeOptionsValues, rather than the options input file
Definition at line 105 of file StatisticalInverseProblemOptions.C.
References m_env, m_prefix, QUESO::BaseEnvironment::optionsInputFileName(), QUESO::BaseEnvironment::subDisplayFile(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   m_ov                         (alternativeOptionsValues),
   m_prefix                     ((std::string)(prefix) + "ip_"),
   m_env                        (env),
   m_optionsDesc                (NULL),
   m_option_help                (m_prefix + "help"                ),
   m_option_computeSolution     (m_prefix + "computeSolution"     ),
   m_option_dataOutputFileName  (m_prefix + "dataOutputFileName"  ),
   m_option_dataOutputAllowedSet(m_prefix + "dataOutputAllowedSet")
 #ifdef UQ_SIP_READS_SOLVER_OPTION
   m_option_solver              (m_prefix + "solver"              )
 #endif
 {
   UQ_FATAL_TEST_MACRO(m_env.optionsInputFileName() != "",
                       m_env.worldRank(),
                       "StatisticalInverseProblemOptions::constructor(2)",
                       "this constructor is incompatible with the existence of an options input file");
   if (m_env.subDisplayFile() != NULL) {
     *m_env.subDisplayFile() << "In StatisticalInverseProblemOptions::constructor(2)"
                             << ": after setting values of options with prefix '" << m_prefix
                             << "', state of object is:"
                             << "\n" << *this
                             << std::endl;
   }
 }
QUESO::StatisticalInverseProblemOptions::~StatisticalInverseProblemOptions ()
Destructor.
Definition at line 136 of file StatisticalInverseProblemOptions.C.
References m_optionsDesc.
 {
   if (m_optionsDesc) delete m_optionsDesc;
 }
Member Function Documentation
void QUESO::StatisticalInverseProblemOptions::defineMyOptions (po::options_description & optionsDesc) const private
Define my SIP options as the default options.
Definition at line 187 of file StatisticalInverseProblemOptions.C.
References m_option_computeSolution, m_option_dataOutputAllowedSet, m_option_dataOutputFileName, m_option_help, UQ_SIP_COMPUTE_SOLUTION_ODV, UQ_SIP_DATA_OUTPUT_ALLOWED_SET_ODV, and UQ_SIP_DATA_OUTPUT_FILE_NAME_ODV.
Referenced by scanOptionsValues().
 {
   optionsDesc.add_options()
     (m_option_help.c_str(),                                                                                              "produce help message for statistical inverse problem")
     (m_option_computeSolution.c_str(),      po::value<bool       >()->default_value(UQ_SIP_COMPUTE_SOLUTION_ODV       ), "compute solution process"                            )
     (m_option_dataOutputFileName.c_str(),   po::value<std::string>()->default_value(UQ_SIP_DATA_OUTPUT_FILE_NAME_ODV  ), "name of data output file"                            )
     (m_option_dataOutputAllowedSet.c_str(), po::value<std::string>()->default_value(UQ_SIP_DATA_OUTPUT_ALLOWED_SET_ODV), "subEnvs that will write to data output file"         )
 #ifdef UQ_SIP_READS_SOLVER_OPTION
     (m_option_solver.c_str(),               po::value<std::string>()->default_value(UQ_SIP_SOLVER_ODV                 ), "algorithm for calibration"                           )
 #endif
   ;
   return;
 }
void QUESO::StatisticalInverseProblemOptions::getMyOptionValues (po::options_description & optionsDesc) private
Gets the option values of the SIP.
Definition at line 203 of file StatisticalInverseProblemOptions.C.
References QUESO::BaseEnvironment::allOptionsMap(), QUESO::SipOptionsValues::m_computeSolution, QUESO::SipOptionsValues::m_dataOutputAllowedSet, QUESO::SipOptionsValues::m_dataOutputFileName, m_env, m_option_computeSolution, m_option_dataOutputAllowedSet, m_option_dataOutputFileName, m_option_help, m_ov, QUESO::MiscReadDoublesFromString(), and QUESO::BaseEnvironment::subDisplayFile().
Referenced by scanOptionsValues().
 {
   if (m_env.allOptionsMap().count(m_option_help)) {
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << optionsDesc
                               << std::endl;
     }
   }
   if (m_env.allOptionsMap().count(m_option_computeSolution)) {
     m_ov.m_computeSolution = ((const po::variable_value&) m_env.allOptionsMap()[m_option_computeSolution]).as<bool>();
   }
   if (m_env.allOptionsMap().count(m_option_dataOutputFileName)) {
     m_ov.m_dataOutputFileName = ((const po::variable_value&) m_env.allOptionsMap()[m_option_dataOutputFileName]).as<std::string>();
   }
   if (m_env.allOptionsMap().count(m_option_dataOutputAllowedSet)) {
     m_ov.m_dataOutputAllowedSet.clear();
     std::vector<double> tmpAllow(0,0.);
     std::string inputString = m_env.allOptionsMap()[m_option_dataOutputAllowedSet].as<std::string>();
     MiscReadDoublesFromString(inputString,tmpAllow);
     if (tmpAllow.size() > 0) {
       for (unsigned int i = 0; i < tmpAllow.size(); ++i) {
         m_ov.m_dataOutputAllowedSet.insert((unsigned int) tmpAllow[i]);
       }
     }
   }
 #ifdef UQ_SIP_READS_SOLVER_OPTION
   if (m_env.allOptionsMap().count(m_option_solver)) {
     m_ov.m_solverString = ((const po::variable_value&) m_env.allOptionsMap()[m_option_solver]).as<std::string>();
   }
 #endif
   return;
 }
void QUESO::StatisticalInverseProblemOptions::print (std::ostream & os) const
It prints the option values.
Definition at line 170 of file StatisticalInverseProblemOptions.C.
References QUESO::SipOptionsValues::m_computeSolution, QUESO::SipOptionsValues::m_dataOutputAllowedSet, QUESO::SipOptionsValues::m_dataOutputFileName, m_option_computeSolution, m_option_dataOutputAllowedSet, m_option_dataOutputFileName, and m_ov.
Referenced by QUESO::operator<<().
 {
   os << "\n" << m_option_computeSolution      << " = " << m_ov.m_computeSolution
      << "\n" << m_option_dataOutputFileName   << " = " << m_ov.m_dataOutputFileName;
   os << "\n" << m_option_dataOutputAllowedSet << " = ";
   for (std::set<unsigned int>::iterator setIt = m_ov.m_dataOutputAllowedSet.begin(); setIt != m_ov.m_dataOutputAllowedSet.end(); ++setIt) {
     os << *setIt << " ";
   }
 #ifdef UQ_SIP_READS_SOLVER_OPTION
      << "\n" << m_option_solver << " = " << m_ov.m_solverString
 #endif
   os << std::endl;
   return;
 }
void QUESO::StatisticalInverseProblemOptions::scanOptionsValues ()
It scans the option values from the options input file.
Definition at line 143 of file StatisticalInverseProblemOptions.C.
References defineMyOptions(), getMyOptionValues(), m_env, m_optionsDesc, m_prefix, QUESO::BaseEnvironment::scanInputFileForMyOptions(), QUESO::BaseEnvironment::subDisplayFile(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(m_optionsDesc == NULL,
                       m_env.worldRank(),
                       "StatisticalInverseProblemOptions::scanOptionsValues()",
                       "m_optionsDesc variable is NULL");
   defineMyOptions                (*m_optionsDesc);
   m_env.scanInputFileForMyOptions(*m_optionsDesc);
   //std::cout << "scan 000\n"
   //          << std::endl;
   getMyOptionValues              (*m_optionsDesc);
   //std::cout << "scan 001\n"
   //          << std::endl;
   if (m_env.subDisplayFile() != NULL) {
     *m_env.subDisplayFile() << "In StatisticalInverseProblemOptions::scanOptionsValues()"
                             << ": after reading values of options with prefix '" << m_prefix
                             << "', state of  object is:"
                             << "\n" << *this
                             << std::endl;
   }
   return;
 }
Member Data Documentation
const BaseEnvironment& QUESO::StatisticalInverseProblemOptions::m_env private
Definition at line 142 of file StatisticalInverseProblemOptions.h.
Referenced by getMyOptionValues(), scanOptionsValues(), and StatisticalInverseProblemOptions().
std::string QUESO::StatisticalInverseProblemOptions::m_option_computeSolution private
Definition at line 146 of file StatisticalInverseProblemOptions.h.
Referenced by defineMyOptions(), getMyOptionValues(), and print().
std::string QUESO::StatisticalInverseProblemOptions::m_option_dataOutputAllowedSet private
Definition at line 148 of file StatisticalInverseProblemOptions.h.
Referenced by defineMyOptions(), getMyOptionValues(), and print().
std::string QUESO::StatisticalInverseProblemOptions::m_option_dataOutputFileName private
Definition at line 147 of file StatisticalInverseProblemOptions.h.
Referenced by defineMyOptions(), getMyOptionValues(), and print().
std::string QUESO::StatisticalInverseProblemOptions::m_option_help private
Definition at line 145 of file StatisticalInverseProblemOptions.h.
Referenced by defineMyOptions(), and getMyOptionValues().
po::options_description* QUESO::StatisticalInverseProblemOptions::m_optionsDesc private
Definition at line 144 of file StatisticalInverseProblemOptions.h.
Referenced by scanOptionsValues(), and ~StatisticalInverseProblemOptions().
SipOptionsValues QUESO::StatisticalInverseProblemOptions::m_ov
Definition at line 132 of file StatisticalInverseProblemOptions.h.
Referenced by getMyOptionValues(), and print().
std::string QUESO::StatisticalInverseProblemOptions::m_prefix
Definition at line 133 of file StatisticalInverseProblemOptions.h.
Referenced by scanOptionsValues(), and StatisticalInverseProblemOptions().
The documentation for this class was generated from the following files:
src/stats/inc/StatisticalInverseProblemOptions.h
src/stats/src/StatisticalInverseProblemOptions.C