queso-0.50.1: QUESO::WignerJointPdf< V, M > Class Template Reference
QUESO::WignerJointPdf< V, M > Class Template Reference
A class for handling Wigner joint PDFs.
#include <WignerJointPdf.h>
Public Member Functions
Constructor/Destructor methods
WignerJointPdf (const char *prefix, const VectorSet< V, M > &domainSet, const V &centerPos, double radius)
Constructor.
~WignerJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Actual value of the PDF (scalar function).
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Computes the logarithm of the value of the function.
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
virtual void setNormalizationStyle (unsigned int value) const
Sets a value to be used in the normalization style (stored in the protected attribute m_normalizationStyle.)
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
Protected Attributes
V * m_centerPos
double m_radius
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Detailed Description
template<class V, class M>
class QUESO::WignerJointPdf< V, M >
A class for handling Wigner joint PDFs.
This class allows the mathematical definition of a Wigner Joint PDF.
Definition at line 49 of file WignerJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::WignerJointPdf< V, M >::WignerJointPdf (const char * prefix, const VectorSet< V, M > & domainSet, const V & centerPos, double radius)
Constructor.
Constructs a new object of the class, given a prefix, the domain set of the PDF, the center position centerPos, and a radius radius.
Definition at line 33 of file WignerJointPdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarFunction< V, M >::m_env, QUESO::BaseScalarFunction< V, M >::m_prefix, QUESO::WignerJointPdf< V, M >::m_radius, QUESO::BaseEnvironment::subDisplayFile(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"uni").c_str(),
          domainSet),
   m_centerPos(new V(centerPos)),
   m_radius   (radius)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering WignerJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   UQ_FATAL_TEST_MACRO(m_radius <= 0.,
                       m_env.worldRank(),
                       "WignerJointPdf<V,M>::constructor()",
                       "invalid radius");
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving WignerJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::WignerJointPdf< V, M >::~WignerJointPdf ()
Destructor.
Definition at line 63 of file WignerJointPdf.C.
 {
   delete m_centerPos;
 }
Member Function Documentation
template<class V , class M > double QUESO::WignerJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Actual value of the PDF (scalar function).
It depends on the distance of the center position to the domain and on the radius.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 70 of file WignerJointPdf.C.
References UQ_FATAL_TEST_MACRO.
 {
   UQ_FATAL_TEST_MACRO(domainVector.sizeLocal() != this->m_domainSet.vectorSpace().dimLocal(),
                       m_env.worldRank(),
                       "WignerJointPdf<V,M>::actualValue()",
                       "invalid input");
   if (gradVector   ) *gradVector     = m_domainSet.vectorSpace().zeroVector();
   if (hessianMatrix) *hessianMatrix *= 0.;
   if (hessianEffect) *hessianEffect  = m_domainSet.vectorSpace().zeroVector();
   double returnValue = 0.;
   double distanceRatio = (domainVector - *m_centerPos).norm2()/m_radius;
   if (distanceRatio < 1.) {
     returnValue = 2.*m_radius*m_radius*sqrt(1. - distanceRatio*distanceRatio)/M_PI;
   }
   returnValue *= exp(m_logOfNormalizationFactor); // [PDF-09]
   return returnValue;
 }
template<class V , class M > double QUESO::WignerJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
Computes the logarithm of the normalization factor.
This routine calls BaseJointPdf::commonComputeLogOfNormalizationFactor().
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 115 of file WignerJointPdf.C.
References QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor().
 {
   double value = 0.;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering WignerJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << std::endl;
   }
   value = BaseJointPdf<V,M>::commonComputeLogOfNormalizationFactor(numSamples, updateFactorInternally);
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving WignerJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << ", m_logOfNormalizationFactor = " << m_logOfNormalizationFactor
                             << std::endl;
   }
   return value;
 }
template<class V , class M > double QUESO::WignerJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Computes the logarithm of the value of the function.
This method calls actualValue() and applies the logarithm to its result.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 98 of file WignerJointPdf.C.
 {
   if (gradVector   ) *gradVector     = m_domainSet.vectorSpace().zeroVector();
   if (hessianMatrix) *hessianMatrix *= 0.;
   if (hessianEffect) *hessianEffect  = m_domainSet.vectorSpace().zeroVector();
   // No need to add m_logOfNormalizationFactor because 'actualValue()' is called [PDF-09]
   return log(this->actualValue(domainVector,domainDirection,gradVector,hessianMatrix,hessianEffect));
 }
Member Data Documentation
template<class V, class M> V* QUESO::WignerJointPdf< V, M >::m_centerPos protected
Definition at line 83 of file WignerJointPdf.h.
template<class V, class M> double QUESO::WignerJointPdf< V, M >::m_radius protected
Definition at line 84 of file WignerJointPdf.h.
Referenced by QUESO::WignerJointPdf< V, M >::WignerJointPdf().
The documentation for this class was generated from the following files:
src/stats/inc/WignerJointPdf.h
src/stats/src/WignerJointPdf.C