queso-0.50.1: src/stats/test/TestExample.C File Reference
TestExample.C File Reference
#include <boost/test/included/unit_test.hpp>
Macros
#define BOOST_TEST_MODULE
Functions
int add (int i, int j)
int mult (int i, int j)
BOOST_AUTO_TEST_CASE (simple_test_add)
BOOST_AUTO_TEST_CASE (simple_test_mult)
Macro Definition Documentation
#define BOOST_TEST_MODULE
Definition at line 1 of file TestExample.C.
Function Documentation
int add (int i, int j)
Definition at line 4 of file TestExample.C.
Referenced by BOOST_AUTO_TEST_CASE().
 { return i+j; }
BOOST_AUTO_TEST_CASE (simple_test_add)
Definition at line 7 of file TestExample.C.
References add().
 {
     BOOST_CHECK(   add( 2,2 ) == 4 );  // continues on error
     BOOST_REQUIRE( add( 2,2 ) == 4 );  // throws on error
 }
BOOST_AUTO_TEST_CASE (simple_test_mult)
Definition at line 13 of file TestExample.C.
References mult().
 {
     BOOST_CHECK(   mult( 2,2 ) == 4 );  // continues on error
     BOOST_REQUIRE( mult( 2,2 ) == 4 );  // throws on error
 }
int mult (int i, int j)
Definition at line 5 of file TestExample.C.
Referenced by BOOST_AUTO_TEST_CASE().
 { return i*j; }