queso-0.51.0: QUESO::InverseGammaVectorRV< V, M > Class Template Reference
QUESO::InverseGammaVectorRV< V, M > Class Template Reference
A class representing a vector RV constructed via Inverse Gamma distribution.
#include <InverseGammaVectorRV.h>
Public Member Functions
Constructor/Destructor methods
InverseGammaVectorRV (const char *prefix, const VectorSet< V, M > &imageSet, const V &alpha, const V &beta)
Default Constructor.
virtual ~InverseGammaVectorRV ()
Virtual destructor.
I/O methods
void print (std::ostream &os) const
TODO: Prints the vector RV.
Public Member Functions inherited from QUESO::BaseVectorRV< V, M >
BaseVectorRV (const char *prefix, const VectorSet< V, M > &imageSet)
Constructor.
virtual ~BaseVectorRV ()
Virtual destructor.
const BaseEnvironment & env () const
QUESO environment; access to private attribute m_env.
const VectorSet< V, M > & imageSet () const
Image set of the vector RV; access to private attribute m_imageSet.
const BaseJointPdf< V, M > & pdf () const
Posterior Density Function of the vector RV; access to private attribute m_pdf.
const BaseVectorRealizer< V, M > & realizer () const
Finds a realization (sample) of the PDF of this vector RV; access to private attribute m_realizer.
const BaseVectorCdf< V, M > & subCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering only the sub-sequence of data; access to private attribute m_subCdf.
const BaseVectorCdf< V, M > & unifiedCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering the unified sequence of data; access to private attribute m_unifiedCdf.
const BaseVectorMdf< V, M > & mdf () const
Finds the Mass Density Function of this vector RV; access to private attribute m_mdf.
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseVectorRV< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_imageSet
BaseJointPdf< V, M > * m_pdf
BaseVectorRealizer< V, M > * m_realizer
const BaseVectorCdf< V, M > * m_subCdf
const BaseVectorCdf< V, M > * m_unifiedCdf
const BaseVectorMdf< V, M > * m_mdf
Detailed Description
template<class V, class M>
class QUESO::InverseGammaVectorRV< V, M >
A class representing a vector RV constructed via Inverse Gamma distribution.
This class allows the user to compute the value of a Inverse Gamma PDF and to generate realizations (samples) from it.
The Inverse Gamma probability density function is defined over the support x > 0 given a shape parameters a and a scale parameter b is:
where is the Gamma function:
The parameters a and b must all be positive, and the values x must lie on the interval .
Definition at line 58 of file InverseGammaVectorRV.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::InverseGammaVectorRV< V, M >::InverseGammaVectorRV (const char * prefix, const VectorSet< V, M > & imageSet, const V & alpha, const V & beta)
Default Constructor.
Construct an Inverse Gamma vector RV with parameters alpha>0 and beta>0, whose variates live in imageSet. The constructor will check whether or not the data provided via imageSet belongs to , which is a requirement imposed by the Inverse Gamma distribution. If this condition is not satisfied, an error message will be displayed and the program will exit.
Definition at line 35 of file InverseGammaVectorRV.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRV< V, M >::imageSet(), QUESO::BaseVectorRV< V, M >::m_env, QUESO::BaseVectorRV< V, M >::m_imageSet, QUESO::BaseVectorRV< V, M >::m_mdf, QUESO::BaseVectorRV< V, M >::m_pdf, QUESO::BaseVectorRV< V, M >::m_prefix, QUESO::BaseVectorRV< V, M >::m_realizer, QUESO::BaseVectorRV< V, M >::m_subCdf, QUESO::BaseVectorRV< V, M >::m_unifiedCdf, QUESO::BoxSubset< V, M >::maxValues(), QUESO::BoxSubset< V, M >::minValues(), QUESO::BaseEnvironment::subDisplayFile(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   BaseVectorRV<V,M>(((std::string)(prefix)+"uni").c_str(),imageSet)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering InverseGammaVectorRV<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 // begin kemelli 2013-April-22 --------------------------
 // InverseGamma dist is defined only in (0,inf)
   const BoxSubset<V,M>* imageBox = dynamic_cast<const BoxSubset<V,M>* >(&imageSet);
   double smallerOfMaxValues = imageBox->maxValues().getMinValue();
   double smallerOfMinValues = imageBox->minValues().getMinValue();
  if( smallerOfMinValues < 0 )
  {
    std::cerr << "In InverseGammaVectorRV<V,M>::constructor()\n"
        << "Inverse Gamma distribution is only defined in (0, infinity).\n"
        << "The data provided is: \n"
        << *imageBox
          << "Sampling will not cover all interval.\n"
          << std::endl;
     UQ_FATAL_TEST_MACRO(smallerOfMaxValues < 0,
                       m_env.worldRank(),
                       "InverseGammaVectorRealizer<V,M>::constructor()",
                       "invalid input: Inverse Gamma distribution is only defined in (0, infinity), and min(m_maxValues)<0");
  }
 // end kemelli 2013-April-22 --------------------------
   m_pdf        = new InverseGammaJointPdf<V,M>(m_prefix.c_str(),
                                                       m_imageSet,
                                                       alpha,
                                                       beta);
   m_realizer   = new InverseGammaVectorRealizer<V,M>(m_prefix.c_str(),
                                                             m_imageSet,
                                                             alpha,
                                                             beta);
   m_subCdf     = NULL; // FIX ME: complete code
   m_unifiedCdf = NULL; // FIX ME: complete code
   m_mdf        = NULL; // FIX ME: complete code
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving InverseGammaVectorRV<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::InverseGammaVectorRV< V, M >::~InverseGammaVectorRV () virtual
Virtual destructor.
Definition at line 91 of file InverseGammaVectorRV.C.
 {
   delete m_mdf;
   delete m_unifiedCdf;
   delete m_subCdf;
   delete m_realizer;
   delete m_pdf;
 }
Member Function Documentation
template<class V , class M > void QUESO::InverseGammaVectorRV< V, M >::print (std::ostream & os) const virtual
TODO: Prints the vector RV.
Todo:
: implement me!
Implements QUESO::BaseVectorRV< V, M >.
Definition at line 102 of file InverseGammaVectorRV.C.
 {
   os << "InverseGammaVectorRV<V,M>::print() says, 'Please implement me.'" << std::endl;
   return;
 }
The documentation for this class was generated from the following files:
src/stats/inc/InverseGammaVectorRV.h
src/stats/src/InverseGammaVectorRV.C