queso-0.51.0: QUESO::ArrayOfOneDTables< V, M > Class Template Reference
QUESO::ArrayOfOneDTables< V, M > Class Template Reference
Class to accommodate arrays of one-dimensional tables.
#include <ArrayOfOneDTables.h>
Public Member Functions
Constructor/Destructor methods
ArrayOfOneDTables (const char *prefix, const VectorSpace< V, M > &rowSpace)
Default constructor.
~ArrayOfOneDTables ()
Destructor.
Math methods
void setOneDTable (unsigned int rowId, const std::vector< double > &values)
Sets the one-dimensional table.
const std::vector< double > & oneDTable (unsigned int rowId) const
Returns the array located at position rowId of the one-dimensional table.
I/O method
void print (std::ostream &os) const
Prints the values in this array of tables.
Private Attributes
const BaseEnvironment & m_env
std::string m_prefix
const VectorSpace< V, M > & m_rowSpace
DistArray< std::vector< double > * > m_oneDTables
Detailed Description
template<class V, class M>
class QUESO::ArrayOfOneDTables< V, M >
Class to accommodate arrays of one-dimensional tables.
Arrays of one-dimensional tables are necessary in the calculation (storage), for instance, of CDFs and MDF of vector functions (refer to BaseVectorCdf, BaseVectorMdf, and derived classes) given the (array of) grid points (ArrayOfOneDGrids).
Definition at line 46 of file ArrayOfOneDTables.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::ArrayOfOneDTables< V, M >::ArrayOfOneDTables (const char * prefix, const VectorSpace< V, M > & rowSpace)
Default constructor.
Definition at line 33 of file ArrayOfOneDTables.C.
References QUESO::ArrayOfOneDTables< V, M >::m_oneDTables, and QUESO::DistArray< T >::MyLength().
   :
   m_env       (rowSpace.env()),
   m_prefix    ((std::string)(prefix)+""),
   m_rowSpace  (rowSpace      ),
   m_oneDTables(m_rowSpace.map(),1)
 {
   for (unsigned int i = 0; i < (unsigned int) m_oneDTables.MyLength(); ++i) {
     m_oneDTables(i,0) = NULL;
   }
 }
template<class V , class M > QUESO::ArrayOfOneDTables< V, M >::~ArrayOfOneDTables ()
Destructor.
Definition at line 49 of file ArrayOfOneDTables.C.
 {
   for (unsigned int i = 0; i < (unsigned int) m_oneDTables.MyLength(); ++i) {
     if (m_oneDTables(i,0)) delete m_oneDTables(i,0);
   }
 }
Member Function Documentation
template<class V , class M > const std::vector< double > & QUESO::ArrayOfOneDTables< V, M >::oneDTable (unsigned int rowId) const
Returns the array located at position rowId of the one-dimensional table.
Definition at line 80 of file ArrayOfOneDTables.C.
References UQ_FATAL_TEST_MACRO.
Referenced by QUESO::SampledVectorCdf< V, M >::SampledVectorCdf().
 {
   UQ_FATAL_TEST_MACRO(rowId >= (unsigned int) m_oneDTables.MyLength(),
                       m_env.worldRank(),
                       "ArrayOfOneDTables<T>::oneDTable()",
                       "rowId is out of range");
   ArrayOfOneDTables<V,M>* tmp = const_cast<ArrayOfOneDTables<V,M>*>(this);
   UQ_FATAL_TEST_MACRO(tmp->m_oneDTables(rowId,0) == NULL,
                       m_env.worldRank(),
                       "ArrayOfOneDTables<T>::oneDTable()",
                       "requested row is still NULL");
   return *(tmp->m_oneDTables(rowId,0));
 }
template<class V , class M > void QUESO::ArrayOfOneDTables< V, M >::print (std::ostream & os) const
Prints the values in this array of tables.
It prints the arrays (inner for-loop) in each position of the table (outer for-loop).
Definition at line 100 of file ArrayOfOneDTables.C.
References QUESO::ArrayOfOneDTables< V, M >::m_oneDTables.
Referenced by QUESO::operator<<().
 {
   ArrayOfOneDTables<V,M>* tmp = const_cast<ArrayOfOneDTables<V,M>*>(this);
   for (unsigned int i = 0; i < (unsigned int) m_oneDTables.MyLength(); ++i) {
     const std::vector<double>& tmpVec = *(tmp->m_oneDTables(i,0));
     os << m_prefix << i << "_values_sub" << m_env.subIdString() << " = zeros(" << tmpVec.size()
        << ","                                                                  << 1
        << ");"
        << std::endl;
     os << m_prefix << i << "_values_sub" << m_env.subIdString() << " = [";
     for (unsigned int j = 0; j < tmpVec.size(); ++j) {
       os << tmpVec[j] << " ";
     }
     os << "];"
        << std::endl;
   }
   return;
 }
template<class V , class M > void QUESO::ArrayOfOneDTables< V, M >::setOneDTable (unsigned int rowId, const std::vector< double > & values)
Sets the one-dimensional table.
This methods assigns the array values to position rowId of the one-dimensional table.
Definition at line 59 of file ArrayOfOneDTables.C.
References UQ_FATAL_TEST_MACRO.
Referenced by QUESO::SequenceOfVectors< V, M >::subUniformlySampledCdf(), and QUESO::SequenceOfVectors< V, M >::unifiedUniformlySampledCdf().
 {
   UQ_FATAL_TEST_MACRO(rowId >= (unsigned int) m_oneDTables.MyLength(),
                       m_env.worldRank(),
                       "ArrayOfOneDTables<T>::setOneDTable()",
                       "rowId is out of range");
   if (m_oneDTables(rowId,0) == NULL) m_oneDTables(rowId,0) = new std::vector<double>(0);
   else                               m_oneDTables(rowId,0)->clear();
   std::vector<double>& vec = *(m_oneDTables(rowId,0));
   vec.resize(values.size(),0.);
   for (unsigned int j = 0; j < values.size(); ++j) {
     vec[j] = values[j];
   }
   return;
 }
Member Data Documentation
template<class V, class M> const BaseEnvironment& QUESO::ArrayOfOneDTables< V, M >::m_env private
Definition at line 75 of file ArrayOfOneDTables.h.
template<class V, class M> DistArray<std::vector<double>*> QUESO::ArrayOfOneDTables< V, M >::m_oneDTables private
Definition at line 78 of file ArrayOfOneDTables.h.
Referenced by QUESO::ArrayOfOneDTables< V, M >::ArrayOfOneDTables(), and QUESO::ArrayOfOneDTables< V, M >::print().
template<class V, class M> std::string QUESO::ArrayOfOneDTables< V, M >::m_prefix private
Definition at line 76 of file ArrayOfOneDTables.h.
template<class V, class M> const VectorSpace<V,M>& QUESO::ArrayOfOneDTables< V, M >::m_rowSpace private
Definition at line 77 of file ArrayOfOneDTables.h.
The documentation for this class was generated from the following files:
src/misc/inc/ArrayOfOneDTables.h
src/misc/src/ArrayOfOneDTables.C