queso-0.51.0: QUESO::ConcatenatedJointPdf< V, M > Class Template Reference
QUESO::ConcatenatedJointPdf< V, M > Class Template Reference
A class for handling concatenated PDFs.
#include <ConcatenatedJointPdf.h>
Public Member Functions
Constructor/Destructor methods
ConcatenatedJointPdf (const char *prefix, const BaseJointPdf< V, M > &density1, const BaseJointPdf< V, M > &density2, const VectorSet< V, M > &concatenatedDomain)
Constructor.
ConcatenatedJointPdf (const char *prefix, const std::vector< const BaseJointPdf< V, M > * > &densities, const VectorSet< V, M > &concatenatedDomain)
Constructor.
~ConcatenatedJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Calculates the actual values of each density.
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Calculates the logarithm of the values of each density.
void setNormalizationStyle (unsigned int value) const
Sets the normalization style of all densities to value.
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
Protected Attributes
std::vector< const
BaseJointPdf< V, M > * > m_densities
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Detailed Description
template<class V, class M>
class QUESO::ConcatenatedJointPdf< V, M >
A class for handling concatenated PDFs.
This class allows the user to defines concatenated probability density distributions, i.e, two or more distinct PDFs can be concatenated into one single PDF. This class used, for instance, to concatenate priors from two or more RVs, where one of them has a uniform distribution whereas the other one(s) has a Gaussian distribution.
Definition at line 52 of file ConcatenatedJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::ConcatenatedJointPdf< V, M >::ConcatenatedJointPdf (const char * prefix, const BaseJointPdf< V, M > & density1, const BaseJointPdf< V, M > & density2, const VectorSet< V, M > & concatenatedDomain)
Constructor.
Concatenates two PDFs: density1 and density2 into one vector PDF, given a prefix and the concatenated domain of such PDFs.
Definition at line 33 of file ConcatenatedJointPdf.C.
References QUESO::ConcatenatedJointPdf< V, M >::m_densities, QUESO::BaseScalarFunction< V, M >::m_env, UQ_FATAL_TEST_MACRO, QUESO::VectorSet< V, M >::vectorSpace(), and QUESO::BaseEnvironment::worldRank().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"concat").c_str(),concatenatedDomain),
   m_densities             (2,(const BaseJointPdf<V,M>*) NULL)
 {
   m_densities[0] = &density1;
   m_densities[1] = &density2;
   unsigned int size1 = m_densities[0]->domainSet().vectorSpace().dimLocal();
   unsigned int size2 = m_densities[1]->domainSet().vectorSpace().dimLocal();
   unsigned int size  = concatenatedDomain.vectorSpace().dimLocal();
   UQ_FATAL_TEST_MACRO((size1+size2) != size,
                       m_env.worldRank(),
                       "ConcatenatedJointPdf<V,M>::constructor(1)",
                       "incompatible dimensions");
 }
template<class V , class M > QUESO::ConcatenatedJointPdf< V, M >::ConcatenatedJointPdf (const char * prefix, const std::vector< const BaseJointPdf< V, M > * > & densities, const VectorSet< V, M > & concatenatedDomain)
Constructor.
Concatenates a sequence of PDFs, given by: std::vector<const BaseJointPdf<V,M>* >& densities into one single PDF, given a prefix and the concatenated domain of such PDFs.
Definition at line 56 of file ConcatenatedJointPdf.C.
References QUESO::ConcatenatedJointPdf< V, M >::m_densities, QUESO::BaseScalarFunction< V, M >::m_env, UQ_FATAL_TEST_MACRO, QUESO::VectorSet< V, M >::vectorSpace(), and QUESO::BaseEnvironment::worldRank().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"concat").c_str(),concatenatedDomain),
   m_densities             (densities.size(),(const BaseJointPdf<V,M>*) NULL)
 {
   unsigned int sumSizes = 0;
   for (unsigned i = 0; i < m_densities.size(); ++i) {
     m_densities[i] = densities[i];
     sumSizes += m_densities[i]->domainSet().vectorSpace().dimLocal();
   }
   unsigned int size  = concatenatedDomain.vectorSpace().dimLocal();
   UQ_FATAL_TEST_MACRO(sumSizes != size,
                       m_env.worldRank(),
                       "ConcatenatedJointPdf<V,M>::constructor(2)",
                       "incompatible dimensions");
 }
template<class V , class M > QUESO::ConcatenatedJointPdf< V, M >::~ConcatenatedJointPdf ()
Destructor.
Definition at line 79 of file ConcatenatedJointPdf.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::ConcatenatedJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Calculates the actual values of each density.
The final actual value is the multiplication of all values calculated.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 95 of file ConcatenatedJointPdf.C.
References UQ_FATAL_TEST_MACRO.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ConcatenatedJointPdf<V,M>::actualValue()"
                             << ": domainVector = " << domainVector
                             << std::endl;
   }
   UQ_FATAL_TEST_MACRO(domainVector.sizeLocal() != this->m_domainSet.vectorSpace().dimLocal(),
                       m_env.worldRank(),
                       "ConcatenatedJointPdf<V,M>::actualValue()",
                       "invalid input");
   UQ_FATAL_TEST_MACRO((domainDirection || gradVector || hessianMatrix || hessianEffect),
                       m_env.worldRank(),
                       "ConcatenatedJointPdf<V,M>::actualValue()",
                       "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   std::vector<V*> vecs(m_densities.size(),(V*) NULL);
   std::vector<double> values(m_densities.size(),0.);
   double returnValue = 1.;
   unsigned int cummulativeSize = 0;
   for (unsigned int i = 0; i < vecs.size(); ++i) {
     vecs[i] = new V(m_densities[i]->domainSet().vectorSpace().zeroVector());
     domainVector.cwExtract(cummulativeSize,*(vecs[i]));
     values[i] = m_densities[i]->actualValue(*(vecs[i]),NULL,NULL,NULL,NULL);
     returnValue *= values[i];
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99)) {
       *m_env.subDisplayFile() << "In ConcatenatedJointPdf<V,M>::actualValue()"
                               << ", *(vecs[" << i << "]) = "       << *(vecs[i])
                               << ": values[" << i << "] = "        << values[i]
                               << ", temporary cumulative value = " << returnValue
                               << std::endl;
     }
     cummulativeSize += vecs[i]->sizeLocal();
     delete vecs[i];
   }
   //returnValue *= exp(m_logOfNormalizationFactor); // No need, because each PDF should be already normalized [PDF-11]
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ConcatenatedJointPdf<V,M>::actualValue()"
                             << ": domainVector = " << domainVector
                             << ", returnValue = "  << returnValue
                             << std::endl;
   }
   return returnValue;
 }
template<class V , class M > double QUESO::ConcatenatedJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
Computes the logarithm of the normalization factor.
This method calls the computeLogOfNormalizationFactor() for each one of the densities that have been concatenated.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 202 of file ConcatenatedJointPdf.C.
 {
   double value = 0.;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering ConcatenatedJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << std::endl;
   }
   double volume = m_domainSet.volume();
   if (((boost::math::isnan)(volume)) ||
       (volume == -INFINITY         ) ||
       (volume ==  INFINITY         ) ||
       (volume <= 0.                )) {
     // Do nothing
   }
   else {
     for (unsigned int i = 0; i < m_densities.size(); ++i) {
       m_densities[i]->computeLogOfNormalizationFactor(numSamples, updateFactorInternally);
     }
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving ConcatenatedJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << ", m_logOfNormalizationFactor = " << m_logOfNormalizationFactor
                             << std::endl;
   }
   return value;
 }
template<class V , class M > double QUESO::ConcatenatedJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Calculates the logarithm of the values of each density.
The final logarithm value is the addition of all values calculated.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 151 of file ConcatenatedJointPdf.C.
References UQ_FATAL_TEST_MACRO.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ConcatenatedJointPdf<V,M>::lnValue()"
                             << ": domainVector = " << domainVector
                             << std::endl;
   }
   UQ_FATAL_TEST_MACRO((domainDirection || gradVector || hessianMatrix || hessianEffect),
                       m_env.worldRank(),
                       "ConcatenatedJointPdf<V,M>::lnValue()",
                       "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   std::vector<V*> vecs(m_densities.size(),(V*) NULL);
   std::vector<double> values(m_densities.size(),0.);
   double returnValue = 0.;
   unsigned int cummulativeSize = 0;
   for (unsigned int i = 0; i < vecs.size(); ++i) {
     vecs[i] = new V(m_densities[i]->domainSet().vectorSpace().zeroVector());
     domainVector.cwExtract(cummulativeSize,*(vecs[i]));
     values[i] = m_densities[i]->lnValue(*(vecs[i]),NULL,NULL,NULL,NULL);
     returnValue += values[i];
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99)) {  // gpmsa
       *m_env.subDisplayFile() << "In ConcatenatedJointPdf<V,M>::lnValue()"
                               << ", *(vecs[" << i << "]) = "       << *(vecs[i])
                               << ": values[" << i << "] = "        << values[i]
                               << ", temporary cumulative value = " << returnValue
                               << std::endl;
     }
     cummulativeSize += vecs[i]->sizeLocal();
     delete vecs[i];
   }
   //returnValue += m_logOfNormalizationFactor; // No need, because each PDF should be already normalized [PDF-11]
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ConcatenatedJointPdf<V,M>::lnValue()"
                             << ": domainVector = " << domainVector
                             << ", returnValue = "  << returnValue
                             << std::endl;
   }
   return returnValue;
 }
template<class V , class M > void QUESO::ConcatenatedJointPdf< V, M >::setNormalizationStyle (unsigned int value) const virtual
Sets the normalization style of all densities to value.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 85 of file ConcatenatedJointPdf.C.
 {
   for (unsigned i = 0; i < m_densities.size(); ++i) {
     m_densities[i]->setNormalizationStyle(value);
   }
   return;
 }
Member Data Documentation
template<class V, class M> std::vector<const BaseJointPdf<V,M>* > QUESO::ConcatenatedJointPdf< V, M >::m_densities protected
Definition at line 100 of file ConcatenatedJointPdf.h.
Referenced by QUESO::ConcatenatedJointPdf< V, M >::ConcatenatedJointPdf().
The documentation for this class was generated from the following files:
src/stats/inc/ConcatenatedJointPdf.h
src/stats/src/ConcatenatedJointPdf.C