queso-0.50.0: QUESO::DistArray< T > Class Template Reference
QUESO::DistArray< T > Class Template Reference
A class for partitioning vectors and matrices.
#include <DistArray.h>
Public Member Functions
Constructor/Destructor methods
DistArray ()
Default constructor. Do not call this directly.
DistArray (const Map &inputMap, const int inputRowSize)
Constructor for a given inputMap and inputRowSize.
DistArray (const DistArray< T > &src)
Copy constructor.
~DistArray ()
Destructor.
Set methods
DistArray< T > & operator= (const DistArray< T > &rhs)
Assignment operator.
Query methods
T & operator() (int localElementId, int colId)
Returns a reference to the colId column component of the localElementId local element.
const T & operator() (int localElementId, int colId) const
Returns a reference to the colId column component of the localElementId local element.(const)
int GlobalLength () const
Returns the global length of the array.
int MyLength () const
Returns the length of the locally owned array.
int RowSize () const
Returns the row size, that is, the amount of data associated with each element.
Private Member Functions
void copy (const DistArray< T > &src)
Copies the array.
Private Attributes
Map m_Map
unsigned int m_rowSize
std::vector< std::vector< T > > m_elements
I/O methods
void print (std::ostream &os) const
std::ostream & operator<< (std::ostream &os, const DistArray< T > &obj)
Detailed Description
template<typename T>
class QUESO::DistArray< T >
A class for partitioning vectors and matrices.
Class DistArray allows the construction and usage of multi-vectors. These vectors contain element of type T, and the storage is row-oriented (instead of and not column-oriented; thus his class should be used as a container for data, on which no BLAS-like operations are performed).
DistArray objects are identified by an Map and a RowSize. The map specifies the distribution of the elements across the processors and therefore the number of local elements, while the RowSize gives the total number of data assigned to each node. RowSize is constant for all elements.
Definition at line 56 of file DistArray.h.
Constructor & Destructor Documentation
template<typename T > QUESO::DistArray< T >::DistArray ()
Default constructor. Do not call this directly.
Definition at line 36 of file DistArray.C.
References UQ_FATAL_TEST_MACRO, and QUESO::UQ_UNAVAILABLE_RANK.
   : m_Map()
 {
   UQ_FATAL_TEST_MACRO(true,
                       UQ_UNAVAILABLE_RANK,
                       "DistArray<T>::constructor()",
                       "should not be called");
 }
template<typename T > QUESO::DistArray< T >::DistArray (const Map & inputMap, const int inputRowSize)
Constructor for a given inputMap and inputRowSize.
Definition at line 47 of file DistArray.C.
References QUESO::DistArray< T >::m_elements, QUESO::DistArray< T >::m_Map, QUESO::DistArray< T >::m_rowSize, and QUESO::Map::NumGlobalElements().
   : m_Map(inputMap),
 #ifdef QUESO_HAS_TRILINOS
   m_epetraDistArray(new EpetraExt::DistArray<T>(inputMap.epetraMap(),inputRowSize))
 #else
   m_rowSize(inputRowSize)
 #endif
 {
 #ifdef QUESO_HAS_TRILINOS
 #else
   m_elements.resize(m_Map.NumGlobalElements());
   for (int i = 0; i < m_Map.NumGlobalElements(); ++i) {
     m_elements[i].resize(m_rowSize);
   }
 #endif
 }
template<typename T> QUESO::DistArray< T >::DistArray (const DistArray< T > & src)
Copy constructor.
Definition at line 66 of file DistArray.C.
References QUESO::DistArray< T >::copy(), and QUESO::DistArray< T >::m_elements.
   : m_Map(src.m_Map)
 #ifdef QUESO_HAS_TRILINOS
   ,
   m_epetraDistArray(NULL)
 #endif
 {
 #ifdef QUESO_HAS_TRILINOS
 #else
   m_elements.clear();
 #endif
   this->copy(src);
 }
template<typename T > QUESO::DistArray< T >::~DistArray ()
Destructor.
Definition at line 82 of file DistArray.C.
 {
 #ifdef QUESO_HAS_TRILINOS
   delete m_epetraDistArray;
   m_epetraDistArray = NULL;
 #else
   for (int i = 0; i < m_Map.NumGlobalElements(); ++i) {
     m_elements[i].clear();
   }
   m_elements.clear();
 #endif
 }
Member Function Documentation
template<typename T> void QUESO::DistArray< T >::copy (const DistArray< T > & src) private
Copies the array.
Definition at line 170 of file DistArray.C.
References queso_not_implemented.
Referenced by QUESO::DistArray< T >::DistArray().
 {
   queso_not_implemented();
 }
template<typename T > int QUESO::DistArray< T >::GlobalLength () const
Returns the global length of the array.
Definition at line 136 of file DistArray.C.
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraDistArray->GlobalLength();
 #else
   return m_Map.NumGlobalElements();
 #endif
 }
template<typename T > int QUESO::DistArray< T >::MyLength () const
Returns the length of the locally owned array.
Definition at line 147 of file DistArray.C.
Referenced by QUESO::ArrayOfOneDTables< V, M >::ArrayOfOneDTables().
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraDistArray->MyLength();
 #else
   return m_Map.NumMyElements();
 #endif
 }
template<typename T > T & QUESO::DistArray< T >::operator() (int localElementId, int colId)
Returns a reference to the colId column component of the localElementId local element.
Definition at line 114 of file DistArray.C.
 {
 #ifdef QUESO_HAS_TRILINOS
   return (*m_epetraDistArray)(localElementId,colId);
 #else
   return m_elements[localElementId][colId];
 #endif
 }
template<typename T > const T & QUESO::DistArray< T >::operator() (int localElementId, int colId) const
Returns a reference to the colId column component of the localElementId local element.(const)
Definition at line 125 of file DistArray.C.
 {
 #ifdef QUESO_HAS_TRILINOS
   return (*m_epetraDistArray)(localElementId,colId);
 #else
   return m_elements[localElementId][colId];
 #endif
 }
template<typename T> DistArray< T > & QUESO::DistArray< T >::operator= (const DistArray< T > & rhs)
Assignment operator.
Definition at line 98 of file DistArray.C.
 {
 #ifdef QUESO_HAS_TRILINOS
 #else
   for (int i = 0; i < m_Map.NumGlobalElements(); ++i) {
     m_elements[i].clear();
   }
   m_elements.clear();
 #endif
   this->copy(rhs);
   return *this;
 }
template<typename T > void QUESO::DistArray< T >::print (std::ostream & os) const
Definition at line 178 of file DistArray.C.
 {
 #ifdef QUESO_HAS_TRILINOS
   os << *m_epetraDistArray;
 #else
   os << "m_rowSize = "           << m_rowSize
      << ", m_elements.size() = " << m_elements.size()
      << std::endl;
 #endif
   return;
 }
template<typename T > int QUESO::DistArray< T >::RowSize () const
Returns the row size, that is, the amount of data associated with each element.
Definition at line 158 of file DistArray.C.
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraDistArray->RowSize();
 #else
   return m_rowSize;
 #endif
 }
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, const DistArray< T > & obj) friend
Definition at line 106 of file DistArray.h.
   {
     obj.print(os);
     return os;
   }
Member Data Documentation
template<typename T> std::vector<std::vector<T> > QUESO::DistArray< T >::m_elements private
Definition at line 124 of file DistArray.h.
Referenced by QUESO::DistArray< T >::DistArray().
template<typename T> Map QUESO::DistArray< T >::m_Map private
Definition at line 119 of file DistArray.h.
Referenced by QUESO::DistArray< T >::DistArray().
template<typename T> unsigned int QUESO::DistArray< T >::m_rowSize private
Definition at line 123 of file DistArray.h.
Referenced by QUESO::DistArray< T >::DistArray().
The documentation for this class was generated from the following files:
src/core/inc/DistArray.h
src/core/src/DistArray.C