queso-0.51.0: QUESO::VectorSubset< V, M > Class Template Reference
QUESO::VectorSubset< V, M > Class Template Reference abstract
A templated class for handling subsets.
#include <VectorSubset.h>
Public Member Functions
Constructor/Destructor methods.
VectorSubset ()
Default Constructor.
VectorSubset (const char *prefix, const VectorSpace< V, M > &vectorSpace, double volume)
Shaped constructor (with volume).
virtual ~VectorSubset ()
Destructor.
Mathematical methods.
const VectorSpace< V, M > & vectorSpace () const
Vector space to which this set belongs to. See template specialization.
virtual bool contains (const V &vec) const =0
Returns whether this contains vector vec. See template specialization.
I/O methods.
virtual void print (std::ostream &os) const
Prints nothing.
Public Member Functions inherited from QUESO::VectorSet< V, M >
VectorSet ()
Default Constructor.
VectorSet (const BaseEnvironment &env, const char *prefix, double volume)
Shaped constructor.
virtual ~VectorSet ()
Virtual destructor.
const BaseEnvironment & env () const
Environment. Access to private attribute m_env.
const std::string & prefix () const
Access to private attribute m_prefix.
double volume () const
Set volume; access to private attribute m_volume.
Protected Attributes
const VectorSpace< V, M > * m_vectorSpace
Protected Attributes inherited from QUESO::VectorSet< V, M >
const BaseEnvironment & m_env
std::string m_prefix
double m_volume
Detailed Description
template<class V, class M>
class QUESO::VectorSubset< V, M >
A templated class for handling subsets.
This class specifies a subset. The most common example of a subset is a subset of a vector space, present, for instance, in the definition of a scalar function: . is a subset of the set , which is also a vector space.
Definition at line 44 of file VectorSubset.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::VectorSubset< V, M >::VectorSubset ()
Default Constructor.
It should not be used by the user.
Definition at line 34 of file VectorSubset.C.
References QUESO::VectorSet< V, M >::m_env, UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   : VectorSet<V,M>(),
     m_vectorSpace(NULL)
 {
   UQ_FATAL_TEST_MACRO(true,
                       m_env.worldRank(),
                       "VectorSubset<V,M>::constructor(), default",
                       "should not be used by user");
 }
template<class V, class M> QUESO::VectorSubset< V, M >::VectorSubset (const char * prefix, const VectorSpace< V, M > & vectorSpace, double volume)
Shaped constructor (with volume).
Definition at line 46 of file VectorSubset.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::VectorSet< V, M >::m_env, and QUESO::BaseEnvironment::subDisplayFile().
   : VectorSet<V,M>(vectorSpace.env(), prefix, volume),
     m_vectorSpace(&vectorSpace)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering VectorSubset<V,M>::constructor()"
               << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving VectorSubset<V,M>::constructor()"
               << std::endl;
   }
 }
template<class V , class M > QUESO::VectorSubset< V, M >::~VectorSubset () virtual
Destructor.
Definition at line 65 of file VectorSubset.C.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering VectorSubset<V,M>::destructor()"
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving VectorSubset<V,M>::destructor()"
                             << std::endl;
   }
 }
Member Function Documentation
template<class V, class M> virtual bool QUESO::VectorSubset< V, M >::contains (const V & vec) const pure virtual
Returns whether this contains vector vec. See template specialization.
Implements QUESO::VectorSet< V, M >.
Implemented in QUESO::ConcatenationSubset< V, M >, QUESO::BoxSubset< V, M >, QUESO::IntersectionSubset< V, M >, and QUESO::DiscreteSubset< V, M >.
template<class V , class M > void QUESO::VectorSubset< V, M >::print (std::ostream & os) const virtual
Prints nothing.
Reimplemented from QUESO::VectorSet< V, M >.
Reimplemented in QUESO::BoxSubset< V, M >, QUESO::BoxSubset< P_V, P_M >, QUESO::BoxSubset< Q_V, Q_M >, QUESO::ConcatenationSubset< V, M >, QUESO::IntersectionSubset< V, M >, and QUESO::DiscreteSubset< V, M >.
Definition at line 87 of file VectorSubset.C.
 {
   os << "In VectorSubset<V,M>::print()"
      << ": nothing to be printed" << std::endl;
   return;
 }
template<class V , class M > const VectorSpace< V, M > & QUESO::VectorSubset< V, M >::vectorSpace () const virtual
Vector space to which this set belongs to. See template specialization.
Implements QUESO::VectorSet< V, M >.
Definition at line 80 of file VectorSubset.C.
Referenced by QUESO::InstantiateIntersection().
 {
   return *m_vectorSpace;
 }
Member Data Documentation
template<class V, class M> const VectorSpace<V,M>* QUESO::VectorSubset< V, M >::m_vectorSpace protected
Definition at line 79 of file VectorSubset.h.
Referenced by QUESO::BoxSubset< V, M >::BoxSubset().
The documentation for this class was generated from the following files:
src/basic/inc/VectorSubset.h
src/basic/src/VectorSubset.C