queso-0.51.0: QUESO::TransformedScaledCovMatrixTKGroup< V, M > Class Template Reference
QUESO::TransformedScaledCovMatrixTKGroup< V, M > Class Template Reference
This class represents a transition kernel with a scaled covariance matrix on hybrid bounded/unbounded state spaces.
#include <TransformedScaledCovMatrixTKGroup.h>
Public Member Functions
void transformToGaussianSpace (const V &physicalPoint, V &transformedPoint) const
Constructor/Destructor methods
TransformedScaledCovMatrixTKGroup (const char *prefix, const BoxSubset< V, M > &boxSubset, const std::vector< double > &scales, const M &covMatrix)
Default constructor.
~TransformedScaledCovMatrixTKGroup ()
Destructor.
Statistical/Mathematical methods
bool symmetric () const
Whether or not the matrix is symmetric. Always 'false'.
const InvLogitGaussianVectorRV
< V, M > & rv (unsigned int stageId) const
InvLogitGaussian increment property to construct a transition kernel.
const InvLogitGaussianVectorRV
< V, M > & rv (const std::vector< unsigned int > &stageIds)
InvLogitGaussian increment property to construct a transition kernel.
void updateLawCovMatrix (const M &covMatrix)
Scales the covariance matrix of the underlying Gaussian distribution.
Misc methods
bool setPreComputingPosition (const V &position, unsigned int stageId)
Sets the pre-computing positions m_preComputingPositions[stageId] with a new vector of size position.
void clearPreComputingPositions ()
Clears the pre-computing positions m_preComputingPositions[stageId].
I/O methods
void print (std::ostream &os) const
TODO: Prints the transition kernel.
Public Member Functions inherited from QUESO::BaseTKGroup< V, M >
BaseTKGroup ()
Default constructor.
BaseTKGroup (const char *prefix, const VectorSpace< V, M > &vectorSpace, const std::vector< double > &scales)
Constructor.
virtual ~BaseTKGroup ()
Destructor.
const BaseEnvironment & env () const
QUESO's environment.
const V & preComputingPosition (unsigned int stageId) const
Pre-computing position; access to protected attribute *m_preComputingPositions[stageId].
Private Member Functions
void setRVsWithZeroMean ()
Sets the mean of the underlying Gaussian RVs to zero.
Private Attributes
const BoxSubset< V, M > & m_boxSubset
M m_originalCovMatrix
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseTKGroup< V, M >
const EmptyEnvironment * m_emptyEnv
const BaseEnvironment & m_env
std::string m_prefix
const VectorSpace< V, M > * m_vectorSpace
std::vector< double > m_scales
std::vector< const V * > m_preComputingPositions
std::vector< BaseVectorRV< V,
M > * > m_rvs
Detailed Description
template<class V, class M>
class QUESO::TransformedScaledCovMatrixTKGroup< V, M >
This class represents a transition kernel with a scaled covariance matrix on hybrid bounded/unbounded state spaces.
The unbounded directions utilise a standard Gaussian proposal. The bounded or half-bounded directions utilise a transformed Gaussian proposal, so that no realizations are generated outside of the state space.
Definition at line 45 of file TransformedScaledCovMatrixTKGroup.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup (const char * prefix, const BoxSubset< V, M > & boxSubset, const std::vector< double > & scales, const M & covMatrix)
Default constructor.
Definition at line 33 of file TransformedScaledCovMatrixTKGroup.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseTKGroup< V, M >::m_env, QUESO::TransformedScaledCovMatrixTKGroup< V, M >::m_originalCovMatrix, QUESO::BaseTKGroup< V, M >::m_preComputingPositions, QUESO::BaseTKGroup< V, M >::m_rvs, QUESO::BaseTKGroup< V, M >::m_scales, QUESO::TransformedScaledCovMatrixTKGroup< V, M >::setRVsWithZeroMean(), and QUESO::BaseEnvironment::subDisplayFile().
   : BaseTKGroup<V, M>(prefix, boxSubset.vectorSpace(), scales),
     m_boxSubset(boxSubset),
     m_originalCovMatrix(covMatrix)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering TransformedScaledCovMatrixTKGroup<V,M>::constructor()"
                            << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "In TransformedScaledCovMatrixTKGroup<V,M>::constructor()"
                            << ": m_scales.size() = "                << m_scales.size()
                            << ", m_preComputingPositions.size() = " << m_preComputingPositions.size()
                            << ", m_rvs.size() = "                   << m_rvs.size()
                            << ", m_originalCovMatrix = "            << m_originalCovMatrix
                            << std::endl;
   }
   // Set RVs to have zero mean in the Gaussian space
   setRVsWithZeroMean();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving TransformedScaledCovMatrixTKGroup<V,M>::constructor()"
                            << std::endl;
   }
 }
template<class V , class M > QUESO::TransformedScaledCovMatrixTKGroup< V, M >::~TransformedScaledCovMatrixTKGroup ()
Destructor.
Definition at line 66 of file TransformedScaledCovMatrixTKGroup.C.
 {
 }
Member Function Documentation
template<class V , class M > void QUESO::TransformedScaledCovMatrixTKGroup< V, M >::clearPreComputingPositions () virtual
Clears the pre-computing positions m_preComputingPositions[stageId].
Reimplemented from QUESO::BaseTKGroup< V, M >.
Definition at line 237 of file TransformedScaledCovMatrixTKGroup.C.
References QUESO::BaseTKGroup< V, M >::clearPreComputingPositions().
 {
   BaseTKGroup<V,M>::clearPreComputingPositions();
   return;
 }
template<class V , class M > void QUESO::TransformedScaledCovMatrixTKGroup< V, M >::print (std::ostream & os) const virtual
TODO: Prints the transition kernel.
Todo:
: implement me!
Reimplemented from QUESO::BaseTKGroup< V, M >.
Definition at line 275 of file TransformedScaledCovMatrixTKGroup.C.
References QUESO::BaseTKGroup< V, M >::print().
 {
   BaseTKGroup<V,M>::print(os);
   return;
 }
template<class V , class M > const InvLogitGaussianVectorRV< V, M > & QUESO::TransformedScaledCovMatrixTKGroup< V, M >::rv (unsigned int stageId) const virtual
InvLogitGaussian increment property to construct a transition kernel.
Implements QUESO::BaseTKGroup< V, M >.
Definition at line 79 of file TransformedScaledCovMatrixTKGroup.C.
References QUESO::InvLogitGaussianVectorRV< V, M >::updateLawExpVector(), and UQ_FATAL_TEST_MACRO.
 {
   UQ_FATAL_TEST_MACRO(m_rvs.size() == 0,
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::rv1()",
                       "m_rvs.size() = 0");
   UQ_FATAL_TEST_MACRO(m_rvs[0] == NULL, // Yes, '0', because that is the id used below
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::rv1()",
                       "m_rvs[0] == NULL");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions.size() <= stageId,
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::rv1()",
                       "m_preComputingPositions.size() <= stageId");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions[stageId] == NULL,
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::rv1()",
                       "m_preComputingPositions[stageId] == NULL");
   if ((m_env.subDisplayFile()        ) &&
       (m_env.displayVerbosity() >= 10)) {
     *m_env.subDisplayFile() << "In TransformedScaledCovMatrixTKGroup<V,M>::rv1()"
                             << ", stageId = " << stageId
                             << ": about to call m_rvs[0]->updateLawExpVector()"
                             << ", vector = " << *m_preComputingPositions[stageId] // FIX ME: might demand parallelism
                             << std::endl;
   }
   InvLogitGaussianVectorRV<V, M> * invlogit_gaussian =
     dynamic_cast<InvLogitGaussianVectorRV<V, M> * >(m_rvs[0]);
   V transformedPreComputingPositions(*m_preComputingPositions[stageId]);
   transformToGaussianSpace(*m_preComputingPositions[stageId],
       transformedPreComputingPositions);
   invlogit_gaussian->updateLawExpVector(transformedPreComputingPositions);
   return (*invlogit_gaussian);
 }
template<class V , class M > const InvLogitGaussianVectorRV< V, M > & QUESO::TransformedScaledCovMatrixTKGroup< V, M >::rv (const std::vector< unsigned int > & stageIds) virtual
InvLogitGaussian increment property to construct a transition kernel.
Implements QUESO::BaseTKGroup< V, M >.
Definition at line 124 of file TransformedScaledCovMatrixTKGroup.C.
References QUESO::InvLogitGaussianVectorRV< V, M >::updateLawExpVector(), and UQ_FATAL_TEST_MACRO.
 {
   UQ_FATAL_TEST_MACRO(m_rvs.size() < stageIds.size(),
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::rv2()",
                       "m_rvs.size() < stageIds.size()");
   UQ_FATAL_TEST_MACRO(m_rvs[stageIds.size()-1] == NULL,
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::rv2()",
                       "m_rvs[stageIds.size()-1] == NULL");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions.size() <= stageIds[0],
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::rv2()",
                       "m_preComputingPositions.size() <= stageIds[0]");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions[stageIds[0]] == NULL,
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::rv2()",
                       "m_preComputingPositions[stageIds[0]] == NULL");
   if ((m_env.subDisplayFile()        ) &&
       (m_env.displayVerbosity() >= 10)) {
     *m_env.subDisplayFile() << "In TransformedScaledCovMatrixTKGroup<V,M>::rv2()"
                             << ", stageIds.size() = " << stageIds.size()
                             << ", stageIds[0] = "     << stageIds[0]
                             << ": about to call m_rvs[stageIds.size()-1]->updateLawExpVector()"
                             << ", vector = " << *m_preComputingPositions[stageIds[0]] // FIX ME: might demand parallelism
                             << std::endl;
   }
   InvLogitGaussianVectorRV<V, M> * invlogit_gaussian =
     dynamic_cast<InvLogitGaussianVectorRV<V, M> * >(m_rvs[stageIds.size()-1]);
   V transformedPreComputingPositions(*m_preComputingPositions[stageIds[0]]);
   transformToGaussianSpace(*m_preComputingPositions[stageIds[0]],
       transformedPreComputingPositions);
   invlogit_gaussian->updateLawExpVector(transformedPreComputingPositions);
   return (*invlogit_gaussian);
 }
template<class V , class M > bool QUESO::TransformedScaledCovMatrixTKGroup< V, M >::setPreComputingPosition (const V & position, unsigned int stageId) virtual
Sets the pre-computing positions m_preComputingPositions[stageId] with a new vector of size position.
The vector position is in physical space. This is then transformed using transformToGaussianSpace to map to a point in Gaussian space where we can, for example, update the mean of the underlying Gaussian RV.
Reimplemented from QUESO::BaseTKGroup< V, M >.
Definition at line 198 of file TransformedScaledCovMatrixTKGroup.C.
References QUESO::InvLogitGaussianJointPdf< V, M >::lawCovMatrix(), and QUESO::BaseTKGroup< V, M >::setPreComputingPosition().
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering TransformedScaledCovMatrixTKGroup<V,M>::setPreComputingPosition()"
                            << ": position = " << position
                            << ", stageId = "  << stageId
                            << std::endl;
   }
   BaseTKGroup<V,M>::setPreComputingPosition(position,stageId);
   //setRVsWithZeroMean();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "In TransformedScaledCovMatrixTKGroup<V,M>::setPreComputingPosition()"
                            << ", position = "        << position
                            << ", stageId = "         << stageId
                            << ": preComputingPos = " << *m_preComputingPositions[stageId];
     if (stageId < m_scales.size()) {
       *m_env.subDisplayFile() << ", factor = " << 1./m_scales[stageId]/m_scales[stageId];
     }
     if (stageId < m_rvs.size()) {
       const InvLogitGaussianJointPdf<V,M>* pdfPtr = dynamic_cast< const InvLogitGaussianJointPdf<V,M>* >(&(m_rvs[stageId]->pdf()));
       *m_env.subDisplayFile() << ", rvCov = " << pdfPtr->lawCovMatrix(); // FIX ME: might demand parallelism
     }
     *m_env.subDisplayFile() << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving TransformedScaledCovMatrixTKGroup<V,M>::setPreComputingPosition()"
                            << ": position = " << position
                            << ", stageId = "  << stageId
                            << std::endl;
   }
   return true;
 }
template<class V , class M > void QUESO::TransformedScaledCovMatrixTKGroup< V, M >::setRVsWithZeroMean () private
Sets the mean of the underlying Gaussian RVs to zero.
Definition at line 247 of file TransformedScaledCovMatrixTKGroup.C.
References UQ_FATAL_TEST_MACRO.
Referenced by QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup().
 {
   UQ_FATAL_TEST_MACRO(m_rvs.size() == 0,
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::setRVsWithZeroMean()",
                       "m_rvs.size() = 0");
   UQ_FATAL_TEST_MACRO(m_rvs.size() != m_scales.size(),
                       m_env.worldRank(),
                       "TransformedScaledCovMatrixTKGroup<V,M>::setRVsWithZeroMean()",
                       "m_rvs.size() != m_scales.size()");
   for (unsigned int i = 0; i < m_scales.size(); ++i) {
     double factor = 1./m_scales[i]/m_scales[i];
     UQ_FATAL_TEST_MACRO(m_rvs[i] != NULL,
                         m_env.worldRank(),
                         "TransformedScaledCovMatrixTKGroup<V,M>::setRVsWithZeroMean()",
                         "m_rvs[i] != NULL");
     m_rvs[i] = new InvLogitGaussianVectorRV<V,M>(m_prefix.c_str(),
         m_boxSubset, m_vectorSpace->zeroVector(),
         factor*m_originalCovMatrix);
   }
   return;
 }
template<class V , class M > bool QUESO::TransformedScaledCovMatrixTKGroup< V, M >::symmetric () const virtual
Whether or not the matrix is symmetric. Always 'false'.
Implements QUESO::BaseTKGroup< V, M >.
Definition at line 72 of file TransformedScaledCovMatrixTKGroup.C.
 {
   return false;
 }
template<class V , class M > void QUESO::TransformedScaledCovMatrixTKGroup< V, M >::transformToGaussianSpace (const V & physicalPoint, V & transformedPoint) const
Definition at line 283 of file TransformedScaledCovMatrixTKGroup.C.
 {
   V min_domain_bounds(this->m_boxSubset.minValues());
   V max_domain_bounds(this->m_boxSubset.maxValues());
   for (unsigned int i = 0; i < transformedPoint.sizeLocal(); i++) {
     double min_val = min_domain_bounds[i];
     double max_val = max_domain_bounds[i];
     if (boost::math::isfinite(min_val) &&
         boost::math::isfinite(max_val)) {
         // Left- and right-hand sides are finite.  Do full transform.
         transformedPoint[i] = std::log(physicalPoint[i] - min_val) -
             std::log(max_val - physicalPoint[i]);
     }
     else if (boost::math::isfinite(min_val) &&
              !boost::math::isfinite(max_val)) {
       // Left-hand side finite, but right-hand side is not.
       // Do only left-hand transform.
       transformedPoint[i] = std::log(physicalPoint[i] - min_val);
     }
     else if (!boost::math::isfinite(min_val) &&
              boost::math::isfinite(max_val)) {
       // Right-hand side is finite, but left-hand side is not.
       // Do only right-hand transform.
       transformedPoint[i] = -std::log(max_val - physicalPoint[i]);
     }
     else {
       // No transform.
       transformedPoint[i] = physicalPoint[i];
     }
   }
 }
template<class V , class M > void QUESO::TransformedScaledCovMatrixTKGroup< V, M >::updateLawCovMatrix (const M & covMatrix)
Scales the covariance matrix of the underlying Gaussian distribution.
The covariance matrix is scaled by a factor of .
Definition at line 170 of file TransformedScaledCovMatrixTKGroup.C.
References QUESO::InvLogitGaussianVectorRV< V, M >::updateLawCovMatrix().
 {
   for (unsigned int i = 0; i < m_scales.size(); ++i) {
     double factor = 1./m_scales[i]/m_scales[i];
     if ((m_env.subDisplayFile()        ) &&
         (m_env.displayVerbosity() >= 10)) {
       *m_env.subDisplayFile() << "In TransformedScaledCovMatrixTKGroup<V,M>::updateLawCovMatrix()"
                               << ", m_scales.size() = " << m_scales.size()
                               << ", i = "               << i
                               << ", m_scales[i] = "     << m_scales[i]
                               << ", factor = "          << factor
                               << ": about to call m_rvs[i]->updateLawCovMatrix()"
                               << ", covMatrix = \n" << factor*covMatrix // FIX ME: might demand parallelism
                               << std::endl;
     }
     InvLogitGaussianVectorRV<V, M> * invlogit_gaussian =
       dynamic_cast<InvLogitGaussianVectorRV<V, M> * >(m_rvs[i]);
     invlogit_gaussian->updateLawCovMatrix(factor*covMatrix);
   }
   return;
 }
Member Data Documentation
template<class V , class M > const BoxSubset<V, M>& QUESO::TransformedScaledCovMatrixTKGroup< V, M >::m_boxSubset private
Definition at line 113 of file TransformedScaledCovMatrixTKGroup.h.
template<class V , class M > M QUESO::TransformedScaledCovMatrixTKGroup< V, M >::m_originalCovMatrix private
Definition at line 114 of file TransformedScaledCovMatrixTKGroup.h.
Referenced by QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup().
The documentation for this class was generated from the following files:
src/stats/inc/TransformedScaledCovMatrixTKGroup.h
src/stats/src/TransformedScaledCovMatrixTKGroup.C