queso-0.50.1: QUESO::ScalarTimesFunc1D1DFunction Class Reference
QUESO::ScalarTimesFunc1D1DFunction Class Reference
Class for multiplication of a one-dimensional function by a scalar.
#include <1D1DFunction.h>
Public Member Functions
Constructor/Destructor methods
ScalarTimesFunc1D1DFunction (double scalar, const Base1D1DFunction &func)
Default constructor.
~ScalarTimesFunc1D1DFunction ()
Destructor.
Mathematical methods
double value (double domainValue) const
Returns the value of the (one-dimensional) function at point domainValue, already multiplied by the scalar (given during construction).
double deriv (double domainValue) const
TODO: Returns the value of the derivative of the function multiplied by the given scalar at point domainValue.
Public Member Functions inherited from QUESO::Base1D1DFunction
Base1D1DFunction (double minDomainValue, double maxDomainValue)
Default constructor.
virtual ~Base1D1DFunction ()
Destructor.
double minDomainValue () const
Returns the minimum value of the domain of the (one-dimensional) function.
double maxDomainValue () const
Returns the maximum value of the domain of the (one-dimensional) function.
virtual double multiplyAndIntegrate (const Base1D1DFunction &func, unsigned int quadratureOrder, double *resultWithMultiplicationByTAsWell) const
TODO: Multiplies this function with function, and integrates it numerically. See template specialization.
Protected Attributes
double m_scalar
const Base1D1DFunction & m_func
Protected Attributes inherited from QUESO::Base1D1DFunction
double m_minDomainValue
double m_maxDomainValue
Detailed Description
Class for multiplication of a one-dimensional function by a scalar.
This class implements the multiplication of a generic one-dimensional function (implemented through any class derived from Base1D1DFunction) by a given scalar.
Definition at line 421 of file 1D1DFunction.h.
Constructor & Destructor Documentation
QUESO::ScalarTimesFunc1D1DFunction::ScalarTimesFunc1D1DFunction (double scalar, const Base1D1DFunction & func)
Default constructor.
Definition at line 665 of file 1D1DFunction.C.
   :
   Base1D1DFunction(func.minDomainValue(),func.maxDomainValue()),
   m_scalar(scalar),
   m_func  (func)
 {
 }
QUESO::ScalarTimesFunc1D1DFunction::~ScalarTimesFunc1D1DFunction ()
Destructor.
Definition at line 675 of file 1D1DFunction.C.
 {
 }
Member Function Documentation
double QUESO::ScalarTimesFunc1D1DFunction::deriv (double domainValue) const virtual
TODO: Returns the value of the derivative of the function multiplied by the given scalar at point domainValue.
Todo:
Please, implement me!
Implements QUESO::Base1D1DFunction.
Definition at line 690 of file 1D1DFunction.C.
References QUESO::Base1D1DFunction::m_maxDomainValue, QUESO::Base1D1DFunction::m_minDomainValue, UQ_FATAL_TEST_MACRO, QUESO::UQ_UNAVAILABLE_RANK, and value().
 {
   double value = 0.;
   if ((domainValue < m_minDomainValue) || (domainValue > m_maxDomainValue)) {
     std::cerr << "In ScalarTimes1D1DFunction::deriv()"
               << ": requested x ("            << domainValue
               << ") is out of the interval (" << m_minDomainValue
               << ", "                         << m_maxDomainValue
               << ")"
               << std::endl;
   }
   UQ_FATAL_TEST_MACRO(((domainValue < m_minDomainValue) || (domainValue > m_maxDomainValue)),
                       UQ_UNAVAILABLE_RANK,
                       "ScalarTimes1D1DFunction::deriv()",
                       "x out of range");
   UQ_FATAL_TEST_MACRO(true,
                       UQ_UNAVAILABLE_RANK,
                       "ScalarTimesFunc1D1DFunction::deriv()",
                       "not implemented yet");
   return value;
 }
double QUESO::ScalarTimesFunc1D1DFunction::value (double domainValue) const virtual
Returns the value of the (one-dimensional) function at point domainValue, already multiplied by the scalar (given during construction).
This function calls the value() method of the given function and multiplies its return value by the scalar passed to the constructor.
Implements QUESO::Base1D1DFunction.
Definition at line 680 of file 1D1DFunction.C.
References m_func, m_scalar, and QUESO::Base1D1DFunction::value().
Referenced by deriv().
 {
   double value = 0.;
   value += m_scalar*m_func.value(domainValue);
   return value;
 }
Member Data Documentation
const Base1D1DFunction& QUESO::ScalarTimesFunc1D1DFunction::m_func protected
Definition at line 449 of file 1D1DFunction.h.
Referenced by value().
double QUESO::ScalarTimesFunc1D1DFunction::m_scalar protected
Definition at line 448 of file 1D1DFunction.h.
Referenced by value().
The documentation for this class was generated from the following files:
src/misc/inc/1D1DFunction.h
src/misc/src/1D1DFunction.C