queso-0.51.0: QUESO::ScaledCovMatrixTKGroup< V, M > Class Template Reference
QUESO::ScaledCovMatrixTKGroup< V, M > Class Template Reference
This class allows the representation of a transition kernel with a scaled covariance matrix.
#include <ScaledCovMatrixTKGroup.h>
Public Member Functions
Constructor/Destructor methods
ScaledCovMatrixTKGroup (const char *prefix, const VectorSpace< V, M > &vectorSpace, const std::vector< double > &scales, const M &covMatrix)
Default constructor.
~ScaledCovMatrixTKGroup ()
Destructor.
Statistical/Mathematical methods
bool symmetric () const
Whether or not the matrix is symmetric. Always 'true'.
const GaussianVectorRV< V, M > & rv (unsigned int stageId) const
Gaussian increment property to construct a transition kernel.
const GaussianVectorRV< V, M > & rv (const std::vector< unsigned int > &stageIds)
Gaussian increment property to construct a transition kernel.
void updateLawCovMatrix (const M &covMatrix)
Scales the covariance matrix.
Misc methods
bool setPreComputingPosition (const V &position, unsigned int stageId)
Sets the pre-computing positions m_preComputingPositions[stageId] with a new vector of size position.
void clearPreComputingPositions ()
Clears the pre-computing positions m_preComputingPositions[stageId].
I/O methods
void print (std::ostream &os) const
TODO: Prints the transition kernel.
Public Member Functions inherited from QUESO::BaseTKGroup< V, M >
BaseTKGroup ()
Default constructor.
BaseTKGroup (const char *prefix, const VectorSpace< V, M > &vectorSpace, const std::vector< double > &scales)
Constructor.
virtual ~BaseTKGroup ()
Destructor.
const BaseEnvironment & env () const
QUESO's environment.
const V & preComputingPosition (unsigned int stageId) const
Pre-computing position; access to protected attribute *m_preComputingPositions[stageId].
Private Member Functions
void setRVsWithZeroMean ()
Sets the mean of the RVs to zero.
Private Attributes
M m_originalCovMatrix
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseTKGroup< V, M >
const EmptyEnvironment * m_emptyEnv
const BaseEnvironment & m_env
std::string m_prefix
const VectorSpace< V, M > * m_vectorSpace
std::vector< double > m_scales
std::vector< const V * > m_preComputingPositions
std::vector< BaseVectorRV< V,
M > * > m_rvs
Detailed Description
template<class V, class M>
class QUESO::ScaledCovMatrixTKGroup< V, M >
This class allows the representation of a transition kernel with a scaled covariance matrix.
Definition at line 41 of file ScaledCovMatrixTKGroup.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup (const char * prefix, const VectorSpace< V, M > & vectorSpace, const std::vector< double > & scales, const M & covMatrix)
Default constructor.
Definition at line 34 of file ScaledCovMatrixTKGroup.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseTKGroup< V, M >::m_env, QUESO::ScaledCovMatrixTKGroup< V, M >::m_originalCovMatrix, QUESO::BaseTKGroup< V, M >::m_preComputingPositions, QUESO::BaseTKGroup< V, M >::m_rvs, QUESO::BaseTKGroup< V, M >::m_scales, QUESO::ScaledCovMatrixTKGroup< V, M >::setRVsWithZeroMean(), and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseTKGroup<V,M>(prefix,vectorSpace,scales),
   m_originalCovMatrix    (covMatrix)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering ScaledCovMatrixTKGroup<V,M>::constructor()"
                            << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "In ScaledCovMatrixTKGroup<V,M>::constructor()"
                            << ": m_scales.size() = "                << m_scales.size()
                            << ", m_preComputingPositions.size() = " << m_preComputingPositions.size()
                            << ", m_rvs.size() = "                   << m_rvs.size()
                            << ", m_originalCovMatrix = "            << m_originalCovMatrix
                            << std::endl;
   }
   setRVsWithZeroMean();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving ScaledCovMatrixTKGroup<V,M>::constructor()"
                            << std::endl;
   }
 }
template<class V , class M > QUESO::ScaledCovMatrixTKGroup< V, M >::~ScaledCovMatrixTKGroup ()
Destructor.
Definition at line 66 of file ScaledCovMatrixTKGroup.C.
 {
 }
Member Function Documentation
template<class V , class M > void QUESO::ScaledCovMatrixTKGroup< V, M >::clearPreComputingPositions () virtual
Clears the pre-computing positions m_preComputingPositions[stageId].
Reimplemented from QUESO::BaseTKGroup< V, M >.
Definition at line 223 of file ScaledCovMatrixTKGroup.C.
References QUESO::BaseTKGroup< V, M >::clearPreComputingPositions().
 {
   BaseTKGroup<V,M>::clearPreComputingPositions();
   return;
 }
template<class V , class M > void QUESO::ScaledCovMatrixTKGroup< V, M >::print (std::ostream & os) const virtual
TODO: Prints the transition kernel.
Todo:
: implement me!
Reimplemented from QUESO::BaseTKGroup< V, M >.
Definition at line 262 of file ScaledCovMatrixTKGroup.C.
References QUESO::BaseTKGroup< V, M >::print().
 {
   BaseTKGroup<V,M>::print(os);
   return;
 }
template<class V , class M > const GaussianVectorRV< V, M > & QUESO::ScaledCovMatrixTKGroup< V, M >::rv (unsigned int stageId) const virtual
Gaussian increment property to construct a transition kernel.
Implements QUESO::BaseTKGroup< V, M >.
Definition at line 79 of file ScaledCovMatrixTKGroup.C.
References QUESO::GaussianVectorRV< V, M >::updateLawExpVector(), and UQ_FATAL_TEST_MACRO.
 {
   UQ_FATAL_TEST_MACRO(m_rvs.size() == 0,
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::rv1()",
                       "m_rvs.size() = 0");
   UQ_FATAL_TEST_MACRO(m_rvs[0] == NULL, // Yes, '0', because that is the id used below
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::rv1()",
                       "m_rvs[0] == NULL");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions.size() <= stageId,
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::rv1()",
                       "m_preComputingPositions.size() <= stageId");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions[stageId] == NULL,
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::rv1()",
                       "m_preComputingPositions[stageId] == NULL");
   if ((m_env.subDisplayFile()        ) &&
       (m_env.displayVerbosity() >= 10)) {
     *m_env.subDisplayFile() << "In ScaledCovMatrixTKGroup<V,M>::rv1()"
                             << ", stageId = " << stageId
                             << ": about to call m_rvs[0]->updateLawExpVector()"
                             << ", vector = " << *m_preComputingPositions[stageId] // FIX ME: might demand parallelism
                             << std::endl;
   }
   GaussianVectorRV<V, M> * gaussian_rv = dynamic_cast<GaussianVectorRV<V, M> * >(m_rvs[0]);
   gaussian_rv->updateLawExpVector(*m_preComputingPositions[stageId]);
   return (*gaussian_rv);
 }
template<class V , class M > const GaussianVectorRV< V, M > & QUESO::ScaledCovMatrixTKGroup< V, M >::rv (const std::vector< unsigned int > & stageIds) virtual
Gaussian increment property to construct a transition kernel.
Implements QUESO::BaseTKGroup< V, M >.
Definition at line 119 of file ScaledCovMatrixTKGroup.C.
References QUESO::GaussianVectorRV< V, M >::updateLawExpVector(), and UQ_FATAL_TEST_MACRO.
 {
   UQ_FATAL_TEST_MACRO(m_rvs.size() < stageIds.size(),
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::rv2()",
                       "m_rvs.size() < stageIds.size()");
   UQ_FATAL_TEST_MACRO(m_rvs[stageIds.size()-1] == NULL,
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::rv2()",
                       "m_rvs[stageIds.size()-1] == NULL");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions.size() <= stageIds[0],
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::rv2()",
                       "m_preComputingPositions.size() <= stageIds[0]");
   UQ_FATAL_TEST_MACRO(m_preComputingPositions[stageIds[0]] == NULL,
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::rv2()",
                       "m_preComputingPositions[stageIds[0]] == NULL");
   if ((m_env.subDisplayFile()        ) &&
       (m_env.displayVerbosity() >= 10)) {
     *m_env.subDisplayFile() << "In ScaledCovMatrixTKGroup<V,M>::rv2()"
                             << ", stageIds.size() = " << stageIds.size()
                             << ", stageIds[0] = "     << stageIds[0]
                             << ": about to call m_rvs[stageIds.size()-1]->updateLawExpVector()"
                             << ", vector = " << *m_preComputingPositions[stageIds[0]] // FIX ME: might demand parallelism
                             << std::endl;
   }
   GaussianVectorRV<V, M> * gaussian_rv = dynamic_cast<GaussianVectorRV<V, M> * >(m_rvs[stageIds.size()-1]);
   gaussian_rv->updateLawExpVector(*m_preComputingPositions[stageIds[0]]);
   return (*gaussian_rv);
 }
template<class V , class M > bool QUESO::ScaledCovMatrixTKGroup< V, M >::setPreComputingPosition (const V & position, unsigned int stageId) virtual
Sets the pre-computing positions m_preComputingPositions[stageId] with a new vector of size position.
Reimplemented from QUESO::BaseTKGroup< V, M >.
Definition at line 184 of file ScaledCovMatrixTKGroup.C.
References QUESO::GaussianJointPdf< V, M >::lawCovMatrix(), and QUESO::BaseTKGroup< V, M >::setPreComputingPosition().
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering ScaledCovMatrixTKGroup<V,M>::setPreComputingPosition()"
                            << ": position = " << position
                            << ", stageId = "  << stageId
                            << std::endl;
   }
   BaseTKGroup<V,M>::setPreComputingPosition(position,stageId);
   //setRVsWithZeroMean();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "In ScaledCovMatrixTKGroup<V,M>::setPreComputingPosition()"
                            << ", position = "        << position
                            << ", stageId = "         << stageId
                            << ": preComputingPos = " << *m_preComputingPositions[stageId];
     if (stageId < m_scales.size()) {
       *m_env.subDisplayFile() << ", factor = " << 1./m_scales[stageId]/m_scales[stageId];
     }
     if (stageId < m_rvs.size()) {
       const GaussianJointPdf<V,M>* pdfPtr = dynamic_cast< const GaussianJointPdf<V,M>* >(&(m_rvs[stageId]->pdf()));
       *m_env.subDisplayFile() << ", rvCov = " << pdfPtr->lawCovMatrix(); // FIX ME: might demand parallelism
     }
     *m_env.subDisplayFile() << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving ScaledCovMatrixTKGroup<V,M>::setPreComputingPosition()"
                            << ": position = " << position
                            << ", stageId = "  << stageId
                            << std::endl;
   }
   return true;
 }
template<class V , class M > void QUESO::ScaledCovMatrixTKGroup< V, M >::setRVsWithZeroMean () private
Sets the mean of the RVs to zero.
Definition at line 233 of file ScaledCovMatrixTKGroup.C.
References UQ_FATAL_TEST_MACRO.
Referenced by QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup().
 {
   UQ_FATAL_TEST_MACRO(m_rvs.size() == 0,
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::setRVsWithZeroMean()",
                       "m_rvs.size() = 0");
   UQ_FATAL_TEST_MACRO(m_rvs.size() != m_scales.size(),
                       m_env.worldRank(),
                       "ScaledCovMatrixTKGroup<V,M>::setRVsWithZeroMean()",
                       "m_rvs.size() != m_scales.size()");
   for (unsigned int i = 0; i < m_scales.size(); ++i) {
     double factor = 1./m_scales[i]/m_scales[i];
     UQ_FATAL_TEST_MACRO(m_rvs[i] != NULL,
                         m_env.worldRank(),
                         "ScaledCovMatrixTKGroup<V,M>::setRVsWithZeroMean()",
                         "m_rvs[i] != NULL");
     m_rvs[i] = new GaussianVectorRV<V,M>(m_prefix.c_str(),
                                                 *m_vectorSpace,
                                                 m_vectorSpace->zeroVector(),
                                                 factor*m_originalCovMatrix);
   }
   return;
 }
template<class V , class M > bool QUESO::ScaledCovMatrixTKGroup< V, M >::symmetric () const virtual
Whether or not the matrix is symmetric. Always 'true'.
Todo:
: It only returns 'true', thus a test for its symmetricity must be included.
Implements QUESO::BaseTKGroup< V, M >.
Definition at line 72 of file ScaledCovMatrixTKGroup.C.
 {
   return true;
 }
template<class V , class M > void QUESO::ScaledCovMatrixTKGroup< V, M >::updateLawCovMatrix (const M & covMatrix)
Scales the covariance matrix.
The covariance matrix is scaled by a factor of .
Definition at line 160 of file ScaledCovMatrixTKGroup.C.
 {
   for (unsigned int i = 0; i < m_scales.size(); ++i) {
     double factor = 1./m_scales[i]/m_scales[i];
     if ((m_env.subDisplayFile()        ) &&
         (m_env.displayVerbosity() >= 10)) {
       *m_env.subDisplayFile() << "In ScaledCovMatrixTKGroup<V,M>::updateLawCovMatrix()"
                               << ", m_scales.size() = " << m_scales.size()
                               << ", i = "               << i
                               << ", m_scales[i] = "     << m_scales[i]
                               << ", factor = "          << factor
                               << ": about to call m_rvs[i]->updateLawCovMatrix()"
                               << ", covMatrix = \n" << factor*covMatrix // FIX ME: might demand parallelism
                               << std::endl;
     }
     dynamic_cast<GaussianVectorRV<V, M> * >(m_rvs[i])->updateLawCovMatrix(factor*covMatrix);
   }
   return;
 }
Member Data Documentation
template<class V , class M > M QUESO::ScaledCovMatrixTKGroup< V, M >::m_originalCovMatrix private
Definition at line 96 of file ScaledCovMatrixTKGroup.h.
Referenced by QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup().
The documentation for this class was generated from the following files:
src/stats/inc/ScaledCovMatrixTKGroup.h
src/stats/src/ScaledCovMatrixTKGroup.C