queso-0.50.0: QUESO::StdScalarCdf< T > Class Template Reference
QUESO::StdScalarCdf< T > Class Template Reference
A class for handling standard CDFs.
#include <StdScalarCdf.h>
Public Member Functions
Constructor/Destructor methods
StdScalarCdf (const BaseEnvironment &env, const char *prefix, const std::vector< T > &cdfGrid, const std::vector< double > &cdfValues)
Default constructor.
~StdScalarCdf ()
Destructor.
Mathematical methods
double value (T paramValue) const
Returns the value of the CDF at paramValue.
T inverse (double cdfValue) const
Returns the position of a given value of CDF.
void getSupport (T &minHorizontal, T &maxHorizontal) const
Returns the support (image) of the CDF between two horizontal values (domain).
I/O methods
void print (std::ostream &os) const
Prints the CDF (values of the grid points and of the CDF at such grid points).
void subWriteContents (const std::string &varNamePrefix, const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds) const
Writes the CDF of an allowed sub-environment to a file.
Public Member Functions inherited from QUESO::BaseScalarCdf< T >
BaseScalarCdf (const BaseEnvironment &env, const char *prefix)
Default constructor.
virtual ~BaseScalarCdf ()
Virtual destructor.
const BaseEnvironment & env () const
Environment. Access to private attribute m_env.
const std::string & prefix () const
Access to private attribute m_prefix.
Protected Attributes
const StdOneDGrid< T > m_cdfGrid
const std::vector< double > m_cdfValues
SampledScalarCdf< T > * m_sampledCdfGrid
Protected Attributes inherited from QUESO::BaseScalarCdf< T >
const BaseEnvironment & m_env
std::string m_prefix
T m_minHorizontal
T m_maxHorizontal
Detailed Description
template<class T>
class QUESO::StdScalarCdf< T >
A class for handling standard CDFs.
This class implements a standard cumulative distribution function (CDF). Its protected attribute m_sampledCdfGrid is an object of the class SampledScalarCdf<T>, so all members of this class are implemented using the members of SampledScalarCdf<T>.
Definition at line 48 of file StdScalarCdf.h.
Constructor & Destructor Documentation
template<class T > QUESO::StdScalarCdf< T >::StdScalarCdf (const BaseEnvironment & env, const char * prefix, const std::vector< T > & cdfGrid, const std::vector< double > & cdfValues)
Default constructor.
Instantiates an object of the class given a prefix, the environment, the grid points where it will be evaluated and its resulting values.
Definition at line 31 of file StdScalarCdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarCdf< T >::env(), QUESO::StdScalarCdf< T >::m_cdfGrid, QUESO::StdScalarCdf< T >::m_cdfValues, QUESO::BaseScalarCdf< T >::m_env, QUESO::BaseScalarCdf< T >::m_prefix, QUESO::StdScalarCdf< T >::m_sampledCdfGrid, QUESO::BaseScalarCdf< T >::prefix(), and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseScalarCdf<T>(env,((std::string)(prefix)+"").c_str()),
   m_cdfGrid              (env,prefix,cdfGrid),
   m_cdfValues            (cdfValues),
   m_sampledCdfGrid       (NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering StdScalarCdf<T>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   m_sampledCdfGrid = new SampledScalarCdf<T>(env,prefix,m_cdfGrid,m_cdfValues);
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving StdScalarCdf<T>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class T > QUESO::StdScalarCdf< T >::~StdScalarCdf ()
Destructor.
Definition at line 58 of file StdScalarCdf.C.
 {
   delete m_sampledCdfGrid;
 }
Member Function Documentation
template<class T > void QUESO::StdScalarCdf< T >::getSupport (T & minHorizontal, T & maxHorizontal) const virtual
Returns the support (image) of the CDF between two horizontal values (domain).
Implements QUESO::BaseScalarCdf< T >.
Definition at line 79 of file StdScalarCdf.C.
 {
   return m_sampledCdfGrid->getSupport(minHorizontal,maxHorizontal);
 }
template<class T > T QUESO::StdScalarCdf< T >::inverse (double cdfValue) const virtual
Returns the position of a given value of CDF.
Implements QUESO::BaseScalarCdf< T >.
Definition at line 72 of file StdScalarCdf.C.
 {
   return m_sampledCdfGrid->inverse(cdfValue);
 }
template<class T > void QUESO::StdScalarCdf< T >::print (std::ostream & os) const virtual
Prints the CDF (values of the grid points and of the CDF at such grid points).
Implements QUESO::BaseScalarCdf< T >.
Definition at line 86 of file StdScalarCdf.C.
 {
   m_sampledCdfGrid->print(os);
   return;
 }
template<class T > void QUESO::StdScalarCdf< T >::subWriteContents (const std::string & varNamePrefix, const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds) const virtual
Writes the CDF of an allowed sub-environment to a file.
It will write the data in Octave/Matlab compatible format.
Reimplemented from QUESO::BaseScalarCdf< T >.
Definition at line 94 of file StdScalarCdf.C.
 {
   m_sampledCdfGrid->subWriteContents(varNamePrefix,fileName,fileType,allowedSubEnvIds);
   return;
 }
template<class T > double QUESO::StdScalarCdf< T >::value (T paramValue) const virtual
Returns the value of the CDF at paramValue.
Implements QUESO::BaseScalarCdf< T >.
Definition at line 65 of file StdScalarCdf.C.
 {
   return m_sampledCdfGrid->value(paramValue);
 }
Member Data Documentation
template<class T > const StdOneDGrid<T> QUESO::StdScalarCdf< T >::m_cdfGrid protected
Definition at line 93 of file StdScalarCdf.h.
Referenced by QUESO::StdScalarCdf< T >::StdScalarCdf().
template<class T > const std::vector<double> QUESO::StdScalarCdf< T >::m_cdfValues protected
Definition at line 94 of file StdScalarCdf.h.
Referenced by QUESO::StdScalarCdf< T >::StdScalarCdf().
template<class T > SampledScalarCdf<T>* QUESO::StdScalarCdf< T >::m_sampledCdfGrid protected
Definition at line 95 of file StdScalarCdf.h.
Referenced by QUESO::StdScalarCdf< T >::StdScalarCdf().
The documentation for this class was generated from the following files:
src/stats/inc/StdScalarCdf.h
src/stats/src/StdScalarCdf.C