queso-0.56.0: QUESO::BaseJointPdf< V, M > Class Template Reference
QUESO::BaseJointPdf< V, M > Class Template Reference abstract
A templated (base) class for handling joint PDFs.
#include <JointPdf.h>
Public Member Functions
Constructor/Destructor methods
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
Mathematical methods
virtual double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const =0
Actual value of the PDF (scalar function).
virtual double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const =0
Logarithm of the value of the function.
virtual void distributionMean (V &meanVector) const
virtual void distributionVariance (M &covMatrix) const
virtual void setNormalizationStyle (unsigned int value) const
Sets a value to be used in the normalization style (stored in the protected attribute m_normalizationStyle.)
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
virtual double computeLogOfNormalizationFactor (unsigned int numSamples, bool m_logOfNormalizationFactor) const =0
Computes the logarithm of the normalization factor. See template specialization.
virtual void print (std::ostream &os) const
Print method. Non-pure for backwards compatibility.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
Protected Member Functions
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Protected Attributes
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::BaseJointPdf< V, M >
A templated (base) class for handling joint PDFs.
This class allows the mathematical definition of a Joint PDF, which is a scalar function such as * ; ie a function of one or more variables that has always one-dimensional range. QUESO currently supports basic PDFs such as uniform and Gaussian and also more complex PDFs, such as the ones coming from a Bayesian analysis. They are implemented in the derived classes UniformJointPdf, GaussianJointPdf, and BayesianJointPdf, respectively. The posterior PDF may be represented within QUESO by GenericJointPdf.
Definition at line 55 of file JointPdf.h.
Constructor & Destructor Documentation
template<class V, class M> QUESO::BaseJointPdf< V, M >::BaseJointPdf (const char * prefix, const VectorSet< V, M > & domainSet)
Default constructor.
Instantiates an object of the class, i.e. a scalar function, given a prefix and its domain.
Definition at line 33 of file JointPdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarFunction< V, M >::m_env, QUESO::BaseScalarFunction< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseScalarFunction<V,M>(((std::string)(prefix)+"pd_").c_str(), domainSet),
   m_normalizationStyle(0),
   m_logOfNormalizationFactor(0.)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering BaseJointPdf<V,M>::constructor() [3]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving BaseJointPdf<V,M>::constructor() [3]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::BaseJointPdf< V, M >::~BaseJointPdf () virtual
Destructor.
Definition at line 55 of file JointPdf.C.
 {
 }
Member Function Documentation
template<class V = GslVector, class M = GslMatrix> virtual double QUESO::BaseJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const pure virtual
Actual value of the PDF (scalar function).
Implements QUESO::BaseScalarFunction< V, M >.
Implemented in QUESO::InvLogitGaussianJointPdf< V, M >, QUESO::GammaJointPdf< V, M >, QUESO::ConcatenatedJointPdf< V, M >, QUESO::GaussianJointPdf< V, M >, QUESO::LogNormalJointPdf< V, M >, QUESO::BayesianJointPdf< V, M >, QUESO::PoweredJointPdf< V, M >, QUESO::InverseGammaJointPdf< V, M >, QUESO::GenericJointPdf< V, M >, QUESO::JeffreysJointPdf< V, M >, QUESO::BetaJointPdf< V, M >, QUESO::WignerJointPdf< V, M >, and QUESO::UniformJointPdf< V, M >.
template<class V , class M > double QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const protected
Common method (to the derived classes) to compute the logarithm of the normalization factor.
The normalization factor is calculated by finding the max and min values of the domain set and then drawing numSamples samples from a uniform distribution varying from min to max. Such samples are averaged and the logarithmic value is assigned to protected attribute m_logOfNormalizationFactor if the parameter m_logOfNormalizationFactor is true.
Definition at line 115 of file JointPdf.C.
References QUESO::BoxSubset< V, M >::maxValues(), QUESO::BoxSubset< V, M >::minValues(), and QUESO::queso_isnan().
Referenced by QUESO::GenericJointPdf< V, M >::computeLogOfNormalizationFactor(), QUESO::UniformJointPdf< V, M >::computeLogOfNormalizationFactor(), QUESO::WignerJointPdf< V, M >::computeLogOfNormalizationFactor(), QUESO::BetaJointPdf< V, M >::computeLogOfNormalizationFactor(), QUESO::InverseGammaJointPdf< V, M >::computeLogOfNormalizationFactor(), QUESO::LogNormalJointPdf< V, M >::computeLogOfNormalizationFactor(), QUESO::JeffreysJointPdf< V, M >::computeLogOfNormalizationFactor(), QUESO::GaussianJointPdf< V, M >::computeLogOfNormalizationFactor(), QUESO::GammaJointPdf< V, M >::computeLogOfNormalizationFactor(), and QUESO::InvLogitGaussianJointPdf< V, M >::computeLogOfNormalizationFactor().
 {
   double value = 0.;
   double volume = m_domainSet.volume();
   if ((queso_isnan(volume)) ||
       (volume == -INFINITY         ) ||
       (volume ==  INFINITY         ) ||
       (volume <= 0.                )) {
     // Do nothing
   }
   else {
     const BoxSubset<V,M>* boxSubset = dynamic_cast<const BoxSubset<V,M>* >(&m_domainSet);
     if (boxSubset == NULL) {
       // Do nothing
     }
     else {
       V tmpVec(m_domainSet.vectorSpace().zeroVector());
       double sum = 0.;
       for (unsigned int i = 0; i < numSamples; ++i) {
         tmpVec.cwSetUniform(boxSubset->minValues(),boxSubset->maxValues());
         sum += this->actualValue(tmpVec,NULL,NULL,NULL,NULL);
       }
       double avgValue = sum/((double) numSamples);
       value = -( log(avgValue) + log(volume) );
       if (updateFactorInternally) {
         m_logOfNormalizationFactor = value;
       }
     }
   }
   return value;
 }
template<class V = GslVector, class M = GslMatrix> virtual double QUESO::BaseJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool m_logOfNormalizationFactor) const pure virtual
Computes the logarithm of the normalization factor. See template specialization.
Implemented in QUESO::InvLogitGaussianJointPdf< V, M >, QUESO::GammaJointPdf< V, M >, QUESO::ConcatenatedJointPdf< V, M >, QUESO::GaussianJointPdf< V, M >, QUESO::BayesianJointPdf< V, M >, QUESO::JeffreysJointPdf< V, M >, QUESO::LogNormalJointPdf< V, M >, QUESO::BayesianJointPdf< QUESO::GslVector, QUESO::GslMatrix >, QUESO::BayesianJointPdf< P_V, P_M >, QUESO::BetaJointPdf< V, M >, QUESO::InverseGammaJointPdf< V, M >, QUESO::PoweredJointPdf< V, M >, QUESO::WignerJointPdf< V, M >, QUESO::UniformJointPdf< V, M >, and QUESO::GenericJointPdf< V, M >.
template<class V, class M > void QUESO::BaseJointPdf< V, M >::distributionMean (V & meanVector) const virtual
Mean value of the underlying random variable. Not implemented in base class, but not pure virtual for backwards compatibility reasons.
Reimplemented in QUESO::InvLogitGaussianJointPdf< V, M >, QUESO::GammaJointPdf< V, M >, QUESO::GaussianJointPdf< V, M >, QUESO::ConcatenatedJointPdf< V, M >, QUESO::BayesianJointPdf< V, M >, QUESO::LogNormalJointPdf< V, M >, QUESO::JeffreysJointPdf< V, M >, QUESO::BetaJointPdf< V, M >, QUESO::InverseGammaJointPdf< V, M >, QUESO::WignerJointPdf< V, M >, and QUESO::UniformJointPdf< V, M >.
Definition at line 62 of file JointPdf.C.
References queso_not_implemented.
 {
   queso_not_implemented();
 }
template<class V , class M> void QUESO::BaseJointPdf< V, M >::distributionVariance (M & covMatrix) const virtual
Covariance matrix of the underlying random variable. Not implemented in base class, but not pure virtual for backwards compatibility reasons.
Reimplemented in QUESO::InvLogitGaussianJointPdf< V, M >, QUESO::GammaJointPdf< V, M >, QUESO::GaussianJointPdf< V, M >, QUESO::ConcatenatedJointPdf< V, M >, QUESO::BayesianJointPdf< V, M >, QUESO::LogNormalJointPdf< V, M >, QUESO::JeffreysJointPdf< V, M >, QUESO::BetaJointPdf< V, M >, QUESO::InverseGammaJointPdf< V, M >, QUESO::WignerJointPdf< V, M >, and QUESO::UniformJointPdf< V, M >.
Definition at line 70 of file JointPdf.C.
References queso_not_implemented.
 {
   queso_not_implemented();
 }
template<class V = GslVector, class M = GslMatrix> virtual double QUESO::BaseJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const pure virtual
Logarithm of the value of the function.
Implements QUESO::BaseScalarFunction< V, M >.
Implemented in QUESO::InvLogitGaussianJointPdf< V, M >, QUESO::GammaJointPdf< V, M >, QUESO::GaussianJointPdf< V, M >, QUESO::ConcatenatedJointPdf< V, M >, QUESO::BayesianJointPdf< V, M >, QUESO::LogNormalJointPdf< V, M >, QUESO::PoweredJointPdf< V, M >, QUESO::JeffreysJointPdf< V, M >, QUESO::BetaJointPdf< V, M >, QUESO::InverseGammaJointPdf< V, M >, QUESO::WignerJointPdf< V, M >, QUESO::GenericJointPdf< V, M >, and QUESO::UniformJointPdf< V, M >.
template<class V , class M > void QUESO::BaseJointPdf< V, M >::print (std::ostream & os) const virtual
Print method. Non-pure for backwards compatibility.
Reimplemented in QUESO::InvLogitGaussianJointPdf< V, M >, and QUESO::GaussianJointPdf< V, M >.
Definition at line 94 of file JointPdf.C.
 {
   // Print m_env?
   // Print mean?
   // Print var?
   os << "Start printing BaseJointPdf<V, M>" << std::endl;
   os << "m_prefix:" << std::endl;
   os << this->m_prefix << std::endl;
   os << "m_domainSet:" << std::endl;
   os << this->m_domainSet << std::endl;
   os << "m_normalizationStyle:" << std::endl;
   os << this->m_normalizationStyle << std::endl;
   os << "m_logOfNormalizationFactor:" << std::endl;
   os << this->m_logOfNormalizationFactor << std::endl;
   os << "End printing BaseJointPdf<V, M>" << std::endl;
 }
template<class V , class M > void QUESO::BaseJointPdf< V, M >::setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
Definition at line 86 of file JointPdf.C.
 {
   m_logOfNormalizationFactor = value;
   return;
 }
template<class V , class M > void QUESO::BaseJointPdf< V, M >::setNormalizationStyle (unsigned int value) const virtual
Sets a value to be used in the normalization style (stored in the protected attribute m_normalizationStyle.)
Reimplemented in QUESO::ConcatenatedJointPdf< V, M >, QUESO::BayesianJointPdf< V, M >, QUESO::BayesianJointPdf< QUESO::GslVector, QUESO::GslMatrix >, QUESO::BayesianJointPdf< P_V, P_M >, and QUESO::PoweredJointPdf< V, M >.
Definition at line 78 of file JointPdf.C.
 {
   m_normalizationStyle = value;
   return;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> double QUESO::BaseJointPdf< V, M >::m_logOfNormalizationFactor mutable protected
Definition at line 114 of file JointPdf.h.
template<class V = GslVector, class M = GslMatrix> unsigned int QUESO::BaseJointPdf< V, M >::m_normalizationStyle mutable protected
Definition at line 113 of file JointPdf.h.
The documentation for this class was generated from the following files:
src/stats/inc/JointPdf.h
src/stats/src/JointPdf.C