queso-0.56.0: QUESO::GammaVectorRealizer< V, M > Class Template Reference
QUESO::GammaVectorRealizer< V, M > Class Template Reference
A class for handling sampling from a Gamma probability density distribution.
#include <GammaVectorRealizer.h>
Public Member Functions
Constructor/Destructor methods
GammaVectorRealizer (const char *prefix, const VectorSet< V, M > &unifiedImageSet, const V &a, const V &b)
Constructor.
~GammaVectorRealizer ()
Destructor.
Public Member Functions inherited from QUESO::BaseVectorRealizer< V, M >
BaseVectorRealizer (const char *prefix, const VectorSet< V, M > &unifiedImageSet, unsigned int subPeriod)
Default constructor.
virtual ~BaseVectorRealizer ()
Virtual destructor.
const VectorSet< V, M > & unifiedImageSet () const
Image set where the realizations lie. Access to protected attribute m_unifiedImageSet.
unsigned int subPeriod () const
Sub-period of the realization. Access to protected attribute m_subPeriod.
Realization-related methods
V m_a
V m_b
void realization (V &nextValues) const
Draws a realization.
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseVectorRealizer< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_unifiedImageSet
unsigned int m_subPeriod
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::GammaVectorRealizer< V, M >
A class for handling sampling from a Gamma probability density distribution.
This class handles sampling from a Gamma probability density distribution, with shape and scale parameters a and b. See GammaJointPdf for more details on the parameterisation of the distribution function.
Definition at line 47 of file GammaVectorRealizer.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::GammaVectorRealizer< V, M >::GammaVectorRealizer (const char * prefix, const VectorSet< V, M > & unifiedImageSet, const V & a, const V & b)
Constructor.
Constructs a new object, given a prefix, the image set of the vector realizer, and the Gamma distribution parameters a and b, which are assigned to private attributes m_alpha and m_beta.
Definition at line 35 of file GammaVectorRealizer.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRealizer< V, M >::m_env, QUESO::BaseVectorRealizer< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRealizer<V,M>(((std::string)(prefix)+"gen").c_str(),unifiedImageSet,std::numeric_limits<unsigned int>::max()),
   m_a(a),
   m_b(b)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering GammaVectorRealizer<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving GammaVectorRealizer<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::GammaVectorRealizer< V, M >::~GammaVectorRealizer ()
Destructor.
Definition at line 59 of file GammaVectorRealizer.C.
 {
 }
Member Function Documentation
template<class V , class M > void QUESO::GammaVectorRealizer< V, M >::realization (V & nextValues) const virtual
Draws a realization.
This function draws a realization of a Gamma distribution and saves it in nextValues. It internally checks whether the image set, where the realization should be drawn, belongs to the interval (0, infinity) - which is the range where Gamma distribution is defined over.
Implements QUESO::BaseVectorRealizer< V, M >.
Definition at line 65 of file GammaVectorRealizer.C.
References QUESO::BoxSubset< V, M >::maxValues(), QUESO::BoxSubset< V, M >::minValues(), and queso_require_greater_equal_msg.
 {
   // nextValues.cwSetGamma(m_a,m_b);
 // begin kemelli 2013-April-22 :
   const BoxSubset<V,M>* imageBox = dynamic_cast<const BoxSubset<V,M>* >(&this->m_unifiedImageSet);
 //  double biggerOfMaxValues = imageBox->maxValues().getMaxValue();
   double smallerOfMaxValues = imageBox->maxValues().getMinValue();
   double smallerOfMinValues = imageBox->minValues().getMinValue();
  // Gamma dist belongs to (0,inf)
  if( smallerOfMinValues < 0 ) //(biggerOfMinValues < 0) ||
  {
    std::cerr << "In GammaVectorRealizer<V,M>::realization()\n"
        << "Gamma distribution is only defined in (0, infinity).\n"
        << "The data provided is: \n"
        << *imageBox
          << "Sampling will not cover all interval.\n"
          << std::endl;
     queso_require_greater_equal_msg(smallerOfMaxValues, 0, "invalid input: Gamma distribution is only defined in (0, infinity), and min(m_maxValues)<0. ");
  //                     m_env.worldRank(),
  //                     "GammaVectorRealizer<V,M>::realization()",
  //                     "invalid input: Gamma distribution is only defined in (0, infinity). ");
  }
   // end kemelli 2013-April-22
   // begin kemelli 2013-April-18 :
   bool outOfSupport = true;
   do {
   nextValues.cwSetGamma(m_a,m_b);
   outOfSupport = !(this->m_unifiedImageSet.contains(nextValues));
   } while (outOfSupport);
   // end kemelli 2013-April-18 :
   return;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> V QUESO::GammaVectorRealizer< V, M >::m_a private
Definition at line 79 of file GammaVectorRealizer.h.
template<class V = GslVector, class M = GslMatrix> V QUESO::GammaVectorRealizer< V, M >::m_b private
Definition at line 80 of file GammaVectorRealizer.h.
The documentation for this class was generated from the following files:
src/stats/inc/GammaVectorRealizer.h
src/stats/src/GammaVectorRealizer.C