queso-0.56.0: QUESO::Algorithm< V, M > Class Template Reference
QUESO::Algorithm< V, M > Class Template Reference
#include <Algorithm.h>
Public Member Functions
Algorithm (const BaseEnvironment &env, const BaseTKGroup< V, M > &tk)
~Algorithm ()
double acceptance_ratio (MarkovChainPositionData< V > x, MarkovChainPositionData< V > y, const V &tk_pos_x, const V &tk_pos_y)
Calculates the finite dimensional Metropolis-Hastings acceptance ratio.
Private Attributes
const BaseEnvironment & m_env
const BaseTKGroup< V, M > & m_tk
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::Algorithm< V, M >
Definition at line 35 of file Algorithm.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::Algorithm< V, M >::Algorithm (const BaseEnvironment & env, const BaseTKGroup< V, M > & tk)
Definition at line 36 of file Algorithm.C.
   :
     m_env(env),
     m_tk(tk)
 {
 }
template<class V , class M > QUESO::Algorithm< V, M >::~Algorithm ()
Definition at line 45 of file Algorithm.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::Algorithm< V, M >::acceptance_ratio (MarkovChainPositionData< V > x, MarkovChainPositionData< V > y, const V & tk_pos_x, const V & tk_pos_y)
Calculates the finite dimensional Metropolis-Hastings acceptance ratio.
tk_pos_x is the position of the tk when evaluating for x tk_pos_y is the position of the tk when evaluating for y
This method is called by the delayed rejection procedure.
Definition at line 51 of file Algorithm.C.
References QUESO::MarkovChainPositionData< V >::logTarget(), QUESO::MarkovChainPositionData< V >::outOfTargetSupport(), QUESO::queso_isnan(), and QUESO::MarkovChainPositionData< V >::vecValues().
 {
   double alphaQuotient = 0.;
   if ((x.outOfTargetSupport() == false) &&
       (y.outOfTargetSupport() == false)) {
     if ((x.logTarget() == -INFINITY) ||
         (x.logTarget() ==  INFINITY) ||
         ( queso_isnan(x.logTarget())      )) {
       std::cerr << "WARNING In Algorithm<V,M>::alpha(x,y)"
                 << ", worldRank "       << m_env.worldRank()
                 << ", fullRank "        << m_env.fullRank()
                 << ", subEnvironment "  << m_env.subId()
                 << ", subRank "         << m_env.subRank()
                 << ", inter0Rank "      << m_env.inter0Rank()
                 << ": x.logTarget() = " << x.logTarget()
                 << ", x.values() = "    << x.vecValues()
                 << ", y.values() = "    << y.vecValues()
                 << std::endl;
     }
     else if ((y.logTarget() == -INFINITY           ) ||
              (y.logTarget() ==  INFINITY           ) ||
              ( queso_isnan(y.logTarget()) )) {
       std::cerr << "WARNING In Algorithm<V,M>::alpha(x,y)"
                 << ", worldRank "       << m_env.worldRank()
                 << ", fullRank "        << m_env.fullRank()
                 << ", subEnvironment "  << m_env.subId()
                 << ", subRank "         << m_env.subRank()
                 << ", inter0Rank "      << m_env.inter0Rank()
                 << ": y.logTarget() = " << y.logTarget()
                 << ", x.values() = "    << x.vecValues()
                 << ", y.values() = "    << y.vecValues()
                 << std::endl;
     }
     else {
       double yLogTargetToUse = y.logTarget();
       if (m_tk.symmetric()) {
         alphaQuotient = std::exp(yLogTargetToUse - x.logTarget());
         if ((m_env.subDisplayFile()                   ) &&
             (m_env.displayVerbosity() >= 3            )) {
           *m_env.subDisplayFile() << "In Algorithm<V,M>::alpha(x,y)"
                                  << ": symmetric proposal case"
                                  << ", x = "               << x.vecValues()
                                  << ", y = "               << y.vecValues()
                                  << ", yLogTargetToUse = " << yLogTargetToUse
                                  << ", x.logTarget() = "   << x.logTarget()
                                  << ", alpha = "           << alphaQuotient
                                  << std::endl;
         }
       }
       else {
         double qyx = m_tk.rv(tk_pos_x).pdf().lnValue(x.vecValues(),NULL,NULL,NULL,NULL);
         if ((m_env.subDisplayFile()                   ) &&
             (m_env.displayVerbosity() >= 10           )) {
           *m_env.subDisplayFile() << m_tk.rv(tk_pos_x).pdf() << std::endl;
         }
         double qxy = m_tk.rv(tk_pos_y).pdf().lnValue(y.vecValues(),NULL,NULL,NULL,NULL);
         if ((m_env.subDisplayFile()                   ) &&
             (m_env.displayVerbosity() >= 10           )) {
           *m_env.subDisplayFile() << m_tk.rv(tk_pos_y).pdf() << std::endl;
         }
         alphaQuotient = std::exp(yLogTargetToUse +
                                  qyx -
                                  x.logTarget() -
                                  qxy);
         if ((m_env.subDisplayFile()                   ) &&
             (m_env.displayVerbosity() >= 3            )) {
           *m_env.subDisplayFile() << "In Algorithm<V,M>::alpha(x,y)"
                                  << ": asymmetric proposal case"
                                  << ", x = "               << x.vecValues()
                                  << ", y = "               << y.vecValues()
                                  << ", yLogTargetToUse = " << yLogTargetToUse
                                  << ", q(y,x) = "          << qyx
                                  << ", x.logTarget() = "   << x.logTarget()
                                  << ", q(x,y) = "          << qxy
                                  << ", alpha = "           << alphaQuotient
                                  << std::endl;
         }
       }
     } // protection logic against logTarget values
   }
   else {
     if ((m_env.subDisplayFile()                   ) &&
         (m_env.displayVerbosity() >= 10           )) {
       *m_env.subDisplayFile() << "In Algorithm<V,M>::alpha(x,y)"
                              << ": x.outOfTargetSupport = " << x.outOfTargetSupport()
                              << ", y.outOfTargetSupport = " << y.outOfTargetSupport()
                              << std::endl;
     }
   }
   return std::min(1.,alphaQuotient);
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> const BaseEnvironment& QUESO::Algorithm< V, M >::m_env private
Definition at line 53 of file Algorithm.h.
template<class V = GslVector, class M = GslMatrix> const BaseTKGroup<V, M>& QUESO::Algorithm< V, M >::m_tk private
Definition at line 54 of file Algorithm.h.
The documentation for this class was generated from the following files:
src/stats/inc/Algorithm.h
src/stats/src/Algorithm.C