queso-0.56.0: QUESO::BaseEnvironment Class Reference
QUESO::BaseEnvironment Class Reference abstract
This (virtual) class sets up the environment underlying the use of the QUESO library by an executable.
#include <Environment.h>
Public Member Functions
Constructor/Destructor methods
BaseEnvironment (const char *passedOptionsInputFileName, EnvOptionsValues *alternativeOptionsValues)
Default constructor.
BaseEnvironment (const std::string &passedOptionsInputFileName, EnvOptionsValues *alternativeOptionsValues)
virtual ~BaseEnvironment ()
Destructor.
Environment, Communicator and Options Input File methods
bool fullEnvIsReady () const
Returns whether the full environment class is ready (constructor has successfully been called).
int worldRank () const
Returns the process world rank.
int fullRank () const
Returns the process full rank.
const MpiComm & fullComm () const
Access function for MpiComm full communicator.
RawType_MPI_Group subGroup () const
Access function for sub-group.
int subRank () const
Access function for sub-rank.
const MpiComm & subComm () const
Access function for MpiComm sub communicator.
const MpiComm & selfComm () const
Access function for MpiComm self-communicator.
int inter0Rank () const
Returns the process inter0 rank.
const MpiComm & inter0Comm () const
Access function for MpiComm inter0-communicator.
std::ofstream * subDisplayFile () const
Access function for m_subDisplayFile (displays file on stream).
std::string subDisplayFileName () const
Access function for m_subDisplayFileName (displays filename on stream).
unsigned int numSubEnvironments () const
Access function to the number of sub-environments.
unsigned int subId () const
Access function to the number of each sub-environment Id: m_subId.
const std::string & subIdString () const
Access to the attribute m_subIdString; which stores the string for the sub-environment, and it will be used, for instance, to create the output files for each sub-environment.
void checkTheParallelEnvironment () const
std::string optionsInputFileName () const
Access to the attribute m_optionsInputFileName, which stores the name of the input file passed by the user to QUESO.
void setOptionsInputFileAccessState (bool newState) const
boost::program_options::variables_map & allOptionsMap () const
void scanInputFileForMyOptions (const boost::program_options::options_description &optionsDesc) const
This method scans the input file provided by the user to QUESO.
unsigned int displayVerbosity () const
unsigned int syncVerbosity () const
Access function to private attribute m_syncVerbosity.
unsigned int checkingLevel () const
Access function to private attribute m_checkingLevel.
const RngBase * rngObject () const
Access to the RNG object.
void resetSeed (int newSeedOption)
Reset RNG seed.
int seed () const
Access to the RNG seed.
const BasicPdfsBase * basicPdfs () const
Access to Basic PDFs.
std::string platformName () const
Access to the platform name.
std::string identifyingString () const
Access function to private attribute m_identifyingString: identifying string.
void resetIdentifyingString (const std::string &newString)
Reset private attribute m_identifyingString with the value newString.
bool isThereInputFile () const
//TODO Not implemented? it is called in examples/validationCycle/tests_old/results_5_25/uqTgaEx4.h.
struct timeval timevalBegin () const
Used to save the time when the combo `QUESO+user's application' started to run.
I/O methods
bool openOutputFile (const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds, bool writeOver, FilePtrSetStruct &filePtrSet) const
Opens an output file for each sub-environment that was chosen to send data to the file.
bool openUnifiedOutputFile (const std::string &fileName, const std::string &fileType, bool writeOver, FilePtrSetStruct &filePtrSet) const
Opens a unified output file, that will contain data from all sub-environments.
bool openInputFile (const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds, FilePtrSetStruct &filePtrSet) const
Opens an input file.
bool openUnifiedInputFile (const std::string &fileName, const std::string &fileType, FilePtrSetStruct &filePtrSet) const
Opens the unified input file.
void closeFile (FilePtrSetStruct &filePtrSet, const std::string &fileType) const
Closes the file.
void setExceptionalCircumstance (bool value) const
Set an exceptional circumstance.
bool exceptionalCircumstance () const
Decides whether there is an exceptional circumstance.
const GetPot & input () const
The GetPot input file parser.
virtual void print (std::ostream &os) const =0
Protected Attributes
bool m_fullEnvIsReady
int m_worldRank
MpiComm * m_fullComm
int m_fullRank
int m_fullCommSize
RawType_MPI_Group m_fullGroup
std::string m_optionsInputFileName
bool m_optionsInputFileAccessState
boost::program_options::options_description * m_allOptionsDesc
boost::program_options::variables_map * m_allOptionsMap
ScopedPtr< GetPot >::Type m_input
unsigned int m_subId
std::string m_subIdString
RawType_MPI_Group m_subGroup
MpiComm * m_subComm
int m_subRank
int m_subCommSize
MpiComm * m_selfComm
RawType_MPI_Group m_inter0Group
MpiComm * m_inter0Comm
int m_inter0Rank
int m_inter0CommSize
std::ofstream * m_subDisplayFile
RngBase * m_rngObject
BasicPdfsBase * m_basicPdfs
struct timeval m_timevalBegin
bool m_exceptionalCircumstance
EnvOptionsValues * m_optionsObj
Detailed Description
This (virtual) class sets up the environment underlying the use of the QUESO library by an executable.
This class sets up the environment underlying the use of the QUESO library by an executable. It:
assigns rank numbers, other than the world rank, to nodes participating in a parallel job,
provides communicators for generating a sequence of vectors in a distributed way,
provides functionality to read options from the 'options input file' (whose name is passed in the constructor of this environment class),
opens output files for messages that would otherwise be written to the screen (one output file per allowed rank is opened and allowed ranks can be specified through the 'options input file').
This class is virtual. It is inherited by 'EmptyEnvironment' and 'FullEnvironment'.
The QUESO environment class is instantiated at the application level, right after 'MPI_Init(&argc,&argv)'.
The QUESO environment is required by reference by many constructors in the QUESO library,
and is available by reference from many classes as well.
Throughout QUESO, there are five classes whose constructors check options in the 'options input file':
BaseEnvironment
StatisticalInverseProblem
StatisticalForwardProblem
MetropolisHastingsSG ('SG' stands for 'sequence generator')
MonteCarloSG
These classes rely on 'options classes' to read their options from the input file.
The options classes are, respectively:
EnvironmentOptions
StatisticalInverseProblemOptions
StatisticalForwardProblemOptions
MetropolisHastingsSGOptions
MonteCarloSGOptions
The last two classes also rely on SequenceStatisticalOptions for reading the options specifying which statistics have to be computed on the sequences of vectors
involved.
The QUESO environment class manages five types of communicators. Let:
'W >= 1' be the size of whole world communicator involved in a parallel run;
'N >= 1' be the size of the communicator passed to the QUESO environment constructor;
'S >= 1' be the number of statistical problems a QUESO environment will be handling at the same time, in parallel.
Usually 'W'='N', but such equality is not necessary. The number 'S' is equal to the QUESO environment option 'm_numSubEnvironments', and is equal to 1 by default. The number 'N' must be a multiple of 'S', otherwise the QUESO class prints a fatal error message and MPI aborts. The five types of communicators that QUESO manages are referred to as:
world = MPI_WORLD_COMM, of size W;
full = communicator passed to the constructor of BaseEnvironment, of size N and usually equal to the world communicator;
sub = communicator of size N/S that contains the number of MPI nodes necessary to solve a statistical inverse problem or a statistical forward problem.
self = MPI_SELF_COMM, of size 1;
inter0 = communicator of size S formed by all MPI nodes that have 'sub' rank 0 in their respective 'sub' communicators.
So, any given node has potentially five different ranks. Of course, if the user is solving just one statistical problem with just one MPI node, then all ranks are equal to zero.
In the QUESO library terminology, one might refer to a QUESO "full" environment composed of
'S' QUESO "sub" environments. Each sub environment is assigned a "sub" id varying from 0 (zero) to S-1. Each sub environment is able to generate a statistical inverse problem and/or a statistical forward problem. That is, each sub environment is able to handle a "sub" Markov chain (a sequence) of vectors and/or a "sub" Monte Carlo sequence of output vectors. The "sub" sequences can be seen as forming a "unified" sequence in a distributed way. Indeed, the virtual class 'VectorSequence' provides "sub" and "unified" statistical operations.
A QUESO "sub" environment eventually prints messages to its own output file. In order for that to happen, the requirements are:
option 'm_subDisplayFileName', a string, must be different than the default value ".";
option 'm_subDisplayAllowedSet', a set of sub ids, must contain the id of the sub environment wanting to write a message to the output file;
the previous requirement is automatically satisfied if the option 'm_subDisplayAllowAll', a boolean, is set to 1 (the default value is 0);
the processor wanting to write a message to the output file must have sub rank 0 (zero).
If all requirements are satisfied, then QUESO will generate a file with name '<m_subDisplayFileName>_sub<sub id>.txt'. For instance, if 'm_subDisplayFileName' is 'pROblem_775_' then a node of sub rank 0 in sub environment 17 will write a message to the file 'pROblem_775_sub17.txt'.
Definition at line 197 of file Environment.h.
Constructor & Destructor Documentation
QUESO::BaseEnvironment::BaseEnvironment (const char * passedOptionsInputFileName, EnvOptionsValues * alternativeOptionsValues)
Default constructor.
Definition at line 141 of file Environment.C.
References m_optionsInputFileName.
   :
   m_fullEnvIsReady             (false),
   m_worldRank                  (-1),
   m_fullComm                   (NULL),
   m_fullRank                   (-1),
   m_fullCommSize               (1),
   m_optionsInputFileName       (""),
   m_optionsInputFileAccessState(true),
 #ifndef DISABLE_BOOST_PROGRAM_OPTIONS
   m_allOptionsDesc             (NULL),
   m_allOptionsMap              (NULL),
 #endif  // DISABLE_BOOST_PROGRAM_OPTIONS
   m_input                      (new GetPot),
   m_subComm                    (NULL),
   m_subRank                    (-1),
   m_subCommSize                (1),
   m_selfComm                   (NULL),
   m_inter0Comm                 (NULL),
   m_inter0Rank                 (-1),
   m_inter0CommSize             (1),
   m_subDisplayFile             (NULL),
   m_rngObject                  (NULL),
   m_basicPdfs                  (NULL),
   m_exceptionalCircumstance    (false),
   m_optionsObj                 (alternativeOptionsValues)
 {
   if (passedOptionsInputFileName) m_optionsInputFileName     = passedOptionsInputFileName;
 }
QUESO::BaseEnvironment::BaseEnvironment (const std::string & passedOptionsInputFileName, EnvOptionsValues * alternativeOptionsValues)
Definition at line 173 of file Environment.C.
   :
   m_fullEnvIsReady             (false),
   m_worldRank                  (-1),
   m_fullComm                   (NULL),
   m_fullRank                   (-1),
   m_fullCommSize               (1),
   m_optionsInputFileName       (passedOptionsInputFileName),
   m_optionsInputFileAccessState(true),
 #ifndef DISABLE_BOOST_PROGRAM_OPTIONS
   m_allOptionsDesc             (NULL),
   m_allOptionsMap              (NULL),
 #endif  // DISABLE_BOOST_PROGRAM_OPTIONS
   m_input                      (new GetPot),
   m_subComm                    (NULL),
   m_subRank                    (-1),
   m_subCommSize                (1),
   m_selfComm                   (NULL),
   m_inter0Comm                 (NULL),
   m_inter0Rank                 (-1),
   m_inter0CommSize             (1),
   m_subDisplayFile             (NULL),
   m_rngObject                  (NULL),
   m_basicPdfs                  (NULL),
   m_exceptionalCircumstance    (false),
   m_optionsObj                 (alternativeOptionsValues)
 {
 }
QUESO::BaseEnvironment::~BaseEnvironment () virtual
Destructor.
It deallocates memory and does other cleanup for the class object and its class members when the object is destroyed. It displays the total run time of the combo QUESO + application using the function gettimeofday() from a struct timeval (as specified in <sys/time.h>).
Definition at line 205 of file Environment.C.
References displayVerbosity(), m_allOptionsDesc, m_allOptionsMap, m_basicPdfs, m_fullComm, m_fullRank, m_inter0Comm, m_rngObject, m_selfComm, m_subComm, m_subDisplayFile, and m_timevalBegin.
 {
   //if (m_subDisplayFile) {
   //  *m_subDisplayFile << "Entering BaseEnvironment::destructor()"
   //                          << std::endl;
   //}
   struct timeval timevalNow;
   /*int iRC = 0;*/
   /*iRC = */gettimeofday(&timevalNow, NULL);
   if( this->displayVerbosity() > 0 )
     {
      if (m_subDisplayFile) {
         *m_subDisplayFile << "Ending run at "    << ctime(&timevalNow.tv_sec)
                           << "Total run time = " << timevalNow.tv_sec - m_timevalBegin.tv_sec
                           << " seconds"
                           << std::endl;
       }
     if (m_fullRank == 0) {
         std::cout << "Ending run at "    << ctime(&timevalNow.tv_sec)
                   << "Total run time = " << timevalNow.tv_sec - m_timevalBegin.tv_sec
                   << " seconds"
                   << std::endl;
       }
     }
 #ifndef DISABLE_BOOST_PROGRAM_OPTIONS
   if (m_allOptionsMap) {
     delete m_allOptionsMap;
     delete m_allOptionsDesc;
   }
 #endif  // DISABLE_BOOST_PROGRAM_OPTIONS
   if (m_basicPdfs) delete m_basicPdfs;
   if (m_rngObject) delete m_rngObject;
   //if (m_subDisplayFile) {
   //  *m_subDisplayFile << "Leaving BaseEnvironment::destructor()"
   //                          << std::endl;
   //}
   if (m_subDisplayFile) delete m_subDisplayFile;
   if (m_inter0Comm    ) delete m_inter0Comm;
   if (m_selfComm      ) delete m_selfComm;
   if (m_subComm       ) delete m_subComm;
   if (m_fullComm      ) delete m_fullComm;
 }
Member Function Documentation
boost::program_options::variables_map & QUESO::BaseEnvironment::allOptionsMap () const
Access function to private attribute m_allOptionsMap. It is an instance of boost::program_options::variables_map(), which allows concrete variables to map which store variables in real map.
Definition at line 385 of file Environment.C.
References m_allOptionsMap, queso_deprecated, and queso_require_msg.
Referenced by QUESO::ExperimentModelOptions::getMyOptionValues(), QUESO::SimulationModelOptions::getMyOptionValues(), QUESO::GpmsaComputerModelOptions::getMyOptionValues(), QUESO::StatisticalForwardProblemOptions::getMyOptionValues(), QUESO::StatisticalInverseProblemOptions::getMyOptionValues(), QUESO::MonteCarloSGOptions::getMyOptionValues(), QUESO::EnvironmentOptions::getMyOptionValues(), and QUESO::MetropolisHastingsSGOptions::getMyOptionValues().
 {
   queso_deprecated();
   queso_require_msg(m_allOptionsMap, "m_allOptionsMap variable is NULL");
   return *m_allOptionsMap;
 }
const BasicPdfsBase * QUESO::BaseEnvironment::basicPdfs () const
Access to Basic PDFs.
Definition at line 489 of file Environment.C.
References m_basicPdfs.
 {
   return m_basicPdfs;
 }
unsigned int QUESO::BaseEnvironment::checkingLevel () const
Access function to private attribute m_checkingLevel.
Definition at line 463 of file Environment.C.
References QUESO::EnvOptionsValues::m_checkingLevel, m_optionsObj, and queso_require_msg.
Referenced by QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo(), QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointInfo(), QUESO::GcmJointTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointTildeInfo(), QUESO::GcmSimulationTildeInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationTildeInfo(), QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZTildeInfo(), and QUESO::GslMatrix::inverse().
 {
   queso_require_msg(m_optionsObj, "m_optionsObj variable is NULL");
   return m_optionsObj->m_checkingLevel;
 }
void QUESO::BaseEnvironment::checkTheParallelEnvironment () const
void QUESO::BaseEnvironment::closeFile (FilePtrSetStruct & filePtrSet, const std::string & fileType) const
Closes the file.
Definition at line 1083 of file Environment.C.
References QUESO::FilePtrSetStruct::ifsVar, m_subDisplayFile, QUESO::FilePtrSetStruct::ofsVar, queso_error_msg, subDisplayFile(), subRank(), UQ_FILE_EXTENSION_FOR_HDF_FORMAT, UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT, and UQ_FILE_EXTENSION_FOR_TXT_FORMAT.
Referenced by QUESO::GslVector::subReadContents(), QUESO::GslMatrix::subReadContents(), QUESO::GslVector::subWriteContents(), and QUESO::GslMatrix::subWriteContents().
 {
   std::string fileType(inputFileType);
 #ifdef QUESO_HAS_HDF5
   // Do nothing
 #else
   if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
     if (m_subDisplayFile) {
       *this->subDisplayFile() << "WARNING in BaseEnvironment::closeFile()"
                               << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                               << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' instead..."
                               << std::endl;
     }
     if (this->subRank() == 0) {
       std::cerr << "WARNING in BaseEnvironment::closeFile()"
                 << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                 << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' instead..."
                 << std::endl;
     }
     fileType = UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT;
   }
 #endif
   if ((fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) ||
       (fileType == UQ_FILE_EXTENSION_FOR_TXT_FORMAT)) {
     //filePtrSet.ofsVar->close(); // close() crashes on Mac; need to use delete(); why? prudenci 2010/June
     delete filePtrSet.ofsVar;
     filePtrSet.ofsVar = NULL;
     //filePtrSet.ifsVar->close();
     delete filePtrSet.ifsVar;
     filePtrSet.ifsVar = NULL;
   }
 #ifdef QUESO_HAS_HDF5
   else if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
     H5Fclose(filePtrSet.h5Var);
   }
 #endif
   else {
     queso_error_msg("invalid file type");
   }
   return;
 }
unsigned int QUESO::BaseEnvironment::displayVerbosity () const
Access function to private attribute m_displayVerbosity. It manages how much information will be release during the use of the QUESO library.
Definition at line 449 of file Environment.C.
References QUESO::EnvOptionsValues::m_displayVerbosity, m_optionsObj, and queso_require_msg.
Referenced by QUESO::AsciiTable< V, M >::AsciiTable(), QUESO::BaseJointPdf< V, M >::BaseJointPdf(), QUESO::BaseMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::BaseMatrixCovarianceFunction(), QUESO::BaseOneDGrid< T >::BaseOneDGrid(), QUESO::BaseScalarCdf< T >::BaseScalarCdf(), QUESO::BaseScalarCovarianceFunction< V, M >::BaseScalarCovarianceFunction(), QUESO::BaseVectorCdf< V, M >::BaseVectorCdf(), QUESO::BaseVectorMdf< V, M >::BaseVectorMdf(), QUESO::BaseVectorRealizer< V, M >::BaseVectorRealizer(), QUESO::BaseVectorRV< V, M >::BaseVectorRV(), QUESO::BetaJointPdf< V, M >::BetaJointPdf(), QUESO::BetaVectorRealizer< V, M >::BetaVectorRealizer(), QUESO::BetaVectorRV< V, M >::BetaVectorRV(), QUESO::ConcatenatedVectorRealizer< V, M >::ConcatenatedVectorRealizer(), QUESO::ConcatenatedVectorRV< V, M >::ConcatenatedVectorRV(), QUESO::FullEnvironment::construct(), QUESO::GslVector::cwSetBeta(), QUESO::GslMatrix::determinant(), QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel(), QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::ExperimentStorage(), QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::ExponentialMatrixCovarianceFunction(), QUESO::ExponentialScalarCovarianceFunction< V, M >::ExponentialScalarCovarianceFunction(), QUESO::FiniteDistribution::FiniteDistribution(), QUESO::GammaJointPdf< V, M >::GammaJointPdf(), QUESO::GammaVectorRealizer< V, M >::GammaVectorRealizer(), QUESO::GammaVectorRV< V, M >::GammaVectorRV(), QUESO::GaussianJointPdf< V, M >::GaussianJointPdf(), QUESO::GaussianVectorCdf< V, M >::GaussianVectorCdf(), QUESO::GaussianVectorMdf< V, M >::GaussianVectorMdf(), QUESO::GaussianVectorRealizer< V, M >::GaussianVectorRealizer(), QUESO::GaussianVectorRV< V, M >::GaussianVectorRV(), QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo(), QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointInfo(), QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationInfo(), QUESO::GcmSimulationTildeInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationTildeInfo(), QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmTotalInfo(), QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo(), QUESO::GenericMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::GenericMatrixCovarianceFunction(), QUESO::GenericScalarCovarianceFunction< V, M >::GenericScalarCovarianceFunction(), QUESO::GenericVectorRealizer< V, M >::GenericVectorRealizer(), QUESO::GenericVectorRV< V, M >::GenericVectorRV(), QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel(), QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), QUESO::horizontalDistance(), QUESO::GslMatrix::inverse(), QUESO::InverseGammaJointPdf< V, M >::InverseGammaJointPdf(), QUESO::InverseGammaVectorRealizer< V, M >::InverseGammaVectorRealizer(), QUESO::InverseGammaVectorRV< V, M >::InverseGammaVectorRV(), QUESO::GslMatrix::invertMultiply(), QUESO::InvLogitGaussianVectorRV< V, M >::InvLogitGaussianVectorRV(), QUESO::JeffreysJointPdf< V, M >::JeffreysJointPdf(), QUESO::JeffreysVectorRealizer< V, M >::JeffreysVectorRealizer(), QUESO::JeffreysVectorRV< V, M >::JeffreysVectorRV(), QUESO::GslMatrix::lnDeterminant(), QUESO::LogNormalJointPdf< V, M >::LogNormalJointPdf(), QUESO::LogNormalVectorRealizer< V, M >::LogNormalVectorRealizer(), QUESO::LogNormalVectorRV< V, M >::LogNormalVectorRV(), QUESO::MetropolisAdjustedLangevinTK< V, M >::MetropolisAdjustedLangevinTK(), openInputFile(), openOutputFile(), openUnifiedInputFile(), openUnifiedOutputFile(), QUESO::PoweredJointPdf< V, M >::PoweredJointPdf(), QUESO::GslMatrix::rank(), QUESO::SampledScalarCdf< T >::SampledScalarCdf(), QUESO::SampledVectorCdf< V, M >::SampledVectorCdf(), QUESO::SampledVectorMdf< V, M >::SampledVectorMdf(), QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup(), QUESO::EnvironmentOptions::scanOptionsValues(), QUESO::SequentialVectorRealizer< V, M >::SequentialVectorRealizer(), QUESO::SimulationModel< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationModel(), QUESO::SimulationStorage< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationStorage(), QUESO::StdOneDGrid< T >::StdOneDGrid(), QUESO::StdScalarCdf< T >::StdScalarCdf(), QUESO::GslMatrix::svdSolve(), QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup(), QUESO::UniformJointPdf< V, M >::UniformJointPdf(), QUESO::UniformOneDGrid< T >::UniformOneDGrid(), QUESO::UniformVectorRealizer< V, M >::UniformVectorRealizer(), QUESO::UniformVectorRV< V, M >::UniformVectorRV(), QUESO::VectorSet< V, M >::VectorSet(), QUESO::VectorSpace< V, M >::VectorSpace(), QUESO::VectorSubset< V, M >::VectorSubset(), QUESO::WignerJointPdf< V, M >::WignerJointPdf(), QUESO::WignerVectorRealizer< V, M >::WignerVectorRealizer(), QUESO::WignerVectorRV< V, M >::WignerVectorRV(), and ~BaseEnvironment().
 {
   queso_require_msg(m_optionsObj, "m_optionsObj variable is NULL");
   return m_optionsObj->m_displayVerbosity;
 }
bool QUESO::BaseEnvironment::exceptionalCircumstance () const
Decides whether there is an exceptional circumstance.
Definition at line 1142 of file Environment.C.
References m_exceptionalCircumstance.
 {
   return m_exceptionalCircumstance;
 }
const MpiComm & QUESO::BaseEnvironment::fullComm () const
Access function for MpiComm full communicator.
Definition at line 274 of file Environment.C.
References m_fullComm, and queso_require_msg.
Referenced by QUESO::FullEnvironment::construct(), QUESO::EnvironmentOptions::getMyOptionValues(), QUESO::MiscCheckTheParallelEnvironment(), and QUESO::InterpolationSurrogateIOASCII< V, M >::read().
 {
   queso_require_msg(m_fullComm, "m_fullComm variable is NULL");
   return *m_fullComm;
 }
bool QUESO::BaseEnvironment::fullEnvIsReady () const
Returns whether the full environment class is ready (constructor has successfully been called).
Definition at line 256 of file Environment.C.
References m_fullEnvIsReady.
 {
   return m_fullEnvIsReady;
 }
int QUESO::BaseEnvironment::fullRank () const
Returns the process full rank.
Definition at line 268 of file Environment.C.
References m_fullRank.
Referenced by QUESO::GslVector::cwSetBeta(), QUESO::EnvironmentOptions::getMyOptionValues(), QUESO::MetropolisHastingsSGOptions::getMyOptionValues(), QUESO::GslMatrix::mpiSum(), QUESO::OptimizerMonitor::print_header(), QUESO::OptimizerMonitor::print_iteration(), QUESO::InterpolationSurrogateIOASCII< V, M >::read(), QUESO::EnvironmentOptions::scanOptionsValues(), QUESO::GslVector::subReadContents(), QUESO::GslMatrix::subReadContents(), and QUESO::MpiComm::syncPrintDebugMsg().
 {
   return m_fullRank;
 }
std::string QUESO::BaseEnvironment::identifyingString () const
Access function to private attribute m_identifyingString: identifying string.
Definition at line 501 of file Environment.C.
References QUESO::EnvOptionsValues::m_identifyingString, and m_optionsObj.
 {
   return m_optionsObj->m_identifyingString;
 }
const GetPot & QUESO::BaseEnvironment::input () const
The GetPot input file parser.
Definition at line 1148 of file Environment.C.
References m_input.
Referenced by QUESO::EmOptionsValues::EmOptionsValues(), QUESO::EnvOptionsValues::EnvOptionsValues(), QUESO::GcmOptionsValues::GcmOptionsValues(), QUESO::MLSamplingLevelOptions::getAllOptions(), QUESO::GPMSAOptions::GPMSAOptions(), QUESO::InfiniteDimensionalMCMCSamplerOptions::InfiniteDimensionalMCMCSamplerOptions(), QUESO::MhOptionsValues::MhOptionsValues(), QUESO::MLSamplingOptions::MLSamplingOptions(), QUESO::operator<<(), QUESO::OptimizerOptions::OptimizerOptions(), QUESO::SfpOptionsValues::SfpOptionsValues(), QUESO::SipOptionsValues::SipOptionsValues(), and QUESO::SmOptionsValues::SmOptionsValues().
 {
   return *m_input;
 }
const MpiComm & QUESO::BaseEnvironment::inter0Comm () const
Access function for MpiComm inter0-communicator.
Definition at line 313 of file Environment.C.
References m_inter0Comm, and queso_require_msg.
Referenced by QUESO::ComputeCovCorrBetweenScalarSequences(), and QUESO::ComputeCovCorrMatricesBetweenVectorSequences().
 {
   queso_require_msg(m_inter0Comm, "m_inter0Comm variable is NULL");
   return *m_inter0Comm;
 }
int QUESO::BaseEnvironment::inter0Rank () const
Returns the process inter0 rank.
Definition at line 307 of file Environment.C.
References m_inter0Rank.
Referenced by QUESO::ComputeCovCorrBetweenScalarSequences(), QUESO::ComputeCovCorrMatricesBetweenVectorSequences(), QUESO::ComputeUnifiedGaussian2dKde(), QUESO::MetropolisHastingsSGOptions::getMyOptionValues(), and QUESO::MpiComm::syncPrintDebugMsg().
 {
   return m_inter0Rank;
 }
bool QUESO::BaseEnvironment::isThereInputFile () const
//TODO Not implemented? it is called in examples/validationCycle/tests_old/results_5_25/uqTgaEx4.h.
unsigned int QUESO::BaseEnvironment::numSubEnvironments () const
Access function to the number of sub-environments.
Definition at line 334 of file Environment.C.
References QUESO::EnvOptionsValues::m_numSubEnvironments, m_optionsObj, and queso_require_msg.
Referenced by QUESO::ComputeUnifiedGaussian2dKde(), and QUESO::MiscCheckTheParallelEnvironment().
 {
   queso_require_msg(m_optionsObj, "m_optionsObj variable is NULL");
   return m_optionsObj->m_numSubEnvironments;
 }
bool QUESO::BaseEnvironment::openInputFile (const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds, FilePtrSetStruct & filePtrSet) const
Opens an input file.
Definition at line 895 of file Environment.C.
References QUESO::CheckFilePath(), displayVerbosity(), QUESO::FilePtrSetStruct::ifsVar, m_subDisplayFile, queso_error_msg, queso_require_greater_equal_msg, queso_require_msg, subDisplayFile(), subRank(), UQ_ENV_FILENAME_FOR_NO_INPUT_FILE, UQ_FILE_EXTENSION_FOR_HDF_FORMAT, UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT, and UQ_FILE_EXTENSION_FOR_TXT_FORMAT.
Referenced by QUESO::GslVector::subReadContents(), and QUESO::GslMatrix::subReadContents().
 {
   std::string fileType(inputFileType);
 #ifdef QUESO_HAS_HDF5
   // Do nothing
 #else
   if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
     if (m_subDisplayFile) {
       *this->subDisplayFile() << "WARNING in BaseEnvironment::openInputFile()"
                               << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                               << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' instead..."
                               << std::endl;
     }
     if (this->subRank() == 0) {
       std::cerr << "WARNING in BaseEnvironment::openInputFile()"
                 << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                 << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' instead..."
                 << std::endl;
     }
     fileType = UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT;
   }
 #endif
   bool returnValue = true;
   filePtrSet.ifsVar = NULL;
   if ((baseFileName                         == UQ_ENV_FILENAME_FOR_NO_INPUT_FILE) ||
       (allowedSubEnvIds.find(this->subId()) == allowedSubEnvIds.end()           )) {
     if ((m_subDisplayFile) && (this->displayVerbosity() >= 10)) {
       *this->subDisplayFile() << "In BaseEnvironment::openInputFile()"
                               << ": no input file opened with base name '" << baseFileName << "." << fileType
                               << "'"
                               << std::endl;
     }
     returnValue = false;
   }
   else {
     // Open file
     if ((m_subDisplayFile) && (this->displayVerbosity() >= 10)) {
       *this->subDisplayFile() << "In BaseEnvironment::openInputFile()"
                               << ": opening input file with base name '" << baseFileName << "." << fileType
                               << "'"
                               << std::endl;
     }
     if (this->subRank() == 0) {
       // Verify parent directory exists (for cases when a user
       // specifies a relative path for the desired output file). prudenci 2010/06/26
       // std::cout << "checking " << baseFileName+"."+fileType << std::endl;
       int irtrn = CheckFilePath((baseFileName+"."+fileType).c_str());
       queso_require_greater_equal_msg(irtrn, 0, "unable to verify input path");
       if ((fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) ||
           (fileType == UQ_FILE_EXTENSION_FOR_TXT_FORMAT)) {
         filePtrSet.ifsVar = new std::ifstream((baseFileName+"."+fileType).c_str(),
                                               std::ofstream::in);
         if ((filePtrSet.ifsVar == NULL) || (filePtrSet.ifsVar->is_open() == false)) {
           std::cerr << "In BaseEnvironment::openInputFile()"
                     << ": failed to open input file with base name '" << baseFileName << "." << fileType
                     << "'"
                     << std::endl;
         }
         queso_require_msg(!((filePtrSet.ifsVar == NULL) || (filePtrSet.ifsVar->is_open() == false)), "file with fileName could not be found");
       }
 #ifdef QUESO_HAS_HDF5
       else if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
         filePtrSet.h5Var = H5Fopen((baseFileName+"."+fileType).c_str(),
                                    H5F_ACC_RDONLY,
                                    H5P_DEFAULT);
       }
 #endif
       else {
         queso_error_msg("invalid file type");
       }
     }
     else {
       returnValue = false;
     }
     //this->subComm().Barrier(); // prudenci-2011-01-17
   }
   return returnValue;
 }
bool QUESO::BaseEnvironment::openOutputFile (const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds, bool writeOver, FilePtrSetStruct & filePtrSet) const
Opens an output file for each sub-environment that was chosen to send data to the file.
Definition at line 520 of file Environment.C.
References QUESO::CheckFilePath(), displayVerbosity(), m_subDisplayFile, QUESO::FilePtrSetStruct::ofsVar, queso_error_msg, queso_require_greater_equal_msg, queso_require_msg, subDisplayFile(), subId(), subIdString(), subRank(), UQ_ENV_FILENAME_FOR_NO_OUTPUT_FILE, UQ_FILE_EXTENSION_FOR_HDF_FORMAT, UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT, and UQ_FILE_EXTENSION_FOR_TXT_FORMAT.
Referenced by QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel(), QUESO::GslVector::subWriteContents(), and QUESO::GslMatrix::subWriteContents().
 {
   std::string fileType(inputFileType);
 #ifdef QUESO_HAS_HDF5
   // Do nothing
 #else
   if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
     if (m_subDisplayFile) {
       *this->subDisplayFile() << "WARNING in BaseEnvironment::openOutputFile()"
                               << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                               << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' instead..."
                               << std::endl;
     }
     if (this->subRank() == 0) {
       std::cerr << "WARNING in BaseEnvironment::openOutputFile()"
                 << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                 << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' instead..."
                 << std::endl;
     }
     fileType = UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT;
   }
 #endif
   bool returnValue = true;
   filePtrSet.ofsVar = NULL;
   if ((baseFileName                         == UQ_ENV_FILENAME_FOR_NO_OUTPUT_FILE) ||
       (allowedSubEnvIds.find(this->subId()) == allowedSubEnvIds.end()            )) {
     if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
       *this->subDisplayFile() << "In BaseEnvironment::openOutputFile()"
                               << ", subId = "     << this->subId()
                               << ": no output file opened with base name '" << baseFileName << "." << fileType
                               << "'"
                               << ", writeOver = " << writeOver
                               << std::endl;
     }
     returnValue = false;
   }
   else {
     // Open file
     if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
       *this->subDisplayFile() << "In BaseEnvironment::openOutputFile()"
                               << ", subId = "     << this->subId()
                               << ": opening output file with base name '" << baseFileName << "." << fileType
                               << "'"
                               << ", writeOver = " << writeOver
                               << std::endl;
     }
     if (this->subRank() == 0) {
 #if 0
       std::cout << "In BaseEnvironment::openOutputFile()"
                 << ": opening output file with base name '" << baseFileName << "." << fileType
                 << "'"
                 << ", writeOver = " << writeOver
                 << std::endl;
 #endif
       // Verify parent directory exists (for cases when a user
       // specifies a relative path for the desired output file).
       // std::cout << "checking " << baseFileName+"_sub"+this->subIdString()+"."+fileType << std::endl;
       if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
         *this->subDisplayFile() << "In BaseEnvironment::openOutputFile()"
                                 << ", subId = "     << this->subId()
                                 << ", trying to open output file with base name '" << baseFileName << "." << fileType
                                 << "'"
                                 << ", writeOver = " << writeOver
                                 << ": calling CheckFilePath()..."
                                 << std::endl;
       }
       int irtrn = CheckFilePath((baseFileName+"_sub"+this->subIdString()+"."+fileType).c_str());
       if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
         *this->subDisplayFile() << "In BaseEnvironment::openOutputFile()"
                                 << ", subId = "     << this->subId()
                                 << ", trying to open output file with base name '" << baseFileName << "." << fileType
                                 << "'"
                                 << ", writeOver = " << writeOver
                                 << ": returned from CheckFilePath() with irtrn = " << irtrn
                                 << std::endl;
       }
       queso_require_greater_equal_msg(irtrn, 0, "unable to verify output path");
       if (writeOver) {
         // Write over an eventual pre-existing file
         if ((fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) ||
             (fileType == UQ_FILE_EXTENSION_FOR_TXT_FORMAT)) {
           filePtrSet.ofsVar = new std::ofstream((baseFileName+"_sub"+this->subIdString()+"."+fileType).c_str(),
                                                 std::ofstream::out | std::ofstream::trunc);
         }
         else if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
           queso_error_msg("hdf file type not supported yet");
         }
         else {
           queso_error_msg("invalid file type");
         }
         if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
           *this->subDisplayFile() << "In BaseEnvironment::openOutputFile()"
                                   << ": just opened output file with base name '" << baseFileName << "." << fileType
                                   << "'"
                                   << ", writeOver = " << writeOver
                                   << ", options 'out|trunc'"
                                   << ", osfvar = " << filePtrSet.ofsVar
                                   << std::endl;
         }
       }
       else {
         // Write at the end of an eventual pre-existing file
         if ((fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) ||
             (fileType == UQ_FILE_EXTENSION_FOR_TXT_FORMAT)) {
 #if 0
           filePtrSet.ofsVar = new std::ofstream((baseFileName+"_sub"+this->subIdString()+"."+fileType).c_str(),
                                                 std::ofstream::in);
           std::cout << "filePtrSet.ofsVar(1) = " << filePtrSet.ofsVar << std::endl;
           if (filePtrSet.ofsVar) std::cout << "filePtrSet.ofsVar(1)->is_open() = " << filePtrSet.ofsVar->is_open() << std::endl;
           if (filePtrSet.ofsVar) delete filePtrSet.ofsVar;
 #endif
           // 'm' and Ranger nodes behave differently on ofstream constructor... prudenci 2010/03/05
           filePtrSet.ofsVar = new std::ofstream((baseFileName+"_sub"+this->subIdString()+"."+fileType).c_str(),
                                                 std::ofstream::out /*| std::ofstream::in*/ | std::ofstream::app);
         }
 #ifdef QUESO_HAS_HDF5
         else if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
           std::string fullFileName =
             baseFileName+"_sub"+this->subIdString()+"."+fileType;
           // Use H5F_ACC_EXCL because not overwriting, so fail on existing file
           filePtrSet.h5Var = H5Fcreate(fullFileName.c_str(),
                                        H5F_ACC_EXCL,
                                        H5P_DEFAULT,
                                        H5P_DEFAULT);
           queso_require_greater_equal_msg(
               filePtrSet.h5Var, 0,
               "error opening file `" << fullFileName << "`");
         }
 #endif
         else {
           queso_error_msg("invalid file type");
         }
         if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
           *this->subDisplayFile() << "In BaseEnvironment::openOutputFile()"
                                   << ": just opened output file with base name '" << baseFileName << "." << fileType
                                   << "'"
                                   << ", writeOver = " << writeOver
                                   << ", options 'out|in|app'"
                                   << ", osfvar = " << filePtrSet.ofsVar
                                   << std::endl;
         }
         if (fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) {
           //std::cout << "filePtrSet.ofsVar(2) = " << filePtrSet.ofsVar << std::endl;
           //if (filePtrSet.ofsVar) std::cout << "filePtrSet.ofsVar(2)->is_open() = " << filePtrSet.ofsVar->is_open() << std::endl;
           if ((filePtrSet.ofsVar            == NULL ) ||
               (filePtrSet.ofsVar->is_open() == false)) {
             //std::cout << "Retrying 1..." << std::endl;
             delete filePtrSet.ofsVar;
             filePtrSet.ofsVar = new std::ofstream((baseFileName+"_sub"+this->subIdString()+"."+fileType).c_str(),
                                                   std::ofstream::out | std::ofstream::trunc);
             if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
               *this->subDisplayFile() << "In BaseEnvironment::openOutputFile()"
                                       << ": just opened output file with base name '" << baseFileName << "." << fileType
                                       << "'"
                                       << ", writeOver = " << writeOver
                                       << ", options 'out|trunc'"
                                       << ", osfvar = " << filePtrSet.ofsVar
                                       << std::endl;
             }
           }
         } // only for matlab formats
       }
       // Check the file actually opened
       if ((fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) ||
           (fileType == UQ_FILE_EXTENSION_FOR_TXT_FORMAT)) {
         queso_require_msg(
             (filePtrSet.ofsVar && filePtrSet.ofsVar->is_open()),
             "failed to open output file");
       }
     }
     else {
       returnValue = false;
     }
     //this->subComm().Barrier(); // prudenci-2011-01-17
   }
   return returnValue;
 }
bool QUESO::BaseEnvironment::openUnifiedInputFile (const std::string & fileName, const std::string & fileType, FilePtrSetStruct & filePtrSet) const
Opens the unified input file.
Definition at line 990 of file Environment.C.
References QUESO::CheckFilePath(), displayVerbosity(), QUESO::FilePtrSetStruct::ifsVar, m_subDisplayFile, queso_error_msg, queso_require_greater_equal_msg, queso_require_msg, subDisplayFile(), subRank(), UQ_ENV_FILENAME_FOR_NO_INPUT_FILE, UQ_FILE_EXTENSION_FOR_HDF_FORMAT, UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT, and UQ_FILE_EXTENSION_FOR_TXT_FORMAT.
 {
   std::string fileType(inputFileType);
 #ifdef QUESO_HAS_HDF5
   // Do nothing
 #else
   if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
     if (m_subDisplayFile) {
       *this->subDisplayFile() << "WARNING in BaseEnvironment::openUnifiedInputFile()"
                               << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                               << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' instead..."
                               << std::endl;
     }
     if (this->subRank() == 0) {
       std::cerr << "WARNING in BaseEnvironment::openUnifiedInputFile()"
                 << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                 << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' instead..."
                 << std::endl;
     }
     fileType = UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT;
   }
 #endif
   bool returnValue = true;
   filePtrSet.ifsVar = NULL;
   if (baseFileName == UQ_ENV_FILENAME_FOR_NO_INPUT_FILE) {
     if ((m_subDisplayFile) && (this->displayVerbosity() >= 10)) {
       *this->subDisplayFile() << "In BaseEnvironment::openUnifiedInputFile()"
                               << ": no input file opened with base name '" << baseFileName << "." << fileType
                               << "'"
                               << std::endl;
     }
     returnValue = false;
   }
   else {
     // Open file
     if ((m_subDisplayFile) && (this->displayVerbosity() >= 10)) {
       *this->subDisplayFile() << "In BaseEnvironment::openUnifiedInputFile()"
                               << ": opening input file with base name '" << baseFileName << "." << fileType
                               << "'"
                               << std::endl;
     }
     if (this->subRank() == 0) { // Needed ???????? prudenci 2010-11-11
       // Verify parent directory exists (for cases when a user
       // specifies a relative path for the desired output file). prudenci 2010/06/26
       // std::cout << "checking " << baseFileName+"."+fileType << std::endl;
       int irtrn = CheckFilePath((baseFileName+"."+fileType).c_str());
       queso_require_greater_equal_msg(irtrn, 0, "unable to verify input path");
       if ((fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) ||
           (fileType == UQ_FILE_EXTENSION_FOR_TXT_FORMAT)) {
         filePtrSet.ifsVar = new std::ifstream((baseFileName+"."+fileType).c_str(),
                                               std::ofstream::in);
         if ((filePtrSet.ifsVar == NULL) || (filePtrSet.ifsVar->is_open() == false)) {
           std::cerr << "In BaseEnvironment::openUnifiedInputFile()"
                     << ": failed to open input file with base name '" << baseFileName << "." << fileType
                     << "'"
                     << std::endl;
         }
         queso_require_msg(!((filePtrSet.ifsVar == NULL) || (filePtrSet.ifsVar->is_open() == false)), "file with fileName could not be found");
       }
 #ifdef QUESO_HAS_HDF5
       else if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
         filePtrSet.h5Var = H5Fopen((baseFileName+"."+fileType).c_str(),
                                    H5F_ACC_RDONLY,
                                    H5P_DEFAULT);
       }
 #endif
       else {
         queso_error_msg("invalid file type");
       }
     }
     //else {
     //  returnValue = false;
     //}
     //this->subComm().Barrier();
   }
   return returnValue;
 }
bool QUESO::BaseEnvironment::openUnifiedOutputFile (const std::string & fileName, const std::string & fileType, bool writeOver, FilePtrSetStruct & filePtrSet) const
Opens a unified output file, that will contain data from all sub-environments.
Definition at line 725 of file Environment.C.
References QUESO::CheckFilePath(), displayVerbosity(), m_subDisplayFile, QUESO::FilePtrSetStruct::ofsVar, queso_error_msg, queso_require_greater_equal_msg, queso_require_msg, subDisplayFile(), subRank(), UQ_FILE_EXTENSION_FOR_HDF_FORMAT, UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT, and UQ_FILE_EXTENSION_FOR_TXT_FORMAT.
 {
   std::string fileType(inputFileType);
 #ifdef QUESO_HAS_HDF5
   // Do nothing
 #else
   if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
     if (m_subDisplayFile) {
       *this->subDisplayFile() << "WARNING in BaseEnvironment::openUnifiedOutputFile()"
                               << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                               << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                               << "' instead..."
                               << std::endl;
     }
     if (this->subRank() == 0) {
       std::cerr << "WARNING in BaseEnvironment::openUnifiedOutputFile()"
                 << ": file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' has been requested, but this QUESO library has not been built with 'hdf5'"
                 << ". Code will therefore process the file format '" << UQ_FILE_EXTENSION_FOR_HDF_FORMAT
                 << "' instead..."
                 << std::endl;
     }
     fileType = UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT;
   }
 #endif
   bool returnValue = true;
   filePtrSet.ofsVar = NULL;
   if (baseFileName == ".") {
     if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
       *this->subDisplayFile() << "In BaseEnvironment::openUnifiedOutputFile()"
                               << ": no unified output file opened with base name '" << baseFileName << "." << fileType
                               << "'"
                               << ", writeOver = " << writeOver
                               << std::endl;
     }
     returnValue = false;
   }
   else {
     // Open file
     if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
       *this->subDisplayFile() << "In BaseEnvironment::openUnifiedOutputFile()"
                               << ": opening unified output file with base name '" << baseFileName << "." << fileType
                               << "'"
                               << ", writeOver = " << writeOver
                               << std::endl;
     }
     //if ((this->subRank   () == 0) &&
     //    (this->inter0Rank() == 0)) {
 #if 0
       std::cout << "In BaseEnvironment::openUnifiedOutputFile()"
                 << ": opening output file with base name '" << baseFileName << "." << fileType
                 << "'"
                 << ", writeOver = " << writeOver
                 << std::endl;
 #endif
       // Verify parent directory exists (for cases when a user
       // specifies a relative path for the desired output file). prudenci 2010/06/26
       // std::cout << "checking " << baseFileName+"."+fileType << std::endl;
       int irtrn = CheckFilePath((baseFileName+"."+fileType).c_str());
       queso_require_greater_equal_msg(irtrn, 0, "unable to verify output path");
       if (writeOver) {
         // Write over an eventual pre-existing file
         if ((fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) ||
             (fileType == UQ_FILE_EXTENSION_FOR_TXT_FORMAT)) {
           filePtrSet.ofsVar = new std::ofstream((baseFileName+"."+fileType).c_str(),
                                                 std::ofstream::out | std::ofstream::trunc);
         }
 #ifdef QUESO_HAS_HDF5
         else if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
           filePtrSet.h5Var = H5Fcreate((baseFileName+"."+fileType).c_str(),
                                        H5F_ACC_TRUNC,
                                        H5P_DEFAULT,
                                        H5P_DEFAULT);
         }
 #endif
         else {
           queso_error_msg("invalid file type");
         }
         if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
           *this->subDisplayFile() << "In BaseEnvironment::openUnifiedOutputFile()"
                                   << ": just opened output file with base name '" << baseFileName << "." << fileType
                                   << "'"
                                   << ", writeOver = " << writeOver
                                   << ", options 'out|trunc'"
                                   << ", osfvar = " << filePtrSet.ofsVar
                                   << std::endl;
         }
       }
       else {
         // Write at the end of an eventual pre-existing file
         // 'm' and Ranger nodes behave differently on ofstream constructor... prudenci 2010/03/05
         if ((fileType == UQ_FILE_EXTENSION_FOR_MATLAB_FORMAT) ||
             (fileType == UQ_FILE_EXTENSION_FOR_TXT_FORMAT)) {
           filePtrSet.ofsVar = new std::ofstream((baseFileName+"."+fileType).c_str(),
                                                 std::ofstream::out /*| std::ofstream::in*/ | std::ofstream::app);
         }
 #ifdef QUESO_HAS_HDF5
         else if (fileType == UQ_FILE_EXTENSION_FOR_HDF_FORMAT) {
           filePtrSet.h5Var = H5Fcreate((baseFileName+"."+fileType).c_str(), // TEMPORARY - FIX ME
                                        H5F_ACC_TRUNC,
                                        H5P_DEFAULT,
                                        H5P_DEFAULT);
           //                    m_worldRank,
           //                    "BaseEnvironment::openUnifiedOutputFile(), writeOver=false",
           //                    "hdf file type not supported yet");
         }
 #endif
         else {
           queso_error_msg("invalid file type");
         }
         if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
           *this->subDisplayFile() << "In BaseEnvironment::openUnifiedOutputFile()"
                                   << ": just opened output file with base name '" << baseFileName << "." << fileType
                                   << "'"
                                   << ", writeOver = " << writeOver
                                   << ", options 'out|in|app'"
                                   << ", osfvar = " << filePtrSet.ofsVar
                                   << std::endl;
         }
         if ((filePtrSet.ofsVar            == NULL ) ||
             (filePtrSet.ofsVar->is_open() == false)) {
 #if 0
           std::cout << "Retrying 2..." << std::endl;
 #endif
           delete filePtrSet.ofsVar;
           filePtrSet.ofsVar = new std::ofstream((baseFileName+"."+fileType).c_str(),
                                                 std::ofstream::out | std::ofstream::trunc);
           if ((m_subDisplayFile) && (this->displayVerbosity() > 10)) { // output debug
             *this->subDisplayFile() << "In BaseEnvironment::openUnifiedOutputFile()"
                                     << ": just opened output file with base name '" << baseFileName << "." << fileType
                                     << "'"
                                     << ", writeOver = " << writeOver
                                     << ", options 'out|trunc'"
                                     << ", osfvar = " << filePtrSet.ofsVar
                                     << std::endl;
           }
         }
       }
       if (filePtrSet.ofsVar == NULL) {
         std::cerr << "In BaseEnvironment::openUnifiedOutputFile()"
                   << ": failed to open unified output file with base name '" << baseFileName << "." << fileType
                   << "'"
                   << std::endl;
       }
       queso_require_msg((filePtrSet.ofsVar && filePtrSet.ofsVar->is_open()), "failed to open output file");
     //}
   }
   return returnValue;
 }
std::string QUESO::BaseEnvironment::optionsInputFileName () const
Access to the attribute m_optionsInputFileName, which stores the name of the input file passed by the user to QUESO.
Definition at line 353 of file Environment.C.
References m_optionsInputFileAccessState, and m_optionsInputFileName.
Referenced by QUESO::EnvironmentOptions::EnvironmentOptions(), QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel(), QUESO::ExperimentModelOptions::ExperimentModelOptions(), QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel(), QUESO::GpmsaComputerModelOptions::GpmsaComputerModelOptions(), QUESO::GPMSAFactory< V, M >::GPMSAFactory(), QUESO::GPMSAOptions::GPMSAOptions(), QUESO::InfiniteDimensionalMCMCSamplerOptions::InfiniteDimensionalMCMCSamplerOptions(), QUESO::MetropolisHastingsSGOptions::MetropolisHastingsSGOptions(), QUESO::MonteCarloSGOptions::MonteCarloSGOptions(), QUESO::MLSamplingLevelOptions::scanOptionsValues(), QUESO::SimulationModel< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationModel(), QUESO::SimulationModelOptions::SimulationModelOptions(), QUESO::StatisticalForwardProblemOptions::StatisticalForwardProblemOptions(), QUESO::StatisticalInverseProblem< P_V, P_M >::StatisticalInverseProblem(), and QUESO::StatisticalInverseProblemOptions::StatisticalInverseProblemOptions().
 {
   if (m_optionsInputFileAccessState) {
     return m_optionsInputFileName;
   }
   else {
     return "";
   }
 }
std::string QUESO::BaseEnvironment::platformName () const
Access to the platform name.
Definition at line 495 of file Environment.C.
References m_optionsObj, and QUESO::EnvOptionsValues::m_platformName.
 {
   return m_optionsObj->m_platformName;
 }
virtual void QUESO::BaseEnvironment::print (std::ostream & os) const pure virtual
Implemented in QUESO::FullEnvironment, and QUESO::EmptyEnvironment.
void QUESO::BaseEnvironment::resetIdentifyingString (const std::string & newString)
Reset private attribute m_identifyingString with the value newString.
Definition at line 507 of file Environment.C.
References QUESO::EnvOptionsValues::m_identifyingString, and m_optionsObj.
 {
   m_optionsObj->m_identifyingString = newString;
   return;
 }
void QUESO::BaseEnvironment::resetSeed (int newSeedOption)
Reset RNG seed.
Definition at line 482 of file Environment.C.
References m_rngObject, and QUESO::RngBase::resetSeed().
 {
   m_rngObject->resetSeed(newSeedOption);
   return;
 }
const RngBase * QUESO::BaseEnvironment::rngObject () const
Access to the RNG object.
Definition at line 470 of file Environment.C.
References m_rngObject.
Referenced by QUESO::GslVector::cwSetBeta(), QUESO::GslVector::cwSetGamma(), QUESO::GslVector::cwSetGaussian(), QUESO::GslVector::cwSetInverseGamma(), QUESO::GslVector::cwSetUniform(), QUESO::InfiniteDimensionalGaussian::draw(), and QUESO::FiniteDistribution::sample().
 {
   return m_rngObject;
 }
void QUESO::BaseEnvironment::scanInputFileForMyOptions (const boost::program_options::options_description & optionsDesc) const
This method scans the input file provided by the user to QUESO.
It checks if no input file is passed and updates the private attribute m_allOptionsDesc, which keeps all the options.
Definition at line 396 of file Environment.C.
References m_allOptionsDesc, m_allOptionsMap, m_optionsInputFileName, queso_deprecated, queso_require_msg, and queso_require_not_equal_to_msg.
Referenced by QUESO::ExperimentModelOptions::scanOptionsValues(), QUESO::SimulationModelOptions::scanOptionsValues(), QUESO::GpmsaComputerModelOptions::scanOptionsValues(), QUESO::StatisticalForwardProblemOptions::scanOptionsValues(), QUESO::StatisticalInverseProblemOptions::scanOptionsValues(), QUESO::MonteCarloSGOptions::scanOptionsValues(), QUESO::EnvironmentOptions::scanOptionsValues(), and QUESO::MetropolisHastingsSGOptions::scanOptionsValues().
 {
   queso_deprecated();
 #ifdef UQ_USES_COMMAND_LINE_OPTIONS
   // If you want to use command line options, the following line does *not* work outside 'main.C',
   // e.g., in the constructor of FullEnvironment:
   // Line: boost::program_options::store(boost::program_options::parse_command_line(argc, argv, *m_allOptionsDesc), *m_allOptionsMap);
   //
   // Instead, put the following three lines *immediately after* instantianting the UQ environment
   // variable "FullEnvironment* env":
   // Line 1: boost::program_options::store(boost::program_options::parse_command_line(argc, argv, env->allOptionsDesc()), env->allOptionsMap());
   // Line 2: boost::program_options::notify(env->allOptionsMap());
   // Line 3: env->getMyOptionValues();
 #endif
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "Entering BaseEnv::scanInputFileForMyOptions()" << std::endl;
 #endif
   queso_require_msg(m_allOptionsDesc, "m_allOptionsDesc variable is NULL");
   m_allOptionsDesc->add(optionsDesc);
   //if (m_subDisplayFile) {
   //  *m_subDisplayFile << *m_allOptionsDesc
   //                    << std::endl;
   //}
   queso_require_not_equal_to_msg(m_optionsInputFileName, std::string(""),
                                  std::string("m_optionsInputFileName is 'nothing'"));
   //std::ifstream ifs(m_optionsInputFileName.c_str());
   std::ifstream* ifs = new std::ifstream(m_optionsInputFileName.c_str());
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "in BaseEnv::scanInputFileForMyOptions(), before store(a)" << std::endl;
 #endif
   queso_require_msg(m_allOptionsMap, "m_allOptionsMap variable is NULL");
   boost::program_options::store(boost::program_options::parse_config_file(*ifs, *m_allOptionsDesc, true), *m_allOptionsMap);
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "in BaseEnv::scanInputFileForMyOptions(), after store(a)" << std::endl;
 #endif
   boost::program_options::notify(*m_allOptionsMap);
   //ifs.close();
   delete ifs;
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "Leaving BaseEnv::scanInputFileForMyOptions()" << std::endl;
 #endif
   return;
 }
int QUESO::BaseEnvironment::seed () const
Access to the RNG seed.
Definition at line 476 of file Environment.C.
References m_rngObject, and QUESO::RngBase::seed().
 {
   return m_rngObject->seed();
 }
const MpiComm & QUESO::BaseEnvironment::selfComm () const
Access function for MpiComm self-communicator.
Definition at line 300 of file Environment.C.
References m_selfComm, and queso_require_msg.
 {
   queso_require_msg(m_selfComm, "m_selfComm variable is NULL");
   return *m_selfComm;
 }
void QUESO::BaseEnvironment::setExceptionalCircumstance (bool value) const
Set an exceptional circumstance.
Definition at line 1135 of file Environment.C.
References m_exceptionalCircumstance.
 {
   m_exceptionalCircumstance = value;
   return;
 }
void QUESO::BaseEnvironment::setOptionsInputFileAccessState (bool newState) const
Definition at line 364 of file Environment.C.
References m_optionsInputFileAccessState.
 {
   m_optionsInputFileAccessState = newState;
   return;
 }
const MpiComm & QUESO::BaseEnvironment::subComm () const
Access function for MpiComm sub communicator.
Definition at line 293 of file Environment.C.
References m_subComm, and queso_require_msg.
Referenced by QUESO::MiscCheckTheParallelEnvironment().
 {
   queso_require_msg(m_subComm, "m_subComm variable is NULL");
   return *m_subComm;
 }
std::ofstream * QUESO::BaseEnvironment::subDisplayFile () const
Access function for m_subDisplayFile (displays file on stream).
Definition at line 320 of file Environment.C.
References m_subDisplayFile.
Referenced by QUESO::AsciiTable< V, M >::AsciiTable(), QUESO::BaseJointPdf< V, M >::BaseJointPdf(), QUESO::BaseMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::BaseMatrixCovarianceFunction(), QUESO::BaseOneDGrid< T >::BaseOneDGrid(), QUESO::BaseScalarCdf< T >::BaseScalarCdf(), QUESO::BaseScalarCovarianceFunction< V, M >::BaseScalarCovarianceFunction(), QUESO::BaseVectorCdf< V, M >::BaseVectorCdf(), QUESO::BaseVectorMdf< V, M >::BaseVectorMdf(), QUESO::BaseVectorRealizer< V, M >::BaseVectorRealizer(), QUESO::BaseVectorRV< V, M >::BaseVectorRV(), QUESO::BetaJointPdf< V, M >::BetaJointPdf(), QUESO::BetaVectorRealizer< V, M >::BetaVectorRealizer(), QUESO::BetaVectorRV< V, M >::BetaVectorRV(), QUESO::GPMSAOptions::checkOptions(), QUESO::MLSamplingOptions::checkOptions(), QUESO::MLSamplingLevelOptions::checkOptions(), closeFile(), QUESO::ComputeConditionalGaussianVectorRV(), QUESO::ConcatenatedVectorRealizer< V, M >::ConcatenatedVectorRealizer(), QUESO::ConcatenatedVectorRV< V, M >::ConcatenatedVectorRV(), QUESO::GslVector::cwSetBeta(), QUESO::GslMatrix::determinant(), QUESO::EnvironmentOptions::EnvironmentOptions(), QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel(), QUESO::ExperimentModelOptions::ExperimentModelOptions(), QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::ExperimentStorage(), QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::ExponentialMatrixCovarianceFunction(), QUESO::ExponentialScalarCovarianceFunction< V, M >::ExponentialScalarCovarianceFunction(), QUESO::FiniteDistribution::FiniteDistribution(), QUESO::GammaJointPdf< V, M >::GammaJointPdf(), QUESO::GammaVectorRealizer< V, M >::GammaVectorRealizer(), QUESO::GammaVectorRV< V, M >::GammaVectorRV(), QUESO::GaussianJointPdf< V, M >::GaussianJointPdf(), QUESO::GaussianVectorCdf< V, M >::GaussianVectorCdf(), QUESO::GaussianVectorMdf< V, M >::GaussianVectorMdf(), QUESO::GaussianVectorRealizer< V, M >::GaussianVectorRealizer(), QUESO::GaussianVectorRV< V, M >::GaussianVectorRV(), QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo(), QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointInfo(), QUESO::GcmJointTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointTildeInfo(), QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationInfo(), QUESO::GcmSimulationTildeInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationTildeInfo(), QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmTotalInfo(), QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo(), QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZTildeInfo(), QUESO::GenericMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::GenericMatrixCovarianceFunction(), QUESO::GenericScalarCovarianceFunction< V, M >::GenericScalarCovarianceFunction(), QUESO::GenericVectorRealizer< V, M >::GenericVectorRealizer(), QUESO::GenericVectorRV< V, M >::GenericVectorRV(), QUESO::ExperimentModelOptions::getMyOptionValues(), QUESO::SimulationModelOptions::getMyOptionValues(), QUESO::GpmsaComputerModelOptions::getMyOptionValues(), QUESO::StatisticalForwardProblemOptions::getMyOptionValues(), QUESO::StatisticalInverseProblemOptions::getMyOptionValues(), QUESO::MonteCarloSGOptions::getMyOptionValues(), QUESO::MetropolisHastingsSGOptions::getMyOptionValues(), QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel(), QUESO::GpmsaComputerModelOptions::GpmsaComputerModelOptions(), QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), QUESO::horizontalDistance(), QUESO::GslMatrix::inverse(), QUESO::InverseGammaJointPdf< V, M >::InverseGammaJointPdf(), QUESO::InverseGammaVectorRealizer< V, M >::InverseGammaVectorRealizer(), QUESO::InverseGammaVectorRV< V, M >::InverseGammaVectorRV(), QUESO::GslMatrix::invertMultiply(), QUESO::InvLogitGaussianVectorRV< V, M >::InvLogitGaussianVectorRV(), QUESO::JeffreysJointPdf< V, M >::JeffreysJointPdf(), QUESO::JeffreysVectorRealizer< V, M >::JeffreysVectorRealizer(), QUESO::JeffreysVectorRV< V, M >::JeffreysVectorRV(), QUESO::GslMatrix::lnDeterminant(), QUESO::LogNormalJointPdf< V, M >::LogNormalJointPdf(), QUESO::LogNormalVectorRealizer< V, M >::LogNormalVectorRealizer(), QUESO::LogNormalVectorRV< V, M >::LogNormalVectorRV(), QUESO::MetropolisAdjustedLangevinTK< V, M >::MetropolisAdjustedLangevinTK(), QUESO::MetropolisHastingsSG< P_V, P_M >::MetropolisHastingsSG(), QUESO::MetropolisHastingsSGOptions::MetropolisHastingsSGOptions(), QUESO::MLSampling< P_V, P_M >::MLSampling(), QUESO::ModelValidation< P_V, P_M, Q_V, Q_M >::ModelValidation(), QUESO::MonteCarloSGOptions::MonteCarloSGOptions(), openInputFile(), openOutputFile(), openUnifiedInputFile(), openUnifiedOutputFile(), QUESO::PoweredJointPdf< V, M >::PoweredJointPdf(), QUESO::GslMatrix::rank(), QUESO::SampledScalarCdf< T >::SampledScalarCdf(), QUESO::SampledVectorCdf< V, M >::SampledVectorCdf(), QUESO::SampledVectorMdf< V, M >::SampledVectorMdf(), QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup(), QUESO::ExperimentModelOptions::scanOptionsValues(), QUESO::SimulationModelOptions::scanOptionsValues(), QUESO::GpmsaComputerModelOptions::scanOptionsValues(), QUESO::StatisticalForwardProblemOptions::scanOptionsValues(), QUESO::StatisticalInverseProblemOptions::scanOptionsValues(), QUESO::MonteCarloSGOptions::scanOptionsValues(), QUESO::MetropolisHastingsSGOptions::scanOptionsValues(), QUESO::SequentialVectorRealizer< V, M >::SequentialVectorRealizer(), QUESO::SimulationModel< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationModel(), QUESO::SimulationModelOptions::SimulationModelOptions(), QUESO::SimulationStorage< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationStorage(), QUESO::StatisticalForwardProblemOptions::StatisticalForwardProblemOptions(), QUESO::StatisticalInverseProblem< P_V, P_M >::StatisticalInverseProblem(), QUESO::StatisticalInverseProblemOptions::StatisticalInverseProblemOptions(), QUESO::StdOneDGrid< T >::StdOneDGrid(), QUESO::StdScalarCdf< T >::StdScalarCdf(), QUESO::GslVector::subReadContents(), QUESO::GslMatrix::subReadContents(), QUESO::GslMatrix::svdSolve(), QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup(), QUESO::UniformJointPdf< V, M >::UniformJointPdf(), QUESO::UniformOneDGrid< T >::UniformOneDGrid(), QUESO::UniformVectorRealizer< V, M >::UniformVectorRealizer(), QUESO::UniformVectorRV< V, M >::UniformVectorRV(), QUESO::ValidationCycle< P_V, P_M, Q_V, Q_M >::ValidationCycle(), QUESO::VectorSet< V, M >::VectorSet(), QUESO::VectorSpace< V, M >::VectorSpace(), QUESO::VectorSubset< V, M >::VectorSubset(), QUESO::WignerJointPdf< V, M >::WignerJointPdf(), QUESO::WignerVectorRealizer< V, M >::WignerVectorRealizer(), and QUESO::WignerVectorRV< V, M >::WignerVectorRV().
 {
   return m_subDisplayFile;
 }
std::string QUESO::BaseEnvironment::subDisplayFileName () const
Access function for m_subDisplayFileName (displays filename on stream).
Definition at line 326 of file Environment.C.
References m_optionsObj, and QUESO::EnvOptionsValues::m_subDisplayFileName.
 {
   if (m_optionsObj == NULL) return ".";
   return m_optionsObj->m_subDisplayFileName;
 }
RawType_MPI_Group QUESO::BaseEnvironment::subGroup () const
Access function for sub-group.
Definition at line 281 of file Environment.C.
References m_subGroup.
 {
   return m_subGroup;
 }
unsigned int QUESO::BaseEnvironment::subId () const
Access function to the number of each sub-environment Id: m_subId.
Definition at line 341 of file Environment.C.
References m_subId.
Referenced by QUESO::MLSamplingLevelOptions::checkOptions(), QUESO::MhOptionsValues::checkOptions(), QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo(), QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointInfo(), QUESO::GcmJointTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointTildeInfo(), QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationInfo(), QUESO::GcmSimulationTildeInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationTildeInfo(), QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZTildeInfo(), QUESO::SimulationModelOptions::getMyOptionValues(), QUESO::GpmsaComputerModelOptions::getMyOptionValues(), QUESO::MetropolisHastingsSGOptions::getMyOptionValues(), QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel(), openOutputFile(), QUESO::SimulationModel< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationModel(), and QUESO::MpiComm::syncPrintDebugMsg().
 {
   return m_subId;
 }
const std::string & QUESO::BaseEnvironment::subIdString () const
Access to the attribute m_subIdString; which stores the string for the sub-environment, and it will be used, for instance, to create the output files for each sub-environment.
Definition at line 347 of file Environment.C.
References m_subIdString.
Referenced by openOutputFile(), QUESO::Sampled1D1DFunction::printForMatlab(), QUESO::GslVector::subWriteContents(), and QUESO::GslMatrix::subWriteContents().
 {
   return m_subIdString;
 }
int QUESO::BaseEnvironment::subRank () const
Access function for sub-rank.
Definition at line 287 of file Environment.C.
References m_subRank.
Referenced by closeFile(), QUESO::MetropolisHastingsSGOptions::getMyOptionValues(), QUESO::MiscCheckTheParallelEnvironment(), openInputFile(), openOutputFile(), openUnifiedInputFile(), openUnifiedOutputFile(), QUESO::GslVector::subReadContents(), QUESO::GslMatrix::subReadContents(), QUESO::GslVector::subWriteContents(), QUESO::GslMatrix::subWriteContents(), and QUESO::MpiComm::syncPrintDebugMsg().
 {
   return m_subRank;
 }
unsigned int QUESO::BaseEnvironment::syncVerbosity () const
Access function to private attribute m_syncVerbosity.
Definition at line 456 of file Environment.C.
References m_optionsObj, QUESO::EnvOptionsValues::m_syncVerbosity, and queso_require_msg.
Referenced by QUESO::MpiComm::syncPrintDebugMsg().
 {
   queso_require_msg(m_optionsObj, "m_optionsObj variable is NULL");
   return m_optionsObj->m_syncVerbosity;
 }
struct timeval QUESO::BaseEnvironment::timevalBegin () const
Used to save the time when the combo `QUESO+user's application' started to run.
Definition at line 514 of file Environment.C.
 {
   return m_timevalBegin;
 }
int QUESO::BaseEnvironment::worldRank () const
Returns the process world rank.
Definition at line 262 of file Environment.C.
References m_worldRank.
Referenced by QUESO::GslMatrix::chol(), QUESO::ComputeCovCorrMatricesBetweenVectorSequences(), QUESO::MetropolisHastingsSGOptions::getMyOptionValues(), and QUESO::GslMatrix::internalSvd().
 {
   return m_worldRank;
 }
Member Data Documentation
boost::program_options::options_description* QUESO::BaseEnvironment::m_allOptionsDesc protected
Definition at line 377 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), scanInputFileForMyOptions(), and ~BaseEnvironment().
boost::program_options::variables_map* QUESO::BaseEnvironment::m_allOptionsMap protected
Definition at line 378 of file Environment.h.
Referenced by allOptionsMap(), QUESO::FullEnvironment::construct(), scanInputFileForMyOptions(), and ~BaseEnvironment().
BasicPdfsBase* QUESO::BaseEnvironment::m_basicPdfs protected
Definition at line 398 of file Environment.h.
Referenced by basicPdfs(), QUESO::FullEnvironment::construct(), and ~BaseEnvironment().
bool QUESO::BaseEnvironment::m_exceptionalCircumstance mutable protected
Definition at line 400 of file Environment.h.
Referenced by exceptionalCircumstance(), and setExceptionalCircumstance().
MpiComm* QUESO::BaseEnvironment::m_fullComm protected
Definition at line 369 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), fullComm(), and ~BaseEnvironment().
int QUESO::BaseEnvironment::m_fullCommSize protected
Definition at line 371 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct().
bool QUESO::BaseEnvironment::m_fullEnvIsReady protected
Definition at line 366 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), and fullEnvIsReady().
RawType_MPI_Group QUESO::BaseEnvironment::m_fullGroup protected
Definition at line 372 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct().
int QUESO::BaseEnvironment::m_fullRank protected
Definition at line 370 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), fullRank(), QUESO::FullEnvironment::readOptionsInputFile(), and ~BaseEnvironment().
ScopedPtr<GetPot>::Type QUESO::BaseEnvironment::m_input protected
Definition at line 380 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), and input().
MpiComm* QUESO::BaseEnvironment::m_inter0Comm protected
Definition at line 392 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), inter0Comm(), and ~BaseEnvironment().
int QUESO::BaseEnvironment::m_inter0CommSize protected
Definition at line 394 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct().
RawType_MPI_Group QUESO::BaseEnvironment::m_inter0Group protected
Definition at line 391 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct().
int QUESO::BaseEnvironment::m_inter0Rank protected
Definition at line 393 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), and inter0Rank().
bool QUESO::BaseEnvironment::m_optionsInputFileAccessState mutable protected
Definition at line 375 of file Environment.h.
Referenced by optionsInputFileName(), and setOptionsInputFileAccessState().
std::string QUESO::BaseEnvironment::m_optionsInputFileName protected
Definition at line 374 of file Environment.h.
Referenced by BaseEnvironment(), QUESO::FullEnvironment::construct(), optionsInputFileName(), QUESO::FullEnvironment::readOptionsInputFile(), and scanInputFileForMyOptions().
EnvOptionsValues* QUESO::BaseEnvironment::m_optionsObj protected
Definition at line 402 of file Environment.h.
Referenced by checkingLevel(), QUESO::FullEnvironment::construct(), displayVerbosity(), identifyingString(), numSubEnvironments(), platformName(), resetIdentifyingString(), subDisplayFileName(), and syncVerbosity().
RngBase* QUESO::BaseEnvironment::m_rngObject protected
Definition at line 397 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), resetSeed(), rngObject(), seed(), and ~BaseEnvironment().
MpiComm* QUESO::BaseEnvironment::m_selfComm protected
Definition at line 389 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), selfComm(), and ~BaseEnvironment().
MpiComm* QUESO::BaseEnvironment::m_subComm protected
Definition at line 385 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), subComm(), and ~BaseEnvironment().
int QUESO::BaseEnvironment::m_subCommSize protected
Definition at line 387 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct().
std::ofstream* QUESO::BaseEnvironment::m_subDisplayFile mutable protected
Definition at line 396 of file Environment.h.
Referenced by closeFile(), QUESO::FullEnvironment::construct(), openInputFile(), openOutputFile(), openUnifiedInputFile(), openUnifiedOutputFile(), subDisplayFile(), and ~BaseEnvironment().
RawType_MPI_Group QUESO::BaseEnvironment::m_subGroup protected
Definition at line 384 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), and subGroup().
unsigned int QUESO::BaseEnvironment::m_subId protected
Definition at line 382 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), and subId().
std::string QUESO::BaseEnvironment::m_subIdString protected
Definition at line 383 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), and subIdString().
int QUESO::BaseEnvironment::m_subRank protected
Definition at line 386 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), and subRank().
struct timeval QUESO::BaseEnvironment::m_timevalBegin protected
Definition at line 399 of file Environment.h.
Referenced by QUESO::FullEnvironment::construct(), and ~BaseEnvironment().
int QUESO::BaseEnvironment::m_worldRank protected
Definition at line 367 of file Environment.h.
Referenced by worldRank().
The documentation for this class was generated from the following files:
src/core/inc/Environment.h
src/core/src/Environment.C