queso-0.56.0: QUESO::Vector Class Reference
QUESO::Vector Class Reference abstract
Class for vector operations (virtual).
#include <Vector.h>
Public Member Functions
Constructor/Destructor methods
Vector (const BaseEnvironment &env, const Map &map)
Shaped Constructor.
virtual ~Vector ()
Virtual Destructor.
Environment and Map methods
const BaseEnvironment & env () const
const Map & map () const
unsigned int numOfProcsForStorage () const
Attribute methods
virtual unsigned int sizeLocal () const =0
Returns the local size of the vector.
virtual unsigned int sizeGlobal () const =0
Returns the global size of the vector.
Get/Set methods
virtual void cwSet (double value)=0
Component-wise set the values of the vector to value.
virtual void cwSetGaussian (double mean, double stdDev)=0
Component-wise set the values of the vector to a random number from a Gaussian distribution.
virtual void cwInvert ()=0
Component-wise invert the values of the vector.
I/O and Miscellaneous methods
virtual void sort ()=0
Sort the elements.
virtual void print (std::ostream &os) const =0
Print this vector.
void setPrintHorizontally (bool value) const
Determines whether vector should be printed horizontally.
bool getPrintHorizontally () const
Checks if vector is printed horizontally.
void setPrintScientific (bool value) const
Determines whether vector should be printed in Scientific Notation.
bool getPrintScientific () const
Checks if the vector should be printed in Scientific Notation.
Protected Member Functions
virtual void base_copy (const Vector &src)
Copies base data from vector src to this vector.
Protected Attributes
const BaseEnvironment & m_env
Environment variable.
const Map & m_map
Mapping variable.
bool m_printHorizontally
Flag for either or not print this matrix horizontally.
bool m_printScientific
Flag for either or not print this matrix in scientific notation.
Private Member Functions
Vector ()
Default Constructor.
Detailed Description
Class for vector operations (virtual).
Base vector class. The vector class is an abstract class designed to be used as a base class for different vector implementations (all actual vector classes in QUESO).
Definition at line 47 of file Vector.h.
Constructor & Destructor Documentation
QUESO::Vector::Vector (const BaseEnvironment & env, const Map & map)
Shaped Constructor.
Definition at line 31 of file Vector.C.
   :
   m_env              (env),
   m_map              (map),
   m_printHorizontally(true),
   m_printScientific  (false) // for compatibility with previous regression tests
 {
   //std::cout << "Entering Vector::constructor(env,map)" << std::endl;
   //std::cout << "In Vector::constructor(env,map)" // mox
   //          << ", m_map.NumMyElements() = " << m_map.NumMyElements()
   //          << std::endl;
   //std::cout << "Leaving Vector::constructor(env,map)" << std::endl;
 }
QUESO::Vector::~Vector () virtual
Virtual Destructor.
Definition at line 48 of file Vector.C.
 {
 }
QUESO::Vector::Vector () private
Default Constructor.
Member Function Documentation
void QUESO::Vector::base_copy (const Vector & src) protected virtual
Copies base data from vector src to this vector.
Definition at line 101 of file Vector.C.
References m_printHorizontally, and m_printScientific.
Referenced by QUESO::GslVector::copy().
 {
   //m_env               = src.env;
   //m_map               = src.map; // prudenci 2010-06-17
   m_printHorizontally = src.m_printHorizontally;
   m_printScientific   = src.m_printScientific;
   return;
 }
virtual void QUESO::Vector::cwInvert () pure virtual
Component-wise invert the values of the vector.
Implemented in QUESO::GslVector.
virtual void QUESO::Vector::cwSet (double value) pure virtual
Component-wise set the values of the vector to value.
Implemented in QUESO::GslVector.
virtual void QUESO::Vector::cwSetGaussian (double mean, double stdDev) pure virtual
Component-wise set the values of the vector to a random number from a Gaussian distribution.
Implemented in QUESO::GslVector.
const BaseEnvironment & QUESO::Vector::env () const
Definition at line 54 of file Vector.C.
References m_env.
Referenced by QUESO::matrixProduct().
 {
   return m_env;
 }
bool QUESO::Vector::getPrintHorizontally () const
Checks if vector is printed horizontally.
Definition at line 82 of file Vector.C.
References m_printHorizontally.
Referenced by QUESO::GslVector::subWriteContents().
 {
   return m_printHorizontally;
 }
bool QUESO::Vector::getPrintScientific () const
Checks if the vector should be printed in Scientific Notation.
Definition at line 95 of file Vector.C.
References m_printScientific.
Referenced by QUESO::GslVector::subWriteContents().
 {
   return m_printScientific;
 }
const Map & QUESO::Vector::map () const
Definition at line 61 of file Vector.C.
References m_map.
Referenced by QUESO::GslVector::GslVector(), and QUESO::matrixProduct().
 {
   return m_map;
 }
unsigned int QUESO::Vector::numOfProcsForStorage () const
Definition at line 68 of file Vector.C.
References QUESO::Map::Comm(), m_map, and QUESO::MpiComm::NumProc().
Referenced by QUESO::GslVector::subReadContents(), and QUESO::GslVector::subWriteContents().
 {
   return m_map.Comm().NumProc();
 }
virtual void QUESO::Vector::print (std::ostream & os) const pure virtual
Print this vector.
Implemented in QUESO::GslVector.
void QUESO::Vector::setPrintHorizontally (bool value) const
Determines whether vector should be printed horizontally.
Definition at line 75 of file Vector.C.
References m_printHorizontally.
Referenced by QUESO::GslVector::subWriteContents().
 {
   m_printHorizontally = value;
   return;
 }
void QUESO::Vector::setPrintScientific (bool value) const
Determines whether vector should be printed in Scientific Notation.
Definition at line 88 of file Vector.C.
References m_printScientific.
Referenced by QUESO::GslVector::subWriteContents().
 {
   m_printScientific = value;
   return;
 }
virtual unsigned int QUESO::Vector::sizeGlobal () const pure virtual
Returns the global size of the vector.
Implemented in QUESO::GslVector.
virtual unsigned int QUESO::Vector::sizeLocal () const pure virtual
Returns the local size of the vector.
Implemented in QUESO::GslVector.
virtual void QUESO::Vector::sort () pure virtual
Sort the elements.
Implemented in QUESO::GslVector.
Member Data Documentation
const BaseEnvironment& QUESO::Vector::m_env protected
Environment variable.
Definition at line 117 of file Vector.h.
Referenced by QUESO::GslVector::cwSetBeta(), QUESO::GslVector::cwSetGamma(), QUESO::GslVector::cwSetGaussian(), QUESO::GslVector::cwSetInverseGamma(), QUESO::GslVector::cwSetUniform(), env(), QUESO::GslVector::subReadContents(), and QUESO::GslVector::subWriteContents().
const Map& QUESO::Vector::m_map protected
Mapping variable.
Definition at line 126 of file Vector.h.
Referenced by QUESO::GslVector::GslVector(), map(), numOfProcsForStorage(), QUESO::GslVector::sizeGlobal(), and QUESO::GslVector::sizeLocal().
bool QUESO::Vector::m_printHorizontally mutable protected
Flag for either or not print this matrix horizontally.
Definition at line 130 of file Vector.h.
Referenced by base_copy(), getPrintHorizontally(), QUESO::GslVector::print(), and setPrintHorizontally().
bool QUESO::Vector::m_printScientific mutable protected
Flag for either or not print this matrix in scientific notation.
Definition at line 133 of file Vector.h.
Referenced by base_copy(), getPrintScientific(), QUESO::GslVector::print(), and setPrintScientific().
The documentation for this class was generated from the following files:
src/core/inc/Vector.h
src/core/src/Vector.C