queso-0.56.0: QUESO::VectorSpace< V, M > Class Template Reference
QUESO::VectorSpace< V, M > Class Template Reference
A class representing a vector space.
#include <VectorSet.h>
Public Member Functions
template<>
GslVector * newVector () const
template<>
GslVector * newVector (double value) const
template<>
GslMatrix * newMatrix () const
template<>
GslMatrix * newDiagMatrix (double diagValue) const
Constructor/Destructor methods
VectorSpace (const BaseEnvironment &env, const char *prefix, unsigned int dimGlobalValue, const std::vector< std::string > *componentsNamesVec)
Shaped constructor.
VectorSpace (const VectorSpace< V, M > &aux)
Copy constructor.
~VectorSpace ()
Destructor.
Attribute methods
const BaseEnvironment & env () const
Environment.
const Map & map () const
Map.
unsigned int numOfProcsForStorage () const
Returns total number of processes.
unsigned int dimLocal () const
unsigned int dimGlobal () const
unsigned int globalIdOfFirstComponent () const
Mathematical methods
const V & zeroVector () const
Returns a vector filled with zeros.
V * newVector () const
Creates an empty vector of size given by Map& map. See template specialization.
V * newVector (double value) const
Creates a vector of size given by Map& map and all values give by value. See template specialization.
V * newVector (const V &v) const
Creates vector as a copy of another.
M * newMatrix () const
Creates an empty matrix of size given by Map& map. See template specialization.
M * newDiagMatrix (const V &v) const
Creates a diagonal matrix with the elements and size of vector v.
M * newDiagMatrix (double diagValue) const
Creates a diagonal matrix with the elements diagValue and size given by Map& map. See template specialization.
M * newProposalMatrix (const V *varVec, const V *auxVec) const
Creates a diagonal matrix conditionally to values from vector varVec, guaranteeing that its values are neither 0, NAN nor INFINITY.
const VectorSpace< V, M > & vectorSpace () const
Accessor method to this. Vector space to which this vector set belongs to.
bool contains (const V &vec) const
Whether vector contains vector vec.
void centroid (V &vec) const
The (INFINITY/nonexistent) centroid of the space.
void moments (M &vec) const
The (INFINITY/nonexistent) matrix of second moments of the space.
const DistArray< std::string > * componentsNamesArray () const
Access to private attribute m_componentsNamesArray, which is an instance of DistArray.
const std::vector< std::string > * componentsNamesVec () const
Access to private attribute m_componentsNamesVec.
const std::string & localComponentName (unsigned int localComponentId) const
Returns the local component names.
I/O methods
void printComponentsNames (std::ostream &os, bool printHorizontally) const
Prints the local component names.
void print (std::ostream &os) const
Prints only a message.
Public Member Functions inherited from QUESO::VectorSet< V, M >
VectorSet (const BaseEnvironment &env, const char *prefix, double volume)
Shaped constructor.
virtual ~VectorSet ()
Virtual destructor.
const BaseEnvironment & env () const
Environment. Access to private attribute m_env.
const std::string & prefix () const
Access to private attribute m_prefix.
double volume () const
Set volume; access to private attribute m_volume.
Protected Member Functions
Map * newMap ()
Creates a new map. See template specialization.
template<>
Map * newMap ()
Protected Attributes
unsigned int m_dimGlobal
Global dimension.
const Map * m_map
Map.
unsigned int m_dimLocal
Local dimension (number of elements owned by the calling processor.).
DistArray< std::string > * m_componentsNamesArray
Array of strings of the type DistArray to store the names of the components.
DistArray< std::string > * m_componentsNamesVec
Vector of strings of the type DistArray to store the names of the components.
std::string m_emptyComponentName
Empty string for the components names.
V * m_zeroVector
A vector of all elements equal to zero.
Protected Attributes inherited from QUESO::VectorSet< V, M >
const BaseEnvironment & m_env
std::string m_prefix
double m_volume
Private Member Functions
VectorSpace ()
Default constructor.
Detailed Description
template<class V, class M>
class QUESO::VectorSpace< V, M >
A class representing a vector space.
Template classes V and M are to represent a vector class and a matrix class respectively. Currently (as of version 0.46.0) QUESO has matrix and vector classes implemented using either GSL or Trilinos-Teuchos libraries.
Definition at line 49 of file VectorSet.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::VectorSpace< V, M >::VectorSpace (const BaseEnvironment & env, const char * prefix, unsigned int dimGlobalValue, const std::vector< std::string > * componentsNamesVec)
Shaped constructor.
Construct a vector space with QUESO environment env and of dimension dimGlobalValue.
Definition at line 38 of file VectorSpace.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::VectorSpace< V, M >::globalIdOfFirstComponent(), QUESO::DistArray< T >::GlobalLength(), QUESO::VectorSpace< V, M >::m_componentsNamesArray, QUESO::VectorSpace< V, M >::m_dimGlobal, QUESO::VectorSpace< V, M >::m_dimLocal, QUESO::VectorSet< V, M >::m_env, QUESO::VectorSpace< V, M >::m_map, QUESO::VectorSet< V, M >::m_prefix, QUESO::VectorSpace< V, M >::m_zeroVector, QUESO::DistArray< T >::MyLength(), QUESO::Map::NumGlobalElements(), queso_require_equal_to_msg, and QUESO::BaseEnvironment::subDisplayFile().
   : VectorSet<V,M> (env,((std::string)(prefix) + "space_").c_str(),INFINITY),
     m_dimGlobal(dimGlobalValue),
     m_map(newMap()),
     m_dimLocal(m_map->NumMyElements()),
     m_componentsNamesArray(NULL),
     m_componentsNamesVec(NULL),
     m_emptyComponentName(""),
     m_zeroVector(new V(m_env,*m_map))
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering VectorSpace<V,M>::constructor(1)"
                             << ", with m_prefix = "                << m_prefix
                             << "\n  m_zeroVector->sizeGlobal() = " << m_zeroVector->sizeGlobal()
                             << "\n  m_dimGlobal                = " << m_dimGlobal
                             << "\n  m_zeroVector->sizeLocal()  = " << m_zeroVector->sizeLocal()
                             << "\n  m_dimLocal                 = " << m_dimLocal
                             << "\n  m_map->NumGlobalElements() = " << m_map->NumGlobalElements()
                             << "\n  componentsNamesVec         = " << componentsNamesVec
                             << std::endl;
   }
   if (m_zeroVector->sizeGlobal() != m_dimGlobal) {
     std::cerr << "In VectorSpace<V,M>::constructor(1)"
               << ", with m_prefix = " << m_prefix
               << ": m_zeroVector->sizeGlobal() = " << m_zeroVector->sizeGlobal()
               << ", m_dimGlobal = "                << m_dimGlobal
               << std::endl;
   }
   queso_require_equal_to_msg(m_zeroVector->sizeGlobal(), m_dimGlobal, "global size of 'm_zeroVector' is not equal to m_dimGlobal");
   if (m_zeroVector->sizeLocal() != m_dimLocal) {
     std::cerr << "In VectorSpace<V,M>::constructor(1)"
               << ", with m_prefix = " << m_prefix
               << ": m_zeroVector->sizeLocal() = " << m_zeroVector->sizeLocal()
               << ", m_dimLocal = "                << m_dimLocal
               << std::endl;
   }
   queso_require_equal_to_msg(m_zeroVector->sizeLocal(), m_dimLocal, "local size of 'm_zeroVector' is not equal to m_dimLocal");
   if (componentsNamesVec != NULL) {
     queso_require_equal_to_msg(componentsNamesVec->size(), (size_t) m_dimGlobal, "global size of 'componentsNames' is not equal to m_dimGlobal");
     m_componentsNamesArray = new DistArray<std::string>(*m_map,1);
     unsigned int myFirstId = this->globalIdOfFirstComponent();
     for (unsigned int i = 0; i < m_dimLocal; ++i) {
       (*m_componentsNamesArray)(i,0) = (*componentsNamesVec)[myFirstId+i];
     }
     queso_require_equal_to_msg(m_componentsNamesArray->GlobalLength(), (int) m_dimGlobal, "global size of 'm_componentsNamesArray' is not equal to m_dimGlobal");
     queso_require_equal_to_msg(m_componentsNamesArray->MyLength(), (int) m_dimLocal, "local size of 'm_componentsNamesArray' is not equal to m_dimLocal");
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving VectorSpace<V,M>::constructor(1)"
                             << ", with m_prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V, class M> QUESO::VectorSpace< V, M >::VectorSpace (const VectorSpace< V, M > & aux)
Copy constructor.
Definition at line 102 of file VectorSpace.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::VectorSpace< V, M >::m_componentsNamesArray, QUESO::VectorSpace< V, M >::m_componentsNamesVec, QUESO::VectorSet< V, M >::m_env, and QUESO::BaseEnvironment::subDisplayFile().
   : VectorSet<V,M>(aux.env(),((std::string)(aux.m_prefix)).c_str(),INFINITY),
     m_dimGlobal(aux.m_dimGlobal),
     m_map(newMap()),
     m_dimLocal(m_map->NumMyElements()),
     m_componentsNamesArray(NULL),
     m_componentsNamesVec(NULL),
     m_emptyComponentName(""),
     m_zeroVector(new V(m_env,*m_map))
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering VectorSpace<V,M>::constructor(2)"
                             << ": aux.m_componentsNamesArray = " << aux.m_componentsNamesArray
                             << ", aux.m_componentsNamesVec = "   << aux.m_componentsNamesVec
                             << std::endl;
   }
   if (aux.m_componentsNamesArray != NULL) {
     m_componentsNamesArray = new DistArray<std::string>(*(aux.m_componentsNamesArray));
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving VectorSpace<V,M>::constructor(2)"
                             << std::endl;
   }
 }
template<class V , class M > QUESO::VectorSpace< V, M >::~VectorSpace ()
Destructor.
Definition at line 131 of file VectorSpace.C.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering VectorSpace<V,M>::destructor()"
                             << std::endl;
   }
   if (m_zeroVector           != NULL) delete m_zeroVector;
   if (m_componentsNamesVec   != NULL) delete m_componentsNamesVec;
   if (m_componentsNamesArray != NULL) delete m_componentsNamesArray;
   if (m_map                  != NULL) delete m_map;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving VectorSpace<V,M>::destructor()"
                             << std::endl;
   }
 }
template<class V, class M> QUESO::VectorSpace< V, M >::VectorSpace () private
Default constructor.
Member Function Documentation
template<class V, class M > void QUESO::VectorSpace< V, M >::centroid (V & vec) const virtual
The (INFINITY/nonexistent) centroid of the space.
Implements QUESO::VectorSet< V, M >.
Definition at line 264 of file VectorSpace.C.
References queso_assert_equal_to.
 {
   queso_assert_equal_to (m_dimLocal, vec.sizeLocal());
   for (unsigned int i = 0; i < m_dimLocal; ++i) {
     vec[i] = INFINITY;
   }
 }
template<class V , class M > const DistArray< std::string > * QUESO::VectorSpace< V, M >::componentsNamesArray () const
Access to private attribute m_componentsNamesArray, which is an instance of DistArray.
Definition at line 286 of file VectorSpace.C.
 {
   return m_componentsNamesArray;
 }
template<class V, class M> const std::vector<std::string>* QUESO::VectorSpace< V, M >::componentsNamesVec () const
Access to private attribute m_componentsNamesVec.
template<class V, class M > bool QUESO::VectorSpace< V, M >::contains (const V & vec) const virtual
Whether vector contains vector vec.
Implements QUESO::VectorSet< V, M >.
Definition at line 258 of file VectorSpace.C.
 {
   return true;
 }
template<class V , class M > unsigned int QUESO::VectorSpace< V, M >::dimGlobal () const
Definition at line 176 of file VectorSpace.C.
Referenced by QUESO::ComputeCovCorrMatricesBetweenVectorSequences(), QUESO::GcmJointTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointTildeInfo(), QUESO::GPMSAFactory< V, M >::GPMSAFactory(), and QUESO::InstantiateIntersection().
 {
   return m_dimGlobal;
 }
template<class V , class M > unsigned int QUESO::VectorSpace< V, M >::dimLocal () const
Definition at line 170 of file VectorSpace.C.
Referenced by QUESO::BoxSubset< V, M >::BoxSubset(), QUESO::ComputeCovCorrMatricesBetweenVectorSequences(), QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::ExponentialMatrixCovarianceFunction(), QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo(), QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointInfo(), QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationInfo(), QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo(), QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel(), QUESO::GPMSAEmulator< V, M >::GPMSAEmulator(), QUESO::SimulationModel< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationModel(), and QUESO::StatisticalInverseProblem< P_V, P_M >::StatisticalInverseProblem().
 {
   return m_dimLocal;
 }
template<class V , class M > const BaseEnvironment & QUESO::VectorSpace< V, M >::env () const
Environment.
Definition at line 151 of file VectorSpace.C.
Referenced by QUESO::InstantiateIntersection().
 {
   return m_env;
 }
template<class V , class M > unsigned int QUESO::VectorSpace< V, M >::globalIdOfFirstComponent () const
Definition at line 182 of file VectorSpace.C.
Referenced by QUESO::VectorSpace< V, M >::VectorSpace().
 {
   return m_map->MinMyGID();
 }
template<class V , class M > const std::string & QUESO::VectorSpace< V, M >::localComponentName (unsigned int localComponentId) const
Returns the local component names.
Definition at line 292 of file VectorSpace.C.
References queso_require_less_equal_msg.
 {
   if (m_componentsNamesArray == NULL) return m_emptyComponentName;
   queso_require_less_equal_msg(localComponentId, m_dimLocal, "localComponentId is too big");
 //return (*(const_cast<DistArray<std::string>*>(m_componentsNamesArray)))(localComponentId,0);
   return (*m_componentsNamesArray)(localComponentId,0);
 }
template<class V , class M > const Map & QUESO::VectorSpace< V, M >::map () const
Map.
Definition at line 157 of file VectorSpace.C.
References queso_require_msg.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel(), QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo(), QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointInfo(), QUESO::GcmJointTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointTildeInfo(), QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationInfo(), QUESO::GcmSimulationTildeInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationTildeInfo(), QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo(), QUESO::GPMSAFactory< V, M >::GPMSAFactory(), and QUESO::SimulationModel< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationModel().
 {
   queso_require_msg(m_map, "m_map is still NULL");
   return *m_map;
 }
template<class V , class M> void QUESO::VectorSpace< V, M >::moments (M & vec) const virtual
The (INFINITY/nonexistent) matrix of second moments of the space.
Implements QUESO::VectorSet< V, M >.
Definition at line 274 of file VectorSpace.C.
References queso_assert_equal_to.
 {
   queso_assert_equal_to (m_dimLocal, mat.numCols());
   mat.zeroLower();
   mat.zeroUpper();
   for (unsigned int i = 0; i < m_dimLocal; ++i) {
     mat(i,i) = INFINITY;
   }
 }
template<> GslMatrix * QUESO::VectorSpace< GslVector, GslMatrix >::newDiagMatrix (double diagValue) const
Definition at line 60 of file GslVectorSpace.C.
 {
   return new GslMatrix(m_env,*m_map,diagValue);
 }
template<class V, class M > M * QUESO::VectorSpace< V, M >::newDiagMatrix (const V & v) const
Creates a diagonal matrix with the elements and size of vector v.
Definition at line 205 of file VectorSpace.C.
 {
   if (v.sizeGlobal() != m_dimGlobal) return NULL;
   if (v.sizeLocal () != m_dimLocal ) return NULL;
   return new M(v);
 }
template<class V, class M> M* QUESO::VectorSpace< V, M >::newDiagMatrix (double diagValue) const
Creates a diagonal matrix with the elements diagValue and size given by Map& map. See template specialization.
template<> Map * QUESO::VectorSpace< GslVector, GslMatrix >::newMap () protected
Definition at line 32 of file GslVectorSpace.C.
 {
   return new Map(m_dimGlobal,0,m_env.selfComm());
 }
template<class V, class M> Map* QUESO::VectorSpace< V, M >::newMap () protected
Creates a new map. See template specialization.
template<> GslMatrix * QUESO::VectorSpace< GslVector, GslMatrix >::newMatrix () const
Definition at line 53 of file GslVectorSpace.C.
 {
   return new GslMatrix(m_env,*m_map,this->dimGlobal());
 }
template<class V, class M> M* QUESO::VectorSpace< V, M >::newMatrix () const
Creates an empty matrix of size given by Map& map. See template specialization.
template<class V, class M > M * QUESO::VectorSpace< V, M >::newProposalMatrix (const V * varVec, const V * auxVec) const
Creates a diagonal matrix conditionally to values from vector varVec, guaranteeing that its values are neither 0, NAN nor INFINITY.
If varVec[i] is either 0, NAN or INFINITY, then this method tries to assign the value (*auxVec)[i])^2 to matrix(i,i). Case (*auxVec)[i])^2 is either NAN or INFINITY, then matrix(i,i)=1.
Definition at line 214 of file VectorSpace.C.
 {
   V tmpVec(*m_zeroVector);
   for (unsigned int i = 0; i < m_dimLocal; ++i) {
     double variance = INFINITY;
     if (varVec) variance = (*varVec)[i];
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In VectorSpace<V,M>::newProposalMatrix()"
                               << ": i = "        << i
                               << ", variance = " << variance
                               << std::endl;
     }
     if ((variance == INFINITY) ||
         (variance == NAN     )) {
       if (auxVec) {
         tmpVec[i] = std::pow( fabs((*auxVec)[i])*0.05,2. );
         if ((tmpVec[i] == 0.      ) ||
             (tmpVec[i] == INFINITY) ||
             (tmpVec[i] == NAN     )) {
           tmpVec[i] = 1.;
         }
       }
       else {
         tmpVec[i] = 1.;
       }
     }
     else if (variance == 0.) {
       tmpVec[i] = 1.;
     }
     else {
       tmpVec[i] = variance;
     }
   }
   return newDiagMatrix(tmpVec);
 }
template<> GslVector * QUESO::VectorSpace< GslVector, GslMatrix >::newVector () const
Definition at line 39 of file GslVectorSpace.C.
 {
   return new GslVector(m_env,*m_map);
 }
template<> GslVector * QUESO::VectorSpace< GslVector, GslMatrix >::newVector (double value) const
Definition at line 46 of file GslVectorSpace.C.
 {
   return new GslVector(m_env,*m_map,value);
 }
template<class V, class M> V* QUESO::VectorSpace< V, M >::newVector () const
Creates an empty vector of size given by Map& map. See template specialization.
template<class V, class M> V* QUESO::VectorSpace< V, M >::newVector (double value) const
Creates a vector of size given by Map& map and all values give by value. See template specialization.
template<class V, class M > V * QUESO::VectorSpace< V, M >::newVector (const V & v) const
Creates vector as a copy of another.
Definition at line 196 of file VectorSpace.C.
 {
   if (v.sizeGlobal() != m_dimGlobal) return NULL;
   if (v.sizeLocal () != m_dimLocal ) return NULL;
   return new V(v);
 }
template<class V , class M > unsigned int QUESO::VectorSpace< V, M >::numOfProcsForStorage () const
Returns total number of processes.
Definition at line 164 of file VectorSpace.C.
Referenced by QUESO::ComputeCovCorrMatricesBetweenVectorRvs(), and QUESO::ComputeCovCorrMatricesBetweenVectorSequences().
 {
   return m_map->Comm().NumProc();
 }
template<class V , class M > void QUESO::VectorSpace< V, M >::print (std::ostream & os) const virtual
Prints only a message.
Reimplemented from QUESO::VectorSet< V, M >.
Definition at line 324 of file VectorSpace.C.
 {
   os << "In VectorSpace<V,M>::print()"
      << ": nothing to be printed" << std::endl;
   return;
 }
template<class V , class M > void QUESO::VectorSpace< V, M >::printComponentsNames (std::ostream & os, bool printHorizontally) const
Prints the local component names.
Definition at line 304 of file VectorSpace.C.
 {
   if (printHorizontally) {
     for (unsigned int i = 0; i < this->dimLocal(); ++i) {
       os << "'" << this->localComponentName(i) << "'"
          << " ";
     }
   }
   else {
     for (unsigned int i = 0; i < this->dimLocal(); ++i) {
       os << "'" << this->localComponentName(i) << "'"
          << std::endl;
     }
   }
   return;
 }
template<class V , class M > const VectorSpace< V, M > & QUESO::VectorSpace< V, M >::vectorSpace () const virtual
Accessor method to this. Vector space to which this vector set belongs to.
It is virtual in the base class 'VectorSet'
Implements QUESO::VectorSet< V, M >.
Definition at line 252 of file VectorSpace.C.
 {
   return *this;
 }
template<class V , class M > const V & QUESO::VectorSpace< V, M >::zeroVector () const
Returns a vector filled with zeros.
Definition at line 189 of file VectorSpace.C.
References queso_require_msg.
Referenced by QUESO::ComputeCovCorrMatricesBetweenVectorRvs(), QUESO::ComputeCovCorrMatricesBetweenVectorSequences(), QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo(), QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointInfo(), QUESO::GcmJointTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmJointTildeInfo(), QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationInfo(), QUESO::GcmSimulationTildeInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::GcmSimulationTildeInfo(), QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZTildeInfo(), and QUESO::SimulationModel< S_V, S_M, P_V, P_M, Q_V, Q_M >::SimulationModel().
 {
   queso_require_msg(m_zeroVector, "m_zeroVector is still NULL");
   return *m_zeroVector;
 }
Member Data Documentation
template<class V, class M> DistArray<std::string>* QUESO::VectorSpace< V, M >::m_componentsNamesArray protected
Array of strings of the type DistArray to store the names of the components.
Definition at line 162 of file VectorSpace.h.
Referenced by QUESO::VectorSpace< V, M >::VectorSpace().
template<class V, class M> DistArray<std::string>* QUESO::VectorSpace< V, M >::m_componentsNamesVec protected
Vector of strings of the type DistArray to store the names of the components.
Definition at line 165 of file VectorSpace.h.
Referenced by QUESO::VectorSpace< V, M >::VectorSpace().
template<class V, class M> unsigned int QUESO::VectorSpace< V, M >::m_dimGlobal protected
Global dimension.
Definition at line 153 of file VectorSpace.h.
Referenced by QUESO::VectorSpace< V, M >::VectorSpace().
template<class V, class M> unsigned int QUESO::VectorSpace< V, M >::m_dimLocal protected
Local dimension (number of elements owned by the calling processor.).
Definition at line 159 of file VectorSpace.h.
Referenced by QUESO::VectorSpace< V, M >::VectorSpace().
template<class V, class M> std::string QUESO::VectorSpace< V, M >::m_emptyComponentName protected
Empty string for the components names.
Definition at line 168 of file VectorSpace.h.
template<class V, class M> const Map* QUESO::VectorSpace< V, M >::m_map protected
Map.
Definition at line 156 of file VectorSpace.h.
Referenced by QUESO::VectorSpace< V, M >::VectorSpace().
template<class V, class M> V* QUESO::VectorSpace< V, M >::m_zeroVector protected
A vector of all elements equal to zero.
Definition at line 171 of file VectorSpace.h.
Referenced by QUESO::VectorSpace< V, M >::VectorSpace().
The documentation for this class was generated from the following files:
src/basic/inc/VectorSet.h
src/basic/inc/VectorSpace.h
src/basic/src/VectorSpace.C