queso-0.53.0: QUESO::GaussianVectorMdf< V, M > Class Template Reference
QUESO::GaussianVectorMdf< V, M > Class Template Reference
TODO: A class for handling Gaussian MDFs.
#include <GaussianVectorMdf.h>
Public Member Functions
Constructor/Destructor methods
GaussianVectorMdf (const char *prefix, const VectorSet< V, M > &domainSet, const V &domainExpectedValues, const V &domainVarianceValues)
TODO: Constructor.
GaussianVectorMdf (const char *prefix, const VectorSet< V, M > &domainSet, const V &domainExpectedValues, const M &covMatrix)
TODO: Constructor.
~GaussianVectorMdf ()
Destructor.
Mathematical method
void values (const V &paramValues, V &mdfVec) const
TODO: Returns the values of the vector CDF at each element of paramValues.
I/O method
void print (std::ostream &os) const
TODO: Prints the vector CDF.
Public Member Functions inherited from QUESO::BaseVectorMdf< V, M >
BaseVectorMdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseVectorMdf ()
Virtual destructor.
const VectorSet< V, M > & domainSet () const
Returns the domain set; access to protected attribute m_domainSet.
Protected Member Functions
void commonConstructor ()
Protected Attributes
const M * m_covMatrix
Protected Attributes inherited from QUESO::BaseVectorMdf< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::GaussianVectorMdf< V, M >
TODO: A class for handling Gaussian MDFs.
This class will implement a Gaussian vector marginal density function function (MDF).
Todo:
: Implement me!
Definition at line 50 of file GaussianVectorMdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::GaussianVectorMdf< V, M >::GaussianVectorMdf (const char * prefix, const VectorSet< V, M > & domainSet, const V & domainExpectedValues, const V & domainVarianceValues)
TODO: Constructor.
Todo:
: implement me! This method calls commonConstructor() which is not yet implemented. Instantiates an object of the class given a prefix, the domain set, and the domain mean and expected values.
Definition at line 31 of file GaussianVectorMdf.C.
References QUESO::GaussianVectorMdf< V, M >::commonConstructor(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorMdf< V, M >::m_env, QUESO::BaseVectorMdf< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorMdf<V,M>(prefix,domainSet),
   m_covMatrix              (m_domainSet.newDiagMatrix(domainVarianceValues*domainVarianceValues))
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering GaussianVectorMdf<V,M>::constructor() [1]"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving GaussianVectorMdf<V,M>::constructor() [1]"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
 }
template<class V , class M > QUESO::GaussianVectorMdf< V, M >::GaussianVectorMdf (const char * prefix, const VectorSet< V, M > & domainSet, const V & domainExpectedValues, const M & covMatrix)
TODO: Constructor.
Todo:
: implement me! This method calls commonConstructor() which is not yet implemented. Instantiates an object of the class given a prefix, the domain set, and the domain mean and covariance matrix.
Definition at line 56 of file GaussianVectorMdf.C.
References QUESO::GaussianVectorMdf< V, M >::commonConstructor(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorMdf< V, M >::m_env, QUESO::BaseVectorMdf< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorMdf<V,M>(prefix,domainSet),
   m_covMatrix              (new M(covMatrix))
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering GaussianVectorMdf<V,M>::constructor() [2]"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving GaussianVectorMdf<V,M>::constructor() [2]"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
 }
template<class V , class M > QUESO::GaussianVectorMdf< V, M >::~GaussianVectorMdf ()
Destructor.
Definition at line 81 of file GaussianVectorMdf.C.
 {
   delete m_covMatrix;
 }
Member Function Documentation
template<class V , class M > void QUESO::GaussianVectorMdf< V, M >::commonConstructor () protected
Definition at line 105 of file GaussianVectorMdf.C.
References queso_error_msg.
Referenced by QUESO::GaussianVectorMdf< V, M >::GaussianVectorMdf().
 {
   queso_error_msg("incomplete code");
   return;
 }
template<class V , class M > void QUESO::GaussianVectorMdf< V, M >::print (std::ostream & os) const virtual
TODO: Prints the vector CDF.
Todo:
: implement me!
Implements QUESO::BaseVectorMdf< V, M >.
Definition at line 98 of file GaussianVectorMdf.C.
 {
   return;
 }
template<class V , class M > void QUESO::GaussianVectorMdf< V, M >::values (const V & paramValues, V & mdfVec) const virtual
TODO: Returns the values of the vector CDF at each element of paramValues.
Todo:
: implement me!
Implements QUESO::BaseVectorMdf< V, M >.
Definition at line 88 of file GaussianVectorMdf.C.
References queso_error_msg.
 {
   queso_error_msg("incomplete code");
   return;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> const M* QUESO::GaussianVectorMdf< V, M >::m_covMatrix protected
Definition at line 89 of file GaussianVectorMdf.h.
The documentation for this class was generated from the following files:
src/stats/inc/GaussianVectorMdf.h
src/stats/src/GaussianVectorMdf.C