queso-0.53.0: QUESO::BoostInputOptionsParser Class Reference
QUESO::BoostInputOptionsParser Class Reference
#include <BoostInputOptionsParser.h>
Public Member Functions
BoostInputOptionsParser (const std::string &filename)
Constructor that parses file filename.
BoostInputOptionsParser ()
Default constructor that sets m_filename to "".
virtual ~BoostInputOptionsParser ()
Destructor.
void scanInputFile ()
This is the method that parses the input file.
template<class T >
void registerOption (std::string name, T defaultValue, std::string description)
Call this to register an option with the parser.
void registerOption (std::string name, std::string description)
For flags without values. Like a help message, for example.
template<class T >
void getOption (std::string &name, T &value)
Get option name from the parser and set value to the parsed value.
template<>
void getOption (std::string &name, std::set< unsigned int, std::less< unsigned int >, std::allocator< unsigned int > > &value)
Public Member Functions inherited from QUESO::BaseInputOptionsParser
BaseInputOptionsParser ()
Default constructor.
virtual ~BaseInputOptionsParser ()
Destructor.
Protected Attributes
const std::string & m_filename
ScopedPtr
< boost::program_options::options_description >
::Type m_optionsDescription
ScopedPtr
< boost::program_options::variables_map >
::Type m_optionsMap
Private Attributes
bool m_scannedInputFile
Friends
std::ostream & operator<< (std::ostream &os, const BoostInputOptionsParser &parser)
Helpful stream operator for printing the parser state.
Detailed Description
Definition at line 43 of file BoostInputOptionsParser.h.
Constructor & Destructor Documentation
QUESO::BoostInputOptionsParser::BoostInputOptionsParser (const std::string & filename)
Constructor that parses file filename.
Definition at line 32 of file BoostInputOptionsParser.C.
   :
     m_filename(filename),
     m_optionsDescription(new boost::program_options::options_description("Input options")),
     m_optionsMap(new boost::program_options::variables_map()),
     m_scannedInputFile(false)
 {
 }
QUESO::BoostInputOptionsParser::BoostInputOptionsParser ()
Default constructor that sets m_filename to "".
The use-case that options are not read in from a file but are instead wholly provided by the user.
Definition at line 41 of file BoostInputOptionsParser.C.
   :
     m_filename(""),
     m_optionsDescription(new boost::program_options::options_description("Input options")),
     m_optionsMap(new boost::program_options::variables_map()),
     m_scannedInputFile(false)
 {
 }
QUESO::BoostInputOptionsParser::~BoostInputOptionsParser () virtual
Destructor.
Deletes m_optionsDescription
Definition at line 50 of file BoostInputOptionsParser.C.
 {
   // Do nothing
 }
Member Function Documentation
template<typename T > void QUESO::BoostInputOptionsParser::getOption (std::string & name, T & value)
Get option name from the parser and set value to the parsed value.
Definition at line 98 of file BoostInputOptionsParser.C.
References m_scannedInputFile.
Referenced by QUESO::EmOptionsValues::EmOptionsValues(), QUESO::EnvOptionsValues::EnvOptionsValues(), QUESO::GcmOptionsValues::GcmOptionsValues(), QUESO::MLSamplingLevelOptions::getAllOptions(), QUESO::GPMSAOptions::GPMSAOptions(), QUESO::InfiniteDimensionalMCMCSamplerOptions::InfiniteDimensionalMCMCSamplerOptions(), QUESO::McOptionsValues::McOptionsValues(), QUESO::MhOptionsValues::MhOptionsValues(), QUESO::MLSamplingOptions::MLSamplingOptions(), QUESO::SfpOptionsValues::SfpOptionsValues(), QUESO::SipOptionsValues::SipOptionsValues(), and QUESO::SmOptionsValues::SmOptionsValues().
 {
   if (m_scannedInputFile) {
     value = (*m_optionsMap)[name].as<T>();
   }
 }
template<> template void QUESO::BoostInputOptionsParser::getOption< std::set< unsigned int, std::less< unsigned int >, std::allocator< unsigned int > > > (std::string & name, std::set< unsigned int, std::less< unsigned int >, std::allocator< unsigned int > > & value)
Definition at line 107 of file BoostInputOptionsParser.C.
References m_scannedInputFile, and QUESO::MiscReadDoublesFromString().
 {
   if (m_scannedInputFile) {
     // Clear before putting things in it
     value.clear();
     // Get the option as a string
     // DM:  Why do it this way?  Doesn't boost support vectors as input
     //      options?
     std::vector<double> tmpVec(0, 0.0);
     std::string optionValue;
     this->getOption<std::string>(name, optionValue);
     MiscReadDoublesFromString(optionValue, tmpVec);
     for (unsigned int i = 0; i < tmpVec.size(); i++) {
       value.insert((unsigned int) tmpVec[i]);  // Why cast?!
     }
   }
 }
template<typename T > void QUESO::BoostInputOptionsParser::registerOption (std::string name, T defaultValue, std::string description)
Call this to register an option with the parser.
The name of the option to look for in the input file is given by name is given by. If no option is present in the input file, then use defaultValue is used for the default value for the option. Describe the option with a helpful message using description.
Definition at line 79 of file BoostInputOptionsParser.C.
References m_optionsDescription.
Referenced by QUESO::MLSamplingLevelOptions::defineAllOptions(), QUESO::EmOptionsValues::EmOptionsValues(), QUESO::EnvOptionsValues::EnvOptionsValues(), QUESO::GcmOptionsValues::GcmOptionsValues(), QUESO::GPMSAOptions::GPMSAOptions(), QUESO::InfiniteDimensionalMCMCSamplerOptions::InfiniteDimensionalMCMCSamplerOptions(), QUESO::McOptionsValues::McOptionsValues(), QUESO::MhOptionsValues::MhOptionsValues(), QUESO::MLSamplingOptions::MLSamplingOptions(), QUESO::SfpOptionsValues::SfpOptionsValues(), QUESO::SipOptionsValues::SipOptionsValues(), and QUESO::SmOptionsValues::SmOptionsValues().
 {
   m_optionsDescription->add_options()
     (name.c_str(),
      boost::program_options::value<T>()->default_value(defaultValue),
      description.c_str());
 }
void QUESO::BoostInputOptionsParser::registerOption (std::string name, std::string description)
For flags without values. Like a help message, for example.
Definition at line 89 of file BoostInputOptionsParser.C.
References m_optionsDescription.
 {
   m_optionsDescription->add_options()
     (name.c_str(),
      description.c_str());
 }
void QUESO::BoostInputOptionsParser::scanInputFile ()
This is the method that parses the input file.
It parses the input file and sets the m_optionsMap member.
Definition at line 56 of file BoostInputOptionsParser.C.
References m_filename, m_optionsDescription, m_optionsMap, m_scannedInputFile, and queso_require_msg.
Referenced by QUESO::EmOptionsValues::EmOptionsValues(), QUESO::EnvOptionsValues::EnvOptionsValues(), QUESO::GcmOptionsValues::GcmOptionsValues(), QUESO::GPMSAOptions::GPMSAOptions(), QUESO::InfiniteDimensionalMCMCSamplerOptions::InfiniteDimensionalMCMCSamplerOptions(), QUESO::McOptionsValues::McOptionsValues(), QUESO::MhOptionsValues::MhOptionsValues(), QUESO::MLSamplingLevelOptions::MLSamplingLevelOptions(), QUESO::MLSamplingOptions::MLSamplingOptions(), QUESO::MLSamplingLevelOptions::scanOptionsValues(), QUESO::SfpOptionsValues::SfpOptionsValues(), QUESO::SipOptionsValues::SipOptionsValues(), and QUESO::SmOptionsValues::SmOptionsValues().
 {
   queso_require_msg(m_optionsDescription, "m_optionsDescription variable is NULL");
   // If it's the empty string then the defaults are used
   if (m_filename != "") {
     std::ifstream ifs;
     ifs.open(m_filename.c_str());
     queso_require_msg(m_optionsMap, "m_allOptionsMap variable is NULL");
     boost::program_options::store(
         boost::program_options::parse_config_file(
           ifs, *m_optionsDescription, true), *m_optionsMap);
     boost::program_options::notify(*m_optionsMap);
     ifs.close();
     m_scannedInputFile = true;
   }
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const BoostInputOptionsParser & parser) friend
Helpful stream operator for printing the parser state.
Definition at line 143 of file BoostInputOptionsParser.C.
 {
   os << *(parser.m_optionsDescription);
   return os;
 }
Member Data Documentation
const std::string& QUESO::BoostInputOptionsParser::m_filename protected
Definition at line 90 of file BoostInputOptionsParser.h.
Referenced by scanInputFile().
ScopedPtr<boost::program_options::options_description>::Type QUESO::BoostInputOptionsParser::m_optionsDescription protected
Definition at line 91 of file BoostInputOptionsParser.h.
Referenced by QUESO::operator<<(), registerOption(), and scanInputFile().
ScopedPtr<boost::program_options::variables_map>::Type QUESO::BoostInputOptionsParser::m_optionsMap protected
Definition at line 92 of file BoostInputOptionsParser.h.
Referenced by scanInputFile().
bool QUESO::BoostInputOptionsParser::m_scannedInputFile private
Definition at line 95 of file BoostInputOptionsParser.h.
Referenced by getOption(), and scanInputFile().
The documentation for this class was generated from the following files:
src/core/inc/BoostInputOptionsParser.h
src/core/src/BoostInputOptionsParser.C