queso-0.53.0: QUESO::GaussianVectorRV< V, M > Class Template Reference
QUESO::GaussianVectorRV< V, M > Class Template Reference
A class representing a Gaussian vector RV.
#include <GaussianVectorRV.h>
Public Member Functions
Constructor/Destructor methods
GaussianVectorRV (const char *prefix, const VectorSet< V, M > &imageSet, const V &lawExpVector, const V &lawVarVector)
Constructor.
GaussianVectorRV (const char *prefix, const VectorSet< V, M > &imageSet, const V &lawExpVector, const M &lawCovMatrix)
Constructor.
virtual ~GaussianVectorRV ()
Virtual destructor.
Statistical methods
void updateLawExpVector (const V &newLawExpVector)
Updates the vector that contains the mean values.
void updateLawCovMatrix (const M &newLawCovMatrix)
Updates the covariance matrix.
I/O methods
void print (std::ostream &os) const
TODO: Prints the vector RV.
Public Member Functions inherited from QUESO::BaseVectorRV< V, M >
BaseVectorRV (const char *prefix, const VectorSet< V, M > &imageSet)
Constructor.
virtual ~BaseVectorRV ()
Virtual destructor.
const BaseEnvironment & env () const
QUESO environment; access to private attribute m_env.
const VectorSet< V, M > & imageSet () const
Image set of the vector RV; access to private attribute m_imageSet.
const BaseJointPdf< V, M > & pdf () const
Posterior Density Function of the vector RV; access to private attribute m_pdf.
const BaseVectorRealizer< V, M > & realizer () const
Finds a realization (sample) of the PDF of this vector RV; access to private attribute m_realizer.
const BaseVectorCdf< V, M > & subCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering only the sub-sequence of data; access to private attribute m_subCdf.
const BaseVectorCdf< V, M > & unifiedCdf () const
Finds the Cumulative Distribution Function of this vector RV, considering the unified sequence of data; access to private attribute m_unifiedCdf.
const BaseVectorMdf< V, M > & mdf () const
Finds the Mass Density Function of this vector RV; access to private attribute m_mdf.
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseVectorRV< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_imageSet
BaseJointPdf< V, M > * m_pdf
BaseVectorRealizer< V, M > * m_realizer
const BaseVectorCdf< V, M > * m_subCdf
const BaseVectorCdf< V, M > * m_unifiedCdf
const BaseVectorMdf< V, M > * m_mdf
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::GaussianVectorRV< V, M >
A class representing a Gaussian vector RV.
This class allows the user to compute the value of a Gaussian PDF and to generate realizations (samples) from it.
In probability theory, the normal (or Gaussian) distribution is a continuous probability distribution, defined by the formula:
The parameter in this formula is the mean or expectation of the distribution (and also its median and mode). The parameter is its standard deviation; its variance is therefore .
Definition at line 63 of file GaussianVectorRV.h.
Constructor & Destructor Documentation
template<class V, class M> QUESO::GaussianVectorRV< V, M >::GaussianVectorRV (const char * prefix, const VectorSet< V, M > & imageSet, const V & lawExpVector, const V & lawVarVector)
Constructor.
Construct a Gaussian vector RV with mean lawExpVector and diagonal covariance matrix lawVarVector whose variates live in imageSet.
Definition at line 35 of file GaussianVectorRV.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRV< V, M >::m_env, QUESO::BaseVectorRV< V, M >::m_imageSet, QUESO::BaseVectorRV< V, M >::m_mdf, QUESO::BaseVectorRV< V, M >::m_pdf, QUESO::BaseVectorRV< V, M >::m_prefix, QUESO::BaseVectorRV< V, M >::m_realizer, QUESO::BaseVectorRV< V, M >::m_subCdf, QUESO::BaseVectorRV< V, M >::m_unifiedCdf, queso_require_greater_msg, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRV<V,M>(((std::string)(prefix)+"gau").c_str(),imageSet)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering GaussianVectorRV<V,M>::constructor() [1]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   queso_require_greater_msg(lawVarVector.getMinValue(), 0.0, "Covariance matrix is not symmetric positive definite.");
   m_pdf = new GaussianJointPdf<V,M>(m_prefix.c_str(),
                                             m_imageSet,
                                             lawExpVector,
                                             lawVarVector);
   V cholDiag(lawVarVector);
   cholDiag.cwSqrt();
   M lowerCholLawCovMatrix(cholDiag);
   lowerCholLawCovMatrix.zeroUpper(false);
   m_realizer = new GaussianVectorRealizer<V,M>(m_prefix.c_str(),
                                                       m_imageSet,
                                                       lawExpVector,
                                                       lowerCholLawCovMatrix);
   m_subCdf     = NULL; // FIX ME: complete code
   m_unifiedCdf = NULL; // FIX ME: complete code
   m_mdf        = NULL; // FIX ME: complete code
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving GaussianVectorRV<V,M>::constructor() [1]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V, class M> QUESO::GaussianVectorRV< V, M >::GaussianVectorRV (const char * prefix, const VectorSet< V, M > & imageSet, const V & lawExpVector, const M & lawCovMatrix)
Constructor.
Construct a Gaussian vector RV with mean lawExpVector and covariance matrix lawCovMatrix whose variates live in imageSet.
Definition at line 78 of file GaussianVectorRV.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorRV< V, M >::m_env, QUESO::BaseVectorRV< V, M >::m_imageSet, QUESO::BaseVectorRV< V, M >::m_mdf, QUESO::BaseVectorRV< V, M >::m_pdf, QUESO::BaseVectorRV< V, M >::m_prefix, QUESO::BaseVectorRV< V, M >::m_realizer, QUESO::BaseVectorRV< V, M >::m_subCdf, QUESO::BaseVectorRV< V, M >::m_unifiedCdf, queso_require_msg, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorRV<V,M>(((std::string)(prefix)+"gau").c_str(),imageSet)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering GaussianVectorRV<V,M>::constructor() [2]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   m_pdf = new GaussianJointPdf<V,M>(m_prefix.c_str(),
                                            m_imageSet,
                                            lawExpVector,
                                            lawCovMatrix);
   M lowerCholLawCovMatrix(lawCovMatrix);
   int iRC = lowerCholLawCovMatrix.chol();
   lowerCholLawCovMatrix.zeroUpper(false);
   if (iRC) {
     std::cerr << "In GaussianVectorRV<V,M>::constructor() [2]: chol failed, will use svd\n";
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In GaussianVectorRV<V,M>::constructor() [2]: chol failed; will use svd; lawCovMatrix contents are\n";
       *m_env.subDisplayFile() << lawCovMatrix; // FIX ME: might demand parallelism
       *m_env.subDisplayFile() << std::endl;
     }
     M matU (lawCovMatrix);
     M matVt(m_imageSet.vectorSpace().zeroVector());
     V vecS (m_imageSet.vectorSpace().zeroVector());
     iRC = lawCovMatrix.svd(matU,vecS,matVt);
     queso_require_msg(!(iRC), "Cholesky decomposition of covariance matrix failed.");
     vecS.cwSqrt();
     m_realizer = new GaussianVectorRealizer<V,M>(m_prefix.c_str(),
                                                         m_imageSet,
                                                         lawExpVector,
                                                         matU,
                                                         vecS, // already square rooted
                                                         matVt);
   }
   else {
     m_realizer = new GaussianVectorRealizer<V,M>(m_prefix.c_str(),
                                                         m_imageSet,
                                                         lawExpVector,
                                                         lowerCholLawCovMatrix);
   }
   m_subCdf     = NULL; // FIX ME: complete code
   m_unifiedCdf = NULL; // FIX ME: complete code
   m_mdf        = NULL; // FIX ME: complete code
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving GaussianVectorRV<V,M>::constructor() [2]"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::GaussianVectorRV< V, M >::~GaussianVectorRV () virtual
Virtual destructor.
Definition at line 140 of file GaussianVectorRV.C.
 {
   delete m_mdf;
   delete m_unifiedCdf;
   delete m_subCdf;
   delete m_realizer;
   delete m_pdf;
 }
Member Function Documentation
template<class V , class M > void QUESO::GaussianVectorRV< V, M >::print (std::ostream & os) const virtual
TODO: Prints the vector RV.
Todo:
: implement me!
Implements QUESO::BaseVectorRV< V, M >.
Definition at line 195 of file GaussianVectorRV.C.
 {
   os << "GaussianVectorRV<V,M>::print() says, 'Please implement me.'" << std::endl;
   return;
 }
template<class V , class M> void QUESO::GaussianVectorRV< V, M >::updateLawCovMatrix (const M & newLawCovMatrix)
Updates the covariance matrix.
This method tries to use Cholesky decomposition; and if it fails, the method then calls a SVD decomposition.
Definition at line 161 of file GaussianVectorRV.C.
References queso_require_msg.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::rv().
 {
   // We are sure that m_pdf (and m_realizer, etc) point to associated Gaussian classes, so all is well
   ( dynamic_cast< GaussianJointPdf<V,M>* >(m_pdf) )->updateLawCovMatrix(newLawCovMatrix);
   M newLowerCholLawCovMatrix(newLawCovMatrix);
   int iRC = newLowerCholLawCovMatrix.chol();
   newLowerCholLawCovMatrix.zeroUpper(false);
   if (iRC) {
     std::cerr << "In GaussianVectorRV<V,M>::updateLawCovMatrix(): chol failed, will use svd\n";
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In GaussianVectorRV<V,M>::updateLawCovMatrix(): chol failed; will use svd; newLawCovMatrix contents are\n";
       *m_env.subDisplayFile() << newLawCovMatrix; // FIX ME: might demand parallelism
       *m_env.subDisplayFile() << std::endl;
     }
     M matU (newLawCovMatrix);
     M matVt(m_imageSet.vectorSpace().zeroVector());
     V vecS (m_imageSet.vectorSpace().zeroVector());
     iRC = newLawCovMatrix.svd(matU,vecS,matVt);
     queso_require_msg(!(iRC), "Cholesky decomposition of covariance matrix failed.");
     vecS.cwSqrt();
     ( dynamic_cast< GaussianVectorRealizer<V,M>* >(m_realizer) )->updateLowerCholLawCovMatrix(matU,
                                                                                                      vecS, // already square rooted
                                                                                                      matVt);
   }
   else {
     ( dynamic_cast< GaussianVectorRealizer<V,M>* >(m_realizer) )->updateLowerCholLawCovMatrix(newLowerCholLawCovMatrix);
   }
   return;
 }
template<class V, class M > void QUESO::GaussianVectorRV< V, M >::updateLawExpVector (const V & newLawExpVector)
Updates the vector that contains the mean values.
Definition at line 151 of file GaussianVectorRV.C.
Referenced by QUESO::ScaledCovMatrixTKGroup< V, M >::rv(), and QUESO::HessianCovMatricesTKGroup< V, M >::rv().
 {
   // We are sure that m_pdf (and m_realizer, etc) point to associated Gaussian classes, so all is well
   ( dynamic_cast< GaussianJointPdf      <V,M>* >(m_pdf     ) )->updateLawExpVector(newLawExpVector);
   ( dynamic_cast< GaussianVectorRealizer<V,M>* >(m_realizer) )->updateLawExpVector(newLawExpVector);
   return;
 }
The documentation for this class was generated from the following files:
src/stats/inc/GaussianVectorRV.h
src/stats/src/GaussianVectorRV.C