queso-0.53.0: src/contrib/ANN/src/ANN.cpp File Reference
ANN.cpp File Reference
#include <cstdlib>
#include <ANN/ANNx.h>
#include <ANN/ANNperf.h>
Functions
ANNdist annDist (int dim, ANNpoint p, ANNpoint q)
void annPrintPt (ANNpoint pt, int dim, std::ostream &out)
ANNpoint annAllocPt (int dim, ANNcoord c)
ANNpointArray annAllocPts (int n, int dim)
void annDeallocPt (ANNpoint &p)
void annDeallocPts (ANNpointArray &pa)
ANNpoint annCopyPt (int dim, ANNpoint source)
void annAssignRect (int dim, ANNorthRect &dest, const ANNorthRect &source)
void annError (const char *msg, ANNerr level)
void annMaxPtsVisit (int maxPts)
Variables
int ANNmaxPtsVisited = 0
int ANNptsVisited
Function Documentation
ANNpoint annAllocPt (int dim, ANNcoord c)
Definition at line 110 of file ANN.cpp.
References dim.
Referenced by ANNorthRect::ANNorthRect(), annReadDump(), and main().
 {
         ANNpoint p = new ANNcoord[dim];
         for (int i = 0; i < dim; i++) p[i] = c;
         return p;
 }
ANNpointArray annAllocPts (int n, int dim)
Definition at line 117 of file ANN.cpp.
References dim.
Referenced by annClusEllipsoids(), annClusGaussPts(), annClusOrthFlats(), annReadDump(), generatePts(), main(), readANN(), and readPts().
 {
         ANNpointArray pa = new ANNpoint[n];                     // allocate points
         ANNpoint          p  = new ANNcoord[n*dim];             // allocate space for coords
         for (int i = 0; i < n; i++) {
                 pa[i] = &(p[i*dim]);
         }
         return pa;
 }
void annAssignRect (int dim, ANNorthRect & dest, const ANNorthRect & source)
Definition at line 148 of file ANN.cpp.
References dim, ANNorthRect::hi, and ANNorthRect::lo.
Referenced by annBnds2Box(), and tryCentroidShrink().
 {
         for (int i = 0; i < dim; i++) {
                 dest.lo[i] = source.lo[i];
                 dest.hi[i] = source.hi[i];
         }
 }
ANNpoint annCopyPt (int dim, ANNpoint source)
Definition at line 140 of file ANN.cpp.
References dim.
Referenced by ANNbd_tree::ANNbd_tree(), ANNkd_tree::ANNkd_tree(), and ANNorthRect::ANNorthRect().
 {
         ANNpoint p = new ANNcoord[dim];
         for (int i = 0; i < dim; i++) p[i] = source[i];
         return p;
 }
void annDeallocPt (ANNpoint & p)
Definition at line 127 of file ANN.cpp.
Referenced by ANNkd_tree::~ANNkd_tree(), and ANNorthRect::~ANNorthRect().
 {
         delete [] p;
         p = NULL;
 }
void annDeallocPts (ANNpointArray & pa)
Definition at line 133 of file ANN.cpp.
Referenced by annClusEllipsoids(), annClusGaussPts(), annClusOrthFlats(), generatePts(), main(), and readPts().
 {
         delete [] pa[0];                                                        // dealloc coordinate storage
         delete [] pa;                                                           // dealloc points
         pa = NULL;
 }
ANNdist annDist (int dim, ANNpoint p, ANNpoint q)
Definition at line 46 of file ANN.cpp.
References ANN_COORD, ANN_FLOP, ANN_POW, ANN_PTS, ANN_SUM, and dim.
Referenced by ANNbruteForce::annkFRSearch(), and ANNbruteForce::annkSearch().
 {
         register int d;
         register ANNcoord diff;
         register ANNcoord dist;
         dist = 0;
         for (d = 0; d < dim; d++) {
                 diff = p[d] - q[d];
                 dist = ANN_SUM(dist, ANN_POW(diff));
         }
         ANN_FLOP(3*dim)                                 // performance counts
         ANN_PTS(1)
         ANN_COORD(dim)
         return dist;
 }
void annError (const char * msg, ANNerr level)
Definition at line 169 of file ANN.cpp.
References ANNabort.
Referenced by ANNbd_tree::ANNbd_tree(), ANNkd_tree::ANNkd_tree(), ANNbruteForce::annkSearch(), ANNkd_tree::annkSearch(), annReadDump(), annReadTree(), ANNpr_queue::insert(), and selectDecomp().
 {
         if (level == ANNabort) {
                 cerr << "ANN: ERROR------->" << msg << "<-------------ERROR\n";
                 exit(1);
         }
         else {
                 cerr << "ANN: WARNING----->" << msg << "<-------------WARNING\n";
         }
 }
void annMaxPtsVisit (int maxPts)
Definition at line 197 of file ANN.cpp.
References ANNmaxPtsVisited, and maxPts.
Referenced by main().
 {
         ANNmaxPtsVisited = maxPts;
 }
void annPrintPt (ANNpoint pt, int dim, std::ostream & out)
Definition at line 70 of file ANN.cpp.
References dim.
Referenced by ANNkd_tree::Dump(), and ANNkd_tree::Print().
 {
         for (int j = 0; j < dim; j++) {
                 out << pt[j];
                 if (j < dim-1) out << " ";
         }
 }
Variable Documentation
int ANNmaxPtsVisited = 0
Definition at line 190 of file ANN.cpp.
Referenced by ANNbd_shrink::ann_FR_search(), ANNkd_split::ann_FR_search(), ANNbd_shrink::ann_search(), ANNkd_split::ann_search(), ANNkd_tree::annkPriSearch(), and annMaxPtsVisit().
int ANNptsVisited
Definition at line 191 of file ANN.cpp.
Referenced by ANNbd_shrink::ann_FR_search(), ANNkd_leaf::ann_pri_search(), ANNbd_shrink::ann_search(), ANNkd_leaf::ann_search(), ANNkd_split::ann_search(), ANNkd_tree::annkPriSearch(), and ANNkd_tree::annkSearch().