queso-0.53.0: QUESO::UniformJointPdf< V, M > Class Template Reference
QUESO::UniformJointPdf< V, M > Class Template Reference
A class for handling uniform joint PDFs.
#include <UniformJointPdf.h>
Public Member Functions
Constructor/Destructor methods
UniformJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Constructor.
~UniformJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Actual value of the uniform PDF.
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Logarithm of the value of the uniform PDF.
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
virtual void setNormalizationStyle (unsigned int value) const
Sets a value to be used in the normalization style (stored in the protected attribute m_normalizationStyle.)
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::UniformJointPdf< V, M >
A class for handling uniform joint PDFs.
This class allows the mathematical definition of a Uniform Joint PDF.
Definition at line 49 of file UniformJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::UniformJointPdf< V, M >::UniformJointPdf (const char * prefix, const VectorSet< V, M > & domainSet)
Constructor.
Constructs a new object of the class, given a prefix and the domain set of the uniform PDF.
Definition at line 33 of file UniformJointPdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarFunction< V, M >::m_env, QUESO::BaseScalarFunction< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"uni").c_str(),
                             domainSet)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering UniformJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving UniformJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::UniformJointPdf< V, M >::~UniformJointPdf ()
Destructor.
Definition at line 54 of file UniformJointPdf.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::UniformJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Actual value of the uniform PDF.
If the domain of the PDF is well defined (neither negative nor infinite), then the actual value is given by 1.0/(the volume of the domain), otherwise the actual value is 1.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 60 of file UniformJointPdf.C.
References queso_require_equal_to_msg.
 {
   queso_require_equal_to_msg(domainVector.sizeLocal(), this->m_domainSet.vectorSpace().dimLocal(), "invalid input");
   if (gradVector   ) *gradVector     = m_domainSet.vectorSpace().zeroVector();
   if (hessianMatrix) *hessianMatrix *= 0.;
   if (hessianEffect) *hessianEffect  = m_domainSet.vectorSpace().zeroVector();
   if (domainDirection) {}; // just to remove compiler warning
   double volume = m_domainSet.volume();
   if (((boost::math::isnan)(volume)) ||
       (volume == -INFINITY         ) ||
       (volume ==  INFINITY         ) ||
       (volume <= 0.                ) ||
       (m_normalizationStyle != 0   )) {
     volume = 1.;
   }
   return 1./volume; // No need to multiply by exp(m_logOfNormalizationFactor) [PDF-04]
 }
template<class V , class M > double QUESO::UniformJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
Computes the logarithm of the normalization factor.
This routine calls BaseJointPdf::commonComputeLogOfNormalizationFactor().
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 117 of file UniformJointPdf.C.
References QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor().
 {
   double value = 0.;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering UniformJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << std::endl;
   }
   value = BaseJointPdf<V,M>::commonComputeLogOfNormalizationFactor(numSamples, updateFactorInternally);
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving UniformJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << ", m_logOfNormalizationFactor = " << m_logOfNormalizationFactor
                             << std::endl;
   }
   return value;
 }
template<class V , class M > double QUESO::UniformJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Logarithm of the value of the uniform PDF.
Analogous to the actualValue routine, except that the logarithm of the calculated value is returned.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 89 of file UniformJointPdf.C.
 {
   if (gradVector   ) *gradVector     = m_domainSet.vectorSpace().zeroVector();
   if (hessianMatrix) *hessianMatrix *= 0.;
   if (hessianEffect) *hessianEffect  = m_domainSet.vectorSpace().zeroVector();
   if (domainVector[0]) {}; // just to remove compiler warning
   if (domainDirection) {}; // just to remove compiler warning
   double volume = m_domainSet.volume();
   if (((boost::math::isnan)(volume)) ||
       (volume == -INFINITY         ) ||
       (volume ==  INFINITY         ) ||
       (volume <= 0.                ) ||
       (m_normalizationStyle != 0   )) {
     volume = 1.;
   }
   return -log(volume);
 }
The documentation for this class was generated from the following files:
src/stats/inc/UniformJointPdf.h
src/stats/src/UniformJointPdf.C