queso-0.57.0: QUESO::ConcatenatedJointPdf< V, M > Class Template Reference
QUESO::ConcatenatedJointPdf< V, M > Class Template Reference
A class for handling concatenated PDFs.
#include <ConcatenatedJointPdf.h>
Public Member Functions
Constructor/Destructor methods
ConcatenatedJointPdf (const char *prefix, const BaseJointPdf< V, M > &density1, const BaseJointPdf< V, M > &density2, const VectorSet< V, M > &concatenatedDomain)
Constructor.
ConcatenatedJointPdf (const char *prefix, const std::vector< const BaseJointPdf< V, M > * > &densities, const VectorSet< V, M > &concatenatedDomain)
Constructor.
~ConcatenatedJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Calculates the actual values of each density.
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Calculates the logarithm of the values of each density.
virtual void distributionMean (V &meanVector) const
Mean value of the underlying random variable.
virtual void distributionVariance (M &covMatrix) const
Covariance matrix of the underlying random variable.
void setNormalizationStyle (unsigned int value) const
Sets the normalization style of all densities to value.
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
virtual void print (std::ostream &os) const
Print method. Non-pure for backwards compatibility.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
void setFiniteDifferenceStepSize (double fdStepSize)
Sets the step size for finite differencing gradients.
void setFiniteDifferenceStepSize (unsigned int i, double fdStepSize)
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
virtual double lnValue (const V &domainVector) const
Returns the logarithm of the function at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector) const
Returns the logarithm of the function and its gradient at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector, const V &domainDirection, V &hessianEffect) const
Protected Attributes
std::vector< const
BaseJointPdf< V, M > * > m_densities
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::ConcatenatedJointPdf< V, M >
A class for handling concatenated PDFs.
This class allows the user to defines concatenated probability density distributions, i.e, two or more distinct PDFs can be concatenated into one single PDF. This class used, for instance, to concatenate priors from two or more RVs, where one of them has a uniform distribution whereas the other one(s) has a Gaussian distribution.
Definition at line 53 of file ConcatenatedJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::ConcatenatedJointPdf< V, M >::ConcatenatedJointPdf (const char * prefix, const BaseJointPdf< V, M > & density1, const BaseJointPdf< V, M > & density2, const VectorSet< V, M > & concatenatedDomain)
Constructor.
Concatenates two PDFs: density1 and density2 into one vector PDF, given a prefix and the concatenated domain of such PDFs.
Definition at line 33 of file ConcatenatedJointPdf.C.
References QUESO::ConcatenatedJointPdf< V, M >::m_densities, QUESO::queso_require_equal_to_msg, QUESO::size, and QUESO::VectorSet< V, M >::vectorSpace().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"concat").c_str(),concatenatedDomain),
   m_densities             (2,(const BaseJointPdf<V,M>*) NULL)
 {
   m_densities[0] = &density1;
   m_densities[1] = &density2;
   unsigned int size1 = m_densities[0]->domainSet().vectorSpace().dimLocal();
   unsigned int size2 = m_densities[1]->domainSet().vectorSpace().dimLocal();
   unsigned int size  = concatenatedDomain.vectorSpace().dimLocal();
   queso_require_equal_to_msg((size1+size2), size, "incompatible dimensions");
 }
template<class V , class M > QUESO::ConcatenatedJointPdf< V, M >::ConcatenatedJointPdf (const char * prefix, const std::vector< const BaseJointPdf< V, M > * > & densities, const VectorSet< V, M > & concatenatedDomain)
Constructor.
Concatenates a sequence of PDFs, given by: std::vector<const BaseJointPdf<V,M>* >& densities into one single PDF, given a prefix and the concatenated domain of such PDFs.
Definition at line 53 of file ConcatenatedJointPdf.C.
References QUESO::ConcatenatedJointPdf< V, M >::m_densities, QUESO::queso_require_equal_to_msg, QUESO::size, and QUESO::VectorSet< V, M >::vectorSpace().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"concat").c_str(),concatenatedDomain),
   m_densities             (densities.size(),(const BaseJointPdf<V,M>*) NULL)
 {
   unsigned int sumSizes = 0;
   for (unsigned i = 0; i < m_densities.size(); ++i) {
     m_densities[i] = densities[i];
     sumSizes += m_densities[i]->domainSet().vectorSpace().dimLocal();
   }
   unsigned int size  = concatenatedDomain.vectorSpace().dimLocal();
   queso_require_equal_to_msg(sumSizes, size, "incompatible dimensions");
 }
template<class V , class M > QUESO::ConcatenatedJointPdf< V, M >::~ConcatenatedJointPdf ()
Destructor.
Definition at line 73 of file ConcatenatedJointPdf.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::ConcatenatedJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Calculates the actual values of each density.
The final actual value is the multiplication of all values calculated.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 89 of file ConcatenatedJointPdf.C.
References QUESO::queso_require_equal_to_msg.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ConcatenatedJointPdf<V,M>::actualValue()"
                             << ": domainVector = " << domainVector
                             << std::endl;
   }
   queso_require_equal_to_msg(domainVector.sizeLocal(), this->m_domainSet.vectorSpace().dimLocal(), "invalid input");
   queso_require_msg(!(domainDirection || gradVector || hessianMatrix || hessianEffect), "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   double returnValue = 1.;
   unsigned int cumulativeSize = 0;
   for (unsigned int i = 0; i < m_densities.size(); ++i) {
     V vec_i(m_densities[i]->domainSet().vectorSpace().zeroVector());
     domainVector.cwExtract(cumulativeSize,vec_i);
     double value_i = m_densities[i]->actualValue(vec_i,NULL,NULL,NULL,NULL);
     returnValue *= value_i;
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99)) {
       *m_env.subDisplayFile() << "In ConcatenatedJointPdf<V,M>::actualValue()"
                               << ", vec_" << i << ") = "       << vec_i
                               << ": value_" << i << " = "        << value_i
                               << ", temporary cumulative value = " << returnValue
                               << std::endl;
     }
     cumulativeSize += vec_i.sizeLocal();
   }
   //returnValue *= exp(m_logOfNormalizationFactor); // No need, because each PDF should be already normalized [PDF-11]
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ConcatenatedJointPdf<V,M>::actualValue()"
                             << ": domainVector = " << domainVector
                             << ", returnValue = "  << returnValue
                             << std::endl;
   }
   return returnValue;
 }
template<class V , class M > double QUESO::ConcatenatedJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
Computes the logarithm of the normalization factor.
This method calls the computeLogOfNormalizationFactor() for each one of the densities that have been concatenated.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 216 of file ConcatenatedJointPdf.C.
References QUESO::queso_isnan().
 {
   double value = 0.;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering ConcatenatedJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << std::endl;
   }
   double volume = m_domainSet.volume();
   if ((queso_isnan(volume)) ||
       (volume == -INFINITY         ) ||
       (volume ==  INFINITY         ) ||
       (volume <= 0.                )) {
     // Do nothing
   }
   else {
     for (unsigned int i = 0; i < m_densities.size(); ++i) {
       m_densities[i]->computeLogOfNormalizationFactor(numSamples, updateFactorInternally);
     }
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving ConcatenatedJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << ", m_logOfNormalizationFactor = " << m_logOfNormalizationFactor
                             << std::endl;
   }
   return value;
 }
template<class V , class M > void QUESO::ConcatenatedJointPdf< V, M >::distributionMean (V & meanVector) const virtual
Mean value of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 202 of file ConcatenatedJointPdf.C.
 {
   unsigned int cumulativeSize = 0;
   for (unsigned int i = 0; i < m_densities.size(); ++i) {
     V vec_i(m_densities[i]->domainSet().vectorSpace().zeroVector());
     m_densities[i]->distributionMean(vec_i);
     meanVector.cwSet(cumulativeSize,vec_i);
     cumulativeSize += vec_i.sizeLocal();
   }
 }
template<class V , class M > void QUESO::ConcatenatedJointPdf< V, M >::distributionVariance (M & covMatrix) const virtual
Covariance matrix of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 181 of file ConcatenatedJointPdf.C.
References QUESO::Map::NumGlobalElements().
 {
   covMatrix.zeroLower();
   covMatrix.zeroUpper();
   unsigned int cumulativeSize = 0;
   for (unsigned int i = 0; i < m_densities.size(); ++i) {
     const Map & map = m_densities[i]->domainSet().vectorSpace().map();
     const unsigned int n_columns = map.NumGlobalElements();
     M mat_i(m_densities[i]->domainSet().env(),
             map, n_columns);
     m_densities[i]->distributionVariance(mat_i);
     covMatrix.cwSet(cumulativeSize,cumulativeSize,mat_i);
     cumulativeSize += n_columns;
   }
 }
template<class V , class M > double QUESO::ConcatenatedJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Calculates the logarithm of the values of each density.
The final logarithm value is the addition of all values calculated.
Reimplemented from QUESO::BaseScalarFunction< V, M >.
Definition at line 136 of file ConcatenatedJointPdf.C.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ConcatenatedJointPdf<V,M>::lnValue()"
                             << ": domainVector = " << domainVector
                             << std::endl;
   }
   queso_require_msg(!(domainDirection || gradVector || hessianMatrix || hessianEffect), "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   double returnValue = 0.;
   unsigned int cumulativeSize = 0;
   for (unsigned int i = 0; i < m_densities.size(); ++i) {
     V vec_i(m_densities[i]->domainSet().vectorSpace().zeroVector());
     domainVector.cwExtract(cumulativeSize,vec_i);
     double value_i = m_densities[i]->lnValue(vec_i,NULL,NULL,NULL,NULL);
     returnValue += value_i;
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99)) {  // gpmsa
       *m_env.subDisplayFile() << "In ConcatenatedJointPdf<V,M>::lnValue()"
                               << ", vec_" << i << " = "       << vec_i
                               << ": value_" << i << " = "        << value_i
                               << ", temporary cumulative value = " << returnValue
                               << std::endl;
     }
     cumulativeSize += vec_i.sizeLocal();
   }
   //returnValue += m_logOfNormalizationFactor; // No need, because each PDF should be already normalized [PDF-11]
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ConcatenatedJointPdf<V,M>::lnValue()"
                             << ": domainVector = " << domainVector
                             << ", returnValue = "  << returnValue
                             << std::endl;
   }
   return returnValue;
 }
template<class V , class M > void QUESO::ConcatenatedJointPdf< V, M >::setNormalizationStyle (unsigned int value) const virtual
Sets the normalization style of all densities to value.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 79 of file ConcatenatedJointPdf.C.
 {
   for (unsigned i = 0; i < m_densities.size(); ++i) {
     m_densities[i]->setNormalizationStyle(value);
   }
   return;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> std::vector<const BaseJointPdf<V,M>* > QUESO::ConcatenatedJointPdf< V, M >::m_densities protected
Definition at line 107 of file ConcatenatedJointPdf.h.
Referenced by QUESO::ConcatenatedJointPdf< V, M >::ConcatenatedJointPdf().
The documentation for this class was generated from the following files:
src/stats/inc/ConcatenatedJointPdf.h
src/stats/src/ConcatenatedJointPdf.C