queso-0.56.2: ANNsampStat Class Reference
ANNsampStat Class Reference
#include <ANNperf.h>
Public Member Functions
void reset ()
ANNsampStat ()
void operator+= (double x)
int samples ()
double mean ()
double stdDev ()
double min ()
double max ()
Private Attributes
int n
double sum
double sum2
double minVal
double maxVal
Detailed Description
Definition at line 85 of file ANNperf.h.
Constructor & Destructor Documentation
ANNsampStat::ANNsampStat () inline
Definition at line 99 of file ANNperf.h.
 { reset(); }            // constructor
Member Function Documentation
double ANNsampStat::max () inline
Definition at line 116 of file ANNperf.h.
Referenced by print_one_stat().
 { return maxVal; } // maximum
double ANNsampStat::mean () inline
Definition at line 110 of file ANNperf.h.
Referenced by print_one_stat().
 { return sum/n; } // mean
double ANNsampStat::min () inline
Definition at line 115 of file ANNperf.h.
Referenced by print_one_stat().
 { return minVal; } // minimum
void ANNsampStat::operator+= (double x) inline
Definition at line 101 of file ANNperf.h.
         {
                 n++;  sum += x;  sum2 += x*x;
                 if (x < minVal) minVal = x;
                 if (x > maxVal) maxVal = x;
         }
void ANNsampStat::reset () inline
Definition at line 91 of file ANNperf.h.
References ANN_DBL_MAX.
Referenced by annResetStats().
         {
                 n = 0;
                 sum = sum2 = 0;
                 minVal = ANN_DBL_MAX;
                 maxVal = -ANN_DBL_MAX;
         }
int ANNsampStat::samples () inline
Definition at line 108 of file ANNperf.h.
 { return n; }           // number of samples
double ANNsampStat::stdDev () inline
Definition at line 113 of file ANNperf.h.
Referenced by print_one_stat().
 { return sqrt((sum2 - (sum*sum)/n)/(n-1));}
Member Data Documentation
double ANNsampStat::maxVal private
Definition at line 89 of file ANNperf.h.
double ANNsampStat::minVal private
Definition at line 89 of file ANNperf.h.
int ANNsampStat::n private
Definition at line 86 of file ANNperf.h.
double ANNsampStat::sum private
Definition at line 87 of file ANNperf.h.
double ANNsampStat::sum2 private
Definition at line 88 of file ANNperf.h.
The documentation for this class was generated from the following file:
src/contrib/ANN/include/ANN/ANNperf.h