queso-0.56.2: QUESO::Fft< T > Class Template Reference
QUESO::Fft< T > Class Template Reference
Class for a Fast Fourier Transform (FFT) algorithm.
#include <Fft.h>
Public Member Functions
template<>
void forward (const std::vector< std::complex< double > > &data, unsigned int fftSize, std::vector< std::complex< double > > &forwardResult)
template<>
void inverse (const std::vector< std::complex< double > > &data, unsigned int fftSize, std::vector< std::complex< double > > &inverseResult)
template<>
void forward (const std::vector< double > &data, unsigned int fftSize, std::vector< std::complex< double > > &forwardResult)
template<>
void inverse (const std::vector< double > &data, unsigned int fftSize, std::vector< std::complex< double > > &inverseResult)
Constructor/Destructor methods
Fft (const BaseEnvironment &env)
Default Constructor.
~Fft ()
Destructor.
Mathematical methods
void forward (const std::vector< T > &data, unsigned int fftSize, std::vector< std::complex< double > > &result)
Calculates the forward Fourier transform (for real data. TODO: complex data).
void inverse (const std::vector< T > &data, unsigned int fftSize, std::vector< std::complex< double > > &result)
Calculates the inverse Fourier transform for real and complex data.
Private Attributes
const BaseEnvironment & m_env
Detailed Description
template<class T>
class QUESO::Fft< T >
Class for a Fast Fourier Transform (FFT) algorithm.
This class implements a Fast Fourier Transform (FFT) algorithm. Fast Fourier Transforms are efficient algorithms for calculating the discrete Fourier transform (DFT),
and its inverse. The DFT usually arises as an approximation to the continuous Fourier transform when functions are sampled at discrete intervals in space or time. The naive evaluation of the discrete Fourier transform is a matrix-vector multiplication . A general matrix-vector multiplication takes operations for data-points. Fast Fourier transform algorithms use a divide-and-conquer strategy to factorize the matrix into smaller sub-matrices, corresponding to the integer factors of the length . If can be factorized into a product of integers then the DFT can be computed in operations. For a radix-2 FFT this gives an operation count of .
Todo:
: Implement Forward Fourier Transform for Complex data.
Definition at line 66 of file Fft.h.
Constructor & Destructor Documentation
template<class T > QUESO::Fft< T >::Fft (const BaseEnvironment & env)
Default Constructor.
Definition at line 31 of file Fft.C.
   :
   m_env(env)
 {
 }
template<class T > QUESO::Fft< T >::~Fft ()
Destructor.
Definition at line 38 of file Fft.C.
 {
 }
Member Function Documentation
template<> void QUESO::Fft< std::complex< double > >::forward (const std::vector< std::complex< double > > & data, unsigned int fftSize, std::vector< std::complex< double > > & forwardResult)
Definition at line 32 of file ComplexFft.C.
 {
   queso_not_implemented();
   std::complex<double> z = data[0]; z += 0.; // just to avoid icpc warnings
   unsigned int         f = fftSize; f += 1;  // just to avoid icpc warnings
   forwardResult[0] = 0.;                     // just to avoid icpc warnings
 #if 0
   if (forwardResult.size() != fftSize) {
     forwardResult.resize(fftSize,std::complex<double>(0.,0.));
     std::vector<std::complex<double> >(forwardResult).swap(forwardResult);
   }
   std::vector<double> internalData(fftSize,0.);
   unsigned int minSize = std::min((unsigned int) data.size(),fftSize);
   for (unsigned int j = 0; j < minSize; ++j) {
     internalData[j] = data[j];
   }
   gsl_fft_real_workspace* realWkSpace = gsl_fft_real_workspace_alloc(fftSize);
   gsl_fft_real_wavetable* realWvTable = gsl_fft_real_wavetable_alloc(fftSize);
   gsl_fft_real_transform(&internalData[0],
                          1,
                          fftSize,
                          realWvTable,
                          realWkSpace);
   gsl_fft_real_wavetable_free(realWvTable);
   gsl_fft_real_workspace_free(realWkSpace);
   unsigned int halfFFTSize = fftSize/2;
   double realPartOfFFT = 0.;
   double imagPartOfFFT = 0.;
   for (unsigned int j = 0; j < internalData.size(); ++j) {
     if (j == 0) {
       realPartOfFFT = internalData[j];
       imagPartOfFFT = 0.;
     }
     else if (j < halfFFTSize) {
       realPartOfFFT = internalData[2*j-1];
       imagPartOfFFT = internalData[2*j  ];
     }
     else if (j == halfFFTSize) {
       realPartOfFFT = internalData[2*j-1];
       imagPartOfFFT = 0.;
     }
     else {
       realPartOfFFT =  internalData[2*(fftSize-j)-1];
       imagPartOfFFT = -internalData[2*(fftSize-j)  ];
     }
     forwardResult[j] = std::complex<double>(realPartOfFFT,imagPartOfFFT);
   }
 #endif
   return;
 }
template<> void QUESO::Fft< double >::forward (const std::vector< double > & data, unsigned int fftSize, std::vector< std::complex< double > > & forwardResult)
Definition at line 34 of file RealFft.C.
 {
   if (forwardResult.size() != fftSize) {
     forwardResult.resize(fftSize,std::complex<double>(0.,0.));
     std::vector<std::complex<double> >(forwardResult).swap(forwardResult);
   }
   std::vector<double> internalData(fftSize,0.);
   unsigned int minSize = std::min((unsigned int) data.size(),fftSize);
   for (unsigned int j = 0; j < minSize; ++j) {
     internalData[j] = data[j];
   }
   //double sumOfAllTerms = 0.;
   //for (unsigned int j = 0; j < fftSize; ++j) {
   //  sumOfAllTerms += internalData[j];
   //}
   //allocTables(fftSize);
   gsl_fft_real_workspace* realWkSpace = gsl_fft_real_workspace_alloc(fftSize);
   gsl_fft_real_wavetable* realWvTable = gsl_fft_real_wavetable_alloc(fftSize);
   gsl_fft_real_transform(&internalData[0],
                          1,
                          fftSize,
                          realWvTable,
                          realWkSpace);
   gsl_fft_real_wavetable_free(realWvTable);
   gsl_fft_real_workspace_free(realWkSpace);
   //freeTables();
   //std::cout << "After FFT"
   //          << ", sumOfAllTerms = "          << sumOfAllTerms
   //          << ", sumOfAllTerms - dft[0] = " << sumOfAllTerms - internalData[0]
   //          << std::endl;
   unsigned int halfFFTSize = fftSize/2;
   double realPartOfFFT = 0.;
   double imagPartOfFFT = 0.;
   for (unsigned int j = 0; j < internalData.size(); ++j) {
     if (j == 0) {
       realPartOfFFT = internalData[j];
       imagPartOfFFT = 0.;
     }
     else if (j < halfFFTSize) {
       realPartOfFFT = internalData[2*j-1];
       imagPartOfFFT = internalData[2*j  ];
     }
     else if (j == halfFFTSize) {
       realPartOfFFT = internalData[2*j-1];
       imagPartOfFFT = 0.;
     }
     else {
       realPartOfFFT =  internalData[2*(fftSize-j)-1];
       imagPartOfFFT = -internalData[2*(fftSize-j)  ];
     }
     forwardResult[j] = std::complex<double>(realPartOfFFT,imagPartOfFFT);
   }
   return;
 }
template<class T> void QUESO::Fft< T >::forward (const std::vector< T > & data, unsigned int fftSize, std::vector< std::complex< double > > & result)
Calculates the forward Fourier transform (for real data. TODO: complex data).
This function uses GSL function 'gsl_fft_real_transform' to compute the FFT of data, a real array (of time-ordered real data) of length fftSize, using a mixed radix decimation-in-frequency algorithm. There is no restriction on the length fftSize. Efficient modules are provided for subtransforms of length 2, 3, 4 and 5. Any remaining factors are computed with a slow, , general- fftSize module. The caller must supply a wavetable containing trigonometric lookup tables and a workspace work.
The definition of the forward Fourier transform, of size is:
Referenced by QUESO::ScalarSequence< T >::autoCorrViaFft(), and QUESO::ScalarSequence< T >::psd().
template<> void QUESO::Fft< std::complex< double > >::inverse (const std::vector< std::complex< double > > & data, unsigned int fftSize, std::vector< std::complex< double > > & inverseResult)
Definition at line 94 of file ComplexFft.C.
 {
   if (inverseResult.size() != fftSize) {
     inverseResult.resize(fftSize,std::complex<double>(0.,0.));
     std::vector<std::complex<double> >(inverseResult).swap(inverseResult);
   }
   std::vector<double> internalData(2*fftSize,0.);                          // Yes, twice the fftSize
   unsigned int minSize = 2 * std::min((unsigned int) data.size(),fftSize); // Yes, 2*
   for (unsigned int j = 0; j < minSize; ++j) {
     internalData[2*j  ] = data[j].real();
     internalData[2*j+1] = data[j].imag();
   }
   gsl_fft_complex_workspace* complexWkSpace = gsl_fft_complex_workspace_alloc(fftSize);
   gsl_fft_complex_wavetable* complexWvTable = gsl_fft_complex_wavetable_alloc(fftSize);
   gsl_fft_complex_inverse(&internalData[0],
                           1,
                           fftSize,
                           complexWvTable,
                           complexWkSpace);
   gsl_fft_complex_wavetable_free(complexWvTable);
   gsl_fft_complex_workspace_free(complexWkSpace);
   for (unsigned int j = 0; j < fftSize; ++j) {
     inverseResult[j] = std::complex<double>(internalData[2*j],internalData[2*j+1]);
   }
   return;
 }
template<> void QUESO::Fft< double >::inverse (const std::vector< double > & data, unsigned int fftSize, std::vector< std::complex< double > > & inverseResult)
Definition at line 102 of file RealFft.C.
 {
   if (inverseResult.size() != fftSize) {
     inverseResult.resize(fftSize,std::complex<double>(0.,0.));
     std::vector<std::complex<double> >(inverseResult).swap(inverseResult);
   }
   std::vector<double> internalData(2*fftSize,0.); // Yes, twice the fftSize
   unsigned int minSize = std::min((unsigned int) data.size(),fftSize);
   for (unsigned int j = 0; j < minSize; ++j) {
     internalData[2*j] = data[j];
   }
   //if (m_subDisplayFile()) {
   //  *m_subDisplayFile() << "In Fft<double>::inverse()"
   //                     << ": about to call gsl_fft_complex_inverse()"
   //                     << " with fftSize = "         << fftSize
   //                     << "; internalData.size() = " << internalData.size()
   //                     << std::endl;
   //}
   gsl_fft_complex_workspace* complexWkSpace = gsl_fft_complex_workspace_alloc(fftSize);
   gsl_fft_complex_wavetable* complexWvTable = gsl_fft_complex_wavetable_alloc(fftSize);
   gsl_fft_complex_inverse(&internalData[0],
                           1,
                           fftSize,
                           complexWvTable,
                           complexWkSpace);
   gsl_fft_complex_wavetable_free(complexWvTable);
   gsl_fft_complex_workspace_free(complexWkSpace);
   //if (m_subDisplayFile()) {
   //  *m_subDisplayFile() << "In Fft<double>::inverse()"
   //                     << ": returned from gsl_fft_complex_inverse()"
   //                     << " with fftSize = "          << fftSize
   //                     << "; inverseResult.size() = " << inverseResult.size()
   //                     << std::endl;
   //}
   for (unsigned int j = 0; j < fftSize; ++j) {
     inverseResult[j] = std::complex<double>(internalData[2*j],internalData[2*j+1]);
   }
   return;
 }
template<class T> void QUESO::Fft< T >::inverse (const std::vector< T > & data, unsigned int fftSize, std::vector< std::complex< double > > & result)
Calculates the inverse Fourier transform for real and complex data.
This function uses GSL function 'gsl_fft_complex_inverse' to compute the FFT of data, a real array (of time-ordered real data) of length fftSize, using a mixed radix decimation-in-frequency algorithm. There is no restriction on the length fftSize. Efficient modules are provided for subtransforms of length 2, 3, 4 and 5. Any remaining factors are computed with a slow, , general- fftSize module. The caller must supply a wavetable containing trigonometric lookup tables and a workspace work.
The definition of the inverse Fourier transform, of size is:
The factor of makes this a true inverse.
Referenced by QUESO::ScalarSequence< T >::autoCorrViaFft(), and QUESO::BaseVectorSequence< V, M >::computeBMM().
Member Data Documentation
template<class T> const BaseEnvironment& QUESO::Fft< T >::m_env private
Definition at line 113 of file Fft.h.
The documentation for this class was generated from the following files:
src/misc/inc/Fft.h
src/misc/src/Fft.C