queso-0.52.0: QUESO::GaussianVectorCdf< V, M > Class Template Reference
QUESO::GaussianVectorCdf< V, M > Class Template Reference
TODO: A class for handling Gaussian CDFs.
#include <GaussianVectorCdf.h>
Public Member Functions
Constructor/Destructor methods
GaussianVectorCdf (const char *prefix, const VectorSet< V, M > &pdfSupport, const V &domainExpectedValues, const V &domainVarianceValues)
TODO: Constructor.
GaussianVectorCdf (const char *prefix, const VectorSet< V, M > &pdfSupport, const V &domainExpectedValues, const M &covMatrix)
TODO: Constructor.
~GaussianVectorCdf ()
Mathematical method
void values (const V &paramValues, V &cdfVec) const
TODO: Returns the values of the vector CDF at each element of paramValues.
I/O method
void print (std::ostream &os) const
TODO: Prints the vector CDF.
Public Member Functions inherited from QUESO::BaseVectorCdf< V, M >
BaseVectorCdf (const char *prefix, const VectorSet< V, M > &pdfSupport)
Default constructor.
virtual ~BaseVectorCdf ()
Virtual destructor.
const VectorSet< V, M > & pdfSupport () const
Returns the image set (support) of the PDF; access to protected attribute m_pdfSupport.
virtual const BaseScalarCdf
< double > & cdf (unsigned int rowId) const =0
virtual void subWriteContents (const std::string &varNamePrefix, const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds) const
Writes the CDF of an allowed sub-environment to a file.
Protected Member Functions
void commonConstructor ()
A common constructor to be used both class constructors.
Protected Attributes
const M * m_covMatrix
Protected Attributes inherited from QUESO::BaseVectorCdf< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_pdfSupport
Detailed Description
template<class V, class M>
class QUESO::GaussianVectorCdf< V, M >
TODO: A class for handling Gaussian CDFs.
This class will implement a Gaussian vector cumulative distribution function (CDF).
Todo:
: Implement me!
Definition at line 48 of file GaussianVectorCdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::GaussianVectorCdf< V, M >::GaussianVectorCdf (const char * prefix, const VectorSet< V, M > & pdfSupport, const V & domainExpectedValues, const V & domainVarianceValues)
TODO: Constructor.
Todo:
: implement me! This method calls commonConstructor() which is not yet implemented. Instantiates an object of the class given a prefix, the support of the related-PDF, and the domain mean and expected values.
Definition at line 31 of file GaussianVectorCdf.C.
References QUESO::GaussianVectorCdf< V, M >::commonConstructor(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorCdf< V, M >::m_env, QUESO::BaseVectorCdf< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorCdf<V,M>(prefix,pdfSupport),
   m_covMatrix              (m_pdfSupport.newDiagMatrix(domainVarianceValues*domainVarianceValues))
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering GaussianVectorCdf<V,M>::constructor() [1]"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving GaussianVectorCdf<V,M>::constructor() [1]"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
 }
template<class V , class M > QUESO::GaussianVectorCdf< V, M >::GaussianVectorCdf (const char * prefix, const VectorSet< V, M > & pdfSupport, const V & domainExpectedValues, const M & covMatrix)
TODO: Constructor.
Todo:
: implement me! This method calls commonConstructor() which is not yet implemented. Instantiates an object of the class given a prefix, the support of the related-PDF, and the domain mean values and covariance matrix.
Definition at line 56 of file GaussianVectorCdf.C.
References QUESO::GaussianVectorCdf< V, M >::commonConstructor(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseVectorCdf< V, M >::m_env, QUESO::BaseVectorCdf< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseVectorCdf<V,M>(prefix,pdfSupport),
   m_covMatrix              (new M(covMatrix))
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Entering GaussianVectorCdf<V,M>::constructor() [2]"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 5)) {
     *m_env.subDisplayFile() << "Leaving GaussianVectorCdf<V,M>::constructor() [2]"
                            << ": prefix = " << m_prefix
                            << std::endl;
   }
 }
template<class V , class M > QUESO::GaussianVectorCdf< V, M >::~GaussianVectorCdf ()
Definition at line 81 of file GaussianVectorCdf.C.
 {
   delete m_covMatrix;
 }
Member Function Documentation
template<class V , class M > void QUESO::GaussianVectorCdf< V, M >::commonConstructor () protected
A common constructor to be used both class constructors.
Definition at line 109 of file GaussianVectorCdf.C.
References UQ_FATAL_TEST_MACRO.
Referenced by QUESO::GaussianVectorCdf< V, M >::GaussianVectorCdf().
 {
   UQ_FATAL_TEST_MACRO(true,
                       m_env.worldRank(),
                       "GaussianVectorCdf<V,M>::commonConstructor()",
                       "incomplete code");
   return;
 }
template<class V , class M > void QUESO::GaussianVectorCdf< V, M >::print (std::ostream & os) const virtual
TODO: Prints the vector CDF.
Todo:
: implement me!
Implements QUESO::BaseVectorCdf< V, M >.
Definition at line 101 of file GaussianVectorCdf.C.
 {
   return;
 }
template<class V , class M > void QUESO::GaussianVectorCdf< V, M >::values (const V & paramValues, V & cdfVec) const virtual
TODO: Returns the values of the vector CDF at each element of paramValues.
Todo:
: implement me!
Implements QUESO::BaseVectorCdf< V, M >.
Definition at line 88 of file GaussianVectorCdf.C.
References UQ_FATAL_TEST_MACRO.
 {
   UQ_FATAL_TEST_MACRO(true,
                       m_env.worldRank(),
                       "GaussianVectorCdf<V,M>::cdfVec()",
                       "incomplete code");
   return;
 }
Member Data Documentation
template<class V , class M > const M* QUESO::GaussianVectorCdf< V, M >::m_covMatrix protected
Definition at line 88 of file GaussianVectorCdf.h.
The documentation for this class was generated from the following files:
src/stats/inc/GaussianVectorCdf.h
src/stats/src/GaussianVectorCdf.C