queso-0.57.0: QUESO::BaseTKGroup< V, M > Class Template Reference
QUESO::BaseTKGroup< V, M > Class Template Reference abstract
This base class allows the representation of a transition kernel.
#include <Algorithm.h>
Public Member Functions
Constructor/Destructor methods
BaseTKGroup ()
Default constructor.
BaseTKGroup (const char *prefix, const VectorSpace< V, M > &vectorSpace, const std::vector< double > &scales)
Constructor.
virtual ~BaseTKGroup ()
Destructor.
Statistical/Mathematical methods
virtual bool symmetric () const =0
Whether or not the matrix is symmetric. See template specialization.
virtual const BaseVectorRV< V,
M > & rv (unsigned int stageId) const =0
Gaussian increment property to construct a transition kernel. See template specialization.
virtual const BaseVectorRV< V,
M > & rv (const std::vector< unsigned int > &stageIds)=0
Gaussian increment property to construct a transition kernel. See template specialization.
virtual const BaseVectorRV< V,
M > & rv (const V &position) const =0
Constructs transition kernel pdf based on internal m_stageId variable.
Misc methods
const BaseEnvironment & env () const
QUESO's environment.
const V & preComputingPosition (unsigned int stageId) const
Pre-computing position; access to protected attribute *m_preComputingPositions[stageId].
virtual bool setPreComputingPosition (const V &position, unsigned int stageId)
Sets the pre-computing positions m_preComputingPositions[stageId] with a new vector of size position.
virtual void clearPreComputingPositions ()
Clears the pre-computing positions m_preComputingPositions[stageId].
virtual unsigned int set_dr_stage (unsigned int stageId)
Does nothing. Subclasses may re-implement. Returns the current stage id.
virtual void updateTK ()
virtual bool covMatrixIsDirty ()=0
virtual void cleanCovMatrix ()=0
I/O methods
virtual void print (std::ostream &os) const
TODO: Prints the transition kernel.
Protected Attributes
const EmptyEnvironment * m_emptyEnv
const BaseEnvironment & m_env
std::string m_prefix
const VectorSpace< V, M > * m_vectorSpace
std::vector< double > m_scales
std::vector< const V * > m_preComputingPositions
std::vector< BaseVectorRV< V,
M > * > m_rvs
unsigned int m_stageId
Detailed Description
template<class V, class M>
class QUESO::BaseTKGroup< V, M >
This base class allows the representation of a transition kernel.
The transition kernel is a conditional distribution function that represents the probability of moving from a point to a point in the set , where is a Borel set over . Since it is a distribution function, , where it is permitted that the chain can make a transition from the point to , that is is not necessarily zero.
Definition at line 32 of file Algorithm.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::BaseTKGroup< V, M >::BaseTKGroup ()
Default constructor.
Definition at line 33 of file TKGroup.C.
   :
   m_emptyEnv             (new EmptyEnvironment()),
   m_env                  (*m_emptyEnv),
   m_prefix               (""),
   m_vectorSpace          (NULL),
   m_scales               (),
   m_preComputingPositions(),
   m_rvs                  (),
   m_stageId              (0)
 {
 }
template<class V, class M> QUESO::BaseTKGroup< V, M >::BaseTKGroup (const char * prefix, const VectorSpace< V, M > & vectorSpace, const std::vector< double > & scales)
Constructor.
Definition at line 47 of file TKGroup.C.
References QUESO::BaseTKGroup< V, M >::m_scales.
   :
   m_emptyEnv             (NULL),
   m_env                  (vectorSpace.env()),
   m_prefix               (prefix),
   m_vectorSpace          (&vectorSpace),
   m_scales               (scales.size(),1.),
   m_preComputingPositions(scales.size()+1,NULL), // Yes, +1
   m_rvs                  (scales.size(),NULL), // IMPORTANT: it stays like this for scaledTK, but it will be overwritten to '+1' by hessianTK constructor
   m_stageId              (0)
 {
   for (unsigned int i = 0; i < m_scales.size(); ++i) {
     m_scales[i] = scales[i];
   }
 }
template<class V , class M > QUESO::BaseTKGroup< V, M >::~BaseTKGroup () virtual
Destructor.
Definition at line 67 of file TKGroup.C.
 {
   for (unsigned int i = 0; i < m_rvs.size(); ++i) {
     if (m_rvs[i]) delete m_rvs[i];
   }
   for (unsigned int i = 0; i < m_preComputingPositions.size(); ++i) {
     if (m_preComputingPositions[i]) delete m_preComputingPositions[i];
   }
   if (m_emptyEnv) delete m_emptyEnv;
 }
Member Function Documentation
template<class V, class M> virtual void QUESO::BaseTKGroup< V, M >::cleanCovMatrix () pure virtual
Performs whatever cleanup is needed (usually just resetting an internal bool flag) after the covariance matrix was modified.
After this method is called, covMatrixIsDirty should return true.
Implemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::MetropolisAdjustedLangevinTK< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
template<class V , class M > void QUESO::BaseTKGroup< V, M >::clearPreComputingPositions () virtual
Clears the pre-computing positions m_preComputingPositions[stageId].
Reimplemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::MetropolisAdjustedLangevinTK< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
Definition at line 111 of file TKGroup.C.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::clearPreComputingPositions(), QUESO::ScaledCovMatrixTKGroup< V, M >::clearPreComputingPositions(), QUESO::MetropolisAdjustedLangevinTK< V, M >::clearPreComputingPositions(), and QUESO::TransformedScaledCovMatrixTKGroup< V, M >::clearPreComputingPositions().
 {
   for (unsigned int i = 0; i < m_preComputingPositions.size(); ++i) {
     if (m_preComputingPositions[i]) {
       delete m_preComputingPositions[i];
       m_preComputingPositions[i] = NULL;
     }
   }
   return;
 }
template<class V, class M> virtual bool QUESO::BaseTKGroup< V, M >::covMatrixIsDirty () pure virtual
This method determines whether or not the user has 'dirtied' the covariance matrix, thereby necessitating an AM reset.
Should return true if the cov matrix was modified in such a way to affect the Adaptive Metropolis sample covariance calculation.
Implemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::MetropolisAdjustedLangevinTK< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
template<class V , class M > const BaseEnvironment & QUESO::BaseTKGroup< V, M >::env () const
QUESO's environment.
Definition at line 80 of file TKGroup.C.
 {
   return m_env;
 }
template<class V , class M > const V & QUESO::BaseTKGroup< V, M >::preComputingPosition (unsigned int stageId) const
Pre-computing position; access to protected attribute *m_preComputingPositions[stageId].
Definition at line 87 of file TKGroup.C.
 {
   queso_require_greater_msg(m_preComputingPositions.size(), stageId, "m_preComputingPositions.size() <= stageId");
   queso_require_msg(m_preComputingPositions[stageId], "m_preComputingPositions[stageId] == NULL");
   return *m_preComputingPositions[stageId];
 }
template<class V , class M > void QUESO::BaseTKGroup< V, M >::print (std::ostream & os) const virtual
TODO: Prints the transition kernel.
Todo:
: implement me!
Reimplemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::MetropolisAdjustedLangevinTK< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
Definition at line 133 of file TKGroup.C.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::print(), QUESO::ScaledCovMatrixTKGroup< V, M >::print(), QUESO::MetropolisAdjustedLangevinTK< V, M >::print(), and QUESO::TransformedScaledCovMatrixTKGroup< V, M >::print().
 {
   os << "In BaseTKGroup<V,M>::print()"
      << ": nothing to be printed" << std::endl;
   return;
 }
template<class V, class M> virtual const BaseVectorRV<V,M>& QUESO::BaseTKGroup< V, M >::rv (unsigned int stageId) const pure virtual
Gaussian increment property to construct a transition kernel. See template specialization.
Implemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::HessianCovMatricesTKGroup< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::MetropolisAdjustedLangevinTK< V, M >.
template<class V, class M> virtual const BaseVectorRV<V,M>& QUESO::BaseTKGroup< V, M >::rv (const std::vector< unsigned int > & stageIds) pure virtual
Gaussian increment property to construct a transition kernel. See template specialization.
Implemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::HessianCovMatricesTKGroup< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::MetropolisAdjustedLangevinTK< V, M >.
template<class V, class M> virtual const BaseVectorRV<V, M>& QUESO::BaseTKGroup< V, M >::rv (const V & position) const pure virtual
Constructs transition kernel pdf based on internal m_stageId variable.
Implemented in QUESO::MetropolisAdjustedLangevinTK< V, M >, QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::HessianCovMatricesTKGroup< V, M >, and QUESO::ScaledCovMatrixTKGroup< V, M >.
template<class V , class M > unsigned int QUESO::BaseTKGroup< V, M >::set_dr_stage (unsigned int stageId) virtual
Does nothing. Subclasses may re-implement. Returns the current stage id.
Reimplemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
Definition at line 125 of file TKGroup.C.
 {
   return this->m_stageId;
 }
template<class V, class M > bool QUESO::BaseTKGroup< V, M >::setPreComputingPosition (const V & position, unsigned int stageId) virtual
Sets the pre-computing positions m_preComputingPositions[stageId] with a new vector of size position.
Reimplemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::MetropolisAdjustedLangevinTK< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::HessianCovMatricesTKGroup< V, M >.
Definition at line 98 of file TKGroup.C.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::setPreComputingPosition(), QUESO::ScaledCovMatrixTKGroup< V, M >::setPreComputingPosition(), QUESO::MetropolisAdjustedLangevinTK< V, M >::setPreComputingPosition(), and QUESO::TransformedScaledCovMatrixTKGroup< V, M >::setPreComputingPosition().
 {
   queso_require_greater_msg(m_preComputingPositions.size(), stageId, "m_preComputingPositions.size() <= stageId");
   queso_require_msg(!(m_preComputingPositions[stageId]), "m_preComputingPositions[stageId] != NULL");
   m_preComputingPositions[stageId] = new V(position);
   return true;
 }
template<class V, class M> virtual bool QUESO::BaseTKGroup< V, M >::symmetric () const pure virtual
Whether or not the matrix is symmetric. See template specialization.
Implemented in QUESO::TransformedScaledCovMatrixTKGroup< V, M >, QUESO::HessianCovMatricesTKGroup< V, M >, QUESO::ScaledCovMatrixTKGroup< V, M >, and QUESO::MetropolisAdjustedLangevinTK< V, M >.
template<class V, class M> virtual void QUESO::BaseTKGroup< V, M >::updateTK () inline virtual
The user can override this method to implement state-dependent transition kernel behaviour.
Default behaviour is a no-op.
Definition at line 102 of file TKGroup.h.
 { };
Member Data Documentation
template<class V, class M> const EmptyEnvironment* QUESO::BaseTKGroup< V, M >::m_emptyEnv protected
Definition at line 127 of file TKGroup.h.
template<class V, class M> const BaseEnvironment& QUESO::BaseTKGroup< V, M >::m_env protected
Definition at line 128 of file TKGroup.h.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), QUESO::MetropolisAdjustedLangevinTK< V, M >::MetropolisAdjustedLangevinTK(), QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup(), and QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup().
template<class V, class M> std::vector<const V*> QUESO::BaseTKGroup< V, M >::m_preComputingPositions protected
Definition at line 132 of file TKGroup.h.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), QUESO::MetropolisAdjustedLangevinTK< V, M >::MetropolisAdjustedLangevinTK(), QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup(), and QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup().
template<class V, class M> std::string QUESO::BaseTKGroup< V, M >::m_prefix protected
Definition at line 129 of file TKGroup.h.
template<class V, class M> std::vector<BaseVectorRV<V,M>* > QUESO::BaseTKGroup< V, M >::m_rvs protected
Definition at line 133 of file TKGroup.h.
Referenced by QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), QUESO::MetropolisAdjustedLangevinTK< V, M >::MetropolisAdjustedLangevinTK(), QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup(), and QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup().
template<class V, class M> std::vector<double> QUESO::BaseTKGroup< V, M >::m_scales protected
Definition at line 131 of file TKGroup.h.
Referenced by QUESO::BaseTKGroup< V, M >::BaseTKGroup(), QUESO::HessianCovMatricesTKGroup< V, M >::HessianCovMatricesTKGroup(), QUESO::MetropolisAdjustedLangevinTK< V, M >::MetropolisAdjustedLangevinTK(), QUESO::ScaledCovMatrixTKGroup< V, M >::ScaledCovMatrixTKGroup(), and QUESO::TransformedScaledCovMatrixTKGroup< V, M >::TransformedScaledCovMatrixTKGroup().
template<class V, class M> unsigned int QUESO::BaseTKGroup< V, M >::m_stageId protected
Definition at line 134 of file TKGroup.h.
template<class V, class M> const VectorSpace<V,M>* QUESO::BaseTKGroup< V, M >::m_vectorSpace protected
Definition at line 130 of file TKGroup.h.
The documentation for this class was generated from the following files:
src/stats/inc/Algorithm.h
src/stats/inc/TKGroup.h
src/stats/src/TKGroup.C