queso-0.57.1: QUESO::FullEnvironment Class Reference
QUESO::FullEnvironment Class Reference
This class sets up the full environment underlying the use of the QUESO library by an executable.
#include <Environment.h>
Public Member Functions
Constructor/Destructor methods
FullEnvironment (RawType_MPI_Comm inputComm, const char *passedOptionsInputFileName, const char *prefix, EnvOptionsValues *alternativeOptionsValues)
Parallel constructor.
FullEnvironment (RawType_MPI_Comm inputComm, const std::string &passedOptionsInputFileName, const std::string &prefix, EnvOptionsValues *alternativeOptionsValues)
FullEnvironment (const char *passedOptionsInputFileName, const char *prefix, EnvOptionsValues *alternativeOptionsValues)
Serial constructor.
FullEnvironment (const std::string &passedOptionsInputFileName, const std::string &prefix, EnvOptionsValues *alternativeOptionsValues)
~FullEnvironment ()
Destructor.
I/O methods
void print (std::ostream &os) const
Sends the environment options to the stream.
Public Member Functions inherited from QUESO::BaseEnvironment
BaseEnvironment (const char *passedOptionsInputFileName, EnvOptionsValues *alternativeOptionsValues)
Default constructor.
BaseEnvironment (const std::string &passedOptionsInputFileName, EnvOptionsValues *alternativeOptionsValues)
virtual ~BaseEnvironment ()
Destructor.
bool fullEnvIsReady () const
Returns whether the full environment class is ready (constructor has successfully been called).
int worldRank () const
Returns the same thing as fullRank()
int fullRank () const
Returns the rank of the MPI process in QUESO's full communicator.
const MpiComm & fullComm () const
Access function for the communicator that was passed to QUESO's environment.
RawType_MPI_Group subGroup () const
Access function for sub-group.
int subRank () const
Returns the rank of the MPI process in the sub-communicator subComm()
const MpiComm & subComm () const
Access function for each sub-environment's communicator.
const MpiComm & selfComm () const
Access function for MpiComm self-communicator.
int inter0Rank () const
Returns the process inter0 rank.
const MpiComm & inter0Comm () const
Access function for MpiComm communicator for processes with subRank() 0.
std::ofstream * subDisplayFile () const
Access function for m_subDisplayFile (displays file on stream).
std::string subDisplayFileName () const
Access function for m_subDisplayFileName (displays filename on stream).
unsigned int numSubEnvironments () const
Access function to the number of sub-environments.
unsigned int subId () const
Access function to the number of each sub-environment Id: m_subId.
const std::string & subIdString () const
Access to the attribute m_subIdString; which stores the string for the sub-environment, and it will be used, for instance, to create the output files for each sub-environment.
void checkTheParallelEnvironment () const
std::string optionsInputFileName () const
Access to the attribute m_optionsInputFileName, which stores the name of the input file passed by the user to QUESO.
void setOptionsInputFileAccessState (bool newState) const
const
boost::program_options::options_description & allOptionsDesc () const
boost::program_options::variables_map & allOptionsMap () const
void scanInputFileForMyOptions (const boost::program_options::options_description &optionsDesc) const
This method scans the input file provided by the user to QUESO.
unsigned int displayVerbosity () const
unsigned int syncVerbosity () const
Access function to private attribute m_syncVerbosity.
unsigned int checkingLevel () const
Access function to private attribute m_checkingLevel.
const RngBase * rngObject () const
Access to the RNG object.
void resetSeed (int newSeedOption)
Reset RNG seed.
int seed () const
Access to the RNG seed.
const BasicPdfsBase * basicPdfs () const
Access to Basic PDFs.
std::string platformName () const
Access to the platform name.
std::string identifyingString () const
Access function to private attribute m_identifyingString: identifying string.
void resetIdentifyingString (const std::string &newString)
Reset private attribute m_identifyingString with the value newString.
bool isThereInputFile () const
//TODO Not implemented? it is called in examples/validationCycle/tests_old/results_5_25/uqTgaEx4.h.
struct timeval timevalBegin () const
Used to save the time when the combo `QUESO+user's application' started to run.
bool openOutputFile (const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds, bool writeOver, FilePtrSetStruct &filePtrSet) const
Opens an output file for each sub-environment that was chosen to send data to the file.
bool openUnifiedOutputFile (const std::string &fileName, const std::string &fileType, bool writeOver, FilePtrSetStruct &filePtrSet) const
Opens a unified output file, that will contain data from all sub-environments.
bool openInputFile (const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds, FilePtrSetStruct &filePtrSet) const
Opens an input file.
bool openUnifiedInputFile (const std::string &fileName, const std::string &fileType, FilePtrSetStruct &filePtrSet) const
Opens the unified input file.
void closeFile (FilePtrSetStruct &filePtrSet, const std::string &fileType) const
Closes the file.
void setExceptionalCircumstance (bool value) const
Set an exceptional circumstance.
bool exceptionalCircumstance () const
Decides whether there is an exceptional circumstance.
const GetPot & input () const
The GetPot input file parser.
Private Member Functions
void construct (RawType_MPI_Comm inputComm, const char *prefix)
Named constructor backend for multiple constructor overloads.
void construct (const char *prefix)
Named constructor backend for multiple constructor overloads.
void readOptionsInputFile ()
Checks the options input file and reads the options.
Additional Inherited Members
Protected Attributes inherited from QUESO::BaseEnvironment
bool m_fullEnvIsReady
int m_worldRank
ScopedPtr< MpiComm >::Type m_fullComm
int m_fullRank
int m_fullCommSize
RawType_MPI_Group m_fullGroup
std::string m_optionsInputFileName
bool m_optionsInputFileAccessState
ScopedPtr
< boost::program_options::options_description >
::Type m_allOptionsDesc
ScopedPtr
< boost::program_options::variables_map >
::Type m_allOptionsMap
ScopedPtr< GetPot >::Type m_input
unsigned int m_subId
std::string m_subIdString
RawType_MPI_Group m_subGroup
ScopedPtr< MpiComm >::Type m_subComm
int m_subRank
int m_subCommSize
ScopedPtr< MpiComm >::Type m_selfComm
RawType_MPI_Group m_inter0Group
ScopedPtr< MpiComm >::Type m_inter0Comm
int m_inter0Rank
int m_inter0CommSize
ScopedPtr< std::ofstream >::Type m_subDisplayFile
ScopedPtr< RngBase >::Type m_rngObject
ScopedPtr< BasicPdfsBase >::Type m_basicPdfs
struct timeval m_timevalBegin
bool m_exceptionalCircumstance
ScopedPtr< EnvOptionsValues >::Type m_optionsObj
Detailed Description
This class sets up the full environment underlying the use of the QUESO library by an executable.
This is the class that is actually used during a QUESO+application run.
Definition at line 508 of file Environment.h.
Constructor & Destructor Documentation
QUESO::FullEnvironment::FullEnvironment (RawType_MPI_Comm inputComm, const char * passedOptionsInputFileName, const char * prefix, EnvOptionsValues * alternativeOptionsValues)
Parallel constructor.
Initializes the full communicator, reads the options, deals with multiple sub-environments, e.g. dealing with sub/self/inter0-communicators, handles path for output files.
Definition at line 1179 of file Environment.C.
References construct().
   :
   BaseEnvironment(passedOptionsInputFileName,alternativeOptionsValues)
 {
   this->construct(inputComm, prefix);
 }
QUESO::FullEnvironment::FullEnvironment (RawType_MPI_Comm inputComm, const std::string & passedOptionsInputFileName, const std::string & prefix, EnvOptionsValues * alternativeOptionsValues)
Definition at line 1190 of file Environment.C.
References construct().
   :
   BaseEnvironment(passedOptionsInputFileName,alternativeOptionsValues)
 {
   this->construct(inputComm, prefix.c_str());
 }
QUESO::FullEnvironment::FullEnvironment (const char * passedOptionsInputFileName, const char * prefix, EnvOptionsValues * alternativeOptionsValues)
Serial constructor.
No communicator is passed. Output path handling is exactly as in the parallel ctor.
Definition at line 1467 of file Environment.C.
References construct().
   :
   BaseEnvironment(passedOptionsInputFileName,alternativeOptionsValues)
 {
   this->construct(prefix);
 }
QUESO::FullEnvironment::FullEnvironment (const std::string & passedOptionsInputFileName, const std::string & prefix, EnvOptionsValues * alternativeOptionsValues)
Definition at line 1477 of file Environment.C.
References construct().
   :
   BaseEnvironment(passedOptionsInputFileName,alternativeOptionsValues)
 {
   this->construct(prefix.c_str());
 }
QUESO::FullEnvironment::~FullEnvironment ()
Destructor.
Definition at line 1720 of file Environment.C.
 {
 }
Member Function Documentation
void QUESO::FullEnvironment::construct (RawType_MPI_Comm inputComm, const char * prefix) private
Named constructor backend for multiple constructor overloads.
Definition at line 1202 of file Environment.C.
References QUESO::CheckFilePath(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseEnvironment::fullComm(), QUESO::BaseEnvironment::m_allOptionsDesc, QUESO::BaseEnvironment::m_allOptionsMap, QUESO::BaseEnvironment::m_basicPdfs, QUESO::BaseEnvironment::m_fullComm, QUESO::BaseEnvironment::m_fullCommSize, QUESO::BaseEnvironment::m_fullEnvIsReady, QUESO::BaseEnvironment::m_fullGroup, QUESO::BaseEnvironment::m_fullRank, QUESO::BaseEnvironment::m_input, QUESO::BaseEnvironment::m_inter0Comm, QUESO::BaseEnvironment::m_inter0CommSize, QUESO::BaseEnvironment::m_inter0Group, QUESO::BaseEnvironment::m_inter0Rank, QUESO::BaseEnvironment::m_optionsInputFileName, QUESO::BaseEnvironment::m_optionsObj, QUESO::BaseEnvironment::m_rngObject, QUESO::BaseEnvironment::m_selfComm, QUESO::BaseEnvironment::m_subComm, QUESO::BaseEnvironment::m_subCommSize, QUESO::BaseEnvironment::m_subDisplayFile, QUESO::BaseEnvironment::m_subGroup, QUESO::BaseEnvironment::m_subId, QUESO::BaseEnvironment::m_subIdString, QUESO::BaseEnvironment::m_subRank, QUESO::BaseEnvironment::m_timevalBegin, QUESO::BaseEnvironment::m_worldRank, QUESO::old_terminate_handler, QUESO::queso_require_equal_to_msg, QUESO::queso_terminate_handler(), QUESO::QUESO_version_print(), and readOptionsInputFile().
Referenced by FullEnvironment().
 {
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "Entering FullEnv" << std::endl;
 #endif
   // Initialize "full" communicator -- Not necessarily MPI_COMM_WORLD
   int mpiRC = MPI_Comm_rank(inputComm,&m_worldRank);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed to get world fullRank()");
   m_fullComm.reset(new MpiComm(*this,inputComm));
   m_fullRank     = m_fullComm->MyPID();
   m_fullCommSize = m_fullComm->NumProc();
   mpiRC = MPI_Comm_group(m_fullComm->Comm(), &m_fullGroup);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed MPI_Comm_group()");
   // saving old uncaught exception handler, invoking queso_terminate
   old_terminate_handler = std::set_terminate(queso_terminate_handler);
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "In FullEnv, finished dealing with MPI initially" << std::endl;
 #endif
   // Read options
   // If NULL, we create one
   if (m_optionsObj == NULL) {
     // If there's an input file, we grab the options from there.  Otherwise the
     // defaults are used
     if (m_optionsInputFileName != "") {
 #ifndef QUESO_DISABLE_BOOST_PROGRAM_OPTIONS
       m_allOptionsMap.reset(new boost::program_options::variables_map());
       m_allOptionsDesc.reset(new boost::program_options::options_description("Allowed options"));
 #endif  // QUESO_DISABLE_BOOST_PROGRAM_OPTIONS
       readOptionsInputFile();
       m_input->parse_input_file(m_optionsInputFileName);
     }
     m_optionsObj.reset(new EnvOptionsValues(this, prefix));
   }
   // If help option was supplied, print info
   if (m_optionsObj->m_help != "") {
     // We write to std::cout because subDisplayFile() isn't ready yet?
     std::cout << (*m_optionsObj) << std::endl;
   }
   queso_require_equal_to_msg(
       fullComm().NumProc() % m_optionsObj->m_numSubEnvironments, 0,
       "total number of processors in environment must be multiple of the specified number of subEnvironments");
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "In FullEnv, finished scanning options" << std::endl;
 #endif
   // Only display these messages if the user wants them
   // NOTE: This got moved below the Read Options section
   // because we need the options to be read to know what
   // the verbosity level is.
   if (this->displayVerbosity() > 0) {
     // Display main initial messages
     // 'std::cout' is for: main trace messages + synchronized trace messages + error messages prior to 'exit()' or 'abort()'
     /*int iRC = 0;*/
     /*iRC = */gettimeofday(&m_timevalBegin, NULL);
     if (m_fullRank == 0) {
       QUESO_version_print(std::cout);
     }
     if (m_fullRank == 0) {
       std::cout << "Beginning run at " << ctime(&m_timevalBegin.tv_sec)
                 << std::endl;
     }
   }
   // Deal with multiple subEnvironments: create the sub communicators, one for each subEnvironment
   unsigned int numRanksPerSubEnvironment = m_fullCommSize/m_optionsObj->m_numSubEnvironments;
   m_subId = m_fullRank/numRanksPerSubEnvironment;
   char tmpSubId[16];
   sprintf(tmpSubId,"%u",m_subId);
   m_subIdString = tmpSubId;
   if (m_optionsObj->m_subDisplayAllowAll) {
     m_optionsObj->m_subDisplayAllowedSet.insert((unsigned int) m_subId);
   }
   std::vector<int> fullRanksOfMySubEnvironment(numRanksPerSubEnvironment,0);
   for (unsigned int i = 0; i < numRanksPerSubEnvironment; ++i) {
     fullRanksOfMySubEnvironment[i] = m_subId * numRanksPerSubEnvironment + i;
   }
   mpiRC = MPI_Group_incl(m_fullGroup, (int) numRanksPerSubEnvironment, &fullRanksOfMySubEnvironment[0], &m_subGroup);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed MPI_Group_incl() for a subEnvironment");
   RawType_MPI_Comm subRawComm;
   mpiRC = MPI_Comm_create(m_fullComm->Comm(), m_subGroup, &subRawComm);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed MPI_Comm_group() for a subEnvironment");
   m_subComm.reset(new MpiComm(*this,subRawComm));
   m_subRank     = m_subComm->MyPID();
   m_subCommSize = m_subComm->NumProc();
   // Deal with multiple subEnvironments: create the self communicator
   m_selfComm.reset(new MpiComm(*this,RawValue_MPI_COMM_SELF));
   // Deal with multiple subEnvironments: create the inter0 communicator
   std::vector<int> fullRanksOfInter0(m_optionsObj->m_numSubEnvironments,0);
   for (unsigned int i = 0; i < m_optionsObj->m_numSubEnvironments; ++i) {
     fullRanksOfInter0[i] = i * numRanksPerSubEnvironment;
   }
   mpiRC = MPI_Group_incl(m_fullGroup, (int) m_optionsObj->m_numSubEnvironments, &fullRanksOfInter0[0], &m_inter0Group);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed MPI_Group_incl() for inter0");
   RawType_MPI_Comm inter0RawComm;
   mpiRC = MPI_Comm_create(m_fullComm->Comm(), m_inter0Group, &inter0RawComm);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed MPI_Comm_group() for inter0");
   if (m_fullRank%numRanksPerSubEnvironment == 0) {
     m_inter0Comm.reset(new MpiComm(*this,inter0RawComm));
     m_inter0Rank     = m_inter0Comm->MyPID();
     m_inter0CommSize = m_inter0Comm->NumProc();
   }
   if (m_optionsObj->m_subDisplayAllowAll) {
     // This situation has been already taken care of above
   }
   else if (m_optionsObj->m_subDisplayAllowInter0) {
     if (m_inter0Rank >= 0) {
       m_optionsObj->m_subDisplayAllowedSet.insert((unsigned int) m_subId);
     }
   }
   // Open "screen" file
   bool openFile = false;
   if ((m_subRank                                               == 0                                              ) &&
       (m_optionsObj->m_subDisplayFileName                 != UQ_ENV_FILENAME_FOR_NO_OUTPUT_FILE             ) &&
       (m_optionsObj->m_subDisplayAllowedSet.find(m_subId) != m_optionsObj->m_subDisplayAllowedSet.end())) {
     openFile = true;
   }
   if (openFile && m_worldRank == 0) {
     // Verify parent directory exists (for cases when a user
     // specifies a relative path for the desired output file).
     int irtrn = CheckFilePath((m_optionsObj->m_subDisplayFileName+"_sub"+m_subIdString+".txt").c_str());
     queso_require_greater_equal_msg(irtrn, 0, "unable to verify output path");
   }
   // Ensure that rank 0 has created path, if necessary, before other tasks use it
   m_fullComm->Barrier();
   if (openFile) {
     // Always write over an eventual pre-existing file
     m_subDisplayFile.reset(new std::ofstream((m_optionsObj->m_subDisplayFileName+"_sub"+m_subIdString+".txt").c_str(),
                                          std::ofstream::out | std::ofstream::trunc));
     queso_require_msg((m_subDisplayFile && m_subDisplayFile->is_open()), "failed to open sub screen file");
     QUESO_version_print(*m_subDisplayFile);
     *m_subDisplayFile << "Beginning run at " << ctime(&m_timevalBegin.tv_sec)
                       << std::endl;
   }
   // Debug message related to subEnvironments
   if (this->displayVerbosity() >= 2) {
     for (int i = 0; i < m_fullCommSize; ++i) {
       if (i == m_fullRank) {
         //std::cout << "In FullEnvironment::commonConstructor()"
         std::cout << "MPI node of worldRank "             << m_worldRank
                   << " has fullRank "                     << m_fullRank
                   << ", belongs to subEnvironment of id " << m_subId
                   << ", and has subRank "                 << m_subRank
                   << std::endl;
         std::cout << "MPI node of worldRank " << m_worldRank
                   << " belongs to sub communicator with full ranks";
         for (unsigned int j = 0; j < fullRanksOfMySubEnvironment.size(); ++j) {
           std::cout << " " << fullRanksOfMySubEnvironment[j];
         }
         std::cout << "\n";
         if (m_inter0Comm) {
           std::cout << "MPI node of worldRank " << m_worldRank
                     << " also belongs to inter0 communicator with full ranks";
           for (unsigned int j = 0; j < fullRanksOfInter0.size(); ++j) {
             std::cout << " " << fullRanksOfInter0[j];
           }
           std::cout << ", and has inter0Rank " << m_inter0Rank;
         }
         std::cout << "\n";
         std::cout << std::endl;
       }
       m_fullComm->Barrier();
     }
     //if (this->fullRank() == 0) std::cout << "Sleeping 3 seconds..."
     //                                     << std::endl;
     //sleep(3);
   }
   // Deal with seed
   if (m_optionsObj->m_rngType == "gsl") {
     m_rngObject.reset(new RngGsl(m_optionsObj->m_seed,m_worldRank));
     m_basicPdfs.reset(new BasicPdfsGsl(m_worldRank));
   }
   else if (m_optionsObj->m_rngType == "boost") {
     m_rngObject.reset(new RngBoost(m_optionsObj->m_seed,m_worldRank));
     m_basicPdfs.reset(new BasicPdfsBoost(m_worldRank));
   }
   else if (m_optionsObj->m_rngType == "cxx11") {
 #ifdef QUESO_HAVE_CXX11
     m_rngObject.reset(new RngCXX11(m_optionsObj->m_seed, m_worldRank));
     m_basicPdfs.reset(new BasicPdfsCXX11(m_worldRank));
 #else
     queso_error_msg("C++11 RNGs requested, but QUESO wasn't compiled with C++11 support");
 #endif
   }
   else {
     std::cerr << "In Environment::constructor()"
               << ": rngType = " << m_optionsObj->m_rngType
               << std::endl;
     queso_error_msg("the requested 'rngType' is not supported yet");
   }
   // Leave commonConstructor()
   m_fullComm->Barrier();
   m_fullEnvIsReady = true;
   if ((m_subDisplayFile) && (this->displayVerbosity() >= 5)) {
     *m_subDisplayFile << "Done with initializations at FullEnvironment::commonConstructor()"
                       << std::endl;
   }
   return;
 }
void QUESO::FullEnvironment::construct (const char * prefix) private
Named constructor backend for multiple constructor overloads.
Definition at line 1488 of file Environment.C.
References QUESO::CheckFilePath(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseEnvironment::fullComm(), QUESO::BaseEnvironment::m_allOptionsDesc, QUESO::BaseEnvironment::m_allOptionsMap, QUESO::BaseEnvironment::m_basicPdfs, QUESO::BaseEnvironment::m_fullComm, QUESO::BaseEnvironment::m_fullCommSize, QUESO::BaseEnvironment::m_fullEnvIsReady, QUESO::BaseEnvironment::m_fullGroup, QUESO::BaseEnvironment::m_fullRank, QUESO::BaseEnvironment::m_input, QUESO::BaseEnvironment::m_inter0Comm, QUESO::BaseEnvironment::m_inter0CommSize, QUESO::BaseEnvironment::m_inter0Group, QUESO::BaseEnvironment::m_inter0Rank, QUESO::BaseEnvironment::m_optionsInputFileName, QUESO::BaseEnvironment::m_optionsObj, QUESO::BaseEnvironment::m_rngObject, QUESO::BaseEnvironment::m_selfComm, QUESO::BaseEnvironment::m_subComm, QUESO::BaseEnvironment::m_subCommSize, QUESO::BaseEnvironment::m_subDisplayFile, QUESO::BaseEnvironment::m_subGroup, QUESO::BaseEnvironment::m_subId, QUESO::BaseEnvironment::m_subIdString, QUESO::BaseEnvironment::m_subRank, QUESO::BaseEnvironment::m_timevalBegin, QUESO::BaseEnvironment::m_worldRank, QUESO::old_terminate_handler, QUESO::queso_require_equal_to_msg, QUESO::queso_terminate_handler(), QUESO::QUESO_version_print(), and readOptionsInputFile().
 {
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "Entering FullEnv" << std::endl;
 #endif
   m_worldRank = 0;
   m_fullComm.reset(new MpiComm(*this));
   m_fullRank     = 0;
   m_fullCommSize = 1;
 #ifndef QUESO_HAS_MPI
   m_fullGroup = 0;
 #endif
   // saving old uncaught exception handler, invoking queso_terminate
   old_terminate_handler = std::set_terminate(queso_terminate_handler);
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "In FullEnv, finished dealing with MPI initially" << std::endl;
 #endif
   // Read options
   // If NULL, we create one
   if (m_optionsObj == NULL) {
     // If there's an input file, we grab the options from there.  Otherwise the
     // defaults are used
     if (m_optionsInputFileName != "") {
 #ifndef QUESO_DISABLE_BOOST_PROGRAM_OPTIONS
       m_allOptionsMap.reset(new boost::program_options::variables_map());
       m_allOptionsDesc.reset(new boost::program_options::options_description("Allowed options"));
 #endif  // QUESO_DISABLE_BOOST_PROGRAM_OPTIONS
       readOptionsInputFile();
       m_input->parse_input_file(m_optionsInputFileName);
     }
     m_optionsObj.reset(new EnvOptionsValues(this, prefix));
   }
   // If help option was supplied, print info
   if (m_optionsObj->m_help != "") {
     // We write to std::cout because subDisplayFile() isn't ready yet?
     std::cout << (*m_optionsObj) << std::endl;
   }
   queso_require_equal_to_msg(
       fullComm().NumProc() % m_optionsObj->m_numSubEnvironments, 0,
       "total number of processors in environment must be multiple of the specified number of subEnvironments");
 #ifdef QUESO_MEMORY_DEBUGGING
   std::cout << "In FullEnv, finished scanning options" << std::endl;
 #endif
   // Only display these messages if the user wants them
   // NOTE: This got moved below the Read Options section
   // because we need the options to be read to know what
   // the verbosity level is.
   if (this->displayVerbosity() > 0) {
     // Display main initial messages
     // 'std::cout' is for: main trace messages + synchronized trace messages + error messages prior to 'exit()' or 'abort()'
     /*int iRC = 0;*/
     /*iRC = */gettimeofday(&m_timevalBegin, NULL);
     QUESO_version_print(std::cout);
     std::cout << "Beginning run at " << ctime(&m_timevalBegin.tv_sec)
               << std::endl;
   }
   m_subId = 0;
   char tmpSubId[16];
   sprintf(tmpSubId,"%u",m_subId);
   m_subIdString = tmpSubId;
   if (m_optionsObj->m_subDisplayAllowAll) {
     m_optionsObj->m_subDisplayAllowedSet.insert((unsigned int) m_subId);
   }
   int fullRanksOfMySubEnvironment = 1;
 #ifndef QUESO_HAS_MPI
   m_subGroup = 0;
 #endif
   m_subComm.reset(new MpiComm(*this));
   m_subRank     = 0;
   m_subCommSize = 1;
   // Deal with multiple subEnvironments: create the self communicator
   m_selfComm.reset(new MpiComm(*this));
   // Deal with multiple subEnvironments: create the inter0 communicator
   int fullRanksOfInter0 = 0;
 #ifndef QUESO_HAS_MPI
   m_inter0Group = 0;
 #endif
   m_inter0Comm.reset(new MpiComm(*this));
   m_inter0Rank     = 0;
   m_inter0CommSize = 1;
   if (m_optionsObj->m_subDisplayAllowAll) {
     // This situation has been already taken care of above
   }
   else if (m_optionsObj->m_subDisplayAllowInter0) {
     if (m_inter0Rank >= 0) {
       m_optionsObj->m_subDisplayAllowedSet.insert((unsigned int) m_subId);
     }
   }
   // Open "screen" file
   bool openFile = false;
   if ((m_subRank                                               == 0                                              ) &&
       (m_optionsObj->m_subDisplayFileName                 != UQ_ENV_FILENAME_FOR_NO_OUTPUT_FILE             ) &&
       (m_optionsObj->m_subDisplayAllowedSet.find(m_subId) != m_optionsObj->m_subDisplayAllowedSet.end())) {
     openFile = true;
   }
   if (openFile && m_worldRank == 0) {
     // Verify parent directory exists (for cases when a user
     // specifies a relative path for the desired output file).
     int irtrn = CheckFilePath((m_optionsObj->m_subDisplayFileName+"_sub"+m_subIdString+".txt").c_str());
     queso_require_greater_equal_msg(irtrn, 0, "unable to verify output path");
   }
   // Ensure that rank 0 has created path, if necessary, before other tasks use it
   m_fullComm->Barrier();
   if (openFile) {
     // Always write over an eventual pre-existing file
     m_subDisplayFile.reset(new std::ofstream((m_optionsObj->m_subDisplayFileName+"_sub"+m_subIdString+".txt").c_str(),
                                          std::ofstream::out | std::ofstream::trunc));
     queso_require_msg((m_subDisplayFile && m_subDisplayFile->is_open()), "failed to open sub screen file");
     QUESO_version_print(*m_subDisplayFile);
     *m_subDisplayFile << "Beginning run at " << ctime(&m_timevalBegin.tv_sec)
                       << std::endl;
   }
   // Debug message related to subEnvironments
   if (this->displayVerbosity() >= 2) {
     for (int i = 0; i < m_fullCommSize; ++i) {
       if (i == m_fullRank) {
         //std::cout << "In FullEnvironment::commonConstructor()"
         std::cout << "MPI node of worldRank "             << m_worldRank
                   << " has fullRank "                     << m_fullRank
                   << ", belongs to subEnvironment of id " << m_subId
                   << ", and has subRank "                 << m_subRank
                   << std::endl;
         std::cout << "MPI node of worldRank " << m_worldRank
                   << " belongs to sub communicator with full ranks";
           std::cout << " " << fullRanksOfMySubEnvironment;
   std::cout << "\n";
         if (m_inter0Comm) {
           std::cout << "MPI node of worldRank " << m_worldRank
                     << " also belongs to inter0 communicator with full ranks";
             std::cout << " " << fullRanksOfInter0;
           std::cout << ", and has inter0Rank " << m_inter0Rank;
         }
   std::cout << "\n";
   std::cout << std::endl;
       }
       m_fullComm->Barrier();
     }
   }
   // Deal with seed
   if (m_optionsObj->m_rngType == "gsl") {
     m_rngObject.reset(new RngGsl(m_optionsObj->m_seed,m_worldRank));
     m_basicPdfs.reset(new BasicPdfsGsl(m_worldRank));
   }
   else if (m_optionsObj->m_rngType == "boost") {
     m_rngObject.reset(new RngBoost(m_optionsObj->m_seed,m_worldRank));
     m_basicPdfs.reset(new BasicPdfsBoost(m_worldRank));
   }
   else if (m_optionsObj->m_rngType == "cxx11") {
 #ifdef QUESO_HAVE_CXX11
     m_rngObject.reset(new RngCXX11(m_optionsObj->m_seed, m_worldRank));
     m_basicPdfs.reset(new BasicPdfsCXX11(m_worldRank));
 #else
     queso_error_msg("C++11 RNGs requested, but QUESO wasn't compiled with C++11 support");
 #endif
   }
   else {
     std::cerr << "In Environment::constructor()"
               << ": rngType = " << m_optionsObj->m_rngType
               << std::endl;
     queso_error_msg("the requested 'rngType' is not supported yet");
   }
   // Leave commonConstructor()
   m_fullComm->Barrier();
   m_fullEnvIsReady = true;
   if ((m_subDisplayFile) && (this->displayVerbosity() >= 5)) {
     *m_subDisplayFile << "Done with initializations at FullEnvironment::commonConstructor()"
                       << std::endl;
   }
   return;
 }
void QUESO::FullEnvironment::print (std::ostream & os) const virtual
Sends the environment options to the stream.
Implements QUESO::BaseEnvironment.
Definition at line 1725 of file Environment.C.
 {
   os.flush(); // just to avoid icpc warnings
   return;
 }
void QUESO::FullEnvironment::readOptionsInputFile () private
Checks the options input file and reads the options.
Definition at line 1758 of file Environment.C.
References QUESO::BaseEnvironment::m_fullRank, and QUESO::BaseEnvironment::m_optionsInputFileName.
Referenced by construct().
 {
   std::ifstream* ifs = new std::ifstream(m_optionsInputFileName.c_str());
   if (ifs->is_open()) {
     //ifs->close();
     delete ifs;
   }
   else {
     if (m_fullRank == 0) std::cout << "An invalid input file has been passed to the 'environment' class constructor!"
                                    << ": name of file is '" << m_optionsInputFileName.c_str() << "'"
                                    << std::endl;
     if (m_fullRank == 0) std::cout << "\nThis is a help message of the QUESO library."
                                    << "\nAn application using the QUESO library shall be executed by typing"
                                    << "\n  '<eventual mpi commands and options> <Application> <InputFile>'"
                                    << "\nin the command line."
                                    << "\n"
                                    << std::endl;
     queso_error();
   }
   return;
 }
The documentation for this class was generated from the following files:
src/core/inc/Environment.h
src/core/src/Environment.C