queso-0.53.0: QUESO::ExperimentModel< S_V, S_M, D_V, D_M > Class Template Reference
QUESO::ExperimentModel< S_V, S_M, D_V, D_M > Class Template Reference
#include <ExperimentModel.h>
Public Member Functions
ExperimentModel (const char *prefix, const EmOptionsValues *alternativeOptionsValues, const ExperimentStorage< S_V, S_M, D_V, D_M > &experimentStorage, const std::vector< D_M * > &Dmats, const std::vector< D_M * > &Kmats_interp)
~ExperimentModel ()
unsigned int numBasis () const
unsigned int numBasisGroups () const
const std::vector< unsigned int > & Gs () const
const D_M & Dmat (unsigned int basisId) const
const D_M & Dmat_BlockDiag () const
const std::vector< D_M * > & Kmats_interp () const
const ExperimentModelOptions & optionsObj () const
void print (std::ostream &os) const
Private Attributes
const BaseEnvironment & m_env
const EmOptionsValues * m_optionsObj
ExperimentModelOptions * m_experimentModelOptions
unsigned int m_paper_p_x
unsigned int m_paper_n
unsigned int m_paper_p_delta
unsigned int m_paper_n_y
std::vector< D_M * > m_Dmats
std::vector< D_M * > m_Kmats_interp
VectorSpace< D_V, D_M > * m_n_y_space
D_M * m_Dmat_BlockDiag
Friends
std::ostream & operator<< (std::ostream &os, const ExperimentModel< S_V, S_M, D_V, D_M > &obj)
Detailed Description
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix>
class QUESO::ExperimentModel< S_V, S_M, D_V, D_M >
Definition at line 39 of file ExperimentModel.h.
Constructor & Destructor Documentation
template<class S_V , class S_M , class D_V , class D_M > QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel (const char * prefix, const EmOptionsValues * alternativeOptionsValues, const ExperimentStorage< S_V, S_M, D_V, D_M > & experimentStorage, const std::vector< D_M * > & Dmats, const std::vector< D_M * > & Kmats_interp)
Definition at line 32 of file ExperimentModel.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_Dmat_BlockDiag, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_Dmats, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_env, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_experimentModelOptions, QUESO::EmOptionsValues::m_Gvalues, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_n_y_space, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_optionsObj, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_paper_n, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_paper_n_y, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_paper_p_delta, QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_paper_p_x, QUESO::EmOptionsValues::m_prefix, QUESO::VectorSpace< V, M >::map(), QUESO::BaseEnvironment::optionsInputFileName(), queso_require_equal_to_msg, queso_require_greater_equal_msg, QUESO::BaseEnvironment::subDisplayFile(), and QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::xs_standard().
   :
   m_env                     (Dmats[0]->env()),
   m_optionsObj              (alternativeOptionsValues),
   m_paper_p_x               (experimentStorage.scenarioSpace().dimLocal()),
   m_paper_n                 (Dmats.size()),
   m_paper_p_delta           (Dmats[0]->numCols()),
   m_paper_n_y               (0),
   m_Dmats                   (Dmats),
   m_Kmats_interp            (Kmats_interp),
   m_n_y_space               (NULL),
   m_Dmat_BlockDiag          (NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering ExperimentModel<S_V,S_M,D_V,D_M>::constructor()"
                             << ": prefix = " << prefix
                             << ", alternativeOptionsValues = " << alternativeOptionsValues
                             << ", m_env.optionsInputFileName() = " << m_env.optionsInputFileName()
                             << "\n  m_paper_p_x = "                << m_paper_p_x
                             << "\n  m_paper_n = "                  << m_paper_n
                             << "\n  m_paper_p_delta = "            << m_paper_p_delta
                             << "\n  m_paper_n_y = "                << "to be set soon"
                             << std::endl;
   }
   // If NULL, we create one
   if (m_optionsObj == NULL) {
     EmOptionsValues * tempOptions = new EmOptionsValues(&m_env, prefix);
     // We did this dance because scanOptionsValues is not a const method, but
     // m_optionsObj is a pointer to const
     m_optionsObj = tempOptions;
   }
   // We'll need to remove this later
   m_experimentModelOptions = new ExperimentModelOptions(m_env, prefix);
   queso_require_greater_equal_msg(m_optionsObj->m_Gvalues.size(), 1, "invalid m_Gs");
   queso_require_equal_to_msg(m_paper_n, experimentStorage.xs_standard().size(), "invalid m_paper_n");
   unsigned int sumGs = 0;
   for (unsigned int i = 0; i < m_optionsObj->m_Gvalues.size(); ++i) {
     sumGs += m_optionsObj->m_Gvalues[i];
   }
   queso_require_equal_to_msg(m_paper_p_delta, sumGs, "inconsistent input");
   //***********************************************************************
   // Form 'Dmat_BlockDiag' matrix
   //***********************************************************************
   for (unsigned int i = 0; i < m_Dmats.size(); ++i) {
     queso_require_equal_to_msg(m_Dmats[i]->numCols(), m_paper_p_delta, "inconsistent m_Dmats");
     m_paper_n_y += m_Dmats[i]->numRowsLocal();
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 3)) {
     *m_env.subDisplayFile() << "In ExperimentModel<S_V,S_M,D_V,D_M>::constructor()"
                             << ": prefix = " << prefix
                             << "\n  m_paper_n_y = " << m_paper_n_y
                             << std::endl;
   }
   m_n_y_space = new VectorSpace<D_V,D_M>(m_env, "n_y_", m_paper_n_y, NULL),
   m_Dmat_BlockDiag = new D_M(m_env,m_n_y_space->map(),m_paper_n*m_paper_p_delta);
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "In ExperimentModel<S_V,S_M,D_V,D_M>::constructor()"
                             << ": key-debug"
                             << ", m_Dmat_BlockDiag just created (not yet populated)"
                             << ", numRowsLocal = " << m_Dmat_BlockDiag->numRowsLocal()
                             << ", numCols = "      << m_Dmat_BlockDiag->numCols()
                             << std::endl;
   }
   m_Dmat_BlockDiag->fillWithBlocksDiagonally(0,0,m_Dmats,true,true);
   std::set<unsigned int> tmpSet;
   tmpSet.insert(m_env.subId());
   if (false) { //gcmOptionsObj.m_dataOutputAllowedSet.find(m_env.subId()) != gcmOptionsObj.m_dataOutputAllowedSet.end()) {
     m_Dmat_BlockDiag->subWriteContents("Dmat_BlockDiag",
                                        "Dmat_BlockDiag",
                                        "m",
                                        tmpSet);
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving ExperimentModel<S_V,S_M,D_V,D_M>::constructor()"
                             << ": prefix = " << m_optionsObj->m_prefix
                             << std::endl;
   }
 }
template<class S_V , class S_M , class D_V , class D_M > QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::~ExperimentModel ()
Definition at line 126 of file ExperimentModel.C.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering ExperimentModel<S_V,S_M,P_V,P_M,Q_V,Q_M>::destructor()..."
                             << std::endl;
   }
   if (m_Dmat_BlockDiag) delete m_Dmat_BlockDiag; // to be deleted on destructor
   if (m_n_y_space     ) delete m_n_y_space;      // to be deleted on destructor
   if (m_optionsObj    ) delete m_optionsObj;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving ExperimentModel<S_V,S_M,P_V,P_M,Q_V,Q_M>::destructor()"
                             << std::endl;
   }
   if (m_experimentModelOptions) {
     delete m_experimentModelOptions;
   }
 }
Member Function Documentation
template<class S_V , class S_M , class D_V , class D_M > const D_M & QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::Dmat (unsigned int basisId) const
Definition at line 177 of file ExperimentModel.C.
 {
   return *(m_Dmats[basisId]);
 }
template<class S_V , class S_M , class D_V , class D_M > const D_M & QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::Dmat_BlockDiag () const
Definition at line 184 of file ExperimentModel.C.
Referenced by QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo().
 {
   return *m_Dmat_BlockDiag;
 }
template<class S_V , class S_M , class D_V , class D_M > const std::vector< unsigned int > & QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::Gs () const
Definition at line 163 of file ExperimentModel.C.
 {
   return m_optionsObj->m_Gvalues;
 }
template<class S_V , class S_M , class D_V , class D_M > const std::vector< D_M * > & QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::Kmats_interp () const
Definition at line 170 of file ExperimentModel.C.
 {
   return m_Kmats_interp;
 }
template<class S_V , class S_M , class D_V , class D_M > unsigned int QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::numBasis () const
Definition at line 149 of file ExperimentModel.C.
Referenced by QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel().
 {
   return m_paper_p_delta;
 }
template<class S_V , class S_M , class D_V , class D_M > unsigned int QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::numBasisGroups () const
Definition at line 156 of file ExperimentModel.C.
 {
   return m_optionsObj->m_Gvalues.size();
 }
template<class S_V , class S_M , class D_V , class D_M > const ExperimentModelOptions & QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::optionsObj () const
Definition at line 192 of file ExperimentModel.C.
References queso_deprecated.
 {
   // This methods returns the old ExperimentModelOptions object.  We're using
   // the new EmOptionsValues so this method is deprecated.
   queso_deprecated();
   return *m_experimentModelOptions;
 }
template<class S_V , class S_M , class D_V , class D_M > void QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::print (std::ostream & os) const
Definition at line 202 of file ExperimentModel.C.
 {
   return;
 }
Friends And Related Function Documentation
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> std::ostream& operator<< (std::ostream & os, const ExperimentModel< S_V, S_M, D_V, D_M > & obj) friend
Definition at line 59 of file ExperimentModel.h.
{
     obj.print(os);
     return os;
   }
Member Data Documentation
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> D_M* QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_Dmat_BlockDiag private
Definition at line 79 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> std::vector<D_M* > QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_Dmats private
Definition at line 76 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> const BaseEnvironment& QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_env private
Definition at line 68 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> ExperimentModelOptions* QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_experimentModelOptions private
Definition at line 70 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> std::vector<D_M* > QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_Kmats_interp private
Definition at line 77 of file ExperimentModel.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> VectorSpace<D_V,D_M>* QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_n_y_space private
Definition at line 78 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> const EmOptionsValues* QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_optionsObj private
Definition at line 69 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> unsigned int QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_paper_n private
Definition at line 73 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> unsigned int QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_paper_n_y private
Definition at line 75 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> unsigned int QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_paper_p_delta private
Definition at line 74 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> unsigned int QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::m_paper_p_x private
Definition at line 72 of file ExperimentModel.h.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
The documentation for this class was generated from the following files:
src/gp/inc/ExperimentModel.h
src/gp/src/ExperimentModel.C