queso-0.57.1: QUESO::PoweredJointPdf< V, M > Class Template Reference
QUESO::PoweredJointPdf< V, M > Class Template Reference
A class for handling a powered joint PDFs.
#include <PoweredJointPdf.h>
Public Member Functions
Constructor/Destructor methods
PoweredJointPdf (const char *prefix, const BaseJointPdf< V, M > &srcDensity, double exponent)
Constructor.
~PoweredJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Actual value of the powered PDF.
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Logarithm of the value of the powered PDF.
void setNormalizationStyle (unsigned int value) const
Sets a value to be used in the normalization style of the powered PDF (ie, protected attribute m_srcDensity).
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
TODO: Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
virtual void distributionMean (V &meanVector) const
virtual void distributionVariance (M &covMatrix) const
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
virtual void print (std::ostream &os) const
Print method. Non-pure for backwards compatibility.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
void setFiniteDifferenceStepSize (double fdStepSize)
Sets the step size for finite differencing gradients.
void setFiniteDifferenceStepSize (unsigned int i, double fdStepSize)
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
virtual double lnValue (const V &domainVector) const
Returns the logarithm of the function at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector) const
Returns the logarithm of the function and its gradient at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector, const V &domainDirection, V &hessianEffect) const
Protected Attributes
const BaseJointPdf< V, M > & m_srcDensity
double m_exponent
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::PoweredJointPdf< V, M >
A class for handling a powered joint PDFs.
This class allows the mathematical definition of a Powered Joint PDF.
Definition at line 50 of file PoweredJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::PoweredJointPdf< V, M >::PoweredJointPdf (const char * prefix, const BaseJointPdf< V, M > & srcDensity, double exponent)
Constructor.
Constructs a new object of the class, given a prefix, the domain set and the exponent of the powered PDF.
Definition at line 33 of file PoweredJointPdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarFunction< V, M >::m_env, QUESO::BaseScalarFunction< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"pow").c_str(),srcDensity.domainSet()),
   m_srcDensity            (srcDensity),
   m_exponent              (exponent)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering PoweredJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "In PoweredJointPdf<V,M>::constructor()"
                           //<< ", prefix = "     << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving PoweredJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::PoweredJointPdf< V, M >::~PoweredJointPdf ()
Destructor.
Definition at line 62 of file PoweredJointPdf.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::PoweredJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Actual value of the powered PDF.
Finds the actual value using BaseJointPdf::actualValue() and apply it to the power of this PDF, which given by exponent, and multiplies it by the normalization factor, which is given by exp(m_logOfNormalizationFactor).
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 76 of file PoweredJointPdf.C.
References QUESO::queso_require_equal_to_msg.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering PoweredJointPdf<V,M>::actualValue()"
                             << ": domainVector = " << domainVector
                             << std::endl;
   }
   queso_require_equal_to_msg(domainVector.sizeLocal(), this->m_domainSet.vectorSpace().dimLocal(), "invalid input");
   double value = m_srcDensity.actualValue(domainVector,domainDirection,gradVector,hessianMatrix,hessianEffect);
   queso_require_msg(!(domainDirection || gradVector || hessianMatrix || hessianEffect), "incomplete code for domainDirection, gradVector, hessianMatrix and hessianEffect calculations");
   double returnValue = pow(value,m_exponent);
   returnValue *= exp(m_logOfNormalizationFactor); // [PDF-08] ???
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving PoweredJointPdf<V,M>::actualValue()"
                             << ": domainVector = " << domainVector
                             << ", returnValue = "  << returnValue
                             << std::endl;
   }
   return returnValue;
 }
template<class V , class M > double QUESO::PoweredJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
TODO: Computes the logarithm of the normalization factor.
Todo:
: implement me!
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 142 of file PoweredJointPdf.C.
References QUESO::queso_isnan().
 {
   double value = 0.;
   double volume = m_domainSet.volume();
   if ((queso_isnan(volume)) ||
       (volume == -INFINITY         ) ||
       (volume ==  INFINITY         ) ||
       (volume <= 0.                )) {
     // Do nothing
   }
   else {
     queso_error_msg("incomplete code for computeLogOfNormalizationFactor()");
   }
   return value;
 }
template<class V , class M > double QUESO::PoweredJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Logarithm of the value of the powered PDF.
Finds the logarithm of actual value using BaseJointPdf::lnValue() and multiplies by the power of this PDF, which given by exponent, and then adds the normalization factor, which is given by m_logOfNormalizationFactor.
Reimplemented from QUESO::BaseScalarFunction< V, M >.
Definition at line 110 of file PoweredJointPdf.C.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering PoweredJointPdf<V,M>::lnValue()"
                             << ": domainVector = " << domainVector
                             << std::endl;
   }
   double value = m_srcDensity.lnValue(domainVector,domainDirection,gradVector,hessianMatrix,hessianEffect);
   queso_require_msg(!(domainDirection || gradVector || hessianMatrix || hessianEffect), "incomplete code for domainDirection, gradVector, hessianMatrix and hessianEffect calculations");
   double returnValue = m_exponent*value;
   returnValue += m_logOfNormalizationFactor; // [PDF-08] ???
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving PoweredJointPdf<V,M>::lnValue()"
                             << ": domainVector = " << domainVector
                             << ", returnValue = "  << returnValue
                             << std::endl;
   }
   return returnValue;
 }
template<class V , class M > void QUESO::PoweredJointPdf< V, M >::setNormalizationStyle (unsigned int value) const virtual
Sets a value to be used in the normalization style of the powered PDF (ie, protected attribute m_srcDensity).
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 68 of file PoweredJointPdf.C.
 {
   m_srcDensity.setNormalizationStyle(value);
   return;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> double QUESO::PoweredJointPdf< V, M >::m_exponent protected
Definition at line 93 of file PoweredJointPdf.h.
template<class V = GslVector, class M = GslMatrix> const BaseJointPdf<V,M>& QUESO::PoweredJointPdf< V, M >::m_srcDensity protected
Definition at line 92 of file PoweredJointPdf.h.
The documentation for this class was generated from the following files:
src/stats/inc/PoweredJointPdf.h
src/stats/src/PoweredJointPdf.C