queso-0.55.0: QUESO::GslBlockMatrix Class Reference
QUESO::GslBlockMatrix Class Reference
Class for representing block matrices using GSL library.
#include <GslBlockMatrix.h>
Public Member Functions
virtual unsigned int numRowsLocal () const
Not implemented yet.
virtual unsigned int numRowsGlobal () const
Not implemented yet.
virtual unsigned int numCols () const
Not implemented yet.
virtual int chol ()
Not implemented yet.
virtual void zeroLower (bool includeDiagonal=false)
Not implemented yet.
virtual void zeroUpper (bool includeDiagonal=false)
Not implemented yet.
GslMatrix & getBlock (unsigned int i) const
Return block i in the block diagonal matrix.
unsigned int numBlocks () const
Return the number of blocks in the block diagonal matrix.
void invertMultiply (const GslVector &b, GslVector &x) const
This function calculates the inverse of this matrix, multiplies it with vector b and stores the result in vector x.
Constructor/Destructor methods
GslBlockMatrix (const std::vector< unsigned int > &blockSizes, const GslVector &v, double diagValue)
Creates a square matrix with size defined by v and diagonal values all equal to diagValue.
~GslBlockMatrix ()
Destructor.
I/O methods
virtual void print (std::ostream &os) const
Print method. Defines the behavior of operator<< inherited from the Object class.
Private Attributes
std::vector< VectorSpace
< GslVector, GslMatrix > * > m_vectorSpaces
std::vector< GslMatrix * > m_blocks
Private Attributes inherited from QUESO::Matrix
const BaseEnvironment & m_env
QUESO environment variable.
const Map & m_map
Mapping variable.
bool m_printHorizontally
Flag for either or not print this matrix.
bool m_inDebugMode
Flag for either or not QUESO is in debug mode.
Additional Inherited Members
Private Member Functions inherited from QUESO::Matrix
Matrix (const BaseEnvironment &env, const Map &map)
Shaped constructor.
virtual ~Matrix ()
Virtual Destructor.
const BaseEnvironment & env () const
const Map & map () const
unsigned int numOfProcsForStorage () const
void setPrintHorizontally (bool value) const
Determines whether the matrix should be printed horizontally.
bool getPrintHorizontally () const
Checks if matrix will be is printed horizontally.
void setInDebugMode (bool value) const
Determines whether QUESO will run through this class in debug mode.
bool getInDebugMode () const
Checks if QUESO will run through this class in debug mode.
virtual void base_copy (const Matrix &src)
Copies base data from matrix src to this matrix.
Detailed Description
Class for representing block matrices using GSL library.
This class provides basic 'invertMultiply' support for matrices of block diagonal structure. Each block is implemented as a GslMatrix object.
Definition at line 50 of file GslBlockMatrix.h.
Constructor & Destructor Documentation
QUESO::GslBlockMatrix::GslBlockMatrix (const std::vector< unsigned int > & blockSizes, const GslVector & v, double diagValue)
Creates a square matrix with size defined by v and diagonal values all equal to diagValue.
The blockSizes array determines the sizes of each (square) block.
Definition at line 29 of file GslBlockMatrix.C.
References m_blocks, QUESO::Matrix::m_env, and m_vectorSpaces.
   : Matrix(v.env(), v.map()),
     m_vectorSpaces(blockSizes.size()),
     m_blocks(blockSizes.size())
 {
   for (unsigned int i = 0; i < this->m_vectorSpaces.size(); i++) {
     this->m_vectorSpaces[i] = new VectorSpace<GslVector, GslMatrix>(m_env,
         "block_param_", blockSizes[i], NULL);
     this->m_blocks[i] = new GslMatrix(this->m_vectorSpaces[i]->zeroVector(),
         diagValue);
   }
 }
QUESO::GslBlockMatrix::~GslBlockMatrix ()
Destructor.
Definition at line 43 of file GslBlockMatrix.C.
References m_blocks, and m_vectorSpaces.
 {
   for (unsigned int i = 0; i < this->m_vectorSpaces.size(); i++) {
     delete this->m_blocks[i];
     delete this->m_vectorSpaces[i];
   }
 }
Member Function Documentation
int QUESO::GslBlockMatrix::chol () virtual
Not implemented yet.
Implements QUESO::Matrix.
Definition at line 73 of file GslBlockMatrix.C.
References queso_not_implemented.
 {
   queso_not_implemented();
   return 0;
 }
GslMatrix & QUESO::GslBlockMatrix::getBlock (unsigned int i) const
Return block i in the block diagonal matrix.
Definition at line 93 of file GslBlockMatrix.C.
References m_blocks.
Referenced by QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::GaussianLikelihoodBlockDiagonalCovariance(), QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients(), and print().
 {
   return *(this->m_blocks[i]);
 }
void QUESO::GslBlockMatrix::invertMultiply (const GslVector & b, GslVector & x) const
This function calculates the inverse of this matrix, multiplies it with vector b and stores the result in vector x.
It checks for a previous LU decomposition of each block matrix and does not recompute it if m_MU != NULL for each block.
Definition at line 105 of file GslBlockMatrix.C.
References m_blocks, m_vectorSpaces, queso_error_msg, and QUESO::GslVector::sizeLocal().
 {
   unsigned int totalCols = 0;
   for (unsigned int i = 0; i < this->m_blocks.size(); i++) {
     totalCols += this->m_blocks[i]->numCols();
   }
   if (totalCols != b.sizeLocal()) {
     queso_error_msg("block matrix and rhs have incompatible sizes");
   }
   if (x.sizeLocal() != b.sizeLocal()) {
     queso_error_msg("solution and rhs have incompatible sizes");
   }
   unsigned int blockOffset = 0;
   // Do an invertMultiply for each block
   for (unsigned int i = 0; i < this->m_blocks.size(); i++) {
     GslVector blockRHS(this->m_vectorSpaces[i]->zeroVector());
     GslVector blockSol(this->m_vectorSpaces[i]->zeroVector());
     // Be sure to copy over the RHS to the right sized vector
     for (unsigned int j = 0; j < this->m_blocks[i]->numCols(); j++) {
       blockRHS[j] = b[blockOffset + j];
     }
     // Solve
     this->m_blocks[i]->invertMultiply(blockRHS, blockSol);
     // Be sure to copy the block solution back to the global solution vector
     for (unsigned int j = 0; j < this->m_blocks[i]->numCols(); j++) {
       x[blockOffset + j] = blockSol[j];
     }
     // Remember to increment the offset so we don't lose our place for the next
     // block
     blockOffset += this->m_blocks[i]->numCols();
   }
 }
unsigned int QUESO::GslBlockMatrix::numBlocks () const
Return the number of blocks in the block diagonal matrix.
Definition at line 99 of file GslBlockMatrix.C.
References m_blocks.
Referenced by QUESO::GaussianLikelihoodBlockDiagonalCovariance< V, M >::GaussianLikelihoodBlockDiagonalCovariance(), QUESO::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients< V, M >::GaussianLikelihoodBlockDiagonalCovarianceRandomCoefficients(), and print().
 {
   return this->m_blocks.size();
 }
unsigned int QUESO::GslBlockMatrix::numCols () const virtual
Not implemented yet.
Implements QUESO::Matrix.
Definition at line 66 of file GslBlockMatrix.C.
References queso_not_implemented.
 {
   queso_not_implemented();
   return 0;
 }
unsigned int QUESO::GslBlockMatrix::numRowsGlobal () const virtual
Not implemented yet.
Implements QUESO::Matrix.
Definition at line 59 of file GslBlockMatrix.C.
References queso_not_implemented.
 {
   queso_not_implemented();
   return 0;
 }
unsigned int QUESO::GslBlockMatrix::numRowsLocal () const virtual
Not implemented yet.
Implements QUESO::Matrix.
Definition at line 53 of file GslBlockMatrix.C.
References queso_not_implemented.
 {
   queso_not_implemented();
 }
void QUESO::GslBlockMatrix::print (std::ostream & os) const virtual
Print method. Defines the behavior of operator<< inherited from the Object class.
Implements QUESO::Matrix.
Definition at line 148 of file GslBlockMatrix.C.
References getBlock(), numBlocks(), and QUESO::GslMatrix::print().
Referenced by QUESO::operator<<().
 {
   for (unsigned int i = 0; i < this->numBlocks(); i++) {
     this->getBlock(i).print(os);
   }
 }
void QUESO::GslBlockMatrix::zeroLower (bool includeDiagonal = false) virtual
Not implemented yet.
Implements QUESO::Matrix.
Definition at line 80 of file GslBlockMatrix.C.
References queso_not_implemented.
 {
   queso_not_implemented();
 }
void QUESO::GslBlockMatrix::zeroUpper (bool includeDiagonal = false) virtual
Not implemented yet.
Implements QUESO::Matrix.
Definition at line 86 of file GslBlockMatrix.C.
References queso_not_implemented.
 {
   queso_not_implemented();
 }
Member Data Documentation
std::vector<GslMatrix *> QUESO::GslBlockMatrix::m_blocks private
Definition at line 105 of file GslBlockMatrix.h.
Referenced by getBlock(), GslBlockMatrix(), invertMultiply(), numBlocks(), and ~GslBlockMatrix().
std::vector<VectorSpace<GslVector, GslMatrix> *> QUESO::GslBlockMatrix::m_vectorSpaces private
Definition at line 104 of file GslBlockMatrix.h.
Referenced by GslBlockMatrix(), invertMultiply(), and ~GslBlockMatrix().
The documentation for this class was generated from the following files:
src/core/inc/GslBlockMatrix.h
src/core/src/GslBlockMatrix.C