queso-0.57.0: QUESO::LikelihoodBase< V, M > Class Template Reference
QUESO::LikelihoodBase< V, M > Class Template Reference abstract
Base class for canned Gaussian likelihoods.
#include <LikelihoodBase.h>
Public Member Functions
virtual void evaluateModel (const V &domainVector, const V *domainDirection, V &modelOutput, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Deprecated. Evaluates the user's model at the point domainVector.
virtual void evaluateModel (const V &domainVector, V &modelOutput) const
Evaluates the user's model at the point domainVector.
virtual double actualValue (const V &domainVector, const V *, V *, M *, V *) const
Actual value of the scalar function.
Constructor/Destructor methods.
LikelihoodBase (const char *prefix, const VectorSet< V, M > &domainSet, const V &observations)
Default constructor.
virtual ~LikelihoodBase ()=0
Destructor, pure to make this class abstract.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
void setFiniteDifferenceStepSize (double fdStepSize)
Sets the step size for finite differencing gradients.
void setFiniteDifferenceStepSize (unsigned int i, double fdStepSize)
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
virtual double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Logarithm of the value of the scalar function. Deprecated.
virtual double lnValue (const V &domainVector) const
Returns the logarithm of the function at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector) const
Returns the logarithm of the function and its gradient at domainVector.
virtual double lnValue (const V &domainVector, V &gradVector, const V &domainDirection, V &hessianEffect) const
Protected Attributes
const V & m_observations
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::LikelihoodBase< V, M >
Base class for canned Gaussian likelihoods.
This class is an abstract base class for 'canned' Gaussian likelihoods. All this class does is add a pure virtual function called evaluateModel that the user will implement to interact with the forward code.
Definition at line 49 of file LikelihoodBase.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::LikelihoodBase< V, M >::LikelihoodBase (const char * prefix, const VectorSet< V, M > & domainSet, const V & observations)
Default constructor.
The vector of observations must be passed. This will be used when evaluating the likelihood functional
Definition at line 35 of file LikelihoodBase.C.
   : BaseScalarFunction<V, M>(prefix, domainSet),
     m_observations(observations)
 {
 }
template<class V , class M > QUESO::LikelihoodBase< V, M >::~LikelihoodBase () pure virtual
Destructor, pure to make this class abstract.
Definition at line 44 of file LikelihoodBase.C.
 {
 }
Member Function Documentation
template<class V = GslVector, class M = GslMatrix> virtual double QUESO::LikelihoodBase< V, M >::actualValue (const V & domainVector, const V * , V * , M * , V *) const inline virtual
Actual value of the scalar function.
Implements QUESO::BaseScalarFunction< V, M >.
Definition at line 98 of file LikelihoodBase.h.
References QUESO::BaseScalarFunction< V, M >::lnValue().
   { return std::exp(this->lnValue(domainVector)); }
template<class V , class M > void QUESO::LikelihoodBase< V, M >::evaluateModel (const V & domainVector, const V * domainDirection, V & modelOutput, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Deprecated. Evaluates the user's model at the point domainVector.
This method is deprecated. The user instead should subclass evaluateModel(const V & domainVector, V & modelOutput).
Definition at line 49 of file LikelihoodBase.C.
Referenced by QUESO::LikelihoodBase< V, M >::evaluateModel().
 {
   std::stringstream ss;
   ss << "ERROR: evaluateModel() not implemented! This interface is deprecated."
      << std::endl
      << "Prefer implementing evaluateModel(const V & domainVector, V & modelOutput)"
      << std::endl;
   queso_error_msg(ss.str());
 }
template<class V = GslVector, class M = GslMatrix> virtual void QUESO::LikelihoodBase< V, M >::evaluateModel (const V & domainVector, V & modelOutput) const inline virtual
Evaluates the user's model at the point domainVector.
Subclass implementations will fill up the modelOutput vector with output from the model. This represents a vector of synthetic observations that will be compared to actual observations when computing the likelihood functional.
The first n components of domainVector are the model parameters. The rest of domainVector contains the hyperparameters, if any. For example, in GaussianLikelihoodFullCovarainceRandomCoefficient, the last component of domainVector contains the multiplicative coefficient of the observational covariance matrix. In this case, the user need not concern themselves with this parameter as it is handled not in the model evaluation but by the likelihood evaluation.
By default, to ensure backward compatibility, this method will call the deprecated evaluateModel(const V & domainVector, const V * domainDirection, V & modelOutput, V * gradVector, M * hessianMatrix, V * hessianEffect).
Definition at line 94 of file LikelihoodBase.h.
References QUESO::LikelihoodBase< V, M >::evaluateModel().
   { this->evaluateModel(domainVector,NULL,modelOutput,NULL,NULL,NULL); }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> const V& QUESO::LikelihoodBase< V, M >::m_observations protected
Definition at line 103 of file LikelihoodBase.h.
The documentation for this class was generated from the following files:
src/stats/inc/LikelihoodBase.h
src/stats/src/LikelihoodBase.C