queso-0.57.1: QUESO::MpiComm Class Reference
QUESO::MpiComm Class Reference
The QUESO MPI Communicator Class.
#include <MpiComm.h>
Public Member Functions
Constructor/Destructor methods
MpiComm (const BaseEnvironment &env, RawType_MPI_Comm inputRawComm)
QUESO MpiComm MPI parallel constructor.
MpiComm (const BaseEnvironment &env)
QUESO MpiComm MPI serial constructor.
MpiComm (const MpiComm &src)
Copy Constructor.
~MpiComm ()
Destructor.
Set methods
MpiComm & operator= (const MpiComm &rhs)
Assignment operator.
Attribute Accessor Methods
RawType_MPI_Comm Comm () const
Extract MPI Communicator from a MpiComm object.
int MyPID () const
Return my process ID.
int NumProc () const
Returns total number of processes.
Methods Overridden from Comm
void Allreduce (void *sendbuf, void *recvbuf, int count, RawType_MPI_Datatype datatype, RawType_MPI_Op op, const char *whereMsg, const char *whatMsg) const
Combines values from all processes and distributes the result back to all processes.
template<typename T >
void Allreduce (const T *sendbuf, T *recvbuf, int count, RawType_MPI_Op op, const char *whereMsg, const char *whatMsg) const
Combines values from all processes and distributes the result back to all processes.
void Barrier () const
Pause every process in *this communicator until all the processes reach this point.
void Bcast (void *buffer, int count, RawType_MPI_Datatype datatype, int root, const char *whereMsg, const char *whatMsg) const
Broadcast values from the root process to the slave processes.
void Gather (void *sendbuf, int sendcnt, RawType_MPI_Datatype sendtype, void *recvbuf, int recvcount, RawType_MPI_Datatype recvtype, int root, const char *whereMsg, const char *whatMsg) const
Gather values from each process to collect on all processes.
template<typename T >
void Gather (const T *sendbuf, int sendcnt, T *recvbuf, int recvcount, int root, const char *whereMsg, const char *whatMsg) const
Gather values from each process to collect on all processes.
void Gatherv (void *sendbuf, int sendcnt, RawType_MPI_Datatype sendtype, void *recvbuf, int *recvcnts, int *displs, RawType_MPI_Datatype recvtype, int root, const char *whereMsg, const char *whatMsg) const
Gathers into specified locations from all processes in a group.
template<typename T >
void Gatherv (const T *sendbuf, int sendcnt, T *recvbuf, int *recvcnts, int *displs, int root, const char *whereMsg, const char *whatMsg) const
Gathers into specified locations from all processes in a group.
void Recv (void *buf, int count, RawType_MPI_Datatype datatype, int source, int tag, RawType_MPI_Status *status, const char *whereMsg, const char *whatMsg) const
Blocking receive of data from this process to another process.
void Send (void *buf, int count, RawType_MPI_Datatype datatype, int dest, int tag, const char *whereMsg, const char *whatMsg) const
Possibly blocking send of data from this process to another process.
Miscellaneous Methods
void syncPrintDebugMsg (const char *msg, unsigned int msgVerbosity, unsigned int numUSecs) const
Synchronizes all the processes and print debug message.
const Epetra_Comm & epetraMpiComm () const
Extract MPI Communicator from a Epetra_MpiComm object.
Private Member Functions
MpiComm ()
Default Constructor.
void copy (const MpiComm &src)
Copies from an existing MpiComm instance.
Private Attributes
const BaseEnvironment & m_env
Epetra_Comm * m_epetraComm
RawType_MPI_Comm m_rawComm
Embedded wrapped opaque MPI_Comm object.
int m_worldRank
World rank.
int m_myPid
Process ID of this process.
int m_numProc
Detailed Description
The QUESO MPI Communicator Class.
This class uses MPI (the Message Passing Interface) for distributed-memory communication between one or more parallel processes. It is meant to insulate the user from the specifics of communication that are not required for normal manipulation of linear algebra objects.
Definition at line 203 of file MpiComm.h.
Constructor & Destructor Documentation
QUESO::MpiComm::MpiComm (const BaseEnvironment & env, RawType_MPI_Comm inputRawComm)
QUESO MpiComm MPI parallel constructor.
This constructs an MpiComm that uses the given "raw" MPI communicator underneath. MPI_Init must have been called before instantiating an object of this type.
The MPI_Comm must be valid for the lifetime of this MpiComm.
Definition at line 38 of file MpiComm.C.
References m_myPid, m_numProc, m_worldRank, and QUESO::queso_require_equal_to_msg.
   :
   m_env          (env),
 #ifdef QUESO_HAS_TRILINOS
   m_epetraComm( new Epetra_MpiComm(inputRawComm) ),
 #endif
   m_rawComm      (inputRawComm),
   m_worldRank    (-1),
   m_myPid        (-1),
   m_numProc      (-1)
 {
 #ifdef QUESO_HAS_MPI
   int mpiRC = MPI_Comm_rank(inputRawComm,&m_worldRank);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed MPI_Comm_rank() on full rank");
   mpiRC = MPI_Comm_rank(inputRawComm,&m_myPid);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed MPI_Comm_rank() on inputRawComm");
   mpiRC = MPI_Comm_size(inputRawComm,&m_numProc);
   queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "failed MPI_Comm_size() on inputRawComm");
 #else
   m_worldRank = 0;
   m_myPid     = 0;
   m_numProc   = 1;
 #endif
 }
QUESO::MpiComm::MpiComm (const BaseEnvironment & env)
QUESO MpiComm MPI serial constructor.
This constructs an MpiComm that defaults to MPI_COMM_SELF underneath. MPI_Init need not be called before using this constructor.
The MPI_Comm must be valid for the lifetime of this MpiComm.
Definition at line 65 of file MpiComm.C.
   :
   m_env          (env),
 #ifdef QUESO_HAS_TRILINOS
   m_epetraComm( new Epetra_SerialComm() ),
 #endif
   m_rawComm      (RawValue_MPI_COMM_SELF),
   m_worldRank    (0),
   m_myPid        (0),
   m_numProc      (1)
 {
 }
QUESO::MpiComm::MpiComm (const MpiComm & src)
Copy Constructor.
Makes an exact copy of an existing MpiComm instance.
QUESO::MpiComm::~MpiComm ()
Destructor.
QUESO::MpiComm::MpiComm () private
Default Constructor.
It should not be used by user.
Definition at line 91 of file MpiComm.C.
References m_epetraComm.
 {
 #ifdef QUESO_HAS_TRILINOS
   delete m_epetraComm;
   m_epetraComm = NULL;
 #endif
 }
Member Function Documentation
void QUESO::MpiComm::Allreduce (void * sendbuf, void * recvbuf, int count, RawType_MPI_Datatype datatype, RawType_MPI_Op op, const char * whereMsg, const char * whatMsg) const
Combines values from all processes and distributes the result back to all processes.
Parameters
sendbuf starting address of send buffer
count number of elements in send buffer
datatype data type of elements of send buffer
op operation
recvbuf (output) starting address of receive buffer
This method is deprecated. Use the templated Allreduce method instead.
Definition at line 143 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
Referenced by QUESO::MiscCheckForSameValueInAllNodes(), QUESO::GslVector::mpiAllReduce(), QUESO::TeuchosVector::mpiAllReduce(), QUESO::GslVector::mpiBcast(), QUESO::TeuchosVector::mpiBcast(), QUESO::MHRawChainInfoStruct::mpiSum(), QUESO::TeuchosMatrix::mpiSum(), and QUESO::GslMatrix::mpiSum().
 {
   queso_deprecated();
   if (NumProc() > 1) {  // Necessarily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     int mpiRC = MPI_Allreduce(sendbuf, recvbuf, count, datatype, op, m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
 }
template<typename T > void QUESO::MpiComm::Allreduce (const T * sendbuf, T * recvbuf, int count, RawType_MPI_Op op, const char * whereMsg, const char * whatMsg) const
Combines values from all processes and distributes the result back to all processes.
Parameters
sendbuf starting address of send buffer containing elements of type T
count number of elements in send buffer
op operation
recvbuf (output) starting address of receive buffer containing elements of type T
Definition at line 156 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
 {
   if (NumProc() > 1) {  // Necessarily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     T * sendbuf_noconst = const_cast<T *>(sendbuf);
     int mpiRC = MPI_Allreduce(sendbuf_noconst, recvbuf, count, StandardType<T>(sendbuf), op, m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
   else {
     size_t dataTypeSize = sizeof(T);
     size_t dataTotal = dataTypeSize*count;
     std::memcpy(recvbuf, sendbuf, dataTotal);
   }
 }
void QUESO::MpiComm::Barrier () const
Pause every process in *this communicator until all the processes reach this point.
Blocks the caller until all processes in the communicator have called it; that is, the call returns at any process only after all members of the communicator have entered the call.
Definition at line 174 of file MpiComm.C.
References m_epetraComm, m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
Referenced by QUESO::VectorFunctionSynchronizer< P_V, P_M, Q_V, Q_M >::callFunction(), QUESO::ComputeCovCorrMatricesBetweenVectorSequences(), QUESO::MiscCheckForSameValueInAllNodes(), QUESO::GslVector::mpiBcast(), QUESO::TeuchosVector::mpiBcast(), and syncPrintDebugMsg().
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraComm->Barrier();
 #endif
   if (NumProc() > 1) {  // Necessarily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     int mpiRC = MPI_Barrier(m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, "mpiRC indicates failure");  // whatMsg);
 #endif
   }
   return;
 }
void QUESO::MpiComm::Bcast (void * buffer, int count, RawType_MPI_Datatype datatype, int root, const char * whereMsg, const char * whatMsg) const
Broadcast values from the root process to the slave processes.
Broadcasts a message from the process with rank "root" to all other processes of the communicator.
Parameters
buffer (input/output) starting address of buffer
count number of entries in buffer
datatype data type of buffer
root rank of broadcast root
Definition at line 191 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
Referenced by QUESO::MiscCheckForSameValueInAllNodes(), QUESO::GslVector::mpiAllQuantile(), QUESO::TeuchosVector::mpiAllQuantile(), QUESO::GslVector::mpiBcast(), QUESO::TeuchosVector::mpiBcast(), QUESO::InterpolationSurrogateIOASCII< V, M >::read(), and QUESO::InterpolationSurrogateData< V, M >::sync_values().
 {
   if (NumProc() > 1) {  // Necesarrily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     int mpiRC = MPI_Bcast(buffer, count, datatype, root, m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
 }
RawType_MPI_Comm QUESO::MpiComm::Comm () const
Extract MPI Communicator from a MpiComm object.
Definition at line 111 of file MpiComm.C.
References m_epetraComm, and m_rawComm.
Referenced by QUESO::GPMSAEmulator< V, M >::lnValue(), and QUESO::GPMSAFactory< V, M >::setUpHyperpriors().
 {
 #ifdef QUESO_HAS_TRILINOS
 #ifdef QUESO_HAS_MPI
   return dynamic_cast<Epetra_MpiComm *>(m_epetraComm)->Comm();
 #endif
 #endif
   return m_rawComm;
 }
void QUESO::MpiComm::copy (const MpiComm & src) private
Copies from an existing MpiComm instance.
Definition at line 368 of file MpiComm.C.
References m_epetraComm, m_myPid, m_numProc, m_rawComm, and m_worldRank.
Referenced by operator=().
 {
 #ifdef QUESO_HAS_TRILINOS
   delete m_epetraComm;
   m_epetraComm = src.m_epetraComm->Clone();
 #endif
   m_rawComm   = src.m_rawComm;
   m_worldRank = src.m_worldRank;
   m_myPid     = src.m_myPid;
   m_numProc   = src.m_numProc;
   return;
 }
const Epetra_Comm & QUESO::MpiComm::epetraMpiComm () const
Extract MPI Communicator from a Epetra_MpiComm object.
Definition at line 360 of file MpiComm.C.
References m_epetraComm.
 {
   return *m_epetraComm;
 }
void QUESO::MpiComm::Gather (void * sendbuf, int sendcnt, RawType_MPI_Datatype sendtype, void * recvbuf, int recvcount, RawType_MPI_Datatype recvtype, int root, const char * whereMsg, const char * whatMsg) const
Gather values from each process to collect on all processes.
Parameters
sendbuf starting address of send buffer
sendcnt number of elements in send buffer
sendtype data type of send buffer elements
recvcount number of elements for any single receive
recvtype data type of recv buffer elements
root rank of receiving process
recvbuf (output) address of receive buffer
This method is deprecated. Use the templated Gather method instead.
Definition at line 202 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
Referenced by QUESO::GslVector::mpiAllQuantile(), and QUESO::TeuchosVector::mpiAllQuantile().
 {
   queso_deprecated();
   if (NumProc() > 1) {  // Necessarily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     //int MPI_Gather (void *sendbuf, int sendcnt, MPI_Datatype sendtype,
     //                void *recvbuf, int recvcount, MPI_Datatype recvtype,
     //                int root, MPI_Comm comm )
     int mpiRC = MPI_Gather(sendbuf, sendcnt, sendtype,
                            recvbuf, recvcount, recvtype,
                            root, m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
 }
template<typename T > void QUESO::MpiComm::Gather (const T * sendbuf, int sendcnt, T * recvbuf, int recvcount, int root, const char * whereMsg, const char * whatMsg) const
Gather values from each process to collect on all processes.
Parameters
sendbuf starting address of send buffer containing elements of type T
sendcnt number of elements in send buffer
recvcount number of elements for any single receive
root rank of receiving process
recvbuf (output) address of receive buffer containing elements of type T
Definition at line 224 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
 {
   if (NumProc() > 1) {  // Necessarily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     //int MPI_Gather (void *sendbuf, int sendcnt, MPI_Datatype sendtype,
     //                void *recvbuf, int recvcount, MPI_Datatype recvtype,
     //                int root, MPI_Comm comm )
     T * sendbuf_noconst = const_cast<T *>(sendbuf);
     int mpiRC = MPI_Gather(sendbuf_noconst, sendcnt, StandardType<T>(sendbuf),
                            recvbuf, recvcount, StandardType<T>(sendbuf),
                            root, m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
   else {
     size_t dataTypeSize = sizeof(T);
     size_t sendTotal = dataTypeSize*sendcnt;
     size_t recvTotal = dataTypeSize*recvcount;
     if (sendTotal != recvTotal) {
       std::cerr << "MpiCommClass::Gather()"
                 << ": sendTotal != recvTotal"
                 << std::endl;
     }
     queso_require_equal_to_msg(sendTotal, recvTotal, whatMsg);
     std::memcpy(recvbuf, sendbuf, sendTotal);
   }
 }
void QUESO::MpiComm::Gatherv (void * sendbuf, int sendcnt, RawType_MPI_Datatype sendtype, void * recvbuf, int * recvcnts, int * displs, RawType_MPI_Datatype recvtype, int root, const char * whereMsg, const char * whatMsg) const
Gathers into specified locations from all processes in a group.
Parameters
sendbuf starting address of send buffer
sendcount number of elements in send buffer
sendtype data type of send buffer elements
recvcounts integer array (of length group size) containing the number of elements that are received from each process
displs integer array (of length group size). Entry i specifies the displacement relative to recvbuf at which to place the incoming data from process i
recvtype data type of recv buffer elements
root rank of receiving process
Definition at line 254 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
 {
   queso_deprecated();
   if (NumProc() > 1) {  // Necessarily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     //int MPI_Gatherv(void *sendbuf, int sendcnt, MPI_Datatype sendtype,
     //                void *recvbuf, int *recvcnts, int *displs, MPI_Datatype recvtype,
     //                int root, MPI_Comm comm )
     int mpiRC = MPI_Gatherv(sendbuf, sendcnt, sendtype,
                             recvbuf, recvcnts, displs, recvtype,
                             root, m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
 }
template<typename T > void QUESO::MpiComm::Gatherv (const T * sendbuf, int sendcnt, T * recvbuf, int * recvcnts, int * displs, int root, const char * whereMsg, const char * whatMsg) const
Gathers into specified locations from all processes in a group.
Parameters
sendbuf starting address of send buffer containing elements of type T
sendcnt number of elements in send buffer
recvcnts integer array (of length group size) containing the number of elements that are received from each process
displs integer array (of length group size). Entry i specifies the displacement relative to recvbuf at which to place the incoming data from process i
root rank of receiving process
Definition at line 276 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
 {
   if (NumProc() > 1) {  // Necessarily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     //int MPI_Gatherv(void *sendbuf, int sendcnt, MPI_Datatype sendtype,
     //                void *recvbuf, int *recvcnts, int *displs, MPI_Datatype recvtype,
     //                int root, MPI_Comm comm )
     T * sendbuf_noconst = const_cast<T *>(sendbuf);
     int mpiRC = MPI_Gatherv(sendbuf_noconst, sendcnt, StandardType<T>(sendbuf),
                             recvbuf, recvcnts, displs,
                             StandardType<T>(recvbuf), root, m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
   else {
     size_t dataTypeSize = sizeof(T);
     size_t sendTotal = dataTypeSize*sendcnt;
     size_t recvTotal = dataTypeSize*recvcnts[0];
     if (sendTotal != recvTotal) {
       std::cerr << "MpiCommClass::Gatherv()"
                 << ": sendTotal != recvTotal"
                 << std::endl;
     }
     queso_require_equal_to_msg(sendTotal, recvTotal, whatMsg);
     std::memcpy(recvbuf, sendbuf, sendTotal);
   }
 }
int QUESO::MpiComm::MyPID () const
Return my process ID.
Definition at line 124 of file MpiComm.C.
References m_epetraComm, and m_myPid.
Referenced by QUESO::MiscCheckForSameValueInAllNodes(), QUESO::GslVector::mpiAllQuantile(), QUESO::TeuchosVector::mpiAllQuantile(), QUESO::GslVector::mpiAllReduce(), QUESO::TeuchosVector::mpiAllReduce(), QUESO::GslVector::mpiBcast(), QUESO::TeuchosVector::mpiBcast(), and syncPrintDebugMsg().
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraComm->MyPID();
 #endif
   return m_myPid;
 }
int QUESO::MpiComm::NumProc () const
Returns total number of processes.
Definition at line 133 of file MpiComm.C.
References m_epetraComm, and m_numProc.
Referenced by Allreduce(), Barrier(), Bcast(), Gather(), Gatherv(), QUESO::EnvironmentOptions::getMyOptionValues(), QUESO::MiscCheckForSameValueInAllNodes(), QUESO::MiscCheckTheParallelEnvironment(), QUESO::GslVector::mpiAllQuantile(), QUESO::TeuchosVector::mpiAllQuantile(), QUESO::GslVector::mpiBcast(), QUESO::TeuchosVector::mpiBcast(), QUESO::Matrix::numOfProcsForStorage(), QUESO::Vector::numOfProcsForStorage(), Recv(), Send(), and syncPrintDebugMsg().
 {
 #ifdef QUESO_HAS_TRILINOS
   return m_epetraComm->NumProc();
 #endif
   return m_numProc;
 }
MpiComm & QUESO::MpiComm::operator= (const MpiComm & rhs)
Assignment operator.
Definition at line 102 of file MpiComm.C.
References copy().
 {
   this->copy(rhs);
   return *this;
 }
void QUESO::MpiComm::Recv (void * buf, int count, RawType_MPI_Datatype datatype, int source, int tag, RawType_MPI_Status * status, const char * whereMsg, const char * whatMsg) const
Blocking receive of data from this process to another process.
Parameters
buf (output) initial address of receive buffer
status (output) status object
count maximum number of elements in receive buffer
datatype datatype of each receive buffer element
source rank of source
tag message tag
Definition at line 307 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
 {
   if (NumProc() > 1) {  // Necesarrily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     int mpiRC = MPI_Recv(buf, count, datatype, source, tag, m_rawComm, status);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
 }
void QUESO::MpiComm::Send (void * buf, int count, RawType_MPI_Datatype datatype, int dest, int tag, const char * whereMsg, const char * whatMsg) const
Possibly blocking send of data from this process to another process.
Parameters
buf initial address of send buffer
count number of elements in send buffer
datatype datatype of each send buffer element
dest rank of destination
tag message tag
Definition at line 320 of file MpiComm.C.
References m_rawComm, NumProc(), and QUESO::queso_require_equal_to_msg.
 {
   if (NumProc() > 1) {  // Necesarrily true if QUESO_HAS_MPI
 #ifdef QUESO_HAS_MPI
     int mpiRC = MPI_Send(buf, count, datatype, dest, tag, m_rawComm);
     queso_require_equal_to_msg(mpiRC, MPI_SUCCESS, whatMsg);
 #endif
   }
 }
void QUESO::MpiComm::syncPrintDebugMsg (const char * msg, unsigned int msgVerbosity, unsigned int numUSecs) const
Synchronizes all the processes and print debug message.
Definition at line 333 of file MpiComm.C.
References Barrier(), QUESO::BaseEnvironment::fullRank(), QUESO::BaseEnvironment::inter0Rank(), m_env, MyPID(), NumProc(), QUESO::BaseEnvironment::subId(), QUESO::BaseEnvironment::subRank(), and QUESO::BaseEnvironment::syncVerbosity().
 {
   if (m_env.syncVerbosity() >= msgVerbosity) {
     this->Barrier();
     for (int i = 0; i < this->NumProc(); ++i) {
       if (i == this->MyPID()) {
         std::cout << msg
                   << ": fullRank "       << m_env.fullRank()
                   << ", subEnvironment " << m_env.subId()
                   << ", subRank "        << m_env.subRank()
                   << ", inter0Rank "     << m_env.inter0Rank()
                   << std::endl;
       }
       usleep(numUSecs);
       this->Barrier();
     }
     //if (this->fullRank() == 0) std::cout << "Sleeping " << numUSecs << " microseconds..."
     //                                     << std::endl;
     //usleep(numUSecs);
     this->Barrier();
   }
   return;
 }
Member Data Documentation
const BaseEnvironment& QUESO::MpiComm::m_env private
Definition at line 395 of file MpiComm.h.
Referenced by syncPrintDebugMsg().
Epetra_Comm* QUESO::MpiComm::m_epetraComm private
Definition at line 399 of file MpiComm.h.
Referenced by Barrier(), Comm(), copy(), epetraMpiComm(), MpiComm(), MyPID(), and NumProc().
int QUESO::MpiComm::m_myPid private
Process ID of this process.
Definition at line 409 of file MpiComm.h.
Referenced by copy(), MpiComm(), and MyPID().
int QUESO::MpiComm::m_numProc private
Definition at line 412 of file MpiComm.h.
Referenced by copy(), MpiComm(), and NumProc().
RawType_MPI_Comm QUESO::MpiComm::m_rawComm private
Embedded wrapped opaque MPI_Comm object.
Definition at line 403 of file MpiComm.h.
Referenced by Allreduce(), Barrier(), Bcast(), Comm(), copy(), Gather(), Gatherv(), Recv(), and Send().
int QUESO::MpiComm::m_worldRank private
World rank.
Definition at line 406 of file MpiComm.h.
Referenced by copy(), and MpiComm().
The documentation for this class was generated from the following files:
src/core/inc/MpiComm.h
src/core/src/MpiComm.C