queso-0.53.0: QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M > Class Template Reference
QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M > Class Template Reference
#include <GcmZInfo.h>
Public Member Functions
GcmZInfo (bool formCMatrix, bool allOutputsAreScalar, const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > &s)
GcmZInfo (bool formCMatrix, bool allOutputsAreScalar, const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > &s, const GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M > &e, const GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M > &jj)
GcmZInfo (bool allOutputsAreScalar, const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > &s, const GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M > &e)
~GcmZInfo ()
Public Attributes
const BaseEnvironment & m_env
unsigned int m_z_size
VectorSpace< D_V, D_M > m_z_space
D_V m_Zvec_hat
D_M * m_Cmat
unsigned int m_Cmat_rank
D_M m_tmp_Smat_z
D_M m_tmp_Smat_extra
D_M m_tmp_Smat_z_hat
D_M m_tmp_Smat_z_hat_inv
Private Member Functions
void commonConstructor ()
Detailed Description
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix>
class QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >
Definition at line 40 of file GcmZInfo.h.
Constructor & Destructor Documentation
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo (bool formCMatrix, bool allOutputsAreScalar, const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > & s)
Definition at line 33 of file GcmZInfo.C.
References QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor(), QUESO::VectorSpace< V, M >::dimLocal(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_env, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_paper_m, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_paper_p_eta, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_z_space, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Zvec_hat, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_Zvec_hat_w, queso_require_equal_to_msg, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_env               (s.m_env),
   m_z_size            (s.m_w_size),
   m_z_space           (m_env, "z_", m_z_size, NULL),
   m_Zvec_hat          (m_z_space.zeroVector()),
   m_Cmat              (NULL), // to be deleted on destructor
   m_Cmat_rank         (0),
   m_tmp_Smat_z        (m_z_space.zeroVector()),
   m_tmp_Smat_extra    (m_z_space.zeroVector()),
   m_tmp_Smat_z_hat    (m_z_space.zeroVector()),
   m_tmp_Smat_z_hat_inv(m_z_space.zeroVector())
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering GcmZInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(1)"
                             << std::endl;
   }
   m_Zvec_hat = s.m_Zvec_hat_w;
   //********************************************************************************
   // Make checks
   //********************************************************************************
   queso_require_equal_to_msg(m_z_space.dimLocal(), (s.m_paper_m * s.m_paper_p_eta), "incompatible calculations for 'z' vector size (1)");
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving GcmZInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(1)"
                             << std::endl;
   }
 }
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo (bool formCMatrix, bool allOutputsAreScalar, const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > & s, const GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M > & e, const GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M > & jj)
Definition at line 71 of file GcmZInfo.C.
References QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor(), QUESO::VectorSpace< V, M >::dimLocal(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Bmat_rank, QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Bmat_with_permut, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Cmat, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Cmat_rank, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_env, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_Kmat, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_Kmat_rank, QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_omega_space, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_paper_m, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_paper_n, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_paper_p_delta, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_paper_p_eta, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_z_size, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_z_space, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Zvec_hat, QUESO::GcmJointInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Zvec_hat_vu, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_Zvec_hat_w, QUESO::VectorSpace< V, M >::map(), queso_require_equal_to_msg, queso_require_greater_msg, queso_require_less_equal_msg, queso_require_msg, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_env               (s.m_env),
   m_z_size            (s.m_w_size + e.m_v_size + jj.m_u_size),
   m_z_space           (m_env, "z_", m_z_size, NULL),
   m_Zvec_hat          (m_z_space.zeroVector()),
   m_Cmat              (NULL), // to be deleted on destructor
   m_Cmat_rank         (0),
   m_tmp_Smat_z        (m_z_space.zeroVector()),
   m_tmp_Smat_extra    (m_z_space.zeroVector()),
   m_tmp_Smat_z_hat    (m_z_space.zeroVector()),
   m_tmp_Smat_z_hat_inv(m_z_space.zeroVector())
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering GcmZInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(2)"
                             << ": formCMatrix = " << formCMatrix
                             << std::endl;
   }
   queso_require_msg(!allOutputsAreScalar, "'allOutputsAreScalar' should be false");
   m_Zvec_hat.cwSetConcatenated(jj.m_Zvec_hat_vu,s.m_Zvec_hat_w);
   if (formCMatrix) {
     //********************************************************************************
     // Form 'C' matrix
     //********************************************************************************
     m_Cmat      = new D_M(m_env,jj.m_omega_space.map(),m_z_size);
     m_Cmat_rank = std::min(m_Cmat->numRowsGlobal(),m_Cmat->numCols()); // Might be smaller
     //********************************************************************************
     // Compute 'C' matrix
     //********************************************************************************
     m_Cmat->cwSet(0.);
     m_Cmat->cwSet(                                    0,                               0,*jj.m_Bmat_with_permut);
     m_Cmat->cwSet(jj.m_Bmat_with_permut->numRowsLocal(),jj.m_Bmat_with_permut->numCols(),  s.m_Kmat            );
     m_Cmat_rank= m_Cmat->rank(0.,1.e-8 ); // todo: should be an option
     unsigned int cRank14    = m_Cmat->rank(0.,1.e-14);
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 3)) {
       *m_env.subDisplayFile() << "In GcmZInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(2)"
                               << ": m_Cmat.numRowsLocal() = "  << m_Cmat->numRowsLocal()
                               << ", m_Cmat.numCols() = "       << m_Cmat->numCols()
                               << ", m_Cmat.rank(0.,1.e-8) = "  << m_Cmat_rank
                               << ", m_Cmat.rank(0.,1.e-14) = " << cRank14
                               << std::endl;
     }
     queso_require_equal_to_msg(m_Cmat_rank, (jj.m_Bmat_rank + s.m_Kmat_rank), "'m_Cmat_rank' should be the sum of 'B' and 'K' ranks");
     queso_require_greater_msg(m_Cmat->numRowsLocal(), m_Cmat->numCols(), "'m_Cmat' should be a 'vertical' rectangular matrix");
     queso_require_equal_to_msg(m_Cmat->numCols(), m_z_space.dimLocal(), "'m_Cmat' has invalid numCols");
     queso_require_less_equal_msg(m_Cmat_rank, m_Cmat->numCols(), "'m_Cmat' has invalid rank");
   }
   //********************************************************************************
   // Make checks
   //********************************************************************************
   queso_require_equal_to_msg(m_z_space.dimLocal(), (e.m_paper_n * e.m_paper_p_delta + e.m_paper_n * s.m_paper_p_eta + s.m_paper_m * s.m_paper_p_eta), "incompatible calculations for 'z' vector size (2)");
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving GcmZInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(2)"
                             << std::endl;
   }
 }
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo (bool allOutputsAreScalar, const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > & s, const GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M > & e)
Definition at line 148 of file GcmZInfo.C.
References QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor(), QUESO::VectorSpace< V, M >::dimLocal(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_env, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_paper_m, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_paper_n, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_paper_p_delta, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_paper_p_eta, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_z_space, QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Zvec_hat, queso_require_equal_to_msg, queso_require_msg, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_env               (s.m_env),
   m_z_size            (s.m_w_size + e.m_v_size),
   m_z_space           (m_env, "z_", m_z_size, NULL),
   m_Zvec_hat          (m_z_space.zeroVector()),
   m_Cmat              (NULL), // to be deleted on destructor
   m_Cmat_rank         (0),
   m_tmp_Smat_z        (m_z_space.zeroVector()),
   m_tmp_Smat_extra    (m_z_space.zeroVector()),
   m_tmp_Smat_z_hat    (m_z_space.zeroVector()),
   m_tmp_Smat_z_hat_inv(m_z_space.zeroVector())
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering GcmZInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(3)"
                             << ": key-debug"
                             << ", some entities just created (not yet populated)"
                             << ", m_Zvec_hat.sizeLocal() = " << m_Zvec_hat.sizeLocal()
                             << std::endl;
   }
   queso_require_msg(allOutputsAreScalar, "'allOutputsAreScalar' should be true");
   //m_Zvec_hat.cwSetConcatenated(e.m_Zvec_hat_v,s.m_Zvec_hat_w); // ppp
   //********************************************************************************
   // Make checks
   //********************************************************************************
   queso_require_equal_to_msg(m_z_space.dimLocal(), (e.m_paper_n * e.m_paper_p_delta + e.m_paper_n * s.m_paper_p_eta + s.m_paper_m * s.m_paper_p_eta), "incompatible calculations for 'z' vector size (2)");
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving GcmZInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(3)"
                             << std::endl;
   }
 }
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::~GcmZInfo ()
Definition at line 190 of file GcmZInfo.C.
 {
   delete m_Cmat; // to be deleted on destructor
 }
Member Function Documentation
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > void QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor () private
Definition at line 197 of file GcmZInfo.C.
Referenced by QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo().
 {
   //********************************************************************************
   // Display information
   //********************************************************************************
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "In GcnZInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::commonConstructor()"
                             << "\n  'z' vector size = " << m_z_space.dimLocal() // = n * p_delta + n * p_eta + m * p_eta
                             << std::endl;
   }
   return;
 }
Member Data Documentation
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> D_M* QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Cmat
Definition at line 64 of file GcmZInfo.h.
Referenced by QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor(), QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo(), and QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZTildeInfo().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> unsigned int QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Cmat_rank
Definition at line 65 of file GcmZInfo.h.
Referenced by QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor(), QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo(), and QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZTildeInfo().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> const BaseEnvironment& QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_env
Definition at line 59 of file GcmZInfo.h.
Referenced by QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> D_M QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_tmp_Smat_extra
Definition at line 68 of file GcmZInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> D_M QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_tmp_Smat_z
Definition at line 67 of file GcmZInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> D_M QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_tmp_Smat_z_hat
Definition at line 69 of file GcmZInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> D_M QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_tmp_Smat_z_hat_inv
Definition at line 70 of file GcmZInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> unsigned int QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_z_size
Definition at line 60 of file GcmZInfo.h.
Referenced by QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> VectorSpace<D_V,D_M> QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_z_space
Definition at line 61 of file GcmZInfo.h.
Referenced by QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo(), and QUESO::GcmZTildeInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZTildeInfo().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> D_V QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_Zvec_hat
Definition at line 62 of file GcmZInfo.h.
Referenced by QUESO::GcmZInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmZInfo().
The documentation for this class was generated from the following files:
src/gp/inc/GcmZInfo.h
src/gp/src/GcmZInfo.C