queso-0.53.0: QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M > Class Template Reference
QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M > Class Template Reference
#include <GcmTotalInfo.h>
Public Member Functions
GcmTotalInfo (const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > &s)
GcmTotalInfo (const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > &s, const GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M > &e)
~GcmTotalInfo ()
unsigned int initializeTotalDim (const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > &s)
unsigned int initializeTotalDim (const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > &s, const GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M > &e)
Public Attributes
const BaseEnvironment & m_env
unsigned int m_numConstituents
std::vector< const VectorSet
< P_V, P_M > * > m_constitutiveDomains
std::vector< const
BaseVectorRV< P_V, P_M > * > m_constitutivePriorRvs
unsigned int m_totalDim
VectorSpace< P_V, P_M > m_totalSpace
double m_totalDomainVolume
ConcatenationSubset< P_V, P_M > m_totalDomain
ConcatenatedVectorRV< P_V, P_M > m_totalPriorRv
GenericVectorRV< P_V, P_M > m_totalPostRv
P_V m_like_previousTotal
P_V m_totalPostMean
P_V m_totalPostMedian
P_V m_totalPostMode
double m_totalPostMaxLnValue
P_V m_totalMLE
double m_totalLikeMaxLnValue
VectorSet< P_V, P_M > * m_solutionDomain
BaseJointPdf< P_V, P_M > * m_solutionPdf
BaseVectorRealizer< P_V, P_M > * m_solutionRealizer
MetropolisHastingsSG< P_V, P_M > * m_mhSeqGenerator
MLSampling< P_V, P_M > * m_mlSampler
BaseVectorSequence< P_V, P_M > * m_chain
Private Member Functions
void commonConstructor ()
Detailed Description
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix>
class QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >
Definition at line 44 of file GcmTotalInfo.h.
Constructor & Destructor Documentation
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmTotalInfo (const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > & s)
Definition at line 32 of file GcmTotalInfo.C.
References QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_env, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_env                 (s.m_env),
   m_numConstituents     (4),
   m_constitutiveDomains (m_numConstituents,(const VectorSet   <P_V,P_M>*) NULL),
   m_constitutivePriorRvs(m_numConstituents,(const BaseVectorRV<P_V,P_M>*) NULL),
   m_totalDim            (initializeTotalDim(s)),
   m_totalSpace          (m_env,"total_",m_totalDim,NULL),
   m_totalDomainVolume   (1.),
   m_totalDomain         ("total_",m_totalSpace,m_totalDomainVolume,m_constitutiveDomains),
   m_totalPriorRv        ("total_prior_",m_constitutivePriorRvs,m_totalDomain),
   m_totalPostRv         ("total_post_",m_totalSpace),
   m_like_previousTotal  (m_totalSpace.zeroVector()),
   m_totalPostMean       (m_totalSpace.zeroVector()),
   m_totalPostMedian     (m_totalSpace.zeroVector()),
   m_totalPostMode       (m_totalSpace.zeroVector()),
   m_totalPostMaxLnValue (-INFINITY),
   m_totalMLE            (m_totalSpace.zeroVector()),
   m_totalLikeMaxLnValue (-INFINITY),
   m_solutionDomain      (NULL),
   m_solutionPdf         (NULL),
   m_solutionRealizer    (NULL),
   m_mhSeqGenerator      (NULL),
   m_mlSampler           (NULL),
   m_chain               (NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering GcmTotalInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(1)"
                             << std::endl;
   }
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving GcmTotalInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(1)"
                             << std::endl;
   }
 }
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmTotalInfo (const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > & s, const GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M > & e)
Definition at line 73 of file GcmTotalInfo.C.
References QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_env, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_env                 (s.m_env),
   m_numConstituents     (8),
   m_constitutiveDomains (m_numConstituents,(const VectorSet<P_V,P_M>*) NULL),
   m_constitutivePriorRvs(m_numConstituents,(const BaseVectorRV<P_V,P_M>*) NULL),
   m_totalDim            (initializeTotalDim(s,e)),
   m_totalSpace          (m_env, "total_", m_totalDim, NULL),
   m_totalDomainVolume   (1.),
   m_totalDomain         ("total_",m_totalSpace,m_totalDomainVolume,m_constitutiveDomains),
   m_totalPriorRv        ("total_prior_",m_constitutivePriorRvs,m_totalDomain),
   m_totalPostRv         ("total_post_",m_totalSpace),
   m_like_previousTotal  (m_totalSpace.zeroVector()),
   m_totalPostMean       (m_totalSpace.zeroVector()),
   m_totalPostMedian     (m_totalSpace.zeroVector()),
   m_totalPostMode       (m_totalSpace.zeroVector()),
   m_totalPostMaxLnValue (-INFINITY),
   m_totalMLE            (m_totalSpace.zeroVector()),
   m_totalLikeMaxLnValue (-INFINITY),
   m_solutionDomain      (NULL),
   m_solutionPdf         (NULL),
   m_solutionRealizer    (NULL),
   m_mhSeqGenerator      (NULL),
   m_mlSampler           (NULL),
   m_chain               (NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering GcmTotalInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(2)"
                             << std::endl;
   }
   commonConstructor();
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving GcmTotalInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::constructor(2)"
                             << std::endl;
   }
 }
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::~GcmTotalInfo ()
Definition at line 115 of file GcmTotalInfo.C.
 {
   if (m_chain) {
     m_chain->clear();
     delete m_chain;
   }
   if (m_mlSampler       ) delete m_mlSampler;
   if (m_mhSeqGenerator  ) delete m_mhSeqGenerator;
   if (m_solutionRealizer) delete m_solutionRealizer;
   if (m_solutionPdf     ) delete m_solutionPdf;
   if (m_solutionDomain  ) delete m_solutionDomain;
 }
Member Function Documentation
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > void QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::commonConstructor () private
Definition at line 175 of file GcmTotalInfo.C.
Referenced by QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmTotalInfo().
 {
   m_totalPriorRv.pdf().setNormalizationStyle(0); // CSRI - 2013-Aug-06 - with Laura
   for (unsigned int i = 0; i < m_numConstituents; ++i) {
     m_totalDomainVolume *= m_constitutiveDomains[i]->volume();
   }
   //********************************************************************************
   // Display information
   //********************************************************************************
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "In GcmTotalInfo<S_V,S_M,D_V,D_M,P_V,P_M,Q_V,Q_M>::commonConstructor()"
                             << "\n  m_totalDim          = "  << m_totalDim
                             << "\n  m_numConstituents   = "  << m_numConstituents
                             << "\n  m_totalDomainVolume = "  << m_totalDomainVolume
                             << std::endl;
   }
   return;
 }
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > unsigned int QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::initializeTotalDim (const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > & s)
Definition at line 130 of file GcmTotalInfo.C.
References QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_1lambdaEtaDim, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_1lambdaEtaDomain, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_1lambdaEtaPriorRv, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_2lambdaWDim, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_2lambdaWDomain, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_2lambdaWPriorRv, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_3rhoWDim, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_3rhoWDomain, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_3rhoWPriorRv, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_4lambdaSDim, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_4lambdaSDomain, and QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_4lambdaSPriorRv.
 {
   m_constitutiveDomains[0] = &(s.m_1lambdaEtaDomain);
   m_constitutiveDomains[1] = &(s.m_2lambdaWDomain);
   m_constitutiveDomains[2] = &(s.m_3rhoWDomain);
   m_constitutiveDomains[3] = &(s.m_4lambdaSDomain);
   m_constitutivePriorRvs[0] = &(s.m_1lambdaEtaPriorRv);
   m_constitutivePriorRvs[1] = &(s.m_2lambdaWPriorRv);
   m_constitutivePriorRvs[2] = &(s.m_3rhoWPriorRv);
   m_constitutivePriorRvs[3] = &(s.m_4lambdaSPriorRv);
   return (s.m_1lambdaEtaDim + s.m_2lambdaWDim + s.m_3rhoWDim + s.m_4lambdaSDim);
 }
template<class S_V , class S_M , class D_V , class D_M , class P_V , class P_M , class Q_V , class Q_M > unsigned int QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::initializeTotalDim (const GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M > & s, const GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M > & e)
Definition at line 148 of file GcmTotalInfo.C.
References QUESO::BaseVectorRV< V, M >::imageSet(), QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_1lambdaEtaDim, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_1lambdaEtaDomain, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_1lambdaEtaPriorRv, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_2lambdaWDim, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_2lambdaWDomain, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_2lambdaWPriorRv, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_3rhoWDim, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_3rhoWDomain, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_3rhoWPriorRv, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_4lambdaSDim, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_4lambdaSDomain, QUESO::GcmSimulationInfo< S_V, S_M, P_V, P_M, Q_V, Q_M >::m_4lambdaSPriorRv, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_5lambdaYDim, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_5lambdaYDomain, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_5lambdaYPriorRv, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_6lambdaVDim, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_6lambdaVDomain, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_6lambdaVPriorRv, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_7rhoVDim, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_7rhoVDomain, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_7rhoVPriorRv, QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_8thetaDim, and QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::m_8thetaPriorRv.
 {
   m_constitutiveDomains[0] = &(s.m_1lambdaEtaDomain);
   m_constitutiveDomains[1] = &(s.m_2lambdaWDomain);
   m_constitutiveDomains[2] = &(s.m_3rhoWDomain);
   m_constitutiveDomains[3] = &(s.m_4lambdaSDomain);
   m_constitutiveDomains[4] = &(e.m_5lambdaYDomain);
   m_constitutiveDomains[5] = &(e.m_6lambdaVDomain);
   m_constitutiveDomains[6] = &(e.m_7rhoVDomain);
   m_constitutiveDomains[7] = &(e.m_8thetaPriorRv.imageSet());
   m_constitutivePriorRvs[0] = &(s.m_1lambdaEtaPriorRv);
   m_constitutivePriorRvs[1] = &(s.m_2lambdaWPriorRv);
   m_constitutivePriorRvs[2] = &(s.m_3rhoWPriorRv);
   m_constitutivePriorRvs[3] = &(s.m_4lambdaSPriorRv);
   m_constitutivePriorRvs[4] = &(e.m_5lambdaYPriorRv);
   m_constitutivePriorRvs[5] = &(e.m_6lambdaVPriorRv);
   m_constitutivePriorRvs[6] = &(e.m_7rhoVPriorRv);
   m_constitutivePriorRvs[7] = &(e.m_8thetaPriorRv);
   return (s.m_1lambdaEtaDim + s.m_2lambdaWDim + s.m_3rhoWDim + s.m_4lambdaSDim + e.m_5lambdaYDim + e.m_6lambdaVDim + e.m_7rhoVDim + e.m_8thetaDim);
 }
Member Data Documentation
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> BaseVectorSequence<P_V,P_M>* QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_chain
Definition at line 82 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> std::vector<const VectorSet <P_V,P_M>* > QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_constitutiveDomains
Definition at line 59 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> std::vector<const BaseVectorRV<P_V,P_M>* > QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_constitutivePriorRvs
Definition at line 60 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> const BaseEnvironment& QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_env
Definition at line 57 of file GcmTotalInfo.h.
Referenced by QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GcmTotalInfo().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> P_V QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_like_previousTotal
Definition at line 68 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> MetropolisHastingsSG<P_V,P_M>* QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_mhSeqGenerator
Definition at line 80 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> MLSampling<P_V,P_M>* QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_mlSampler
Definition at line 81 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> unsigned int QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_numConstituents
Definition at line 58 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> VectorSet<P_V,P_M>* QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_solutionDomain
Definition at line 76 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> BaseJointPdf<P_V,P_M>* QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_solutionPdf
Definition at line 77 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> BaseVectorRealizer<P_V,P_M>* QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_solutionRealizer
Definition at line 78 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> unsigned int QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalDim
Definition at line 61 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> ConcatenationSubset<P_V,P_M> QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalDomain
Definition at line 64 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> double QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalDomainVolume
Definition at line 63 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> double QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalLikeMaxLnValue
Definition at line 74 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> P_V QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalMLE
Definition at line 73 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> double QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalPostMaxLnValue
Definition at line 72 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> P_V QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalPostMean
Definition at line 69 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> P_V QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalPostMedian
Definition at line 70 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> P_V QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalPostMode
Definition at line 71 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> GenericVectorRV<P_V,P_M> QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalPostRv
Definition at line 66 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> ConcatenatedVectorRV<P_V,P_M> QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalPriorRv
Definition at line 65 of file GcmTotalInfo.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix, class P_V = GslVector, class P_M = GslMatrix, class Q_V = GslVector, class Q_M = GslMatrix> VectorSpace<P_V,P_M> QUESO::GcmTotalInfo< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::m_totalSpace
Definition at line 62 of file GcmTotalInfo.h.
The documentation for this class was generated from the following files:
src/gp/inc/GcmTotalInfo.h
src/gp/src/GcmTotalInfo.C