queso-0.57.1: QUESO::TeuchosVector Class Reference
QUESO::TeuchosVector Class Reference
Class for vector operations using Teuchos (Trilinos).
#include <TeuchosVector.h>
Public Member Functions
Constructor/Destructor methods.
TeuchosVector (const BaseEnvironment &env, const Map &map)
Shaped constructor: creates an empty vector of size given by Map& map.
TeuchosVector (const BaseEnvironment &env, const Map &map, double value)
Shaped constructor: creates an vector of values value and of size given by Map& map.
TeuchosVector (const BaseEnvironment &env, double d1, double d2, const Map &map)
Shaped constructor: creates an vector of size given by Map& map and of values given by an average involving d1, d2 and the vector size.
TeuchosVector (const TeuchosVector &v, double d1, double d2)
Shaped constructor: creates an vector of size given by vector v and of values given by an average involving d1, d2 and vector size.
TeuchosVector (const TeuchosVector &y)
Copy constructor.
~TeuchosVector ()
Destructor.
Set methods.
TeuchosVector & operator= (double a)
Set all values in the vector to a constant value.
TeuchosVector & operator= (const TeuchosVector &rhs)
Copies values from one vector to another.
TeuchosVector & operator*= (double a)
Stores in this vector the coordinate-wise multiplication of this and a.
TeuchosVector & operator/= (double a)
Stores in this vector the coordinate-wise division of this by a.
TeuchosVector & operator*= (const TeuchosVector &rhs)
Stores in this vector the coordinate-wise multiplication of this with rhs.
TeuchosVector & operator/= (const TeuchosVector &rhs)
Stores in this vector the coordinate-wise division of this by rhs.
TeuchosVector & operator+= (const TeuchosVector &rhs)
Stores in this vector the coordinate-wise addition of this and rhs.
TeuchosVector & operator-= (const TeuchosVector &rhs)
Stores in this vector the coordinate-wise subtraction of this and rhs.
void cwSet (double value)
Component-wise sets all values to this with value.
void cwSet (unsigned int initialPos, const TeuchosVector &vec)
Component-wise sets all values of this with vector vec, starting at position initialPos.
void cwExtract (unsigned int initialPos, TeuchosVector &vec) const
Component-wise extracts all values of this with vector vec, starting at position initialPos.
void cwInvert ()
This function inverts component-wise the element values of this.
void cwSqrt ()
Component-wise sets the square-root of this.
void cwSetConcatenated (const TeuchosVector &v1, const TeuchosVector &v2)
This function concatenates vectors v1 and v2 into this vector.
void cwSetGaussian (double mean, double stdDev)
This function sets component-wise Gaussian random variates, with mean mean and standard deviation stdDev.
void cwSetGaussian (const TeuchosVector &meanVec, const TeuchosVector &stdDevVec)
This function sets component-wise Gaussian random variates, with vectors for mean and standard deviation.
void cwSetUniform (const TeuchosVector &lowerBoundVec, const TeuchosVector &upperBoundVec)
This function sets component-wise a number uniformly distributed in the range of elements of [lowerBoundVec,upperBoundVec].
void cwSetBeta (const TeuchosVector &alpha, const TeuchosVector &beta)
This function sets component-wise random variates from the Beta distribution, with vector parameters alpha and beta.
void cwSetGamma (const TeuchosVector &a, const TeuchosVector &b)
This function sets component-wise random variates from the Inverse Gamma distribution, with parameters given by vectors a and b.
void cwSetInverseGamma (const TeuchosVector &a, const TeuchosVector &b)
This function sets component-wise random variates from the Inverse Gamma distribution, with parameters given by vectors a and b.
Accessor methods.
double & operator[] (unsigned int i)
Element access method (non-const).
const double & operator[] (unsigned int i) const
Element access method (const).
Attribute methods.
unsigned int sizeLocal () const
Returns the length of this vector.
unsigned int sizeGlobal () const
Returns the global length of this vector.
double * values ()
double getMaxValue () const
Returns the maximum value in the this vector.
double getMinValue () const
Returns the minimum value in the this vector.
int getMaxValueIndex () const
This function returns the index of the maximum value in the vector this.
int getMinValueIndex () const
This function returns the index of the minimum value in the vector this.
void getMaxValueAndIndex (double &value, int &index)
This function returns maximum value in the vector this and its the index.
void getMinValueAndIndex (double &value, int &index)
This function returns minimum value in the vector this and its the index.
Norm methods
double norm2Sq () const
Returns the norm of the vector, as the square root of 2-norm of this vector.
double norm2 () const
Returns the 2-norm (Euclidean norm) of the vector.
double norm1 () const
Returns the 1-norm of the vector.
double normInf () const
Returns the infinity-norm (maximum norm) of the vector.
Comparison methods.
bool atLeastOneComponentSmallerThan (const TeuchosVector &rhs) const
This function returns true if at least one component of this is smaller than the respective component of rhs.
bool atLeastOneComponentBiggerThan (const TeuchosVector &rhs) const
This function returns true if at least one component of this is bigger than the respective component of rhs.
bool atLeastOneComponentSmallerOrEqualThan (const TeuchosVector &rhs) const
This function returns true if at least one component of this is smaller than or equal to the respective component of rhs.
bool atLeastOneComponentBiggerOrEqualThan (const TeuchosVector &rhs) const
This function returns true if at least one component of this is bigger than or equal to the respective component of rhs.
Miscellaneous methods.
TeuchosVector abs () const
This function returns absolute value of all elements in this.
void copy_to_std_vector (std::vector< double > &vec)
Copies the values of this vector (a TeuchosVector) to a std::vector structure.
void copy_from_std_vector (const std::vector< double > vec)
Copies the values of std::vector structure to this vector (a TeuchosVector).
void sort ()
This function sorts the elements of the vector this in ascending numerical order.
double sumOfComponents () const
Returns the sum of the components of the vector.
void mpiBcast (int srcRank, const MpiComm &bcastComm)
Broadcasts a message from the process with srcRank root to all other processes of the group.
void mpiAllReduce (RawType_MPI_Op mpiOperation, const MpiComm &opComm, TeuchosVector &resultVec) const
Combines values from all processes and distributes the result back to all processes.
void mpiAllQuantile (double probability, const MpiComm &opComm, TeuchosVector &resultVec) const
Gathers values from a group of processes and returns all quantiles.
void matlabLinearInterpExtrap (const TeuchosVector &xVec, const TeuchosVector &yVec, const TeuchosVector &xiVec)
Reproduces MATLAB linear inter/extra-polation.
void matlabDiff (unsigned int firstPositionToStoreDiff, double valueForRemainderPosition, TeuchosVector &outputVec) const
I/O methods.
void print (std::ostream &os) const
Print method. Defines the behavior of the std::ostream << operator inherited from the Object class.
void subReadContents (const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds)
void subWriteContents (const std::string &varNamePrefix, const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds) const
Public Member Functions inherited from QUESO::Vector
Vector (const BaseEnvironment &env, const Map &map)
Shaped Constructor.
virtual ~Vector ()
Virtual Destructor.
const BaseEnvironment & env () const
const Map & map () const
unsigned int numOfProcsForStorage () const
void setPrintHorizontally (bool value) const
Determines whether vector should be printed horizontally.
bool getPrintHorizontally () const
Checks if vector is printed horizontally.
void setPrintScientific (bool value) const
Determines whether vector should be printed in Scientific Notation.
bool getPrintScientific () const
Checks if the vector should be printed in Scientific Notation.
Private Member Functions
TeuchosVector ()
Default Constructor.
void copy (const TeuchosVector &src)
This function copies the elements of the vector src into this.
Private Attributes
Teuchos::SerialDenseVector
< int, double > m_vec
Teuchos vector.
Additional Inherited Members
Protected Member Functions inherited from QUESO::Vector
virtual void base_copy (const Vector &src)
Copies base data from vector src to this vector.
Protected Attributes inherited from QUESO::Vector
const BaseEnvironment & m_env
Environment variable.
const Map m_map
Mapping variable.
const Map & m_map
Mapping variable.
bool m_printHorizontally
Flag for either or not print this matrix horizontally.
bool m_printScientific
Flag for either or not print this matrix in scientific notation.
Detailed Description
Class for vector operations using Teuchos (Trilinos).
This class creates and provides basic support for vectors of templated type as a specialization of Vector using Teuchos vectors (from Trilinos), which are defined by an encapsulated Teuchos::SerialDenseVector structure.
Definition at line 55 of file TeuchosVector.h.
Constructor & Destructor Documentation
QUESO::TeuchosVector::TeuchosVector (const BaseEnvironment & env, const Map & map)
Shaped constructor: creates an empty vector of size given by Map& map.
Definition at line 38 of file TeuchosVector.C.
References QUESO::Vector::m_map, m_vec, QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), and QUESO::queso_require_equal_to_msg.
   :
   Vector(env,map)
 {
   m_vec.size(map.NumGlobalElements());
   queso_require_equal_to_msg(m_vec.length(), map.NumMyElements(), "incompatible local vec size");
   queso_require_equal_to_msg(m_vec.length(), map.NumGlobalElements(), "incompatible global vec size");
   queso_require_equal_to_msg(m_vec.length(), m_map.NumMyElements(), "incompatible own vec size");
   //std::cout << "In TeuchosVector::constructor(env,map)"
   //          << "\n  m_vec.length()             = " << m_vec.length()
   //          << "\n  map.NumGlobalElements() = " << map.NumGlobalElements()
   //          << "\n  map.NumMyElements()     = " << map.NumMyElements()
   //          << std::endl;
 }
QUESO::TeuchosVector::TeuchosVector (const BaseEnvironment & env, const Map & map, double value)
Shaped constructor: creates an vector of values value and of size given by Map& map.
Definition at line 58 of file TeuchosVector.C.
References QUESO::Vector::m_map, m_vec, QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), and QUESO::queso_require_equal_to_msg.
   :
   Vector(env,map)
 {
   m_vec.size(map.NumGlobalElements());
   m_vec = value;
   queso_require_equal_to_msg(m_vec.length(), map.NumMyElements(), "incompatible local vec size");
   queso_require_equal_to_msg(m_vec.length(), map.NumGlobalElements(), "incompatible global vec size");
   queso_require_equal_to_msg(m_vec.length(), m_map.NumMyElements(), "incompatible own vec size");
 }
QUESO::TeuchosVector::TeuchosVector (const BaseEnvironment & env, double d1, double d2, const Map & map)
Shaped constructor: creates an vector of size given by Map& map and of values given by an average involving d1, d2 and the vector size.
Definition at line 73 of file TeuchosVector.C.
References QUESO::Vector::m_map, m_vec, QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), and QUESO::queso_require_equal_to_msg.
   :
   Vector(env,map)
   {
   m_vec.size(map.NumGlobalElements());
   queso_require_equal_to_msg(m_vec.length(), map.NumMyElements(), "incompatible local vec size");
   queso_require_equal_to_msg(m_vec.length(), map.NumGlobalElements(), "incompatible global vec size");
   for (int i = 0; i < m_vec.length(); ++i) {
     double alpha = (double) i / ((double) m_vec.length() - 1.);
     (*this)[i] = (1.-alpha)*d1 + alpha*d2;
   }
   queso_require_equal_to_msg(m_vec.length(), m_map.NumMyElements(), "incompatible own vec size");
 }
QUESO::TeuchosVector::TeuchosVector (const TeuchosVector & v, double d1, double d2)
Shaped constructor: creates an vector of size given by vector v and of values given by an average involving d1, d2 and vector size.
Definition at line 92 of file TeuchosVector.C.
References QUESO::Vector::m_map, m_vec, QUESO::Vector::map(), QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), QUESO::queso_require_equal_to_msg, and sizeLocal().
   :
   Vector(v.env(),v.map())
 {
   m_vec.size(v.sizeLocal());
   queso_require_equal_to_msg(m_vec.length(), v.map().NumMyElements(), "incompatible local vec size");
   queso_require_equal_to_msg(m_vec.length(), v.map().NumGlobalElements(), "incompatible global vec size");
   for ( int i = 0; i < m_vec.length(); ++i) {
     double alpha = (double) i / ((double) m_vec.length() - 1.);
     (*this)[i] = (1.-alpha)*d1 + alpha*d2;
   }
   queso_require_equal_to_msg(m_vec.length(), m_map.NumMyElements(), "incompatible own vec size");
 }
QUESO::TeuchosVector::TeuchosVector (const TeuchosVector & y)
Copy constructor.
Definition at line 111 of file TeuchosVector.C.
References copy(), QUESO::Vector::m_map, m_vec, QUESO::Vector::map(), QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), QUESO::queso_require_equal_to_msg, and sizeLocal().
   :
   Vector(v.env(),v.map())
  {
    m_vec.size(v.sizeLocal());
   queso_require_equal_to_msg(m_vec.length(), v.map().NumMyElements(), "incompatible local vec size");
   queso_require_equal_to_msg(m_vec.length(), v.map().NumGlobalElements(), "incompatible global vec size");
   this->copy(v);
   queso_require_equal_to_msg(m_vec.length(), m_map.NumMyElements(), "incompatible own vec size");
 }
QUESO::TeuchosVector::~TeuchosVector ()
Destructor.
Definition at line 127 of file TeuchosVector.C.
 {
 };
QUESO::TeuchosVector::TeuchosVector () private
Default Constructor.
Creates an empty vector of no length.
Member Function Documentation
TeuchosVector QUESO::TeuchosVector::abs () const
This function returns absolute value of all elements in this.
Definition at line 650 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   TeuchosVector abs_of_this_vec( *this );
   unsigned int size = abs_of_this_vec.sizeLocal();
   for( unsigned int i = 0; i < size; ++i )
     {
       abs_of_this_vec[i] = std::fabs( (*this)[i] );
     }
   return abs_of_this_vec;
 }
bool QUESO::TeuchosVector::atLeastOneComponentBiggerOrEqualThan (const TeuchosVector & rhs) const
This function returns true if at least one component of this is bigger than or equal to the respective component of rhs.
Definition at line 454 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, QUESO::size, and sizeLocal().
 {
   queso_require_equal_to_msg(this->sizeLocal(), rhs.sizeLocal(), "vectors have different sizes");
   bool result = false;
   unsigned int i = 0;
   unsigned int size = this->sizeLocal();
   while ((i < size) && (result == false)) {
     result = ( (*this)[i] >= rhs[i] ); // prudencio 2012-02-06
     i++;
   };
   return result;
 }
bool QUESO::TeuchosVector::atLeastOneComponentBiggerThan (const TeuchosVector & rhs) const
This function returns true if at least one component of this is bigger than the respective component of rhs.
Definition at line 420 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, QUESO::size, and sizeLocal().
 {
   queso_require_equal_to_msg(this->sizeLocal(), rhs.sizeLocal(), "vectors have different sizes");
   bool result = false;
   unsigned int i = 0;
   unsigned int size = this->sizeLocal();
   while ((i < size) && (result == false)) {
     result = ( (*this)[i] > rhs[i] );
     i++;
   };
   return result;
 }
bool QUESO::TeuchosVector::atLeastOneComponentSmallerOrEqualThan (const TeuchosVector & rhs) const
This function returns true if at least one component of this is smaller than or equal to the respective component of rhs.
Definition at line 437 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, QUESO::size, and sizeLocal().
 {
   queso_require_equal_to_msg(this->sizeLocal(), rhs.sizeLocal(), "vectors have different sizes");
   bool result = false;
   unsigned int i = 0;
   unsigned int size = this->sizeLocal();
   while ((i < size) && (result == false)) {
     result = ( (*this)[i] <= rhs[i] ); // prudencio 2012-02-06
     i++;
   };
   return result;
 }
bool QUESO::TeuchosVector::atLeastOneComponentSmallerThan (const TeuchosVector & rhs) const
This function returns true if at least one component of this is smaller than the respective component of rhs.
Definition at line 403 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, QUESO::size, and sizeLocal().
 {
   queso_require_equal_to_msg(this->sizeLocal(), rhs.sizeLocal(), "vectors have different sizes");
   bool result = false;
   unsigned int i = 0;
   unsigned int size = this->sizeLocal();
   while ((i < size) && (result == false)) {
     result = ( (*this)[i] < rhs[i] );
     i++;
   };
   return result;
 }
void QUESO::TeuchosVector::copy (const TeuchosVector & src) private
This function copies the elements of the vector src into this.
Definition at line 1149 of file TeuchosVector.C.
References QUESO::Vector::base_copy(), m_vec, and sizeLocal().
Referenced by TeuchosVector().
 {
   this->Vector::base_copy(rhs);
   unsigned int size1 = m_vec.length();
   unsigned int size2 = rhs.sizeLocal();
   if (size1==size2){
     for (unsigned int i=0;i<size1;i++){
     m_vec[i]=rhs[i];
     }
   }
   return;
 }
void QUESO::TeuchosVector::copy_from_std_vector (const std::vector< double > vec)
Copies the values of std::vector structure to this vector (a TeuchosVector).
With this method, after a std::vector is sorted, it may be copied to a TeuchosVector.
Definition at line 680 of file TeuchosVector.C.
References m_vec, QUESO::queso_require_equal_to_msg, and sizeLocal().
 {
   unsigned int size1 = vec.size(), size2= this->sizeLocal();
   queso_require_equal_to_msg(size1, size2, "vectors have different sizes");
   for (unsigned int i = 0; i < size1; ++i)
       m_vec[i] = vec[i];
   return;
 }
void QUESO::TeuchosVector::copy_to_std_vector (std::vector< double > & vec)
Copies the values of this vector (a TeuchosVector) to a std::vector structure.
With this method, the std::vector copy of the TeuchosVector may be sorted using std::sort.
Definition at line 667 of file TeuchosVector.C.
References m_vec, QUESO::size, and sizeLocal().
 {
   unsigned int size = this->sizeLocal();
   vec.resize(size);
   for (unsigned int i = 0; i < size; ++i)
         vec[i] = m_vec[i];
   return;
 }
void QUESO::TeuchosVector::cwExtract (unsigned int initialPos, TeuchosVector & vec) const
Component-wise extracts all values of this with vector vec, starting at position initialPos.
Definition at line 496 of file TeuchosVector.C.
References sizeLocal().
 {
    queso_require_less_msg(initialPos, this->sizeLocal(), "invalid initialPos");
    queso_require_less_equal_msg((initialPos +vec.sizeLocal()), this->sizeLocal(), "invalid vec.sizeLocal()");
   for (unsigned int i = 0; i < vec.sizeLocal(); ++i) {
     vec[i] = (*this)[initialPos+i];
   }
   return;
 }
void QUESO::TeuchosVector::cwInvert () virtual
This function inverts component-wise the element values of this.
Implements QUESO::Vector.
Definition at line 510 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
Referenced by QUESO::operator/().
 {
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     (*this)[i] = 1./(*this)[i];
   }
   return;
 }
void QUESO::TeuchosVector::cwSet (double value) virtual
Component-wise sets all values to this with value.
Implements QUESO::Vector.
Definition at line 472 of file TeuchosVector.C.
Referenced by QUESO::TeuchosMatrix::inverse().
 {
   (*this)=value;
   return;
 }
void QUESO::TeuchosVector::cwSet (unsigned int initialPos, const TeuchosVector & vec)
Component-wise sets all values of this with vector vec, starting at position initialPos.
Definition at line 480 of file TeuchosVector.C.
References sizeLocal().
 {
    queso_require_less_msg(initialPos, this->sizeLocal(), "invalid initialPos");
    queso_require_less_equal_msg((initialPos +vec.sizeLocal()), this->sizeLocal(), "invalid vec.sizeLocal()");
   for (unsigned int i = 0; i < vec.sizeLocal(); ++i) {
     (*this)[initialPos+i] = vec[i];
   }
   return;
 }
void QUESO::TeuchosVector::cwSetBeta (const TeuchosVector & alpha, const TeuchosVector & beta)
This function sets component-wise random variates from the Beta distribution, with vector parameters alpha and beta.
Definition at line 591 of file TeuchosVector.C.
References QUESO::RngBase::betaSample(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseEnvironment::fullRank(), QUESO::Vector::m_env, QUESO::queso_require_equal_to_msg, QUESO::BaseEnvironment::rngObject(), sizeLocal(), and QUESO::BaseEnvironment::subDisplayFile().
 {
   queso_require_equal_to_msg(this->sizeLocal(), alpha.sizeLocal(), "incompatible alpha size");
   queso_require_equal_to_msg(this->sizeLocal(), beta.sizeLocal(), "incompatible beta size");
   for (unsigned int i = 0; i < this->sizeLocal(); ++i)
   {
     (*this)[i] = m_env.rngObject()->betaSample(alpha[i],beta[i]);
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99))
     {
       *m_env.subDisplayFile() << "In TeuchosVector::cwSetBeta()"
                               << ": fullRank "   << m_env.fullRank()
                               << ", i = "        << i
                               << ", alpha[i] = " << alpha[i]
                               << ", beta[i] = "  << beta[i]
                               << ", sample = "   << (*this)[i]
                               << std::endl;
         }
   }
   return;
 };
void QUESO::TeuchosVector::cwSetConcatenated (const TeuchosVector & v1, const TeuchosVector & v2)
This function concatenates vectors v1 and v2 into this vector.
Definition at line 533 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, and sizeLocal().
 {
    queso_require_equal_to_msg(this->sizeLocal(), v1.sizeLocal() + v2.sizeLocal(), "incompatible vector sizes");
 //  if ( this->sizeLocal() != v1.sizeLocal() + v2.sizeLocal() ) {
 //    std::cout << "ERROR in TeuchosVector:: cwSetConcatenated  ---> the vectors' sizes are not compatible.\n";
 //    cout << "      in TeuchosVector:: cwSetConcatenated  ---> resizing resulting vector... new size = "
 //         << v1.sizeLocal()+v1.sizeLocal() <<endl;
 //
 //    m_vec.resize(v1.sizeLocal()+v1.sizeLocal());
 //  }
   for (unsigned int i = 0; i < v1.sizeLocal(); ++i) {
     (*this)[i] = v1[i];
   }
   for (unsigned int i = 0; i < v2.sizeLocal(); ++i) {
     (*this)[v1.sizeLocal()+i] = v2[i];
   }
   return;
 }
void QUESO::TeuchosVector::cwSetGamma (const TeuchosVector & a, const TeuchosVector & b)
This function sets component-wise random variates from the Inverse Gamma distribution, with parameters given by vectors a and b.
Definition at line 617 of file TeuchosVector.C.
References QUESO::RngBase::gammaSample(), QUESO::Vector::m_env, QUESO::queso_require_equal_to_msg, QUESO::BaseEnvironment::rngObject(), and sizeLocal().
 {
   queso_require_equal_to_msg(this->sizeLocal(), aVec.sizeLocal(), "incompatible a size");
   queso_require_equal_to_msg(this->sizeLocal(), bVec.sizeLocal(), "incompatible b size");
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = m_env.rngObject()->gammaSample(aVec[i],bVec[i]);
   }
   return;
 }
void QUESO::TeuchosVector::cwSetGaussian (double mean, double stdDev) virtual
This function sets component-wise Gaussian random variates, with mean mean and standard deviation stdDev.
Implements QUESO::Vector.
Definition at line 558 of file TeuchosVector.C.
References QUESO::RngBase::gaussianSample(), QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), and sizeLocal().
 {
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
         (*this)[i] = mean + m_env.rngObject()->gaussianSample(stdDev);
   }
   return;
 };
void QUESO::TeuchosVector::cwSetGaussian (const TeuchosVector & meanVec, const TeuchosVector & stdDevVec)
This function sets component-wise Gaussian random variates, with vectors for mean and standard deviation.
Definition at line 568 of file TeuchosVector.C.
References QUESO::RngBase::gaussianSample(), QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), and sizeLocal().
 {
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = meanVec[i] + m_env.rngObject()->gaussianSample(stdDevVec[i]);
   }
   return;
 };
void QUESO::TeuchosVector::cwSetInverseGamma (const TeuchosVector & a, const TeuchosVector & b)
This function sets component-wise random variates from the Inverse Gamma distribution, with parameters given by vectors a and b.
Definition at line 633 of file TeuchosVector.C.
References QUESO::RngBase::gammaSample(), QUESO::Vector::m_env, QUESO::queso_require_equal_to_msg, QUESO::BaseEnvironment::rngObject(), and sizeLocal().
 {
   queso_require_equal_to_msg(this->sizeLocal(), alpha.sizeLocal(), "incompatible alpha size");
   queso_require_equal_to_msg(this->sizeLocal(), beta.sizeLocal(), "incompatible beta size");
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = 1./m_env.rngObject()->gammaSample(alpha[i],1./beta[i]);
   }
   return;
 }
void QUESO::TeuchosVector::cwSetUniform (const TeuchosVector & lowerBoundVec, const TeuchosVector & upperBoundVec)
This function sets component-wise a number uniformly distributed in the range of elements of [lowerBoundVec,upperBoundVec].
Definition at line 580 of file TeuchosVector.C.
References QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), sizeLocal(), and QUESO::RngBase::uniformSample().
 {
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = aVec[i] + (bVec[i]-aVec[i])*m_env.rngObject()->uniformSample();
   }
   return;
 }
void QUESO::TeuchosVector::cwSqrt ()
Component-wise sets the square-root of this.
Definition at line 521 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     (*this)[i] = sqrt((*this)[i]);
   }
   return;
 }
double QUESO::TeuchosVector::getMaxValue () const
Returns the maximum value in the this vector.
Definition at line 273 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   const unsigned int size = this->sizeLocal();
   std::vector<double> aux;
   for (unsigned int i=0; i<size; i++ ) {
     aux.push_back((*this)[i]) ;
   }
   return *max_element (aux.begin(),aux.end());
 }
void QUESO::TeuchosVector::getMaxValueAndIndex (double & value, int & index)
This function returns maximum value in the vector this and its the index.
Definition at line 326 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   const unsigned int size = this->sizeLocal();
   std::vector<double> vect;
   for (unsigned int i=0; i<size; i++ ) {
     vect.push_back((*this)[i]) ;
   }
   std::vector<double>::iterator iter_max = max_element(vect.begin(), vect.end());
   max_value = *iter_max;
   max_value_index =  distance(vect.begin(), iter_max);
   return;
 }
int QUESO::TeuchosVector::getMaxValueIndex () const
This function returns the index of the maximum value in the vector this.
Definition at line 300 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   const unsigned int size = this->sizeLocal();
   std::vector<double> vect;
   for (unsigned int i=0; i<size; i++ ) {
     vect.push_back((*this)[i]) ;
   }
   std::vector<double>::iterator iter_max = max_element(vect.begin(), vect.end());
   return distance(vect.begin(), iter_max);
 }
double QUESO::TeuchosVector::getMinValue () const
Returns the minimum value in the this vector.
Definition at line 286 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
    const unsigned int size = this->sizeLocal();
    std::vector<double> aux;
   for (unsigned int i=0; i<size; i++ ) {
     aux.push_back((*this)[i]) ;
     }
  return *min_element (aux.begin(),aux.end());
 }
void QUESO::TeuchosVector::getMinValueAndIndex (double & value, int & index)
This function returns minimum value in the vector this and its the index.
Definition at line 343 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   const unsigned int size = this->sizeLocal();
   std::vector<double> vect;
   for (unsigned int i=0; i<size; i++ ) {
     vect.push_back((*this)[i]) ;
   }
   std::vector<double>::iterator iter_min = min_element(vect.begin(), vect.end());
   min_value = *iter_min;
   min_value_index = distance(vect.begin(), iter_min);
   return;
 }
int QUESO::TeuchosVector::getMinValueIndex () const
This function returns the index of the minimum value in the vector this.
Definition at line 313 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   const unsigned int size = this->sizeLocal();
   std::vector<double> vect;
   for (unsigned int i=0; i<size; i++ ) {
     vect.push_back((*this)[i]) ;
   }
   std::vector<double>::iterator iter_min = min_element(vect.begin(), vect.end());
   return distance(vect.begin(), iter_min);
 }
void QUESO::TeuchosVector::matlabDiff (unsigned int firstPositionToStoreDiff, double valueForRemainderPosition, TeuchosVector & outputVec) const
Definition at line 903 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, QUESO::size, and sizeLocal().
 {
   unsigned int size = this->sizeLocal();
   queso_require_less_equal_msg(firstPositionToStoreDiff, 1, "invalid firstPositionToStoreDiff");
   queso_require_equal_to_msg(size, outputVec.sizeLocal(), "invalid size of outputVecs");
   for (unsigned int i = 0; i < (size-1); ++i) {
     outputVec[firstPositionToStoreDiff+i] = (*this)[i+1]-(*this)[i];
   }
   if (firstPositionToStoreDiff == 0) {
     outputVec[size-1] = valueForRemainderPosition;
   }
   else {
     outputVec[0] = valueForRemainderPosition;
   }
   return;
 }
void QUESO::TeuchosVector::matlabLinearInterpExtrap (const TeuchosVector & xVec, const TeuchosVector & yVec, const TeuchosVector & xiVec)
Reproduces MATLAB linear inter/extra-polation.
yiVec.matlabLinearInterpExtrap(xVec,yVec,xiVec) interpolates/extrapolates to find yiVec, the values of the underlying function yVec at the points in the vector xiVec. Thus, yVec and xVec must have the same size; and yiVec and xiVec must have the same size.
Definition at line 834 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, and sizeLocal().
Referenced by QUESO::TeuchosMatrix::matlabLinearInterpExtrap().
 {
   queso_require_greater_msg(x1Vec.sizeLocal(), 1, "invalid 'x1' size");
   queso_require_equal_to_msg(x1Vec.sizeLocal(), y1Vec.sizeLocal(), "invalid 'x1' and 'y1' sizes");
   queso_require_equal_to_msg(x2Vec.sizeLocal(), this->sizeLocal(), "invalid 'x2' and 'this' sizes");
   for (unsigned int i = 1; i < x1Vec.sizeLocal(); ++i) { // Yes, '1'
     queso_require_greater_msg(x1Vec[i], x1Vec[i-1], "invalid 'x1' values");
   }
   for (unsigned int id2 = 0; id2 < x2Vec.sizeLocal(); ++id2) {
     double x2 = x2Vec[id2];
     unsigned int id1 = 0;
     bool found1 = false;
     for (id1 = 0; id1 < x1Vec.sizeLocal(); ++id1) {
       if (x2 <= x1Vec[id1]) {
         found1 = true;
         break;
       }
     }
     bool makeLinearModel = false;
     double xa = 0.;
     double xb = 0.;
     double ya = 0.;
     double yb = 0.;
     if (x2 == x1Vec[id1]) {
       (*this)[id2] = y1Vec[id1];
     }
     else if (x2 < x1Vec[0]) {
       // Extrapolation case
       makeLinearModel = true;
       xa = x1Vec[0];
       xb = x1Vec[1];
       ya = y1Vec[0];
       yb = y1Vec[1];
     }
     else if (found1 == true) {
       // Interpolation case
       makeLinearModel = true;
       xa = x1Vec[id1-1];
       xb = x1Vec[id1];
       ya = y1Vec[id1-1];
       yb = y1Vec[id1];
     }
     else {
       // Extrapolation case
       makeLinearModel = true;
       xa = x1Vec[x1Vec.sizeLocal()-2];
       xb = x1Vec[x1Vec.sizeLocal()-1];
       ya = y1Vec[x1Vec.sizeLocal()-2];
       yb = y1Vec[x1Vec.sizeLocal()-1];
     }
     if (makeLinearModel) {
       double rate = (yb-ya)/(xb-xa);
       (*this)[id2] = ya + (x2-xa)*rate;
     }
   }
   return;
 }
void QUESO::TeuchosVector::mpiAllQuantile (double probability, const MpiComm & opComm, TeuchosVector & resultVec) const
Gathers values from a group of processes and returns all quantiles.
Definition at line 800 of file TeuchosVector.C.
References QUESO::MpiComm::Bcast(), QUESO::MpiComm::Gather(), QUESO::MpiComm::MyPID(), QUESO::MpiComm::NumProc(), QUESO::queso_require_equal_to_msg, QUESO::size, and sizeLocal().
 {
   // Filter out those nodes that should not participate
   if (opComm.MyPID() < 0) return;
   queso_require_msg(!((probability < 0.) || (1. < probability)), "invalid input");
   unsigned int size = this->sizeLocal();
   queso_require_equal_to_msg(size, resultVec.sizeLocal(), "different vector sizes");
   for (unsigned int i = 0; i < size; ++i) {
     double auxDouble = (int) (*this)[i];
     std::vector<double> vecOfDoubles(opComm.NumProc(),0.);
     opComm.Gather<double>(&auxDouble, 1, &vecOfDoubles[0], (int) 1, 0,
                   "TeuchosVector::mpiAllQuantile()",
                   "failed MPI.Gather()");
     std::sort(vecOfDoubles.begin(), vecOfDoubles.end());
     double result = vecOfDoubles[(unsigned int)( probability*((double)(vecOfDoubles.size()-1)) )];
     opComm.Bcast((void *) &result, (int) 1, RawValue_MPI_DOUBLE, 0,
                  "TeuchosVector::mpiAllQuantile()",
                  "failed MPI.Bcast()");
     resultVec[i] = result;
   }
   return;
 }
void QUESO::TeuchosVector::mpiAllReduce (RawType_MPI_Op mpiOperation, const MpiComm & opComm, TeuchosVector & resultVec) const
Combines values from all processes and distributes the result back to all processes.
Definition at line 777 of file TeuchosVector.C.
References QUESO::MpiComm::Allreduce(), QUESO::MpiComm::MyPID(), QUESO::queso_require_equal_to_msg, QUESO::size, and sizeLocal().
 {
   // Filter out those nodes that should not participate
   if (opComm.MyPID() < 0) return;
   unsigned int size = this->sizeLocal();
   queso_require_equal_to_msg(size, resultVec.sizeLocal(), "different vector sizes");
   for (unsigned int i = 0; i < size; ++i) {
     double srcValue = (*this)[i];
     double resultValue = 0.;
     opComm.Allreduce<double>(&srcValue, &resultValue, (int) 1, mpiOperation,
                      "TeuchosVector::mpiAllReduce()",
                      "failed MPI.Allreduce()");
     resultVec[i] = resultValue;
   }
   return;
 }
void QUESO::TeuchosVector::mpiBcast (int srcRank, const MpiComm & bcastComm)
Broadcasts a message from the process with srcRank root to all other processes of the group.
Definition at line 720 of file TeuchosVector.C.
References QUESO::MpiComm::Allreduce(), QUESO::MpiComm::Barrier(), QUESO::MpiComm::Bcast(), QUESO::MpiComm::MyPID(), QUESO::MpiComm::NumProc(), QUESO::queso_require_equal_to_msg, and sizeLocal().
 {
   // Filter out those nodes that should not participate
   if (bcastComm.MyPID() < 0) return;
   // Check 'srcRank'
   queso_require_msg(!((srcRank < 0) || (srcRank >= bcastComm.NumProc())), "invalud srcRank");
   // Check number of participant nodes
   double localNumNodes = 1.;
   double totalNumNodes = 0.;
   bcastComm.Allreduce<double>(&localNumNodes, &totalNumNodes, (int) 1, RawValue_MPI_SUM,
                       "TeuchosVector::mpiBcast()",
                       "failed MPI.Allreduce() for numNodes");
   queso_require_equal_to_msg(((int) totalNumNodes), bcastComm.NumProc(), "inconsistent numNodes");
   // Check that all participant nodes have the same vector size
   double localVectorSize  = this->sizeLocal();
   double sumOfVectorSizes = 0.;
   bcastComm.Allreduce<double>(&localVectorSize, &sumOfVectorSizes, (int) 1, RawValue_MPI_SUM,
                       "TeuchosVector::mpiBcast()",
                       "failed MPI.Allreduce() for vectorSize");
   if ( ((unsigned int) sumOfVectorSizes) != ((unsigned int)(totalNumNodes*localVectorSize)) ) {
     std::cerr << "rank "                 << bcastComm.MyPID()
               << ": sumOfVectorSizes = " << sumOfVectorSizes
               << ", totalNumNodes = "    << totalNumNodes
               << ", localVectorSize = "  << localVectorSize
               << std::endl;
   }
   bcastComm.Barrier();
   queso_require_equal_to_msg(((unsigned int) sumOfVectorSizes), ((unsigned int)(totalNumNodes*localVectorSize)), "inconsistent vectorSize");
   // Ok, bcast data
   std::vector<double> dataBuffer((unsigned int) localVectorSize, 0.);
   if (bcastComm.MyPID() == srcRank) {
     for (unsigned int i = 0; i < dataBuffer.size(); ++i) {
       dataBuffer[i] = (*this)[i];
     }
   }
   bcastComm.Bcast((void *) &dataBuffer[0], (int) localVectorSize, RawValue_MPI_DOUBLE, srcRank,
                   "TeuchosVector::mpiBcast()",
                   "failed MPI.Bcast()");
   if (bcastComm.MyPID() != srcRank) {
     for (unsigned int i = 0; i < dataBuffer.size(); ++i) {
       (*this)[i] = dataBuffer[i];
     }
   }
   return;
 }
double QUESO::TeuchosVector::norm1 () const
Returns the 1-norm of the vector.
Definition at line 373 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   double result = 0.;
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     result += fabs((*this)[i]);
   }
   return result;
 }
double QUESO::TeuchosVector::norm2 () const
Returns the 2-norm (Euclidean norm) of the vector.
Definition at line 367 of file TeuchosVector.C.
References norm2Sq().
Referenced by QUESO::TeuchosMatrix::invertMultiply().
 {
   return std::sqrt(this->norm2Sq());
 }
double QUESO::TeuchosVector::norm2Sq () const
Returns the norm of the vector, as the square root of 2-norm of this vector.
Definition at line 361 of file TeuchosVector.C.
References m_vec.
Referenced by norm2().
 {
  return (m_vec).dot(m_vec );
 }
double QUESO::TeuchosVector::normInf () const
Returns the infinity-norm (maximum norm) of the vector.
Definition at line 386 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   double result = 0.;
   unsigned int size = this->sizeLocal();
   double aux = 0.;
   for (unsigned int i = 0; i < size; ++i) {
     aux = fabs((*this)[i]);
     if (aux > result) result = aux;
   }
   return result;
 }
TeuchosVector & QUESO::TeuchosVector::operator*= (double a)
Stores in this vector the coordinate-wise multiplication of this and a.
Definition at line 158 of file TeuchosVector.C.
References m_vec.
 {
   m_vec.scale(a);       //Scale this vector by a; *this = a*this.
   return *this;
 }
TeuchosVector & QUESO::TeuchosVector::operator*= (const TeuchosVector & rhs)
Stores in this vector the coordinate-wise multiplication of this with rhs.
Definition at line 172 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, and sizeLocal().
 {
   unsigned int size1 = this->sizeLocal();
   unsigned int size2 = rhs.sizeLocal();
   queso_require_equal_to_msg(size1, size2, "the vectors do NOT have the same size.\n");
   if (size1==size2){
     for (unsigned int i = 0; i < size1; ++i) {
       (*this)[i] *= rhs[i];
     }
  }
  return *this;
 }
TeuchosVector & QUESO::TeuchosVector::operator+= (const TeuchosVector & rhs)
Stores in this vector the coordinate-wise addition of this and rhs.
Definition at line 201 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, and sizeLocal().
 {
   unsigned int size1 = this->sizeLocal();
   unsigned int size2 = rhs.sizeLocal();
   queso_require_equal_to_msg(size1, size2, "the vectors do NOT have the same size.\n");
   if (size1==size2){
     for (unsigned int i = 0; i < size1; ++i) {
       (*this)[i] += rhs[i];
     }
   }
   return *this;
 }
TeuchosVector & QUESO::TeuchosVector::operator-= (const TeuchosVector & rhs)
Stores in this vector the coordinate-wise subtraction of this and rhs.
Definition at line 217 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, and sizeLocal().
 {
   unsigned int size1 = this->sizeLocal();
   unsigned int size2 = rhs.sizeLocal();
   queso_require_equal_to_msg(size1, size2, "the vectors do NOT have the same size.\n");
   if (size1==size2){
     for (unsigned int i = 0; i < size1; ++i) {
       (*this)[i] -= rhs[i];
     }
   }
   return *this;
 }
TeuchosVector & QUESO::TeuchosVector::operator/= (double a)
Stores in this vector the coordinate-wise division of this by a.
Definition at line 165 of file TeuchosVector.C.
 {
   (*this) *= (1.0/a);
   return *this;
 }
TeuchosVector & QUESO::TeuchosVector::operator/= (const TeuchosVector & rhs)
Stores in this vector the coordinate-wise division of this by rhs.
Definition at line 186 of file TeuchosVector.C.
References QUESO::queso_require_equal_to_msg, and sizeLocal().
 {
   unsigned int size1 = this->sizeLocal();
   unsigned int size2 = rhs.sizeLocal();
   queso_require_equal_to_msg(size1, size2, "the vectors do NOT have the same size.\n");
   if (size1==size2){
     for (unsigned int i = 0; i < size1; ++i) {
       (*this)[i] /= rhs[i];
     }
   }
   return *this;
 }
TeuchosVector & QUESO::TeuchosVector::operator= (double a)
Set all values in the vector to a constant value.
Definition at line 134 of file TeuchosVector.C.
References m_vec.
 {
   m_vec.putScalar(a);
   return *this;
 }
TeuchosVector & QUESO::TeuchosVector::operator= (const TeuchosVector & rhs)
Copies values from one vector to another.
Definition at line 141 of file TeuchosVector.C.
References m_vec, QUESO::queso_require_equal_to_msg, and sizeLocal().
 {
   unsigned int size1 = m_vec.length();
   unsigned int size2 = rhs.sizeLocal();
   queso_require_equal_to_msg(size1, size2, "the vectors do NOT have the same size.\n");
   if (size1==size2){
     for (unsigned int i=0;i<size1;i++){
     m_vec[i]=rhs[i];
     }
   }
   return *this;
 }
double & QUESO::TeuchosVector::operator[] (unsigned int i)
Element access method (non-const).
Definition at line 236 of file TeuchosVector.C.
References m_vec.
 {
   return m_vec[i];
 }
const double & QUESO::TeuchosVector::operator[] (unsigned int i) const
Element access method (const).
Definition at line 242 of file TeuchosVector.C.
References m_vec.
 {
   return m_vec[i];
 }
void QUESO::TeuchosVector::print (std::ostream & os) const virtual
Print method. Defines the behavior of the std::ostream << operator inherited from the Object class.
Implements QUESO::Vector.
Definition at line 930 of file TeuchosVector.C.
References QUESO::Vector::m_printHorizontally, QUESO::Vector::m_printScientific, QUESO::size, and sizeLocal().
Referenced by QUESO::operator<<().
 {
   unsigned int size = this->sizeLocal();
   std::ostream::fmtflags curr_fmt = os.flags();
   if (m_printScientific) {
     unsigned int savedPrecision = os.precision();
     os.precision(16);
     if (m_printHorizontally) {
       for (unsigned int i = 0; i < size; ++i) {
         os << std::scientific << (*this)[i]
            << " ";
       }
     }
     else {
       for (unsigned int i = 0; i < size; ++i) {
         os << std::scientific << (*this)[i]
            << std::endl;
       }
     }
     os.precision(savedPrecision);
   }
   else {
     if (m_printHorizontally) {
       for (unsigned int i = 0; i < size; ++i) {
         os << std::dec << (*this)[i]
            << " ";
       }
     }
     else {
       for (unsigned int i = 0; i < size; ++i) {
         os << std::dec << (*this)[i]
            << std::endl;
       }
     }
   }
   os.flags(curr_fmt);
   return;
 }
unsigned int QUESO::TeuchosVector::sizeGlobal () const virtual
Returns the global length of this vector.
Implements QUESO::Vector.
Definition at line 257 of file TeuchosVector.C.
References QUESO::Vector::m_map, m_vec, QUESO::Map::NumGlobalElements(), and QUESO::queso_require_equal_to_msg.
 {
    queso_require_equal_to_msg(m_vec.length(), (int) m_map.NumGlobalElements(), "incompatible vec size");
   return m_vec.length();
 }
unsigned int QUESO::TeuchosVector::sizeLocal () const virtual
Returns the length of this vector.
Implements QUESO::Vector.
Definition at line 249 of file TeuchosVector.C.
References QUESO::Vector::m_map, m_vec, QUESO::Map::NumMyElements(), and QUESO::queso_require_equal_to_msg.
Referenced by abs(), atLeastOneComponentBiggerOrEqualThan(), atLeastOneComponentBiggerThan(), atLeastOneComponentSmallerOrEqualThan(), atLeastOneComponentSmallerThan(), copy(), copy_from_std_vector(), copy_to_std_vector(), cwExtract(), cwInvert(), cwSet(), cwSetBeta(), cwSetConcatenated(), cwSetGamma(), cwSetGaussian(), cwSetInverseGamma(), cwSetUniform(), cwSqrt(), QUESO::TeuchosMatrix::eigen(), QUESO::TeuchosMatrix::fillWithTensorProduct(), QUESO::TeuchosMatrix::getColumn(), getMaxValue(), getMaxValueAndIndex(), getMaxValueIndex(), getMinValue(), getMinValueAndIndex(), getMinValueIndex(), QUESO::TeuchosMatrix::getRow(), QUESO::TeuchosMatrix::invertMultiply(), QUESO::TeuchosMatrix::invertMultiplyForceLU(), QUESO::TeuchosMatrix::largestEigen(), QUESO::leftDiagScaling(), matlabDiff(), matlabLinearInterpExtrap(), QUESO::TeuchosMatrix::matlabLinearInterpExtrap(), QUESO::matrixProduct(), mpiAllQuantile(), mpiAllReduce(), mpiBcast(), QUESO::TeuchosMatrix::multiply(), norm1(), normInf(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), QUESO::operator==(), print(), QUESO::TeuchosMatrix::rank(), QUESO::rightDiagScaling(), QUESO::scalarProduct(), QUESO::TeuchosMatrix::setColumn(), QUESO::TeuchosMatrix::setRow(), QUESO::TeuchosMatrix::smallestEigen(), subReadContents(), subWriteContents(), sumOfComponents(), QUESO::TeuchosMatrix::svd(), QUESO::TeuchosMatrix::svdSolve(), QUESO::TeuchosMatrix::TeuchosMatrix(), and TeuchosVector().
 {
   queso_require_equal_to_msg(m_vec.length(), (int) m_map.NumMyElements(), "incompatible vec size");
   return m_vec.length();
 }
void QUESO::TeuchosVector::sort () virtual
This function sorts the elements of the vector this in ascending numerical order.
It copies this vector to a std::vector and uses the std::sort functionality to sort it.
Implements QUESO::Vector.
Definition at line 693 of file TeuchosVector.C.
 {
   std::vector<double> vec;
   (*this).copy_to_std_vector(vec);
   // using default comparison (operator <):
   std::sort (vec.begin(), vec.end());
   (*this).copy_from_std_vector(vec);
 };
void QUESO::TeuchosVector::subReadContents (const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds)
Definition at line 976 of file TeuchosVector.C.
References QUESO::BaseEnvironment::closeFile(), QUESO::BaseEnvironment::fullRank(), QUESO::FilePtrSetStruct::ifsVar, QUESO::Vector::m_env, QUESO::Vector::numOfProcsForStorage(), QUESO::BaseEnvironment::openInputFile(), QUESO::queso_require_equal_to_msg, sizeLocal(), QUESO::BaseEnvironment::subDisplayFile(), and QUESO::BaseEnvironment::subRank().
 {
   queso_require_greater_equal_msg(m_env.subRank(), 0, "unexpected subRank");
   queso_require_less_equal_msg(this->numOfProcsForStorage(), 1, "implemented just for sequential vectors for now");
   FilePtrSetStruct filePtrSet;
   if (m_env.openInputFile(fileName,
                           fileType, // "m or hdf"
                           allowedSubEnvIds,
                           filePtrSet)) {
     double subReadSize = this->sizeLocal();
     // In the logic below, the id of a line' begins with value 0 (zero)
     unsigned int idOfMyFirstLine = 1;
     unsigned int idOfMyLastLine = this->sizeLocal();
     unsigned int numParams = 1; // Yes, just '1'
     // Read number of chain positions in the file by taking care of the first line,
     // which resembles something like 'variable_name = zeros(n_positions,m_params);'
     std::string tmpString;
     // Read 'variable name' string
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Just read '" << tmpString << "'" << std::endl;
     // Read '=' sign
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Just read '" << tmpString << "'" << std::endl;
     queso_require_equal_to_msg(tmpString, "=", "string should be the '=' sign");
     // Read 'zeros(n_positions,n_params)' string
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Just read '" << tmpString << "'" << std::endl;
     unsigned int posInTmpString = 6;
     // Isolate 'n_positions' in a string
     char nPositionsString[tmpString.size()-posInTmpString+1];
     unsigned int posInPositionsString = 0;
     do {
       queso_require_less_msg(posInTmpString, tmpString.size(), "symbol ',' not found in first line of file");
       nPositionsString[posInPositionsString++] = tmpString[posInTmpString++];
     } while (tmpString[posInTmpString] != ',');
     nPositionsString[posInPositionsString] = '\0';
     // Isolate 'n_params' in a string
     posInTmpString++; // Avoid reading ',' char
     char nParamsString[tmpString.size()-posInTmpString+1];
     unsigned int posInParamsString = 0;
     do {
       queso_require_less_msg(posInTmpString, tmpString.size(), "symbol ')' not found in first line of file");
       nParamsString[posInParamsString++] = tmpString[posInTmpString++];
     } while (tmpString[posInTmpString] != ')');
     nParamsString[posInParamsString] = '\0';
     // Convert 'n_positions' and 'n_params' strings to numbers
     unsigned int sizeOfVecInFile = (unsigned int) strtod(nPositionsString,NULL);
     unsigned int numParamsInFile = (unsigned int) strtod(nParamsString,   NULL);
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In TeuchosVector::subReadContents()"
                               << ": fullRank "            << m_env.fullRank()
                               << ", sizeOfVecInFile = "   << sizeOfVecInFile
                               << ", numParamsInFile = "   << numParamsInFile
                               << ", this->sizeLocal() = " << this->sizeLocal()
                               << std::endl;
     }
     // Check if [size of vec in file] >= [requested sub vec size]
     queso_require_greater_equal_msg(sizeOfVecInFile, subReadSize, "size of vec in file is not big enough");
     // Check if [num params in file] == [num params in current vec]
     queso_require_equal_to_msg(numParamsInFile, numParams, "number of parameters of vec in file is different than number of parameters in this vec object");
     // Code common to any core in a communicator
     unsigned int maxCharsPerLine = 64*numParams; // Up to about 60 characters to represent each parameter value
     unsigned int lineId = 0;
     while (lineId < idOfMyFirstLine) {
       filePtrSet.ifsVar->ignore(maxCharsPerLine,'\n');
       lineId++;
     };
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In TeuchosVector::subReadContents()"
                               << ": beginning to read input actual data"
                               << std::endl;
     }
     // Take care of initial part of the first data line,
     // which resembles something like 'variable_name = [value1 value2 ...'
     // Read 'variable name' string
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Core 0 just read '" << tmpString << "'" << std::endl;
     // Read '=' sign
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Core 0 just read '" << tmpString << "'" << std::endl;
     queso_require_equal_to_msg(tmpString, "=", "in core 0, string should be the '=' sign");
     // Take into account the ' [' portion
     std::streampos tmpPos = filePtrSet.ifsVar->tellg();
     filePtrSet.ifsVar->seekg(tmpPos+(std::streampos)2);
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In TeuchosVector::subReadContents()"
                               << ": beginning to read lines with numbers only"
                               << ", lineId = " << lineId
                               << ", idOfMyFirstLine = " << idOfMyFirstLine
                               << ", idOfMyLastLine = " << idOfMyLastLine
                               << std::endl;
     }
     while (lineId <= idOfMyLastLine) {
       *filePtrSet.ifsVar >> (*this)[lineId - idOfMyFirstLine];
       lineId++;
     };
     m_env.closeFile(filePtrSet,fileType);
   }
   return;
 }
void QUESO::TeuchosVector::subWriteContents (const std::string & varNamePrefix, const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds) const
Definition at line 1104 of file TeuchosVector.C.
References QUESO::BaseEnvironment::closeFile(), QUESO::Vector::getPrintHorizontally(), QUESO::Vector::getPrintScientific(), QUESO::Vector::m_env, QUESO::Vector::numOfProcsForStorage(), QUESO::FilePtrSetStruct::ofsVar, QUESO::BaseEnvironment::openOutputFile(), QUESO::Vector::setPrintHorizontally(), QUESO::Vector::setPrintScientific(), sizeLocal(), QUESO::BaseEnvironment::subIdString(), and QUESO::BaseEnvironment::subRank().
 {
   queso_require_greater_equal_msg(m_env.subRank(), 0, "unexpected subRank");
   queso_require_less_equal_msg(this->numOfProcsForStorage(), 1, "implemented just for sequential vectors for now");
   FilePtrSetStruct filePtrSet;
   if (m_env.openOutputFile(fileName,
                            fileType, // "m or hdf"
                            allowedSubEnvIds,
                            false,
                            filePtrSet)) {
     *filePtrSet.ofsVar << varNamePrefix << "_sub" << m_env.subIdString() << " = zeros(" << this->sizeLocal()
                        << ","                                                           << 1
                        << ");"
                        << std::endl;
     *filePtrSet.ofsVar << varNamePrefix << "_sub" << m_env.subIdString() << " = [";
     bool savedVectorPrintScientific   = this->getPrintScientific();
     bool savedVectorPrintHorizontally = this->getPrintHorizontally();
     this->setPrintScientific  (true);
     this->setPrintHorizontally(false);
     *filePtrSet.ofsVar << *this;
                      //<< std::endl; // No need for 'endl' because horizontally = 'false'
     this->setPrintHorizontally(savedVectorPrintHorizontally);
     this->setPrintScientific  (savedVectorPrintScientific);
     *filePtrSet.ofsVar << "];\n";
     m_env.closeFile(filePtrSet,fileType);
   }
   return;
 }
double QUESO::TeuchosVector::sumOfComponents () const
Returns the sum of the components of the vector.
Definition at line 706 of file TeuchosVector.C.
References QUESO::size, and sizeLocal().
 {
   double result = 0.;
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     result += (*this)[i];
   }
   return result;
 }
double * QUESO::TeuchosVector::values ()
Definition at line 266 of file TeuchosVector.C.
References m_vec.
Referenced by QUESO::TeuchosMatrix::internalSvd(), and QUESO::TeuchosMatrix::svdSolve().
 {
   return  m_vec.values();
 };
Member Data Documentation
Teuchos::SerialDenseVector<int,double> QUESO::TeuchosVector::m_vec private
Teuchos vector.
Definition at line 284 of file TeuchosVector.h.
Referenced by copy(), copy_from_std_vector(), copy_to_std_vector(), norm2Sq(), operator*=(), operator=(), operator[](), sizeGlobal(), sizeLocal(), TeuchosVector(), and values().
The documentation for this class was generated from the following files:
src/core/inc/TeuchosVector.h
src/core/src/TeuchosVector.C