queso-0.55.0: QUESO::StatisticalForwardProblemOptions Class Reference
QUESO::StatisticalForwardProblemOptions Class Reference
This class reads option values for a Statistical Forward Problem from an input file.
#include <StatisticalForwardProblemOptions.h>
Public Member Functions
Constructor/Destructor methods
StatisticalForwardProblemOptions (const BaseEnvironment &env, const char *prefix)
Constructor: reads options from the input file.
StatisticalForwardProblemOptions (const BaseEnvironment &env, const char *prefix, const SfpOptionsValues &alternativeOptionsValues)
Constructor: with alternative option values.
~StatisticalForwardProblemOptions ()
Destructor.
I/O methods
void scanOptionsValues ()
It scans the option values from the options input file.
void print (std::ostream &os) const
It prints the option values.
Public Attributes
SfpOptionsValues m_ov
std::string m_prefix
Private Member Functions
void defineMyOptions (boost::program_options::options_description &optionsDesc) const
Define my SFP options as the default options.
void getMyOptionValues (boost::program_options::options_description &optionsDesc)
Gets the option values of the SFP.
Private Attributes
const BaseEnvironment & m_env
boost::program_options::options_description * m_optionsDesc
std::string m_option_help
std::string m_option_computeSolution
std::string m_option_computeCovariances
std::string m_option_computeCorrelations
std::string m_option_dataOutputFileName
std::string m_option_dataOutputAllowedSet
Detailed Description
This class reads option values for a Statistical Forward Problem from an input file.
This class reads the option values for the Statistical Forward Problem (SFP) from an input file provided by the user. The class expects the prefix '<prefix>_fp_'. For instance, if 'prefix' is 'foo_775_', then the constructor will read all options that begin with 'foo_775_fp_'. If the options request data to be written in the output file (MATLAB .m format only, for now), the user can run 'grep zeros <OUTPUT FILE NAME>' after the solution procedure ends in order to check which MATLAB variables are defined and set. The names of the variables are self explanatory.
Definition at line 138 of file StatisticalForwardProblemOptions.h.
Constructor & Destructor Documentation
QUESO::StatisticalForwardProblemOptions::StatisticalForwardProblemOptions (const BaseEnvironment & env, const char * prefix)
Constructor: reads options from the input file.
Definition at line 174 of file StatisticalForwardProblemOptions.C.
References m_env, QUESO::BaseEnvironment::optionsInputFileName(), queso_deprecated, and queso_require_not_equal_to_msg.
   :
   m_ov                         (),
   m_prefix                     ((std::string)(prefix) + "fp_"   ),
   m_env                        (env),
   m_optionsDesc                (new boost::program_options::options_description("Statistical Forward Problem options")),
   m_option_help                (m_prefix + "help"                ),
   m_option_computeSolution     (m_prefix + "computeSolution"     ),
   m_option_computeCovariances  (m_prefix + "computeCovariances"  ),
   m_option_computeCorrelations (m_prefix + "computeCorrelations" ),
   m_option_dataOutputFileName  (m_prefix + "dataOutputFileName"  ),
   m_option_dataOutputAllowedSet(m_prefix + "dataOutputAllowedSet")
 #ifdef UQ_SFP_READS_SOLVER_OPTION
   m_option_solver              (m_prefix + "solver"              )
 #endif
 {
   queso_deprecated();
   queso_require_not_equal_to_msg(m_env.optionsInputFileName(), "", "this constructor is incompatible with the absence of an options input file");
 }
QUESO::StatisticalForwardProblemOptions::StatisticalForwardProblemOptions (const BaseEnvironment & env, const char * prefix, const SfpOptionsValues & alternativeOptionsValues)
Constructor: with alternative option values.
In this constructor, the input options are given by alternativeOptionsValues, rather than the options input file
Definition at line 197 of file StatisticalForwardProblemOptions.C.
References m_env, m_prefix, QUESO::BaseEnvironment::optionsInputFileName(), queso_deprecated, queso_require_equal_to_msg, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_ov                         (alternativeOptionsValues         ),
   m_prefix                     ((std::string)(prefix) + "fp_"    ),
   m_env                        (env),
   m_optionsDesc                (NULL),
   m_option_help                (m_prefix + "help"                ),
   m_option_computeSolution     (m_prefix + "computeSolution"     ),
   m_option_computeCovariances  (m_prefix + "computeCovariances"  ),
   m_option_computeCorrelations (m_prefix + "computeCorrelations" ),
   m_option_dataOutputFileName  (m_prefix + "dataOutputFileName"  ),
   m_option_dataOutputAllowedSet(m_prefix + "dataOutputAllowedSet")
 #ifdef UQ_SFP_READS_SOLVER_OPTION
   m_option_solver              (m_prefix + "solver"              )
 #endif
 {
   queso_deprecated();
   queso_require_equal_to_msg(m_env.optionsInputFileName(), "", "this constructor is incompatible with the existence of an options input file");
   if (m_env.subDisplayFile() != NULL) {
     *m_env.subDisplayFile() << "In StatisticalForwardProblemOptions::constructor(2)"
                             << ": after setting values of options with prefix '" << m_prefix
                             << "', state of object is:"
                             << "\n" << *this
                             << std::endl;
   }
 }
QUESO::StatisticalForwardProblemOptions::~StatisticalForwardProblemOptions ()
Destructor.
Definition at line 229 of file StatisticalForwardProblemOptions.C.
References m_optionsDesc, and queso_deprecated.
 {
   queso_deprecated();
   if (m_optionsDesc) delete m_optionsDesc;
 }
Member Function Documentation
void QUESO::StatisticalForwardProblemOptions::defineMyOptions (boost::program_options::options_description & optionsDesc) const private
Define my SFP options as the default options.
Definition at line 282 of file StatisticalForwardProblemOptions.C.
References m_option_computeCorrelations, m_option_computeCovariances, m_option_computeSolution, m_option_dataOutputAllowedSet, m_option_dataOutputFileName, m_option_help, queso_deprecated, UQ_SFP_COMPUTE_CORRELATIONS_ODV, UQ_SFP_COMPUTE_COVARIANCES_ODV, UQ_SFP_COMPUTE_SOLUTION_ODV, UQ_SFP_DATA_OUTPUT_ALLOWED_SET_ODV, and UQ_SFP_DATA_OUTPUT_FILE_NAME_ODV.
Referenced by scanOptionsValues().
 {
   queso_deprecated();
   optionsDesc.add_options()
     (m_option_help.c_str(),                                                                                              "produce help message for statistical forward problem")
     (m_option_computeSolution.c_str(),      boost::program_options::value<bool       >()->default_value(UQ_SFP_COMPUTE_SOLUTION_ODV       ), "compute solution process"                            )
     (m_option_computeCovariances.c_str(),   boost::program_options::value<bool       >()->default_value(UQ_SFP_COMPUTE_COVARIANCES_ODV    ), "compute pq covariances"                              )
     (m_option_computeCorrelations.c_str(),  boost::program_options::value<bool       >()->default_value(UQ_SFP_COMPUTE_CORRELATIONS_ODV   ), "compute pq correlations"                             )
     (m_option_dataOutputFileName.c_str(),   boost::program_options::value<std::string>()->default_value(UQ_SFP_DATA_OUTPUT_FILE_NAME_ODV  ), "name of data output file"                            )
     (m_option_dataOutputAllowedSet.c_str(), boost::program_options::value<std::string>()->default_value(UQ_SFP_DATA_OUTPUT_ALLOWED_SET_ODV), "subEnvs that will write to data output file"         )
 #ifdef UQ_SFP_READS_SOLVER_OPTION
     (m_option_solver.c_str(),               boost::program_options::value<std::string>()->default_value(UQ_SFP_SOLVER_ODV                 ), "algorithm for propagation"                           )
 #endif
   ;
   return;
 }
void QUESO::StatisticalForwardProblemOptions::getMyOptionValues (boost::program_options::options_description & optionsDesc) private
Gets the option values of the SFP.
Definition at line 302 of file StatisticalForwardProblemOptions.C.
References QUESO::BaseEnvironment::allOptionsMap(), QUESO::SfpOptionsValues::m_computeCorrelations, QUESO::SfpOptionsValues::m_computeCovariances, QUESO::SfpOptionsValues::m_computeSolution, QUESO::SfpOptionsValues::m_dataOutputAllowedSet, QUESO::SfpOptionsValues::m_dataOutputFileName, m_env, m_option_computeCorrelations, m_option_computeCovariances, m_option_computeSolution, m_option_dataOutputAllowedSet, m_option_dataOutputFileName, m_option_help, m_ov, QUESO::MiscReadDoublesFromString(), queso_deprecated, and QUESO::BaseEnvironment::subDisplayFile().
Referenced by scanOptionsValues().
 {
   queso_deprecated();
   if (m_env.allOptionsMap().count(m_option_help)) {
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << optionsDesc
                               << std::endl;
     }
   }
   if (m_env.allOptionsMap().count(m_option_computeSolution)) {
     m_ov.m_computeSolution = ((const boost::program_options::variable_value&) m_env.allOptionsMap()[m_option_computeSolution]).as<bool>();
   }
   if (m_env.allOptionsMap().count(m_option_computeCovariances)) {
     m_ov.m_computeCovariances = ((const boost::program_options::variable_value&) m_env.allOptionsMap()[m_option_computeCovariances]).as<bool>();
   }
   if (m_env.allOptionsMap().count(m_option_computeCorrelations)) {
     m_ov.m_computeCorrelations = ((const boost::program_options::variable_value&) m_env.allOptionsMap()[m_option_computeCorrelations]).as<bool>();
   }
   if (m_env.allOptionsMap().count(m_option_dataOutputFileName)) {
     m_ov.m_dataOutputFileName = ((const boost::program_options::variable_value&) m_env.allOptionsMap()[m_option_dataOutputFileName]).as<std::string>();
   }
   if (m_env.allOptionsMap().count(m_option_dataOutputAllowedSet)) {
     m_ov.m_dataOutputAllowedSet.clear();
     std::vector<double> tmpAllow(0,0.);
     std::string inputString = m_env.allOptionsMap()[m_option_dataOutputAllowedSet].as<std::string>();
     MiscReadDoublesFromString(inputString,tmpAllow);
     if (tmpAllow.size() > 0) {
       for (unsigned int i = 0; i < tmpAllow.size(); ++i) {
         m_ov.m_dataOutputAllowedSet.insert((unsigned int) tmpAllow[i]);
       }
     }
   }
 #ifdef UQ_SFP_READS_SOLVER_OPTION
   if (m_env.allOptionsMap().count(m_option_solver)) {
     m_ov.m_solverString = ((const boost::program_options::variable_value&) m_env.allOptionsMap()[m_option_solver]).as<std::string>();
   }
 #endif
   return;
 }
void QUESO::StatisticalForwardProblemOptions::print (std::ostream & os) const
It prints the option values.
Definition at line 260 of file StatisticalForwardProblemOptions.C.
References QUESO::SfpOptionsValues::m_computeCorrelations, QUESO::SfpOptionsValues::m_computeCovariances, QUESO::SfpOptionsValues::m_computeSolution, QUESO::SfpOptionsValues::m_dataOutputAllowedSet, QUESO::SfpOptionsValues::m_dataOutputFileName, m_option_computeCorrelations, m_option_computeCovariances, m_option_computeSolution, m_option_dataOutputAllowedSet, m_option_dataOutputFileName, m_ov, and queso_deprecated.
Referenced by QUESO::operator<<().
 {
   queso_deprecated();
   os <<         m_option_computeSolution      << " = " << m_ov.m_computeSolution
      << "\n" << m_option_computeCovariances   << " = " << m_ov.m_computeCovariances
      << "\n" << m_option_computeCorrelations  << " = " << m_ov.m_computeCorrelations
      << "\n" << m_option_dataOutputFileName   << " = " << m_ov.m_dataOutputFileName;
   os << "\n" << m_option_dataOutputAllowedSet << " = ";
   for (std::set<unsigned int>::iterator setIt = m_ov.m_dataOutputAllowedSet.begin(); setIt != m_ov.m_dataOutputAllowedSet.end(); ++setIt) {
     os << *setIt << " ";
   }
 #ifdef UQ_SFP_READS_SOLVER_OPTION
        << "\n" << m_option_solver << " = " << m_ov.m_solverString
 #endif
   os << std::endl;
   return;
 }
void QUESO::StatisticalForwardProblemOptions::scanOptionsValues ()
It scans the option values from the options input file.
Definition at line 238 of file StatisticalForwardProblemOptions.C.
References defineMyOptions(), getMyOptionValues(), m_env, m_optionsDesc, m_prefix, queso_deprecated, queso_require_msg, QUESO::BaseEnvironment::scanInputFileForMyOptions(), and QUESO::BaseEnvironment::subDisplayFile().
 {
   queso_deprecated();
   queso_require_msg(m_optionsDesc, "m_optionsDesc variable is NULL");
   defineMyOptions                (*m_optionsDesc);
   m_env.scanInputFileForMyOptions(*m_optionsDesc);
   getMyOptionValues              (*m_optionsDesc);
   if (m_env.subDisplayFile() != NULL) {
     *m_env.subDisplayFile() << "In StatisticalForwardProblemOptions::scanOptionsValues()"
                             << ": after reading values of options with prefix '" << m_prefix
                             << "', state of  object is:"
                             << "\n" << *this
                             << std::endl;
   }
   return;
 }
Member Data Documentation
const BaseEnvironment& QUESO::StatisticalForwardProblemOptions::m_env private
Definition at line 174 of file StatisticalForwardProblemOptions.h.
Referenced by getMyOptionValues(), scanOptionsValues(), and StatisticalForwardProblemOptions().
std::string QUESO::StatisticalForwardProblemOptions::m_option_computeCorrelations private
Definition at line 180 of file StatisticalForwardProblemOptions.h.
Referenced by defineMyOptions(), getMyOptionValues(), and print().
std::string QUESO::StatisticalForwardProblemOptions::m_option_computeCovariances private
Definition at line 179 of file StatisticalForwardProblemOptions.h.
Referenced by defineMyOptions(), getMyOptionValues(), and print().
std::string QUESO::StatisticalForwardProblemOptions::m_option_computeSolution private
Definition at line 178 of file StatisticalForwardProblemOptions.h.
Referenced by defineMyOptions(), getMyOptionValues(), and print().
std::string QUESO::StatisticalForwardProblemOptions::m_option_dataOutputAllowedSet private
Definition at line 182 of file StatisticalForwardProblemOptions.h.
Referenced by defineMyOptions(), getMyOptionValues(), and print().
std::string QUESO::StatisticalForwardProblemOptions::m_option_dataOutputFileName private
Definition at line 181 of file StatisticalForwardProblemOptions.h.
Referenced by defineMyOptions(), getMyOptionValues(), and print().
std::string QUESO::StatisticalForwardProblemOptions::m_option_help private
Definition at line 177 of file StatisticalForwardProblemOptions.h.
Referenced by defineMyOptions(), and getMyOptionValues().
boost::program_options::options_description* QUESO::StatisticalForwardProblemOptions::m_optionsDesc private
Definition at line 176 of file StatisticalForwardProblemOptions.h.
Referenced by scanOptionsValues(), and ~StatisticalForwardProblemOptions().
SfpOptionsValues QUESO::StatisticalForwardProblemOptions::m_ov
Definition at line 164 of file StatisticalForwardProblemOptions.h.
Referenced by getMyOptionValues(), and print().
std::string QUESO::StatisticalForwardProblemOptions::m_prefix
Definition at line 165 of file StatisticalForwardProblemOptions.h.
Referenced by scanOptionsValues(), and StatisticalForwardProblemOptions().
The documentation for this class was generated from the following files:
src/stats/inc/StatisticalForwardProblemOptions.h
src/stats/src/StatisticalForwardProblemOptions.C