queso-0.57.1: QUESO::VectorSet< V, M > Class Template Reference
QUESO::VectorSet< V, M > Class Template Reference abstract
A templated class for handling sets.
#include <VectorSet.h>
Public Member Functions
Constructor/Destructor methods.
VectorSet (const BaseEnvironment &env, const char *prefix, double volume)
Shaped constructor.
virtual ~VectorSet ()
Virtual destructor.
Environment methods
const BaseEnvironment & env () const
Environment. Access to private attribute m_env.
const std::string & prefix () const
Access to private attribute m_prefix.
Mathematical methods.
double volume () const
Set volume; access to private attribute m_volume.
virtual const VectorSpace< V, M > & vectorSpace () const =0
Vector space to which this set belongs to. See template specialization.
virtual bool contains (const V &vec) const =0
Checks whether a set contains vector vec. See template specialization.
virtual void centroid (V &vec) const =0
Returns the set centroid in the vector vec. See template specialization.
virtual void moments (M &mat) const =0
Returns the set moments of inertia in the matrix mat. See template specialization.
Protected Attributes
const BaseEnvironment & m_env
std::string m_prefix
double m_volume
Private Member Functions
VectorSet ()
Default Constructor.
I/O methods.
virtual void print (std::ostream &os) const
Prints nothing.
std::ostream & operator<< (std::ostream &os, const VectorSet< V, M > &obj)
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::VectorSet< V, M >
A templated class for handling sets.
This class allows the mathematical definition of a scalar function such as: \(\pi: B \subset R^n \rightarrow R \), since it requires the specification of the domain \(B \), which is a subset of the vector space \(R^n \), which is itself a set.
Definition at line 52 of file VectorSet.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::VectorSet< V, M >::VectorSet (const BaseEnvironment & env, const char * prefix, double volume)
Shaped constructor.
Creates a vector set given an environment, a identifying prefix and a volume.
Definition at line 44 of file VectorSet.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::VectorSet< V, M >::m_env, and QUESO::BaseEnvironment::subDisplayFile().
   : m_env(env),
     m_prefix(prefix),
     m_volume(volume)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering VectorSet<V,M>::constructor()"
                            << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving VectorSet<V,M>::constructor()"
                            << std::endl;
   }
 }
template<class V , class M > QUESO::VectorSet< V, M >::~VectorSet () virtual
Virtual destructor.
Definition at line 63 of file VectorSet.C.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering VectorSet<V,M>::destructor()"
                            << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving VectorSet<V,M>::destructor()"
                            << std::endl;
   }
 }
template<class V , class M > QUESO::VectorSet< V, M >::VectorSet () private
Default Constructor.
It should not be used by the user.
Definition at line 37 of file VectorSet.C.
   : m_env(*(new EmptyEnvironment()))
 {
 }
Member Function Documentation
template<class V = GslVector, class M = GslMatrix> virtual void QUESO::VectorSet< V, M >::centroid (V & vec) const pure virtual
Returns the set centroid in the vector vec. See template specialization.
Implemented in QUESO::VectorSpace< V, M >, QUESO::ConcatenationSubset< V, M >, QUESO::BoxSubset< V, M >, and QUESO::IntersectionSubset< V, M >.
template<class V = GslVector, class M = GslMatrix> virtual bool QUESO::VectorSet< V, M >::contains (const V & vec) const pure virtual
Checks whether a set contains vector vec. See template specialization.
Implemented in QUESO::VectorSpace< V, M >, QUESO::ConcatenationSubset< V, M >, QUESO::VectorSubset< V, M >, QUESO::BoxSubset< V, M >, QUESO::IntersectionSubset< V, M >, and QUESO::DiscreteSubset< V, M >.
template<class V , class M > const BaseEnvironment & QUESO::VectorSet< V, M >::env () const
Environment. Access to private attribute m_env.
Definition at line 78 of file VectorSet.C.
 {
   return m_env;
 }
template<class V = GslVector, class M = GslMatrix> virtual void QUESO::VectorSet< V, M >::moments (M & mat) const pure virtual
Returns the set moments of inertia in the matrix mat. See template specialization.
Implemented in QUESO::VectorSpace< V, M >, QUESO::ConcatenationSubset< V, M >, QUESO::BoxSubset< V, M >, and QUESO::IntersectionSubset< V, M >.
template<class V , class M > const std::string & QUESO::VectorSet< V, M >::prefix () const
Access to private attribute m_prefix.
Definition at line 84 of file VectorSet.C.
Referenced by QUESO::InstantiateIntersection().
 {
   return m_prefix;
 }
template<class V , class M > void QUESO::VectorSet< V, M >::print (std::ostream & os) const virtual
Prints nothing.
Reimplemented in QUESO::VectorSpace< V, M >, QUESO::VectorSpace< QUESO::GslVector, QUESO::GslMatrix >, QUESO::VectorSpace< P_V, P_M >, QUESO::VectorSpace< Q_V, Q_M >, QUESO::BoxSubset< V, M >, QUESO::BoxSubset< Q_V, Q_M >, QUESO::ConcatenationSubset< V, M >, QUESO::IntersectionSubset< V, M >, QUESO::VectorSubset< V, M >, QUESO::VectorSubset< Q_V, Q_M >, and QUESO::DiscreteSubset< V, M >.
Definition at line 98 of file VectorSet.C.
 {
   os << "In VectorSet<V,M>::print()"
      << ": nothing to be printed" << std::endl;
   return;
 }
template<class V = GslVector, class M = GslMatrix> virtual const VectorSpace<V,M>& QUESO::VectorSet< V, M >::vectorSpace () const pure virtual
Vector space to which this set belongs to. See template specialization.
Implemented in QUESO::VectorSpace< V, M >, QUESO::VectorSpace< QUESO::GslVector, QUESO::GslMatrix >, QUESO::VectorSpace< P_V, P_M >, QUESO::VectorSpace< Q_V, Q_M >, QUESO::VectorSubset< V, M >, and QUESO::VectorSubset< Q_V, Q_M >.
Referenced by QUESO::ComputeCovCorrMatricesBetweenVectorRvs(), QUESO::ConcatenatedJointPdf< V, M >::ConcatenatedJointPdf(), QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::ExponentialMatrixCovarianceFunction(), QUESO::InstantiateIntersection(), and QUESO::StatisticalInverseProblem< P_V, P_M >::StatisticalInverseProblem().
template<class V , class M > double QUESO::VectorSet< V, M >::volume () const
Set volume; access to private attribute m_volume.
Definition at line 91 of file VectorSet.C.
Referenced by QUESO::MonteCarloQuadrature< V, M >::MonteCarloQuadrature(), and QUESO::UniformVectorRealizer< V, M >::realization().
 {
   return m_volume;
 }
Friends And Related Function Documentation
template<class V = GslVector, class M = GslMatrix> std::ostream& operator<< (std::ostream & os, const VectorSet< V, M > & obj) friend
Definition at line 96 of file VectorSet.h.
{
     obj.print(os);
     return os;
   }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> const BaseEnvironment& QUESO::VectorSet< V, M >::m_env protected
Definition at line 104 of file VectorSet.h.
Referenced by QUESO::VectorSet< V, M >::VectorSet(), QUESO::VectorSpace< V, M >::VectorSpace(), and QUESO::VectorSubset< V, M >::VectorSubset().
template<class V = GslVector, class M = GslMatrix> std::string QUESO::VectorSet< V, M >::m_prefix protected
Definition at line 105 of file VectorSet.h.
Referenced by QUESO::VectorSpace< V, M >::VectorSpace().
template<class V = GslVector, class M = GslMatrix> double QUESO::VectorSet< V, M >::m_volume protected
Definition at line 106 of file VectorSet.h.
Referenced by QUESO::BoxSubset< V, M >::BoxSubset(), and QUESO::DiscreteSubset< V, M >::DiscreteSubset().
The documentation for this class was generated from the following files:
src/basic/inc/VectorSet.h
src/basic/src/VectorSet.C