queso-0.54.0: QUESO::FuncTimesFunc1D1DFunction Class Reference
QUESO::FuncTimesFunc1D1DFunction Class Reference
Class for multiplication of a one-dimensional function by another.
#include <1D1DFunction.h>
Public Member Functions
Constructor/Destructor methods
FuncTimesFunc1D1DFunction (const Base1D1DFunction &func1, const Base1D1DFunction &func2)
Default constructor.
~FuncTimesFunc1D1DFunction ()
Destructor.
Mathematical methods
double value (double domainValue) const
Returns the value of the multiplication of a function func1 by another function func2 at the point domainValue, i.e. returnValue = func1(domainValue)*func2(domainValue) .
double deriv (double domainValue) const
TODO: Returns the value of the derivative of the function func1 by another function func2 at the point domainValue.
Public Member Functions inherited from QUESO::Base1D1DFunction
Base1D1DFunction (double minDomainValue, double maxDomainValue)
Default constructor.
virtual ~Base1D1DFunction ()
Destructor.
double minDomainValue () const
Returns the minimum value of the domain of the (one-dimensional) function.
double maxDomainValue () const
Returns the maximum value of the domain of the (one-dimensional) function.
virtual double multiplyAndIntegrate (const Base1D1DFunction &func, unsigned int quadratureOrder, double *resultWithMultiplicationByTAsWell) const
TODO: Multiplies this function with function, and integrates it numerically. See template specialization.
Protected Attributes
const Base1D1DFunction & m_func1
const Base1D1DFunction & m_func2
Protected Attributes inherited from QUESO::Base1D1DFunction
double m_minDomainValue
double m_maxDomainValue
Detailed Description
Class for multiplication of a one-dimensional function by another.
This class implements the multiplication of a generic one-dimensional function by another (both functions may be of any type of functions derived from Base1D1DFunction).
Definition at line 462 of file 1D1DFunction.h.
Constructor & Destructor Documentation
QUESO::FuncTimesFunc1D1DFunction::FuncTimesFunc1D1DFunction (const Base1D1DFunction & func1, const Base1D1DFunction & func2)
Default constructor.
Definition at line 647 of file 1D1DFunction.C.
   :
   Base1D1DFunction(std::max(func1.minDomainValue(),func2.minDomainValue()),std::min(func1.maxDomainValue(),func2.maxDomainValue())),
   m_func1(func1),
   m_func2(func2)
 {
 }
QUESO::FuncTimesFunc1D1DFunction::~FuncTimesFunc1D1DFunction ()
Destructor.
Definition at line 657 of file 1D1DFunction.C.
 {
 }
Member Function Documentation
double QUESO::FuncTimesFunc1D1DFunction::deriv (double domainValue) const virtual
TODO: Returns the value of the derivative of the function func1 by another function func2 at the point domainValue.
Todo:
Please, implement me!
This method objective requires clarification: are we calculating either (func1*func2)' or func1'*func2'?
Implements QUESO::Base1D1DFunction.
Definition at line 672 of file 1D1DFunction.C.
References QUESO::Base1D1DFunction::m_maxDomainValue, QUESO::Base1D1DFunction::m_minDomainValue, queso_not_implemented, queso_require_msg, and value().
 {
   double value = 0.;
   if ((domainValue < m_minDomainValue) || (domainValue > m_maxDomainValue)) {
     std::cerr << "In FuncTimes1D1DFunction::deriv()"
               << ": requested x ("            << domainValue
               << ") is out of the interval (" << m_minDomainValue
               << ", "                         << m_maxDomainValue
               << ")"
               << std::endl;
   }
   queso_require_msg(!((domainValue < m_minDomainValue) || (domainValue > m_maxDomainValue)), "x out of range");
   queso_not_implemented();
   return value;
 }
double QUESO::FuncTimesFunc1D1DFunction::value (double domainValue) const virtual
Returns the value of the multiplication of a function func1 by another function func2 at the point domainValue, i.e. returnValue = func1(domainValue)*func2(domainValue) .
This function calls the value() method of the both functions and multiplies their return value with one another.
Implements QUESO::Base1D1DFunction.
Definition at line 662 of file 1D1DFunction.C.
References m_func1, m_func2, and QUESO::Base1D1DFunction::value().
Referenced by deriv().
 {
   double value = 0.;
   value += m_func1.value(domainValue)*m_func2.value(domainValue);
   return value;
 }
Member Data Documentation
const Base1D1DFunction& QUESO::FuncTimesFunc1D1DFunction::m_func1 protected
Definition at line 491 of file 1D1DFunction.h.
Referenced by value().
const Base1D1DFunction& QUESO::FuncTimesFunc1D1DFunction::m_func2 protected
Definition at line 492 of file 1D1DFunction.h.
Referenced by value().
The documentation for this class was generated from the following files:
src/misc/inc/1D1DFunction.h
src/misc/src/1D1DFunction.C