queso-0.54.0: ANNbruteForce Class Reference
ANNbruteForce Class Reference
#include <ANN.h>
Public Member Functions
ANNbruteForce (ANNpointArray pa, int n, int dd)
~ANNbruteForce ()
void annkSearch (ANNpoint q, int k, ANNidxArray nn_idx, ANNdistArray dd, double eps=0.0)
int annkFRSearch (ANNpoint q, ANNdist sqRad, int k=0, ANNidxArray nn_idx=NULL, ANNdistArray dd=NULL, double eps=0.0)
int theDim ()
int nPoints ()
ANNpointArray thePoints ()
Public Member Functions inherited from ANNpointSet
virtual ~ANNpointSet ()
Private Attributes
int dim
int n_pts
ANNpointArray pts
Detailed Description
Definition at line 538 of file ANN.h.
Constructor & Destructor Documentation
ANNbruteForce::ANNbruteForce (ANNpointArray pa, int n, int dd)
Definition at line 44 of file brute.cpp.
References dim, n_pts, and pts.
 {
         dim = dd;  n_pts = n;  pts = pa;
 }
ANNbruteForce::~ANNbruteForce ()
Definition at line 52 of file brute.cpp.
 { }             // destructor (empty)
Member Function Documentation
int ANNbruteForce::annkFRSearch (ANNpoint q, ANNdist sqRad, int k = 0, ANNidxArray nn_idx = NULL, ANNdistArray dd = NULL, double eps = 0.0) virtual
Implements ANNpointSet.
Definition at line 80 of file brute.cpp.
References ANN_ALLOW_SELF_MATCH, annDist(), dim, ANNmin_k::insert(), ANNmin_k::ith_smallest_info(), ANNmin_k::ith_smallest_key(), k, n_pts, and pts.
Referenced by getTrueNN().
 {
         ANNmin_k mk(k);                                         // construct a k-limited priority queue
         int i;
         int pts_in_range = 0;                           // number of points in query range
                                                                                 // run every point through queue
         for (i = 0; i < n_pts; i++) {
                                                                                 // compute distance to point
                 ANNdist sqDist = annDist(dim, pts[i], q);
                 if (sqDist <= sqRad &&                  // within radius bound
                         (ANN_ALLOW_SELF_MATCH || sqDist != 0)) { // ...and no self match
                         mk.insert(sqDist, i);
                         pts_in_range++;
                 }
         }
         for (i = 0; i < k; i++) {                       // extract the k closest points
                 if (dd != NULL)
                         dd[i] = mk.ith_smallest_key(i);
                 if (nn_idx != NULL)
                         nn_idx[i] = mk.ith_smallest_info(i);
         }
         return pts_in_range;
 }
void ANNbruteForce::annkSearch (ANNpoint q, int k, ANNidxArray nn_idx, ANNdistArray dd, double eps = 0.0) virtual
Implements ANNpointSet.
Definition at line 54 of file brute.cpp.
References ANN_ALLOW_SELF_MATCH, ANNabort, annDist(), annError(), dim, ANNmin_k::insert(), ANNmin_k::ith_smallest_info(), ANNmin_k::ith_smallest_key(), k, n_pts, and pts.
Referenced by getTrueNN().
 {
         ANNmin_k mk(k);                                         // construct a k-limited priority queue
         int i;
         if (k > n_pts) {                                        // too many near neighbors?
                 annError("Requesting more near neighbors than data points", ANNabort);
         }
                                                                                 // run every point through queue
         for (i = 0; i < n_pts; i++) {
                                                                                 // compute distance to point
                 ANNdist sqDist = annDist(dim, pts[i], q);
                 if (ANN_ALLOW_SELF_MATCH || sqDist != 0)
                         mk.insert(sqDist, i);
         }
         for (i = 0; i < k; i++) {                       // extract the k closest points
                 dd[i] = mk.ith_smallest_key(i);
                 nn_idx[i] = mk.ith_smallest_info(i);
         }
 }
int ANNbruteForce::nPoints () inline virtual
Implements ANNpointSet.
Definition at line 568 of file ANN.h.
References n_pts.
                 { return n_pts; }
int ANNbruteForce::theDim () inline virtual
Implements ANNpointSet.
Definition at line 565 of file ANN.h.
References dim.
                 { return dim; }
ANNpointArray ANNbruteForce::thePoints () inline virtual
Implements ANNpointSet.
Definition at line 571 of file ANN.h.
References pts.
                 {  return pts;  }
Member Data Documentation
int ANNbruteForce::dim private
Definition at line 539 of file ANN.h.
Referenced by ANNbruteForce(), annkFRSearch(), and annkSearch().
int ANNbruteForce::n_pts private
Definition at line 540 of file ANN.h.
Referenced by ANNbruteForce(), annkFRSearch(), and annkSearch().
ANNpointArray ANNbruteForce::pts private
Definition at line 541 of file ANN.h.
Referenced by ANNbruteForce(), annkFRSearch(), and annkSearch().
The documentation for this class was generated from the following files:
src/contrib/ANN/include/ANN/ANN.h
src/contrib/ANN/src/brute.cpp