queso-0.51.1: QUESO::GslVector Class Reference
QUESO::GslVector Class Reference
Class for vector operations using GSL library.
#include <GslVector.h>
Public Member Functions
void sort ()
This function sorts the elements of the vector this in ascending numerical order.
void matlabDiff (unsigned int firstPositionToStoreDiff, double valueForRemainderPosition, GslVector &outputVec) const
void matlabLinearInterpExtrap (const GslVector &x1Vec, const GslVector &y1Vec, const GslVector &x2Vec)
void mpiBcast (int srcRank, const MpiComm &bcastComm)
void mpiAllReduce (RawType_MPI_Op mpiOperation, const MpiComm &opComm, GslVector &resultVec) const
void mpiAllQuantile (double probability, const MpiComm &opComm, GslVector &resultVec) const
void subWriteContents (const std::string &varNamePrefix, const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds) const
void subReadContents (const std::string &fileName, const std::string &fileType, const std::set< unsigned int > &allowedSubEnvIds)
gsl_vector * data () const
Constructor/Destructor methods.
GslVector ()
Default Constructor.
GslVector (const BaseEnvironment &env, const Map &map)
GslVector (const BaseEnvironment &env, const Map &map, double value)
GslVector (const BaseEnvironment &env, double d1, double d2, const Map &map)
GslVector (const GslVector &v, double start, double end)
Construct a vector, with length the same as v, with evenly spaced numbers from start to end, inclusive.
GslVector (const GslVector &y)
~GslVector ()
Destructor.
Set methods.
GslVector & operator= (const GslVector &rhs)
Copies values from vector rhs to this.
GslVector & operator*= (double a)
Stores in this the coordinate-wise multiplication of this and a.
GslVector & operator/= (double a)
Stores in this the coordinate-wise division of this by a.
GslVector & operator*= (const GslVector &rhs)
Stores in this the coordinate-wise multiplication of this with rhs.
GslVector & operator/= (const GslVector &rhs)
Stores in this the coordinate-wise division of this by rhs.
GslVector & operator+= (const GslVector &rhs)
Stores in this the coordinate-wise addition of this and rhs.
GslVector & operator-= (const GslVector &rhs)
Stores in this the coordinate-wise subtraction of this by rhs.
void cwSet (double value)
Component-wise sets all values to this with value.
void cwSetGaussian (double mean, double stdDev)
This function sets component-wise Gaussian random variates, with mean mean and standard deviation stdDev.
void cwSetGaussian (const GslVector &meanVec, const GslVector &stdDevVec)
This function sets component-wise Gaussian random variates, with vectors for mean and standard deviation.
void cwSetUniform (const GslVector &aVec, const GslVector &bVec)
This function sets component-wise a number uniformly distributed in the range of elements of [aVec,bVec].
void cwSetBeta (const GslVector &alpha, const GslVector &beta)
This function returns a random variate from the beta distribution, with vector parameters alpha and beta.
void cwSetGamma (const GslVector &a, const GslVector &b)
This function returns a random variate from the gamma distribution with vector parameters a and b.
void cwSetInverseGamma (const GslVector &alpha, const GslVector &beta)
This function returns a random variate from the inverse gamma distribution with vector parameters alpha and beta.
void cwSetConcatenated (const GslVector &v1, const GslVector &v2)
This function concatenates GslVector v1 and GslVector v2 into this.
void cwSetConcatenated (const std::vector< const GslVector * > &vecs)
This function concatenates vectors v1 and v2 into this vector.
void cwSet (unsigned int initialPos, const GslVector &vec)
This function sets the vector vec into this starting at position initialPos.
void cwExtract (unsigned int initialPos, GslVector &vec) const
This function sets the values of this starting at position initialPos ans saves them in vector vec.
void cwInvert ()
This function inverts component-wise the element values of this.
void cwSqrt ()
This function returns component-wise the square-root of this.
Accessor methods.
double & operator[] (unsigned int i)
Element access method (non-const).
const double & operator[] (unsigned int i) const
Element access method (const).
Attribute methods.
unsigned int sizeLocal () const
Returns the length of this vector.
unsigned int sizeGlobal () const
Returns the global length of this vector.
double getMaxValue () const
Returns the maximum value in the vector this.
double getMinValue () const
Returns minimum value in the vector this.
int getMaxValueIndex () const
This function returns the index of the maximum value in the vector this.
int getMinValueIndex () const
This function returns the index of the minimum value in the vector this.
void getMaxValueAndIndex (double &value, int &index)
This function returns maximum value in the vector this and its the index.
void getMinValueAndIndex (double &value, int &index)
This function returns minimum value in the vector this and its the index.
GslVector abs () const
This function returns absolute value of elements in this.
Mathematical methods.
double norm2Sq () const
Returns the norm of the vector, as the square root of 2-norm of this vector.
double norm2 () const
Returns the 2-norm (Euclidean norm) of the vector.
double norm1 () const
Returns the 1-norm of the vector.
double normInf () const
Returns the infinity-norm (maximum norm) of the vector.
double sumOfComponents () const
Returns the sum of the components of the vector.
I/O methods.
void print (std::ostream &os) const
Print method. Defines the behavior of the std::ostream << operator inherited from the Object class.
Comparison methods.
bool atLeastOneComponentSmallerThan (const GslVector &rhs) const
This function returns true if at least one component of this is smaller than the respective component of rhs.
bool atLeastOneComponentBiggerThan (const GslVector &rhs) const
This function returns true if at least one component of this is bigger than the respective component of rhs.
bool atLeastOneComponentSmallerOrEqualThan (const GslVector &rhs) const
This function returns true if at least one component of this is smaller than or equal to the respective component of rhs.
bool atLeastOneComponentBiggerOrEqualThan (const GslVector &rhs) const
This function returns true if at least one component of this is bigger than or equal to the respective component of rhs.
Public Member Functions inherited from QUESO::Vector
Vector ()
Default Constructor.
Vector (const BaseEnvironment &env, const Map &map)
Shaped Constructor.
Vector (const Vector &rhs)
Copy Constructor.
virtual ~Vector ()
Virtual Destructor.
Vector & operator= (const Vector &rhs)
Operator for copying a vector.
Vector & operator*= (double a)
Operator for multiplication of the vector by a scalar.
Vector & operator/= (double a)
Operator for division of the vector by a scalar.
Vector & operator+= (const Vector &rhs)
Operator for addition (element-wise) of two vectors.
Vector & operator-= (const Vector &rhs)
Operator for subtraction (element-wise) of two vectors.
const BaseEnvironment & env () const
const Map & map () const
unsigned int numOfProcsForStorage () const
void setPrintHorizontally (bool value) const
Determines whether vector should be printed horizontally.
bool getPrintHorizontally () const
Checks if vector is printed horizontally.
void setPrintScientific (bool value) const
Determines whether vector should be printed in Scientific Notation.
bool getPrintScientific () const
Checks if the vector should be printed in Scientific Notation.
Private Member Functions
void copy (const GslVector &src)
This function copies the elements of the vector src into this.
Private Attributes
gsl_vector * m_vec
GSL vector.
Additional Inherited Members
Protected Member Functions inherited from QUESO::Vector
virtual void copy (const Vector &src)
Copies vector src to this matrix.
Protected Attributes inherited from QUESO::Vector
const BaseEnvironment & m_env
Environment variable.
const Map & m_map
Mapping variable.
bool m_printHorizontally
Flag for either or not print this matrix horizontally.
bool m_printScientific
Flag for either or not print this matrix in scientific notation.
Detailed Description
Class for vector operations using GSL library.
This class creates and provides basic support for vectors of templated type as a specialization of Vector using GSL vectors, which are defined by an encapsulated gsl_vector structure.
Definition at line 48 of file GslVector.h.
Constructor & Destructor Documentation
QUESO::GslVector::GslVector ()
Default Constructor.
Creates an empty vector of no length.
Definition at line 32 of file GslVector.C.
References QUESO::Vector::m_env, UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   Vector()
 {
   UQ_FATAL_TEST_MACRO(true,
                       m_env.worldRank(),
                       "GslVector::constructor(), default",
                       "should not be used by user");
 }
QUESO::GslVector::GslVector (const BaseEnvironment & env, const Map & map)
Definition at line 42 of file GslVector.C.
References QUESO::Vector::m_env, QUESO::Vector::m_map, m_vec, QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   Vector(env,map),
   m_vec        (gsl_vector_calloc(map.NumGlobalElements()))
 {
   //std::cout << "Entering GslVector::constructor(1)" << std::endl;
   UQ_FATAL_TEST_MACRO((m_vec == NULL),
                       m_env.worldRank(),
                       "GslVector::constructor(1)",
                       "null vector generated");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(1)",
                       "incompatible local vec size");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) map.NumGlobalElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(1)",
                       "incompatible global vec size");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) m_map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(1)",
                       "incompatible own vec size");
   //std::cout << "In GslVector::constructor(env,map)"
   //          << "\n  m_vec->size             = " << m_vec->size
   //          << "\n  map.NumGlobalElements() = " << map.NumGlobalElements()
   //          << "\n  map.NumMyElements()     = " << map.NumMyElements()
   //          << std::endl;
   //std::cout << "Leaving GslVector::constructor(1)" << std::endl;
 }
QUESO::GslVector::GslVector (const BaseEnvironment & env, const Map & map, double value)
Definition at line 78 of file GslVector.C.
References cwSet(), QUESO::Vector::m_env, QUESO::Vector::m_map, m_vec, QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   Vector(env,map),
   m_vec        (gsl_vector_calloc(map.NumGlobalElements()))
 {
   //std::cout << "Entering GslVector::constructor(2)" << std::endl;
   UQ_FATAL_TEST_MACRO((m_vec == NULL),
                       m_env.worldRank(),
                       "GslVector::constructor(2)",
                       "null vector generated");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(2)",
                       "incompatible local vec size");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) map.NumGlobalElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(2)",
                       "incompatible global vec size");
   this->cwSet(value);
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) m_map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(2)",
                       "incompatible own vec size");
   //std::cout << "Leaving GslVector::constructor(2)" << std::endl;
 }
QUESO::GslVector::GslVector (const BaseEnvironment & env, double d1, double d2, const Map & map)
Definition at line 110 of file GslVector.C.
References QUESO::Vector::m_env, QUESO::Vector::m_map, m_vec, QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   Vector(env,map),
   m_vec        (gsl_vector_calloc(map.NumGlobalElements()))
 {
   //std::cout << "Entering GslVector::constructor(3)" << std::endl;
   UQ_FATAL_TEST_MACRO((m_vec == NULL),
                       m_env.worldRank(),
                       "GslVector::constructor(3), linspace",
                       "null vector generated");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(3)",
                       "incompatible local vec size");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) map.NumGlobalElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(3)",
                       "incompatible global vec size");
   for (unsigned int i = 0; i < m_vec->size; ++i) {
     double alpha = (double) i / ((double) m_vec->size - 1.);
     (*this)[i] = (1.-alpha)*d1 + alpha*d2;
   }
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) m_map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(3)",
                       "incompatible own vec size");
   //std::cout << "Leaving GslVector::constructor(3)" << std::endl;
 }
QUESO::GslVector::GslVector (const GslVector & v, double start, double end)
Construct a vector, with length the same as v, with evenly spaced numbers from start to end, inclusive.
Definition at line 145 of file GslVector.C.
References QUESO::Vector::m_env, QUESO::Vector::m_map, m_vec, QUESO::Vector::map(), QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   Vector(v.env(),v.map()),
   m_vec        (gsl_vector_calloc(v.sizeLocal()))
 {
   //std::cout << "Entering GslVector::constructor(4)" << std::endl;
   UQ_FATAL_TEST_MACRO((m_vec == NULL),
                       m_env.worldRank(),
                       "GslVector::constructor(4), linspace",
                       "null vector generated");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) v.map().NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(4)",
                       "incompatible local vec size");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) v.map().NumGlobalElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(4)",
                       "incompatible global vec size");
   for (unsigned int i = 0; i < m_vec->size; ++i) {
     double alpha = (double) i / ((double) m_vec->size - 1.);
     (*this)[i] = (1. - alpha) * start + alpha * end;
   }
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) m_map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(4)",
                       "incompatible own vec size");
   //std::cout << "Leaving GslVector::constructor(4)" << std::endl;
 }
QUESO::GslVector::GslVector (const GslVector & y)
Definition at line 180 of file GslVector.C.
References copy(), QUESO::Vector::m_env, QUESO::Vector::m_map, m_vec, QUESO::Vector::map(), QUESO::Map::NumGlobalElements(), QUESO::Map::NumMyElements(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   :
   Vector(v.env(),v.map()),
   m_vec        (gsl_vector_calloc(v.sizeLocal()))
 {
   //std::cout << "Entering GslVector::constructor(5)" << std::endl;
   // prudenci 2010-06-17 mox
   UQ_FATAL_TEST_MACRO((m_vec == NULL),
                       m_env.worldRank(),
                       "GslVector::constructor(5), copy",
                       "null vector generated");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) v.map().NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(5)",
                       "incompatible local vec size");
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) v.map().NumGlobalElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(5)",
                       "incompatible global vec size");
   this->copy(v);
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) m_map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::constructor(5)",
                       "incompatible own vec size");
   //std::cout << "Leaving GslVector::constructor(5)" << std::endl;
 }
QUESO::GslVector::~GslVector ()
Destructor.
Definition at line 213 of file GslVector.C.
References m_vec.
 {
   if (m_vec) gsl_vector_free(m_vec);
 }
Member Function Documentation
GslVector QUESO::GslVector::abs () const
This function returns absolute value of elements in this.
Definition at line 1304 of file GslVector.C.
References sizeLocal().
Referenced by QUESO::GslMatrix::largestEigen(), and QUESO::GslMatrix::smallestEigen().
 {
   GslVector abs_of_this_vec( *this );
   unsigned int size = abs_of_this_vec.sizeLocal();
   for( unsigned int i = 0; i < size; ++i )
     {
       abs_of_this_vec[i] = std::fabs( (*this)[i] );
     }
   return abs_of_this_vec;
 }
bool QUESO::GslVector::atLeastOneComponentBiggerOrEqualThan (const GslVector & rhs) const
This function returns true if at least one component of this is bigger than or equal to the respective component of rhs.
Definition at line 1243 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO((this->sizeLocal() != rhs.sizeLocal()),
                       m_env.worldRank(),
                       "GslVector::atLeastOneComponentBiggerOrEqualThan()",
                       "vectors have different sizes");
   bool result = false;
   unsigned int i = 0;
   unsigned int size = this->sizeLocal();
   while ((i < size) && (result == false)) {
     result = ( (*this)[i] >= rhs[i] ); // prudencio 2012-02-06
     i++;
   };
   return result;
 }
bool QUESO::GslVector::atLeastOneComponentBiggerThan (const GslVector & rhs) const
This function returns true if at least one component of this is bigger than the respective component of rhs.
Definition at line 1205 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO((this->sizeLocal() != rhs.sizeLocal()),
                       m_env.worldRank(),
                       "GslVector::atLeastOneComponentBiggerThan()",
                       "vectors have different sizes");
   bool result = false;
   unsigned int i = 0;
   unsigned int size = this->sizeLocal();
   while ((i < size) && (result == false)) {
     result = ( (*this)[i] > rhs[i] );
     i++;
   };
   return result;
 }
bool QUESO::GslVector::atLeastOneComponentSmallerOrEqualThan (const GslVector & rhs) const
This function returns true if at least one component of this is smaller than or equal to the respective component of rhs.
Definition at line 1224 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO((this->sizeLocal() != rhs.sizeLocal()),
                       m_env.worldRank(),
                       "GslVector::atLeastOneComponentSmallerOrEqualThan()",
                       "vectors have different sizes");
   bool result = false;
   unsigned int i = 0;
   unsigned int size = this->sizeLocal();
   while ((i < size) && (result == false)) {
     result = ( (*this)[i] <= rhs[i] ); // prudencio 2012-02-06
     i++;
   };
   return result;
 }
bool QUESO::GslVector::atLeastOneComponentSmallerThan (const GslVector & rhs) const
This function returns true if at least one component of this is smaller than the respective component of rhs.
Definition at line 1186 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO((this->sizeLocal() != rhs.sizeLocal()),
                       m_env.worldRank(),
                       "GslVector::atLeastOneComponentSmallerThan()",
                       "vectors have different sizes");
   bool result = false;
   unsigned int i = 0;
   unsigned int size = this->sizeLocal();
   while ((i < size) && (result == false)) {
     result = ( (*this)[i] < rhs[i] );
     i++;
   };
   return result;
 }
void QUESO::GslVector::copy (const GslVector & src) private
This function copies the elements of the vector src into this.
Definition at line 329 of file GslVector.C.
References QUESO::Vector::copy(), QUESO::Vector::m_env, m_vec, UQ_FATAL_RC_MACRO, and QUESO::BaseEnvironment::worldRank().
Referenced by GslVector(), and operator=().
 {
   this->Vector::copy(src); // prudenci 2010-06-17 mox
   int iRC;
   iRC = gsl_vector_memcpy(this->m_vec, src.m_vec);
   UQ_FATAL_RC_MACRO(iRC,
                     m_env.worldRank(),
                     "GslVector::copy()",
                     "failed");
   return;
 }
void QUESO::GslVector::cwExtract (unsigned int initialPos, GslVector & vec) const
This function sets the values of this starting at position initialPos ans saves them in vector vec.
Definition at line 634 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(initialPos >= this->sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwExtract()",
                       "invalid initialPos");
   UQ_FATAL_TEST_MACRO((initialPos +vec.sizeLocal()) > this->sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwExtract()",
                       "invalid vec.sizeLocal()");
   for (unsigned int i = 0; i < vec.sizeLocal(); ++i) {
     vec[i] = (*this)[initialPos+i];
   }
   return;
 }
void QUESO::GslVector::cwInvert () virtual
This function inverts component-wise the element values of this.
Implements QUESO::Vector.
Definition at line 654 of file GslVector.C.
References sizeLocal().
Referenced by QUESO::operator/().
 {
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     (*this)[i] = 1./(*this)[i];
   }
   return;
 }
void QUESO::GslVector::cwSet (double value) virtual
Component-wise sets all values to this with value.
Implements QUESO::Vector.
Definition at line 435 of file GslVector.C.
References sizeLocal().
Referenced by QUESO::GslOptimizer::GslOptimizer(), GslVector(), and QUESO::GslMatrix::inverse().
 {
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     (*this)[i] = value;
   }
   return;
 }
void QUESO::GslVector::cwSet (unsigned int initialPos, const GslVector & vec)
This function sets the vector vec into this starting at position initialPos.
Definition at line 614 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(initialPos >= this->sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSet()",
                       "invalid initialPos");
   UQ_FATAL_TEST_MACRO((initialPos +vec.sizeLocal()) > this->sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSet()",
                       "invalid vec.sizeLocal()");
   for (unsigned int i = 0; i < vec.sizeLocal(); ++i) {
     (*this)[initialPos+i] = vec[i];
   }
   return;
 }
void QUESO::GslVector::cwSetBeta (const GslVector & alpha, const GslVector & beta)
This function returns a random variate from the beta distribution, with vector parameters alpha and beta.
Definition at line 474 of file GslVector.C.
References QUESO::RngBase::betaSample(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseEnvironment::fullRank(), QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), sizeLocal(), QUESO::BaseEnvironment::subDisplayFile(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(this->sizeLocal() != alpha.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSetBeta()",
                       "incompatible alpha size");
   UQ_FATAL_TEST_MACRO(this->sizeLocal() != beta.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSetBeta()",
                       "incompatible beta size");
   double tmpSample = 0.;
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     tmpSample = m_env.rngObject()->betaSample(alpha[i],beta[i]);
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99)) {
       *m_env.subDisplayFile() << "In GslVector::cwSetBeta()"
                               << ": fullRank "   << m_env.fullRank()
                               << ", i = "        << i
                               << ", alpha[i] = " << alpha[i]
                               << ", beta[i] = "  << beta[i]
                               << ", sample = "   << tmpSample
                               << std::endl;
     }
     if ((alpha[i] == 1. ) &&
         (beta [i] == 0.1)) {
       if (tmpSample == 1.) {
         if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 99)) {
           *m_env.subDisplayFile() << "Hitting 'sampe = 1' in GslVector::cwSetBeta()"
                                   << ": fullRank "   << m_env.fullRank()
                                   << ", i = "        << i
                                   << ", alpha[i] = " << alpha[i]
                                   << ", beta[i] = "  << beta[i]
                                   << ", sample = "   << tmpSample
                                   << std::endl;
         }
 #if 1
         std::cerr << "Hitting 'sample = 1' in GslVector::cwSetBeta()"
                   << ": fullRank "   << m_env.fullRank()
                   << ", i = "        << i
                   << ", alpha[i] = " << alpha[i]
                   << ", beta[i] = "  << beta[i]
                   << ", sample = "   << tmpSample
                   << std::endl;
         do {
           tmpSample = m_env.rngObject()->betaSample(alpha[i],beta[i]);
         } while (tmpSample == 1.);
         std::cerr << "Code was able to get 'sample != 1' in GslVector::cwSetBeta()"
                   << ": fullRank "   << m_env.fullRank()
                   << ", i = "        << i
                   << ", alpha[i] = " << alpha[i]
                   << ", beta[i] = "  << beta[i]
                   << ", sample = "   << tmpSample
                   << std::endl;
       }
 #endif
     }
     (*this)[i] = tmpSample;
   }
   return;
 }
void QUESO::GslVector::cwSetConcatenated (const GslVector & v1, const GslVector & v2)
This function concatenates GslVector v1 and GslVector v2 into this.
Definition at line 575 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(this->sizeLocal() != v1.sizeLocal() + v2.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSetConcatenated(1)",
                       "incompatible vector sizes");
   for (unsigned int i = 0; i < v1.sizeLocal(); ++i) {
     (*this)[i] = v1[i];
   }
   for (unsigned int i = 0; i < v2.sizeLocal(); ++i) {
     (*this)[v1.sizeLocal()+i] = v2[i];
   }
   return;
 }
void QUESO::GslVector::cwSetConcatenated (const std::vector< const GslVector * > & vecs)
This function concatenates vectors v1 and v2 into this vector.
Definition at line 594 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   unsigned int cummulativeSize = 0;
   for (unsigned int i = 0; i < vecs.size(); ++i) {
     GslVector tmpVec(*(vecs[i]));
     for (unsigned int j = 0; j < vecs[i]->sizeLocal(); ++j) {
       (*this)[cummulativeSize+j] = tmpVec[j];
     }
     cummulativeSize += vecs[i]->sizeLocal();
   }
   UQ_FATAL_TEST_MACRO(this->sizeLocal() != cummulativeSize,
                       m_env.worldRank(),
                       "GslVector::cwSetConcatenated(1)",
                       "incompatible vector sizes");
   return;
 }
void QUESO::GslVector::cwSetGamma (const GslVector & a, const GslVector & b)
This function returns a random variate from the gamma distribution with vector parameters a and b.
Definition at line 537 of file GslVector.C.
References QUESO::RngBase::gammaSample(), QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(this->sizeLocal() != a.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSetGamma()",
                       "incompatible a size");
   UQ_FATAL_TEST_MACRO(this->sizeLocal() != b.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSetGamma()",
                       "incompatible b size");
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = m_env.rngObject()->gammaSample(a[i],b[i]);
   }
   return;
 }
void QUESO::GslVector::cwSetGaussian (double mean, double stdDev) virtual
This function sets component-wise Gaussian random variates, with mean mean and standard deviation stdDev.
Implements QUESO::Vector.
Definition at line 446 of file GslVector.C.
References QUESO::RngBase::gaussianSample(), QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), and sizeLocal().
 {
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = mean + m_env.rngObject()->gaussianSample(stdDev);
   }
   return;
 }
void QUESO::GslVector::cwSetGaussian (const GslVector & meanVec, const GslVector & stdDevVec)
This function sets component-wise Gaussian random variates, with vectors for mean and standard deviation.
Definition at line 456 of file GslVector.C.
References QUESO::RngBase::gaussianSample(), QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), and sizeLocal().
 {
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = meanVec[i] + m_env.rngObject()->gaussianSample(stdDevVec[i]);
   }
   return;
 }
void QUESO::GslVector::cwSetInverseGamma (const GslVector & alpha, const GslVector & beta)
This function returns a random variate from the inverse gamma distribution with vector parameters alpha and beta.
Definition at line 556 of file GslVector.C.
References QUESO::RngBase::gammaSample(), QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(this->sizeLocal() != alpha.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSetInverseGamma()",
                       "incompatible alpha size");
   UQ_FATAL_TEST_MACRO(this->sizeLocal() != beta.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::cwSetInverseGamma()",
                       "incompatible beta size");
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = 1./m_env.rngObject()->gammaSample(alpha[i],1./beta[i]);
   }
   return;
 }
void QUESO::GslVector::cwSetUniform (const GslVector & aVec, const GslVector & bVec)
This function sets component-wise a number uniformly distributed in the range of elements of [aVec,bVec].
Definition at line 465 of file GslVector.C.
References QUESO::Vector::m_env, QUESO::BaseEnvironment::rngObject(), sizeLocal(), and QUESO::RngBase::uniformSample().
 {
   for (unsigned int i = 0; i < this->sizeLocal(); ++i) {
     (*this)[i] = aVec[i] + (bVec[i]-aVec[i])*m_env.rngObject()->uniformSample();
   }
   return;
 }
void QUESO::GslVector::cwSqrt ()
This function returns component-wise the square-root of this.
Definition at line 665 of file GslVector.C.
References sizeLocal().
 {
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     (*this)[i] = sqrt((*this)[i]);
   }
   return;
 }
gsl_vector * QUESO::GslVector::data () const
Definition at line 1180 of file GslVector.C.
References m_vec.
Referenced by QUESO::GslMatrix::eigen(), QUESO::GslMatrix::internalSvd(), QUESO::GslMatrix::invertMultiply(), QUESO::GslMatrix::invertMultiplyForceLU(), QUESO::GslMatrix::setColumn(), QUESO::GslMatrix::setRow(), and QUESO::GslMatrix::svdSolve().
 {
   return m_vec;
 }
double QUESO::GslVector::getMaxValue () const
Returns the maximum value in the vector this.
Definition at line 1262 of file GslVector.C.
References m_vec.
Referenced by getMaxValueAndIndex().
 {
   return gsl_vector_max( m_vec );
 }
void QUESO::GslVector::getMaxValueAndIndex (double & value, int & index)
This function returns maximum value in the vector this and its the index.
Definition at line 1286 of file GslVector.C.
References getMaxValue(), and getMaxValueIndex().
 {
   max_value = this->getMaxValue();
   max_value_index = this->getMaxValueIndex();
   return;
 }
int QUESO::GslVector::getMaxValueIndex () const
This function returns the index of the maximum value in the vector this.
Definition at line 1274 of file GslVector.C.
References m_vec.
Referenced by getMaxValueAndIndex().
 {
   return gsl_vector_max_index( m_vec );
 }
double QUESO::GslVector::getMinValue () const
Returns minimum value in the vector this.
Definition at line 1268 of file GslVector.C.
References m_vec.
Referenced by getMinValueAndIndex().
 {
   return gsl_vector_min( m_vec );
 }
void QUESO::GslVector::getMinValueAndIndex (double & value, int & index)
This function returns minimum value in the vector this and its the index.
Definition at line 1295 of file GslVector.C.
References getMinValue(), and getMinValueIndex().
 {
   min_value = this->getMinValue();
   min_value_index = this->getMinValueIndex();
   return;
 }
int QUESO::GslVector::getMinValueIndex () const
This function returns the index of the minimum value in the vector this.
Definition at line 1280 of file GslVector.C.
References m_vec.
Referenced by getMinValueAndIndex().
 {
   return gsl_vector_min_index( m_vec );
 }
void QUESO::GslVector::matlabDiff (unsigned int firstPositionToStoreDiff, double valueForRemainderPosition, GslVector & outputVec) const
Definition at line 676 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   unsigned int size = this->sizeLocal();
   UQ_FATAL_TEST_MACRO(firstPositionToStoreDiff > 1,
                       m_env.worldRank(),
                       "GslVector::matlabDiff()",
                       "invalid firstPositionToStoreDiff");
   UQ_FATAL_TEST_MACRO(size != outputVec.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::matlabDiff()",
                       "invalid size of outputVecs");
   for (unsigned int i = 0; i < (size-1); ++i) {
     outputVec[firstPositionToStoreDiff+i] = (*this)[i+1]-(*this)[i];
   }
   if (firstPositionToStoreDiff == 0) {
     outputVec[size-1] = valueForRemainderPosition;
   }
   else {
     outputVec[0] = valueForRemainderPosition;
   }
   return;
 }
void QUESO::GslVector::matlabLinearInterpExtrap (const GslVector & x1Vec, const GslVector & y1Vec, const GslVector & x2Vec)
Definition at line 707 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
Referenced by QUESO::GslMatrix::matlabLinearInterpExtrap().
 {
   UQ_FATAL_TEST_MACRO(x1Vec.sizeLocal() <= 1,
                       m_env.worldRank(),
                       "GslVector::matlabLinearInterpExtrap()",
                       "invalid 'x1' size");
   UQ_FATAL_TEST_MACRO(x1Vec.sizeLocal() != y1Vec.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::matlabLinearInterpExtrap()",
                       "invalid 'x1' and 'y1' sizes");
   UQ_FATAL_TEST_MACRO(x2Vec.sizeLocal() != this->sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::matlabLinearInterpExtrap()",
                       "invalid 'x2' and 'this' sizes");
   for (unsigned int i = 1; i < x1Vec.sizeLocal(); ++i) { // Yes, '1'
     UQ_FATAL_TEST_MACRO(x1Vec[i] <= x1Vec[i-1],
                         m_env.worldRank(),
                         "GslVector::matlabLinearInterpExtrap()",
                         "invalid 'x1' values");
   }
   for (unsigned int id2 = 0; id2 < x2Vec.sizeLocal(); ++id2) {
     double x2 = x2Vec[id2];
     unsigned int id1 = 0;
     bool found1 = false;
     for (id1 = 0; id1 < x1Vec.sizeLocal(); ++id1) {
       if (x2 <= x1Vec[id1]) {
         found1 = true;
         break;
       }
     }
     bool makeLinearModel = false;
     double xa = 0.;
     double xb = 0.;
     double ya = 0.;
     double yb = 0.;
     if (x2 == x1Vec[id1]) {
       (*this)[id2] = y1Vec[id1];
     }
     else if (x2 < x1Vec[0]) {
       // Extrapolation case
       makeLinearModel = true;
       xa = x1Vec[0];
       xb = x1Vec[1];
       ya = y1Vec[0];
       yb = y1Vec[1];
     }
     else if (found1 == true) {
       // Interpolation case
       makeLinearModel = true;
       xa = x1Vec[id1-1];
       xb = x1Vec[id1];
       ya = y1Vec[id1-1];
       yb = y1Vec[id1];
     }
     else {
       // Extrapolation case
       makeLinearModel = true;
       xa = x1Vec[x1Vec.sizeLocal()-2];
       xb = x1Vec[x1Vec.sizeLocal()-1];
       ya = y1Vec[x1Vec.sizeLocal()-2];
       yb = y1Vec[x1Vec.sizeLocal()-1];
     }
     if (makeLinearModel) {
       double rate = (yb-ya)/(xb-xa);
       (*this)[id2] = ya + (x2-xa)*rate;
     }
   }
   return;
 }
void QUESO::GslVector::mpiAllQuantile (double probability, const MpiComm & opComm, GslVector & resultVec) const
Definition at line 885 of file GslVector.C.
References QUESO::MpiComm::Bcast(), QUESO::MpiComm::Gather(), QUESO::Vector::m_env, QUESO::MpiComm::MyPID(), QUESO::MpiComm::NumProc(), RawValue_MPI_DOUBLE, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   // Filter out those nodes that should not participate
   if (opComm.MyPID() < 0) return;
   UQ_FATAL_TEST_MACRO((probability < 0.) || (1. < probability),
                       m_env.worldRank(),
                       "GslVector::mpiAllQuantile()",
                       "invalid input");
   unsigned int size = this->sizeLocal();
   UQ_FATAL_TEST_MACRO(size != resultVec.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::mpiAllQuantile()",
                       "different vector sizes");
   for (unsigned int i = 0; i < size; ++i) {
     double auxDouble = (int) (*this)[i];
     std::vector<double> vecOfDoubles(opComm.NumProc(),0.);
     opComm.Gather((void *) &auxDouble, 1, RawValue_MPI_DOUBLE, (void *) &vecOfDoubles[0], (int) 1, RawValue_MPI_DOUBLE, 0,
                   "GslVector::mpiAllQuantile()",
                   "failed MPI.Gather()");
     std::sort(vecOfDoubles.begin(), vecOfDoubles.end());
     double result = vecOfDoubles[(unsigned int)( probability*((double)(vecOfDoubles.size()-1)) )];
     opComm.Bcast((void *) &result, (int) 1, RawValue_MPI_DOUBLE, 0,
                  "GslVector::mpiAllQuantile()",
                  "failed MPI.Bcast()");
     resultVec[i] = result;
   }
   return;
 }
void QUESO::GslVector::mpiAllReduce (RawType_MPI_Op mpiOperation, const MpiComm & opComm, GslVector & resultVec) const
Definition at line 861 of file GslVector.C.
References QUESO::MpiComm::Allreduce(), QUESO::Vector::m_env, QUESO::MpiComm::MyPID(), RawValue_MPI_DOUBLE, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   // Filter out those nodes that should not participate
   if (opComm.MyPID() < 0) return;
   unsigned int size = this->sizeLocal();
   UQ_FATAL_TEST_MACRO(size != resultVec.sizeLocal(),
                       m_env.worldRank(),
                       "GslVector::mpiAllReduce()",
                       "different vector sizes");
   for (unsigned int i = 0; i < size; ++i) {
     double srcValue = (*this)[i];
     double resultValue = 0.;
     opComm.Allreduce((void *) &srcValue, (void *) &resultValue, (int) 1, RawValue_MPI_DOUBLE, mpiOperation,
                      "GslVector::mpiAllReduce()",
                      "failed MPI.Allreduce()");
     resultVec[i] = resultValue;
   }
   return;
 }
void QUESO::GslVector::mpiBcast (int srcRank, const MpiComm & bcastComm)
Definition at line 797 of file GslVector.C.
References QUESO::MpiComm::Allreduce(), QUESO::MpiComm::Barrier(), QUESO::MpiComm::Bcast(), QUESO::Vector::m_env, QUESO::MpiComm::MyPID(), QUESO::MpiComm::NumProc(), RawValue_MPI_DOUBLE, RawValue_MPI_SUM, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   // Filter out those nodes that should not participate
   if (bcastComm.MyPID() < 0) return;
   // Check 'srcRank'
   UQ_FATAL_TEST_MACRO((srcRank < 0) || (srcRank >= bcastComm.NumProc()),
                       m_env.worldRank(),
                       "GslVector::mpiBcast()",
                       "invalud srcRank");
   // Check number of participant nodes
   double localNumNodes = 1.;
   double totalNumNodes = 0.;
   bcastComm.Allreduce((void *) &localNumNodes, (void *) &totalNumNodes, (int) 1, RawValue_MPI_DOUBLE, RawValue_MPI_SUM,
                       "GslVector::mpiBcast()",
                       "failed MPI.Allreduce() for numNodes");
   UQ_FATAL_TEST_MACRO(((int) totalNumNodes) != bcastComm.NumProc(),
                       m_env.worldRank(),
                       "GslVector::mpiBcast()",
                       "inconsistent numNodes");
   // Check that all participant nodes have the same vector size
   double localVectorSize  = this->sizeLocal();
   double sumOfVectorSizes = 0.;
   bcastComm.Allreduce((void *) &localVectorSize, (void *) &sumOfVectorSizes, (int) 1, RawValue_MPI_DOUBLE, RawValue_MPI_SUM,
                       "GslVector::mpiBcast()",
                       "failed MPI.Allreduce() for vectorSize");
   if ( ((unsigned int) sumOfVectorSizes) != ((unsigned int)(totalNumNodes*localVectorSize)) ) {
     std::cerr << "rank "                 << bcastComm.MyPID()
               << ": sumOfVectorSizes = " << sumOfVectorSizes
               << ", totalNumNodes = "    << totalNumNodes
               << ", localVectorSize = "  << localVectorSize
               << std::endl;
   }
   bcastComm.Barrier();
   UQ_FATAL_TEST_MACRO(((unsigned int) sumOfVectorSizes) != ((unsigned int)(totalNumNodes*localVectorSize)),
                       m_env.worldRank(),
                       "GslVector::mpiBcast()",
                       "inconsistent vectorSize");
   // Ok, bcast data
   std::vector<double> dataBuffer((unsigned int) localVectorSize, 0.);
   if (bcastComm.MyPID() == srcRank) {
     for (unsigned int i = 0; i < dataBuffer.size(); ++i) {
       dataBuffer[i] = (*this)[i];
     }
   }
   bcastComm.Bcast((void *) &dataBuffer[0], (int) localVectorSize, RawValue_MPI_DOUBLE, srcRank,
                   "GslVector::mpiBcast()",
                   "failed MPI.Bcast()");
   if (bcastComm.MyPID() != srcRank) {
     for (unsigned int i = 0; i < dataBuffer.size(); ++i) {
       (*this)[i] = dataBuffer[i];
     }
   }
   return;
 }
double QUESO::GslVector::norm1 () const
Returns the 1-norm of the vector.
Definition at line 395 of file GslVector.C.
References sizeLocal().
 {
   double result = 0.;
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     result += fabs((*this)[i]);
   }
   return result;
 }
double QUESO::GslVector::norm2 () const
Returns the 2-norm (Euclidean norm) of the vector.
Definition at line 389 of file GslVector.C.
References norm2Sq().
Referenced by QUESO::GslMatrix::invertMultiply().
 {
   return std::sqrt(this->norm2Sq());
 }
double QUESO::GslVector::norm2Sq () const
Returns the norm of the vector, as the square root of 2-norm of this vector.
Definition at line 383 of file GslVector.C.
References QUESO::scalarProduct().
Referenced by norm2().
 {
   return scalarProduct(*this,*this);
 }
double QUESO::GslVector::normInf () const
Returns the infinity-norm (maximum norm) of the vector.
Definition at line 408 of file GslVector.C.
References sizeLocal().
 {
   double result = 0.;
   unsigned int size = this->sizeLocal();
   double aux = 0.;
   for (unsigned int i = 0; i < size; ++i) {
     aux = fabs((*this)[i]);
     if (aux > result) result = aux;
   }
   return result;
 }
GslVector & QUESO::GslVector::operator*= (double a)
Stores in this the coordinate-wise multiplication of this and a.
Definition at line 238 of file GslVector.C.
References QUESO::Vector::m_env, m_vec, UQ_FATAL_RC_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   int iRC;
   iRC = gsl_vector_scale(m_vec,a);
   UQ_FATAL_RC_MACRO(iRC,
                     m_env.worldRank(),
                     "GslVector::operator*=()",
                     "failed");
   return *this;
 }
GslVector & QUESO::GslVector::operator*= (const GslVector & rhs)
Stores in this the coordinate-wise multiplication of this with rhs.
Definition at line 258 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   unsigned int size1 = this->sizeLocal();
   unsigned int size2 = rhs.sizeLocal();
   UQ_FATAL_TEST_MACRO((size1 != size2),
                       m_env.worldRank(),
                       "GslVector::operator*=()",
                       "different sizes of this and rhs");
   for (unsigned int i = 0; i < size1; ++i) {
     (*this)[i] *= rhs[i];
   }
   return *this;
 }
GslVector & QUESO::GslVector::operator+= (const GslVector & rhs)
Stores in this the coordinate-wise addition of this and rhs.
Definition at line 292 of file GslVector.C.
References QUESO::Vector::m_env, m_vec, UQ_FATAL_RC_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   int iRC;
   iRC = gsl_vector_add(m_vec,rhs.m_vec);
   UQ_FATAL_RC_MACRO(iRC,
                     m_env.worldRank(),
                     "GslVector::operator+=()",
                     "failed");
   return *this;
 }
GslVector & QUESO::GslVector::operator-= (const GslVector & rhs)
Stores in this the coordinate-wise subtraction of this by rhs.
Definition at line 304 of file GslVector.C.
References QUESO::Vector::m_env, m_vec, UQ_FATAL_RC_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   int iRC;
   iRC = gsl_vector_sub(m_vec,rhs.m_vec);
   UQ_FATAL_RC_MACRO(iRC,
                     m_env.worldRank(),
                     "GslVector::operator-=()",
                     "failed");
   return *this;
 }
GslVector & QUESO::GslVector::operator/= (double a)
Stores in this the coordinate-wise division of this by a.
Definition at line 250 of file GslVector.C.
 {
   *this *= (1./a);
   return *this;
 }
GslVector & QUESO::GslVector::operator/= (const GslVector & rhs)
Stores in this the coordinate-wise division of this by rhs.
Definition at line 275 of file GslVector.C.
References QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   unsigned int size1 = this->sizeLocal();
   unsigned int size2 = rhs.sizeLocal();
   UQ_FATAL_TEST_MACRO((size1 != size2),
                       m_env.worldRank(),
                       "GslVector::operator/=()",
                       "different sizes of this and rhs");
   for (unsigned int i = 0; i < size1; ++i) {
     (*this)[i] /= rhs[i];
   }
   return *this;
 }
GslVector & QUESO::GslVector::operator= (const GslVector & rhs)
Copies values from vector rhs to this.
Definition at line 219 of file GslVector.C.
References copy(), QUESO::Vector::m_env, sizeLocal(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   //std::cout << "In GslVector::operator=()" // mox
   //          << ": setting size1"
   //          << std::endl;
   unsigned int size1 = this->sizeLocal();
   //std::cout << "In GslVector::operator=()" // mox
   //          << ": setting size2"
   //          << std::endl;
   unsigned int size2 = rhs.sizeLocal();
   UQ_FATAL_TEST_MACRO(size1 != size2, // mox
                       m_env.worldRank(),
                       "GslVector::operator=()",
                       "sizes are not compatible");
   this->copy(rhs);
   return *this;
 }
double & QUESO::GslVector::operator[] (unsigned int i)
Element access method (non-const).
Returns the i-th element if x[i] is specified, the expression x(i) will return the same element.
Definition at line 317 of file GslVector.C.
References m_vec.
 {
   return *gsl_vector_ptr(m_vec,i);
 }
const double & QUESO::GslVector::operator[] (unsigned int i) const
Element access method (const).
Returns the i-th element if x[i] is specified, the expression x(i) will return the same element.
Definition at line 323 of file GslVector.C.
References m_vec.
 {
   return *gsl_vector_const_ptr(m_vec,i);
 }
void QUESO::GslVector::print (std::ostream & os) const virtual
Print method. Defines the behavior of the std::ostream << operator inherited from the Object class.
Implements QUESO::Vector.
Definition at line 923 of file GslVector.C.
References QUESO::Vector::m_printHorizontally, QUESO::Vector::m_printScientific, and sizeLocal().
Referenced by QUESO::operator<<().
 {
   //std::cout << "In GslVector::print(): before sizelocal()"
   //          << std::endl;
   unsigned int size = this->sizeLocal();
   //std::cout << "In GslVector::print(): after sizelocal()"
   //          << std::endl;
   //std::cout << "In GslVector::print(): before os.flags()"
   //          << std::endl;
   std::ostream::fmtflags curr_fmt = os.flags();
   //std::cout << "In GslVector::print(): after os.flags()"
   //          << std::endl;
   if (m_printScientific) {
     unsigned int savedPrecision = os.precision();
     os.precision(16);
     if (m_printHorizontally) {
       for (unsigned int i = 0; i < size; ++i) {
         os << std::scientific << (*this)[i]
            << " ";
       }
     }
     else {
       for (unsigned int i = 0; i < size; ++i) {
         os << std::scientific << (*this)[i]
            << std::endl;
       }
     }
     os.precision(savedPrecision);
   }
   else {
     if (m_printHorizontally) {
       //std::cout << "In GslVector::print(): where expected"
       //          << std::endl;
       for (unsigned int i = 0; i < size; ++i) {
         os << std::dec << (*this)[i]
            << " ";
       }
     }
     else {
       for (unsigned int i = 0; i < size; ++i) {
         os << std::dec << (*this)[i]
            << std::endl;
       }
     }
   }
   //std::cout << "In GslVector::print(): before os.flags(curr_fmt)"
   //          << std::endl;
   os.flags(curr_fmt);
   //std::cout << "In GslVector::print(): after os.flags(curr_fmt)"
   //          << std::endl;
   return;
 }
unsigned int QUESO::GslVector::sizeGlobal () const virtual
Returns the global length of this vector.
Implements QUESO::Vector.
Definition at line 372 of file GslVector.C.
References QUESO::Vector::m_env, QUESO::Vector::m_map, m_vec, QUESO::Map::NumGlobalElements(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) m_map.NumGlobalElements(),
                       m_env.worldRank(),
                       "GslVector::sizeGlobal()",
                       "incompatible vec size");
   return m_vec->size;
 }
unsigned int QUESO::GslVector::sizeLocal () const virtual
Returns the length of this vector.
Implements QUESO::Vector.
Definition at line 343 of file GslVector.C.
References QUESO::Vector::m_env, QUESO::Vector::m_map, m_vec, QUESO::Map::NumMyElements(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
Referenced by abs(), atLeastOneComponentBiggerOrEqualThan(), atLeastOneComponentBiggerThan(), atLeastOneComponentSmallerOrEqualThan(), atLeastOneComponentSmallerThan(), cwExtract(), cwInvert(), cwSet(), cwSetBeta(), cwSetConcatenated(), cwSetGamma(), cwSetGaussian(), cwSetInverseGamma(), cwSetUniform(), cwSqrt(), QUESO::GslMatrix::eigen(), QUESO::GslMatrix::fillWithTensorProduct(), QUESO::GslMatrix::getColumn(), QUESO::GslMatrix::getRow(), QUESO::GslMatrix::GslMatrix(), QUESO::GslMatrix::invertMultiply(), QUESO::GslMatrix::invertMultiplyForceLU(), QUESO::GslMatrix::largestEigen(), QUESO::leftDiagScaling(), matlabDiff(), matlabLinearInterpExtrap(), QUESO::GslMatrix::matlabLinearInterpExtrap(), QUESO::matrixProduct(), mpiAllQuantile(), mpiAllReduce(), mpiBcast(), QUESO::GslMatrix::multiply(), norm1(), normInf(), operator*=(), operator/=(), operator=(), QUESO::operator==(), print(), QUESO::GslMatrix::rank(), QUESO::rightDiagScaling(), QUESO::scalarProduct(), QUESO::GslMatrix::setColumn(), QUESO::GslOptimizer::setInitialPoint(), QUESO::GslMatrix::setRow(), QUESO::GslMatrix::smallestEigen(), subReadContents(), subWriteContents(), sumOfComponents(), QUESO::GslMatrix::svd(), and QUESO::GslMatrix::svdSolve().
 {
   // mox
   //std::cout << "Entering GslVector::sizeLocal()"
   //          << ": &m_map = "                << &m_map
   //          << std::endl;
   //std::cout << ", m_map.NumMyElements() = " << m_map.NumMyElements()
   //          << std::endl;
   //std::cout << ", m_vec = "                 << m_vec
   //          << std::endl;
   //std::cout << ", m_vec->size = "           << m_vec->size
   //          << std::endl;
   UQ_FATAL_TEST_MACRO(m_vec->size != (unsigned int) m_map.NumMyElements(),
                       m_env.worldRank(),
                       "GslVector::sizeLocal()",
                       "incompatible vec size");
   //std::cout << "Leaving GslVector::sizeLocal()"
   //          << ": m_vec = " << m_vec
   //          << ", m_vec->size = " << m_vec->size
   //          << ", &m_map = " << &m_map
   //          << ", m_map.NumMyElements() = " << m_map.NumMyElements()
   //          << std::endl;
   return m_vec->size;
 }
void QUESO::GslVector::sort () virtual
This function sorts the elements of the vector this in ascending numerical order.
Implements QUESO::Vector.
Definition at line 789 of file GslVector.C.
References m_vec.
 {
   gsl_sort_vector(m_vec);
   return;
 }
void QUESO::GslVector::subReadContents (const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds)
Definition at line 1029 of file GslVector.C.
References QUESO::BaseEnvironment::closeFile(), QUESO::BaseEnvironment::fullRank(), QUESO::Vector::m_env, QUESO::Vector::numOfProcsForStorage(), QUESO::BaseEnvironment::openInputFile(), sizeLocal(), QUESO::BaseEnvironment::subDisplayFile(), QUESO::BaseEnvironment::subRank(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(m_env.subRank() < 0,
                       m_env.worldRank(),
                       "GslVector::subReadContents()",
                       "unexpected subRank");
   UQ_FATAL_TEST_MACRO(this->numOfProcsForStorage() > 1,
                       m_env.worldRank(),
                       "GslVector::subReadContents()",
                       "implemented just for sequential vectors for now");
   FilePtrSetStruct filePtrSet;
   if (m_env.openInputFile(fileName,
                           fileType, // "m or hdf"
                           allowedSubEnvIds,
                           filePtrSet)) {
     double subReadSize = this->sizeLocal();
     // In the logic below, the id of a line' begins with value 0 (zero)
     unsigned int idOfMyFirstLine = 1;
     unsigned int idOfMyLastLine = this->sizeLocal();
     unsigned int numParams = 1; // Yes, just '1'
     // Read number of chain positions in the file by taking care of the first line,
     // which resembles something like 'variable_name = zeros(n_positions,m_params);'
     std::string tmpString;
     // Read 'variable name' string
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Just read '" << tmpString << "'" << std::endl;
     // Read '=' sign
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Just read '" << tmpString << "'" << std::endl;
     UQ_FATAL_TEST_MACRO(tmpString != "=",
                         m_env.worldRank(),
                         "GslVector::subReadContents()",
                         "string should be the '=' sign");
     // Read 'zeros(n_positions,n_params)' string
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Just read '" << tmpString << "'" << std::endl;
     unsigned int posInTmpString = 6;
     // Isolate 'n_positions' in a string
     char nPositionsString[tmpString.size()-posInTmpString+1];
     unsigned int posInPositionsString = 0;
     do {
       UQ_FATAL_TEST_MACRO(posInTmpString >= tmpString.size(),
                           m_env.worldRank(),
                           "GslVector::subReadContents()",
                           "symbol ',' not found in first line of file");
       nPositionsString[posInPositionsString++] = tmpString[posInTmpString++];
     } while (tmpString[posInTmpString] != ',');
     nPositionsString[posInPositionsString] = '\0';
     // Isolate 'n_params' in a string
     posInTmpString++; // Avoid reading ',' char
     char nParamsString[tmpString.size()-posInTmpString+1];
     unsigned int posInParamsString = 0;
     do {
       UQ_FATAL_TEST_MACRO(posInTmpString >= tmpString.size(),
                           m_env.worldRank(),
                           "GslVector::subReadContents()",
                           "symbol ')' not found in first line of file");
       nParamsString[posInParamsString++] = tmpString[posInTmpString++];
     } while (tmpString[posInTmpString] != ')');
     nParamsString[posInParamsString] = '\0';
     // Convert 'n_positions' and 'n_params' strings to numbers
     unsigned int sizeOfVecInFile = (unsigned int) strtod(nPositionsString,NULL);
     unsigned int numParamsInFile = (unsigned int) strtod(nParamsString,   NULL);
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In GslVector::subReadContents()"
                               << ": fullRank "            << m_env.fullRank()
                               << ", sizeOfVecInFile = "   << sizeOfVecInFile
                               << ", numParamsInFile = "   << numParamsInFile
                               << ", this->sizeLocal() = " << this->sizeLocal()
                               << std::endl;
     }
     // Check if [size of vec in file] >= [requested sub vec size]
     UQ_FATAL_TEST_MACRO(sizeOfVecInFile < subReadSize,
                         m_env.worldRank(),
                         "GslVector::subReadContents()",
                         "size of vec in file is not big enough");
     // Check if [num params in file] == [num params in current vec]
     UQ_FATAL_TEST_MACRO(numParamsInFile != numParams,
                         m_env.worldRank(),
                         "GslVector::subReadContents()",
                         "number of parameters of vec in file is different than number of parameters in this vec object");
     // Code common to any core in a communicator
     unsigned int maxCharsPerLine = 64*numParams; // Up to about 60 characters to represent each parameter value
     unsigned int lineId = 0;
     while (lineId < idOfMyFirstLine) {
       filePtrSet.ifsVar->ignore(maxCharsPerLine,'\n');
       lineId++;
     };
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In GslVector::subReadContents()"
                               << ": beginning to read input actual data"
                               << std::endl;
     }
     // Take care of initial part of the first data line,
     // which resembles something like 'variable_name = [value1 value2 ...'
     // Read 'variable name' string
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Core 0 just read '" << tmpString << "'" << std::endl;
     // Read '=' sign
     *filePtrSet.ifsVar >> tmpString;
     //std::cout << "Core 0 just read '" << tmpString << "'" << std::endl;
     UQ_FATAL_TEST_MACRO(tmpString != "=",
                         m_env.worldRank(),
                         "GslVector::subReadContents()",
                         "in core 0, string should be the '=' sign");
     // Take into account the ' [' portion
     std::streampos tmpPos = filePtrSet.ifsVar->tellg();
     filePtrSet.ifsVar->seekg(tmpPos+(std::streampos)2);
     if (m_env.subDisplayFile()) {
       *m_env.subDisplayFile() << "In GslVector::subReadContents()"
                               << ": beginning to read lines with numbers only"
                               << ", lineId = " << lineId
                               << ", idOfMyFirstLine = " << idOfMyFirstLine
                               << ", idOfMyLastLine = " << idOfMyLastLine
                               << std::endl;
     }
     while (lineId <= idOfMyLastLine) {
       *filePtrSet.ifsVar >> (*this)[lineId - idOfMyFirstLine];
       lineId++;
     };
     m_env.closeFile(filePtrSet,fileType);
   }
   return;
 }
void QUESO::GslVector::subWriteContents (const std::string & varNamePrefix, const std::string & fileName, const std::string & fileType, const std::set< unsigned int > & allowedSubEnvIds) const
Definition at line 983 of file GslVector.C.
References QUESO::BaseEnvironment::closeFile(), QUESO::Vector::getPrintHorizontally(), QUESO::Vector::getPrintScientific(), QUESO::Vector::m_env, QUESO::Vector::numOfProcsForStorage(), QUESO::FilePtrSetStruct::ofsVar, QUESO::BaseEnvironment::openOutputFile(), QUESO::Vector::setPrintHorizontally(), QUESO::Vector::setPrintScientific(), sizeLocal(), QUESO::BaseEnvironment::subIdString(), QUESO::BaseEnvironment::subRank(), UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
 {
   UQ_FATAL_TEST_MACRO(m_env.subRank() < 0,
                       m_env.worldRank(),
                       "GslVector::subWriteContents()",
                       "unexpected subRank");
   UQ_FATAL_TEST_MACRO(this->numOfProcsForStorage() > 1,
                       m_env.worldRank(),
                       "GslVector::subWriteContents()",
                       "implemented just for sequential vectors for now");
   FilePtrSetStruct filePtrSet;
   if (m_env.openOutputFile(fileName,
                            fileType, // "m or hdf"
                            allowedSubEnvIds,
                            false,
                            filePtrSet)) {
     *filePtrSet.ofsVar << varNamePrefix << "_sub" << m_env.subIdString() << " = zeros(" << this->sizeLocal()
                        << ","                                                           << 1
                        << ");"
                        << std::endl;
     *filePtrSet.ofsVar << varNamePrefix << "_sub" << m_env.subIdString() << " = [";
     bool savedVectorPrintScientific   = this->getPrintScientific();
     bool savedVectorPrintHorizontally = this->getPrintHorizontally();
     this->setPrintScientific  (true);
     this->setPrintHorizontally(false);
     *filePtrSet.ofsVar << *this;
                      //<< std::endl; // No need for 'endl' because horizontally = 'false'
     this->setPrintHorizontally(savedVectorPrintHorizontally);
     this->setPrintScientific  (savedVectorPrintScientific);
     *filePtrSet.ofsVar << "];\n";
     m_env.closeFile(filePtrSet,fileType);
   }
   return;
 }
double QUESO::GslVector::sumOfComponents () const
Returns the sum of the components of the vector.
Definition at line 423 of file GslVector.C.
References sizeLocal().
 {
   double result = 0.;
   unsigned int size = this->sizeLocal();
   for (unsigned int i = 0; i < size; ++i) {
     result += (*this)[i];
   }
   return result;
 }
Member Data Documentation
gsl_vector* QUESO::GslVector::m_vec private
GSL vector.
Definition at line 245 of file GslVector.h.
Referenced by copy(), data(), getMaxValue(), getMaxValueIndex(), getMinValue(), getMinValueIndex(), GslVector(), operator*=(), operator+=(), operator-=(), operator[](), sizeGlobal(), sizeLocal(), sort(), and ~GslVector().
The documentation for this class was generated from the following files:
src/core/inc/GslVector.h
src/core/src/GslVector.C