queso-0.51.1: QUESO::BoxSubset< V, M > Class Template Reference
QUESO::BoxSubset< V, M > Class Template Reference
Class representing a subset of a vector space shaped like a hypercube.
#include <BoxSubset.h>
Public Member Functions
void print (std::ostream &os) const
Prints the volume, the minimum and the maximum values of this.
Constructor/Destructor methods
BoxSubset (const char *prefix, const VectorSpace< V, M > &vectorSpace, const V &minValues, const V &maxValues)
Shaped, default constructor.
~BoxSubset ()
Destructor.
Mathematical methods.
bool contains (const V &vec) const
Checks whether this box subset contains vector vec.
const V & minValues () const
Vector of the minimum values of the box subset.
const V & maxValues () const
Vector of the maximum values of the box subset.
Public Member Functions inherited from QUESO::VectorSubset< V, M >
VectorSubset ()
Default Constructor.
VectorSubset (const char *prefix, const VectorSpace< V, M > &vectorSpace, double volume)
Shaped constructor (with volume).
virtual ~VectorSubset ()
Destructor.
const VectorSpace< V, M > & vectorSpace () const
Vector space to which this set belongs to. See template specialization.
Public Member Functions inherited from QUESO::VectorSet< V, M >
VectorSet ()
Default Constructor.
VectorSet (const BaseEnvironment &env, const char *prefix, double volume)
Shaped constructor.
virtual ~VectorSet ()
Virtual destructor.
const BaseEnvironment & env () const
Environment. Access to private attribute m_env.
const std::string & prefix () const
Access to private attribute m_prefix.
double volume () const
Set volume; access to private attribute m_volume.
Protected Attributes
V m_minValues
Vector of templated type V to store the minimum values of the box subset class.
V m_maxValues
Vector of templated type V to store the maximum values of the box subset class.
Protected Attributes inherited from QUESO::VectorSubset< V, M >
const VectorSpace< V, M > * m_vectorSpace
Protected Attributes inherited from QUESO::VectorSet< V, M >
const BaseEnvironment & m_env
std::string m_prefix
double m_volume
Detailed Description
template<class V, class M>
class QUESO::BoxSubset< V, M >
Class representing a subset of a vector space shaped like a hypercube.
This class is determined by a collection of upper and lower limits of the hypercube. (line segment in , rectangle in , and so on).
Definition at line 41 of file BoxSubset.h.
Constructor & Destructor Documentation
template<class V, class M> QUESO::BoxSubset< V, M >::BoxSubset (const char * prefix, const VectorSpace< V, M > & vectorSpace, const V & minValues, const V & maxValues)
Shaped, default constructor.
Construct a subspace of vectorSpace, with min and max values given by the vectors minValues and maxValues, respectively. It checks for possible inconsistencies between the values stored in minValues and maxValues, and calculates the volume of the box subset, assigning it to m_volume.
Definition at line 34 of file BoxSubset.C.
References QUESO::VectorSpace< V, M >::dimLocal(), QUESO::VectorSet< V, M >::m_env, QUESO::BoxSubset< V, M >::m_maxValues, QUESO::BoxSubset< V, M >::m_minValues, QUESO::VectorSubset< V, M >::m_vectorSpace, QUESO::VectorSet< V, M >::m_volume, UQ_FATAL_TEST_MACRO, and QUESO::BaseEnvironment::worldRank().
   : VectorSubset<V,M>(prefix,vectorSpace,0.),
     m_minValues(minValues),
     m_maxValues(maxValues)
 {
   UQ_FATAL_TEST_MACRO(minValues.sizeLocal() != maxValues.sizeLocal(),
                       m_env.worldRank(),
                       "BoxSubset<V,M>::BoxSubset()",
                       "vectors 'minValues' and 'maxValues' should have the same size");
   UQ_FATAL_TEST_MACRO(minValues.sizeLocal() != vectorSpace.dimLocal(),
                       m_env.worldRank(),
                       "BoxSubset<V,M>::BoxSubset()",
                       "sizes of vectors 'minValues' and 'maxValues' should be equal to dimension of the vector space");
   for (unsigned int i = 0; i < m_vectorSpace->dimLocal(); ++i) {
     UQ_FATAL_TEST_MACRO(minValues[i] > maxValues[i],
                         m_env.worldRank(),
                         "BoxSubset<V,M>::BoxSubset()",
                         "it should happen minValue <= maxValue for all dimensions");
   }
   m_volume = 1.;
   for (unsigned int i = 0; i < m_vectorSpace->dimLocal(); ++i) {
     m_volume *= (m_maxValues[i] - m_minValues[i]);
   }
 }
template<class V , class M > QUESO::BoxSubset< V, M >::~BoxSubset ()
Destructor.
Definition at line 65 of file BoxSubset.C.
 {
 }
Member Function Documentation
template<class V, class M > bool QUESO::BoxSubset< V, M >::contains (const V & vec) const virtual
Checks whether this box subset contains vector vec.
It checks if both statements are true: 1) all components in vec are larger than m_minValues, and 2) all all components in vec are smaller than m_maxValues.
Implements QUESO::VectorSubset< V, M >.
Definition at line 71 of file BoxSubset.C.
 {
   // prudenci, 2012-09-26: allow boundary values because of 'beta' realizer, which can generate a sample with boundary value '1'
   //return (!vec.atLeastOneComponentSmallerOrEqualThan(m_minValues) &&
   //        !vec.atLeastOneComponentBiggerOrEqualThan (m_maxValues));
   return (!vec.atLeastOneComponentSmallerThan(m_minValues) &&
           !vec.atLeastOneComponentBiggerThan (m_maxValues));
 }
template<class V , class M > const V & QUESO::BoxSubset< V, M >::maxValues () const
Vector of the maximum values of the box subset.
Definition at line 88 of file BoxSubset.C.
Referenced by QUESO::BetaVectorRV< V, M >::BetaVectorRV(), QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor(), QUESO::GammaVectorRV< V, M >::GammaVectorRV(), QUESO::InstantiateIntersection(), QUESO::InverseGammaVectorRV< V, M >::InverseGammaVectorRV(), QUESO::LogNormalVectorRV< V, M >::LogNormalVectorRV(), QUESO::JeffreysVectorRealizer< V, M >::realization(), QUESO::UniformVectorRealizer< V, M >::realization(), QUESO::GammaVectorRealizer< V, M >::realization(), and QUESO::MetropolisHastingsSG< P_V, P_M >::transformInitialCovMatrixToGaussianSpace().
 {
   return m_maxValues;
 }
template<class V , class M > const V & QUESO::BoxSubset< V, M >::minValues () const
Vector of the minimum values of the box subset.
Definition at line 82 of file BoxSubset.C.
Referenced by QUESO::BetaVectorRV< V, M >::BetaVectorRV(), QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor(), QUESO::GammaVectorRV< V, M >::GammaVectorRV(), QUESO::InstantiateIntersection(), QUESO::InverseGammaVectorRV< V, M >::InverseGammaVectorRV(), QUESO::LogNormalVectorRV< V, M >::LogNormalVectorRV(), QUESO::JeffreysVectorRealizer< V, M >::realization(), QUESO::UniformVectorRealizer< V, M >::realization(), QUESO::GammaVectorRealizer< V, M >::realization(), and QUESO::MetropolisHastingsSG< P_V, P_M >::transformInitialCovMatrixToGaussianSpace().
 {
   return m_minValues;
 }
template<class V , class M > void QUESO::BoxSubset< V, M >::print (std::ostream & os) const virtual
Prints the volume, the minimum and the maximum values of this.
Reimplemented from QUESO::VectorSubset< V, M >.
Definition at line 95 of file BoxSubset.C.
 {
   os << "In BoxSubset<V,M>::print()"
      << ": m_minValues = " << m_minValues
      << ", m_maxValues = " << m_maxValues
      << ", m_volume = "    << m_volume
      << std::endl;
   return;
 }
Member Data Documentation
template<class V, class M> V QUESO::BoxSubset< V, M >::m_maxValues protected
Vector of templated type V to store the maximum values of the box subset class.
Definition at line 86 of file BoxSubset.h.
Referenced by QUESO::BoxSubset< V, M >::BoxSubset().
template<class V, class M> V QUESO::BoxSubset< V, M >::m_minValues protected
Vector of templated type V to store the minimum values of the box subset class.
Definition at line 83 of file BoxSubset.h.
Referenced by QUESO::BoxSubset< V, M >::BoxSubset().
The documentation for this class was generated from the following files:
src/basic/inc/BoxSubset.h
src/basic/src/BoxSubset.C