/*--------------------------------------------------------------------------
 *--------------------------------------------------------------------------
 *
 * Copyright (C) 2008 The PECOS Development Team
 *
 * Please see http://pecos.ices.utexas.edu for more information.
 *
 * This file is part of the QUESO Library (Quantification of Uncertainty
 * for Estimation, Simulation and Optimization).
 *
 * QUESO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QUESO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with QUESO. If not, see <http://www.gnu.org/licenses/>.
 *
 *--------------------------------------------------------------------------
 *
 * Brief description of this file:
 */
/* This is an example of how to define and run a PECOS validation cycle for a
 * thermogravimetric analysis (TGA) model
 * using QUESO classes and algorithms. The code itself is in the templated
 * routine 'uqAppl(*env)'. This routine is called right after the initialization
 * of the MPI environment and of the QUESO environment and is available in
 * file 'exTgaValidationCycle_gsl.C'.
 *
 * It is easier to understand this example after undertanding three other simpler
 * examples:
 * (1) examples/simpleStatisticalInverseProblem/src/example_main.C
 * (2) examples/simpleStatisticalForwardProblem/src/simple_sfp_example_main.C
 * (3) examples/gravity/src/gravity_main.C
 *
 * Example (1) focuses on the templated class StatisticalInverseProblem<P_V,P_M>.
 * Example (2) focuses on the templated class StatisticalForwardProblem<P_V,P_M,Q_V,Q_M>.
 * Example (3) focuses on both classes, since it uses the solution of the inverse problem
 * as input to the forward problem.
 *
 * This example with TGA uses both statistical problem templated classes, twice each in
 * fact, but it also:
 * - uses the templated class ValidationCycle<P_V,P_M,Q_V,Q_M>,
 * - reads experimental data from files in order to compute the likelihood function
 *   at candidate parameter vectors generated by the Metropolis-Hastings algorithm, and
 * - compares the qoi cdfs computed from the two statistical forward problems at
 *   the prediction scenario.
 *--------------------------------------------------------------------------
 *-------------------------------------------------------------------------- */

#include <exTgaValidationCycle_appl.h>
#include <queso/GslMatrix.h>
#include <queso/EnvironmentOptions.h>

int main(int argc, char* argv[])
{
  //************************************************
  // Initialize environment
  //************************************************
#ifdef QUESO_HAS_MPI
  MPI_Init(&argc,&argv);
#endif

  QUESO::EnvOptionsValues* envOptionsValues = NULL;
#ifdef UQ_EXAMPLES_USES_QUESO_INPUT_FILE
  UQ_FATAL_TEST_MACRO(argc != 2,
                      QUESO::UQ_UNAVAILABLE_RANK,
                      "main()",
                      "input file must be specified in command line as argv[1], just after executable argv[0]");
#ifdef QUESO_HAS_MPI
  QUESO::FullEnvironment* env = new QUESO::FullEnvironment(MPI_COMM_WORLD,argv[1],"",envOptionsValues);
#else
  QUESO::FullEnvironment* env = new QUESO::FullEnvironment(argv[1],"",envOptionsValues);
#endif

#else
  envOptionsValues = new QUESO::EnvOptionsValues();
  envOptionsValues->m_subDisplayFileName   = "outputData/display";
  envOptionsValues->m_subDisplayAllowedSet.insert(0);
  envOptionsValues->m_subDisplayAllowedSet.insert(1);
  envOptionsValues->m_displayVerbosity     = 2;
  envOptionsValues->m_seed                 = 0;

#ifdef QUESO_HAS_MPI
  QUESO::FullEnvironment* env = new QUESO::FullEnvironment(MPI_COMM_WORLD,"","",envOptionsValues);
#else
  QUESO::FullEnvironment* env = new QUESO::FullEnvironment("","",envOptionsValues);
#endif
#endif

  //************************************************
  // Run application
  //************************************************
  uqAppl<QUESO::GslVector, // type for parameter vectors
         QUESO::GslMatrix, // type for parameter matrices
         QUESO::GslVector, // type for qoi vectors
         QUESO::GslMatrix  // type for qoi matrices
        >(*env);

  //************************************************
  // Finalize environment
  //************************************************
  delete env;
  delete envOptionsValues;
#ifdef QUESO_HAS_MPI
  MPI_Finalize();
#endif
  return 0;
}
