queso-0.56.1: QUESO::ExperimentStorage< S_V, S_M, D_V, D_M > Class Template Reference
QUESO::ExperimentStorage< S_V, S_M, D_V, D_M > Class Template Reference
#include <ExperimentStorage.h>
Public Member Functions
ExperimentStorage (const VectorSpace< S_V, S_M > &scenarioSpace, unsigned int numExperiments)
~ExperimentStorage ()
void addExperiment (const S_V &scenarioVec_standard, const D_V &dataVec_transformed, const D_M &covMat_transformed_inv)
unsigned int numExperiments () const
const VectorSpace< S_V, S_M > & scenarioSpace () const
const std::vector< const S_V * > & xs_standard () const
const std::vector< unsigned int > & n_ys_transformed () const
unsigned int n_y () const
const S_V & scenarioVec_standard (unsigned int experimentId) const
const D_V & dataVec_transformed (unsigned int experimentId) const
const D_V & yVec_transformed () const
const D_M & Wy () const
const BaseEnvironment & env () const
void print (std::ostream &os) const
Private Attributes
const BaseEnvironment & m_env
const VectorSpace< S_V, S_M > & m_scenarioSpace
unsigned int m_paper_n
std::vector< unsigned int > m_paper_n_ys_transformed
unsigned int m_paper_n_y
unsigned int m_addId
std::vector< const S_V * > m_scenarioVecs_standard
std::vector< const D_V * > m_dataVecs_transformed
std::vector< const D_M * > m_covMats_transformed_inv
VectorSpace< D_V, D_M > * m_y_space
D_V * m_yVec_transformed
D_M * m_Wy
Friends
std::ostream & operator<< (std::ostream &os, const ExperimentStorage< S_V, S_M, D_V, D_M > &obj)
Detailed Description
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix>
class QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >
Definition at line 36 of file ExperimentStorage.h.
Constructor & Destructor Documentation
template<class S_V , class S_M , class D_V , class D_M > QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::ExperimentStorage (const VectorSpace< S_V, S_M > & scenarioSpace, unsigned int numExperiments)
Definition at line 32 of file ExperimentStorage.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_env, QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_paper_n, and QUESO::BaseEnvironment::subDisplayFile().
   :
   m_env                    (scenarioSpace.env()),
   m_scenarioSpace          (scenarioSpace),
   m_paper_n                (numExperiments),
   m_paper_n_ys_transformed (m_paper_n,0),
   m_paper_n_y              (0),
   m_addId                  (0),
   m_scenarioVecs_standard  (m_paper_n, (S_V*) NULL),
   m_dataVecs_transformed   (m_paper_n, (D_V*) NULL),
   m_covMats_transformed_inv(m_paper_n, (D_M*) NULL),
   m_y_space                (NULL),
   m_yVec_transformed       (NULL),
   m_Wy                     (NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering ExperimentStorage<S_V,S_M,D_V,D_M>::constructor()"
                             << "\n  m_paper_n = " << m_paper_n
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving ExperimentStorage<S_V,S_M,D_V,D_M>::constructor()"
                             << std::endl;
   }
 }
template<class S_V , class S_M , class D_V , class D_M > QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::~ExperimentStorage ()
Definition at line 62 of file ExperimentStorage.C.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering ExperimentStorage<S_V,S_M,P_V,P_M,Q_V,Q_M>::destructor()..."
                             << std::endl;
   }
   delete m_Wy;
   delete m_yVec_transformed;
   delete m_y_space;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving ExperimentStorage<S_V,S_M,P_V,P_M,Q_V,Q_M>::destructor()"
                             << std::endl;
   }
 }
Member Function Documentation
template<class S_V , class S_M , class D_V , class D_M > void QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::addExperiment (const S_V & scenarioVec_standard, const D_V & dataVec_transformed, const D_M & covMat_transformed_inv)
Definition at line 81 of file ExperimentStorage.C.
References queso_require_less_msg.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering ExperimentStorage<S_V,S_M,D_V,D_M>::addExperiment()"
                             << ": m_addId = " << m_addId
                             << "\n  scenarioVec_standard = "   << scenarioVec_standard
                             << "\n  dataVec_transformed = "    << dataVec_transformed
                             << "\n  covMat_transformed_inv = " << covMat_transformed_inv
                             << std::endl;
   }
   queso_require_less_msg(m_addId, m_paper_n, "too many adds...");
   m_scenarioVecs_standard  [m_addId] = &scenarioVec_standard;
   m_dataVecs_transformed   [m_addId] = &dataVec_transformed;
   m_covMats_transformed_inv[m_addId] = &covMat_transformed_inv;
   m_paper_n_ys_transformed[m_addId] = dataVec_transformed.sizeLocal();
   m_paper_n_y += m_paper_n_ys_transformed[m_addId];
   m_addId++;
   if (m_addId == m_paper_n) {
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
       *m_env.subDisplayFile() << "KEY In ExperimentStorage<S_V,S_M,D_V,D_M>::addExperiment()"
                               << ": m_addId = " << m_addId
                               << ", m_paper_n_y = " << m_paper_n_y
                               << std::endl;
     }
     //***********************************************************************
     // Form 'yVec_transformed', 'Wy' matrix, and compute its inverse
     //***********************************************************************
     m_y_space = new VectorSpace<D_V,D_M>(m_env, "m_y_exp_storage", m_paper_n_y, NULL),
     m_yVec_transformed = new D_V(m_y_space->zeroVector());
     m_yVec_transformed->cwSetConcatenated(m_dataVecs_transformed);
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 3)) {
       *m_env.subDisplayFile() << "In ExperimentStorage<S_V,S_M,D_V,D_M>::addExperiment()"
                               << ": populated yVec_transformed of size = " << m_yVec_transformed->sizeLocal()
                               << "\n *m_yVec_transformed = " << *m_yVec_transformed
                               << std::endl;
     }
     m_Wy = new D_M(m_y_space->zeroVector());
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
       *m_env.subDisplayFile() << "In ExperimentStorage<S_V,S_M,D_V,D_M>::addExperiment()"
                               << ": key-debug"
                               << ", m_Wy just created (not yet populated)"
                               << ", numRowsLocal = " << m_Wy->numRowsLocal()
                               << ", numCols = "      << m_Wy->numCols()
                               << std::endl;
     }
     m_Wy->fillWithBlocksDiagonally(0,0,m_covMats_transformed_inv,true,true);
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
       *m_env.subDisplayFile() << "In ExperimentStorage<S_V,S_M,D_V,D_M>::addExperiment()"
                               << ": key-debug"
                               << ", m_Wy just populated"
                               << std::endl;
     }
     if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 3)) {
       *m_env.subDisplayFile() << "In ExperimentStorage<S_V,S_M,D_V,D_M>::addExperiment()"
                               << ": m_Wy->lnDeterminant() = " << m_Wy->lnDeterminant()
                               << std::endl;
     }
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving ExperimentStorage<S_V,S_M,D_V,D_M>::addExperiment()"
                             << ": m_addId = " << m_addId
                             << std::endl;
   }
   return;
 }
template<class S_V , class S_M , class D_V , class D_M > const D_V & QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::dataVec_transformed (unsigned int experimentId) const
Definition at line 208 of file ExperimentStorage.C.
References queso_require_less_msg, and queso_require_msg.
 {
   queso_require_less_msg(experimentId, m_dataVecs_transformed.size(), "experimentId is too large");
   queso_require_msg(m_dataVecs_transformed[experimentId], "vector is NULL");
   return *(m_dataVecs_transformed[experimentId]);
 }
template<class S_V , class S_M , class D_V , class D_M > const BaseEnvironment & QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::env () const
Definition at line 237 of file ExperimentStorage.C.
 {
   return m_env;
 }
template<class S_V , class S_M , class D_V , class D_M > unsigned int QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::n_y () const
Definition at line 190 of file ExperimentStorage.C.
 {
   return m_paper_n_y;
 }
template<class S_V , class S_M , class D_V , class D_M > const std::vector< unsigned int > & QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::n_ys_transformed () const
Definition at line 183 of file ExperimentStorage.C.
Referenced by QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel().
 {
   return m_paper_n_ys_transformed;
 }
template<class S_V , class S_M , class D_V , class D_M > unsigned int QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::numExperiments () const
Definition at line 169 of file ExperimentStorage.C.
Referenced by QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel().
 {
   return m_paper_n;
 }
template<class S_V , class S_M , class D_V , class D_M > void QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::print (std::ostream & os) const
Definition at line 244 of file ExperimentStorage.C.
 {
   return;
 }
template<class S_V , class S_M , class D_V , class D_M > const VectorSpace< S_V, S_M > & QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::scenarioSpace () const
Definition at line 176 of file ExperimentStorage.C.
Referenced by QUESO::GpmsaComputerModel< S_V, S_M, D_V, D_M, P_V, P_M, Q_V, Q_M >::GpmsaComputerModel().
 {
   return m_scenarioSpace;
 }
template<class S_V , class S_M , class D_V , class D_M > const S_V & QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::scenarioVec_standard (unsigned int experimentId) const
Definition at line 197 of file ExperimentStorage.C.
References queso_require_less_msg, and queso_require_msg.
 {
   queso_require_less_msg(experimentId, m_scenarioVecs_standard.size(), "experimentId is too large");
   queso_require_msg(m_scenarioVecs_standard[experimentId], "vector is NULL");
   return *(m_scenarioVecs_standard[experimentId]);
 }
template<class S_V , class S_M , class D_V , class D_M > const D_M & QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::Wy () const
Definition at line 228 of file ExperimentStorage.C.
References queso_require_msg.
Referenced by QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo().
 {
   queso_require_msg(m_Wy, "'m_Wy' is NULL");
   return *m_Wy;
 }
template<class S_V , class S_M , class D_V , class D_M > const std::vector< const S_V * > & QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::xs_standard () const
Definition at line 162 of file ExperimentStorage.C.
Referenced by QUESO::ExperimentModel< S_V, S_M, D_V, D_M >::ExperimentModel().
 {
   return m_scenarioVecs_standard;
 }
template<class S_V , class S_M , class D_V , class D_M > const D_V & QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::yVec_transformed () const
Definition at line 219 of file ExperimentStorage.C.
References queso_require_msg.
Referenced by QUESO::GcmExperimentInfo< S_V, S_M, D_V, D_M, P_V, P_M >::GcmExperimentInfo().
 {
   queso_require_msg(m_yVec_transformed, "'m_yVec_transformed' is NULL");
   return *m_yVec_transformed;
 }
Friends And Related Function Documentation
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> std::ostream& operator<< (std::ostream & os, const ExperimentStorage< S_V, S_M, D_V, D_M > & obj) friend
Definition at line 55 of file ExperimentStorage.h.
{
     obj.print(os);
     return os;
   }
Member Data Documentation
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> unsigned int QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_addId private
Definition at line 70 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> std::vector<const D_M* > QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_covMats_transformed_inv private
Definition at line 73 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> std::vector<const D_V* > QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_dataVecs_transformed private
Definition at line 72 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> const BaseEnvironment& QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_env private
Definition at line 64 of file ExperimentStorage.h.
Referenced by QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::ExperimentStorage().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> unsigned int QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_paper_n private
Definition at line 66 of file ExperimentStorage.h.
Referenced by QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::ExperimentStorage().
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> unsigned int QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_paper_n_y private
Definition at line 68 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> std::vector<unsigned int> QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_paper_n_ys_transformed private
Definition at line 67 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> const VectorSpace<S_V,S_M>& QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_scenarioSpace private
Definition at line 65 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> std::vector<const S_V* > QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_scenarioVecs_standard private
Definition at line 71 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> D_M* QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_Wy private
Definition at line 76 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> VectorSpace<D_V,D_M>* QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_y_space private
Definition at line 74 of file ExperimentStorage.h.
template<class S_V = GslVector, class S_M = GslMatrix, class D_V = GslVector, class D_M = GslMatrix> D_V* QUESO::ExperimentStorage< S_V, S_M, D_V, D_M >::m_yVec_transformed private
Definition at line 75 of file ExperimentStorage.h.
The documentation for this class was generated from the following files:
src/gp/inc/ExperimentStorage.h
src/gp/src/ExperimentStorage.C