queso-0.56.1: ANNmin_k Class Reference
ANNmin_k Class Reference
#include <pr_queue_k.h>
Classes
struct mk_node
Public Member Functions
ANNmin_k (int max)
~ANNmin_k ()
PQKkey ANNmin_key ()
PQKkey max_key ()
PQKkey ith_smallest_key (int i)
PQKinfo ith_smallest_info (int i)
void insert (PQKkey kv, PQKinfo inf)
Private Attributes
int k
int n
mk_node * mk
Detailed Description
Definition at line 66 of file pr_queue_k.h.
Constructor & Destructor Documentation
ANNmin_k::ANNmin_k (int max) inline
Definition at line 77 of file pr_queue_k.h.
References k, mk, and n.
                 {
                         n = 0;                                          // initially no items
                         k = max;                                        // maximum number of items
                         mk = new mk_node[max+1];        // sorted array of keys
                 }
ANNmin_k::~ANNmin_k () inline
Definition at line 84 of file pr_queue_k.h.
References mk.
                 { delete [] mk; }
Member Function Documentation
PQKkey ANNmin_k::ANNmin_key () inline
Definition at line 87 of file pr_queue_k.h.
References mk, n, and PQ_NULL_KEY.
                 { return (n > 0 ? mk[0].key : PQ_NULL_KEY); }
void ANNmin_k::insert (PQKkey kv, PQKinfo inf) inline
Definition at line 99 of file pr_queue_k.h.
References ANN_FLOP, ANNmin_k::mk_node::info, k, ANNmin_k::mk_node::key, mk, and n.
Referenced by ANNkd_leaf::ann_FR_search(), ANNkd_leaf::ann_pri_search(), ANNkd_leaf::ann_search(), ANNbruteForce::annkFRSearch(), and ANNbruteForce::annkSearch().
                 {
                         register int i;
                                                                                 // slide larger values up
                         for (i = n; i > 0; i--) {
                                 if (mk[i-1].key > kv)
                                         mk[i] = mk[i-1];
                                 else
                                         break;
                         }
                         mk[i].key = kv;                         // store element here
                         mk[i].info = inf;
                         if (n < k) n++;                         // increment number of items
                         ANN_FLOP(k-i+1)                         // increment floating ops
                 }
PQKinfo ANNmin_k::ith_smallest_info (int i) inline
Definition at line 96 of file pr_queue_k.h.
References mk, n, and PQ_NULL_INFO.
Referenced by ANNbruteForce::annkFRSearch(), ANNkd_tree::annkFRSearch(), ANNkd_tree::annkPriSearch(), ANNbruteForce::annkSearch(), and ANNkd_tree::annkSearch().
                 { return (i < n ? mk[i].info : PQ_NULL_INFO); }
PQKkey ANNmin_k::ith_smallest_key (int i) inline
Definition at line 93 of file pr_queue_k.h.
References mk, n, and PQ_NULL_KEY.
Referenced by ANNbruteForce::annkFRSearch(), ANNkd_tree::annkFRSearch(), ANNkd_tree::annkPriSearch(), ANNbruteForce::annkSearch(), and ANNkd_tree::annkSearch().
                 { return (i < n ? mk[i].key : PQ_NULL_KEY); }
PQKkey ANNmin_k::max_key () inline
Definition at line 90 of file pr_queue_k.h.
References k, mk, n, and PQ_NULL_KEY.
Referenced by ANNkd_leaf::ann_pri_search(), ANNkd_leaf::ann_search(), and ANNkd_tree::annkPriSearch().
                 { return (n == k ? mk[k-1].key : PQ_NULL_KEY); }
Member Data Documentation
int ANNmin_k::k private
Definition at line 72 of file pr_queue_k.h.
Referenced by ANNmin_k(), insert(), and max_key().
mk_node* ANNmin_k::mk private
Definition at line 74 of file pr_queue_k.h.
Referenced by ANNmin_k(), ANNmin_key(), insert(), ith_smallest_info(), ith_smallest_key(), max_key(), and ~ANNmin_k().
int ANNmin_k::n private
Definition at line 73 of file pr_queue_k.h.
Referenced by ANNmin_k(), ANNmin_key(), insert(), ith_smallest_info(), ith_smallest_key(), and max_key().
The documentation for this class was generated from the following file:
src/contrib/ANN/src/pr_queue_k.h