queso-0.56.1: QUESO::InverseGammaJointPdf< V, M > Class Template Reference
QUESO::InverseGammaJointPdf< V, M > Class Template Reference
A class for handling Inverse Gamma joint PDFs.
#include <InverseGammaJointPdf.h>
Public Member Functions
Constructor/Destructor methods
InverseGammaJointPdf (const char *prefix, const VectorSet< V, M > &domainSet, const V &alpha, const V &beta)
Constructor.
~InverseGammaJointPdf ()
Destructor.
Math methods
double actualValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
Actual value of the Gamma PDF.
double lnValue (const V &domainVector, const V *domainDirection, V *gradVector, M *hessianMatrix, V *hessianEffect) const
TODO: Logarithm of the value of the Gamma PDF.
virtual void distributionMean (V &meanVector) const
Mean value of the underlying random variable.
virtual void distributionVariance (M &covMatrix) const
Covariance matrix of the underlying random variable.
double computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Computes the logarithm of the normalization factor.
Public Member Functions inherited from QUESO::BaseJointPdf< V, M >
BaseJointPdf (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseJointPdf ()
Destructor.
virtual void setNormalizationStyle (unsigned int value) const
void setLogOfNormalizationFactor (double value) const
Sets a logarithmic value to be used in the normalization factor (stored in the protected attribute m_normalizationStyle.)
virtual void print (std::ostream &os) const
Print method. Non-pure for backwards compatibility.
Public Member Functions inherited from QUESO::BaseScalarFunction< V, M >
BaseScalarFunction (const char *prefix, const VectorSet< V, M > &domainSet)
Default constructor.
virtual ~BaseScalarFunction ()
Destructor.
const VectorSet< V, M > & domainSet () const
Access to the protected attribute m_domainSet: domain set of the scalar function.
Protected Attributes
V m_alpha
V m_beta
Protected Attributes inherited from QUESO::BaseJointPdf< V, M >
unsigned int m_normalizationStyle
double m_logOfNormalizationFactor
Protected Attributes inherited from QUESO::BaseScalarFunction< V, M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< V, M > & m_domainSet
Domain set of the scalar function.
Additional Inherited Members
Protected Member Functions inherited from QUESO::BaseJointPdf< V, M >
double commonComputeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const
Common method (to the derived classes) to compute the logarithm of the normalization factor.
Detailed Description
template<class V = GslVector, class M = GslMatrix>
class QUESO::InverseGammaJointPdf< V, M >
A class for handling Inverse Gamma joint PDFs.
This class allows the mathematical definition of an Inverse Gamma Joint PDF.
Definition at line 50 of file InverseGammaJointPdf.h.
Constructor & Destructor Documentation
template<class V , class M > QUESO::InverseGammaJointPdf< V, M >::InverseGammaJointPdf (const char * prefix, const VectorSet< V, M > & domainSet, const V & alpha, const V & beta)
Constructor.
Constructs a new object of the class, given a prefix, the domain set, and the parameters alpha and beta of the Inverse Gamma PDF.
Definition at line 33 of file InverseGammaJointPdf.C.
References QUESO::BaseEnvironment::displayVerbosity(), QUESO::BaseScalarFunction< V, M >::m_env, QUESO::BaseScalarFunction< V, M >::m_prefix, and QUESO::BaseEnvironment::subDisplayFile().
   :
   BaseJointPdf<V,M>(((std::string)(prefix)+"uni").c_str(),domainSet),
   m_alpha(alpha),
   m_beta (beta)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering InverseGammaJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving InverseGammaJointPdf<V,M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class V , class M > QUESO::InverseGammaJointPdf< V, M >::~InverseGammaJointPdf ()
Destructor.
Definition at line 57 of file InverseGammaJointPdf.C.
 {
 }
Member Function Documentation
template<class V , class M > double QUESO::InverseGammaJointPdf< V, M >::actualValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
Actual value of the Gamma PDF.
This routine calls method lnValue() and returns the exponent of the returning value of such method.
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 63 of file InverseGammaJointPdf.C.
References queso_require_equal_to_msg, and queso_require_msg.
 {
   queso_require_equal_to_msg(domainVector.sizeLocal(), this->m_domainSet.vectorSpace().dimLocal(), "invalid input");
   queso_require_msg(!(domainDirection || gradVector || hessianMatrix || hessianEffect), "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   // No need to multiply by exp(m_logOfNormalizationFactor) because 'lnValue()' is called [PDF-07]
   return exp(this->lnValue(domainVector,domainDirection,gradVector,hessianMatrix,hessianEffect));
 }
template<class V , class M > double QUESO::InverseGammaJointPdf< V, M >::computeLogOfNormalizationFactor (unsigned int numSamples, bool updateFactorInternally) const virtual
Computes the logarithm of the normalization factor.
This routine calls BaseJointPdf::commonComputeLogOfNormalizationFactor().
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 135 of file InverseGammaJointPdf.C.
References QUESO::BaseJointPdf< V, M >::commonComputeLogOfNormalizationFactor().
 {
   double value = 0.;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Entering InverseGammaJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << std::endl;
   }
   value = BaseJointPdf<V,M>::commonComputeLogOfNormalizationFactor(numSamples, updateFactorInternally);
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 2)) {
     *m_env.subDisplayFile() << "Leaving InverseGammaJointPdf<V,M>::computeLogOfNormalizationFactor()"
                             << ", m_logOfNormalizationFactor = " << m_logOfNormalizationFactor
                             << std::endl;
   }
   return value;
 }
template<class V , class M > void QUESO::InverseGammaJointPdf< V, M >::distributionMean (V & meanVector) const virtual
Mean value of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 104 of file InverseGammaJointPdf.C.
References queso_assert_equal_to, and queso_assert_greater.
 {
   queso_assert_equal_to(m_alpha.sizeLocal(), m_beta.sizeLocal());
   queso_assert_equal_to(m_alpha.sizeLocal(), meanVector.sizeLocal());
   for (unsigned int i = 0; i < m_alpha.sizeLocal(); ++i) {
     queso_assert_greater(m_alpha[i], 1);
     meanVector[i] = m_beta[i] / (m_alpha[i] - 1);
   }
 }
template<class V , class M > void QUESO::InverseGammaJointPdf< V, M >::distributionVariance (M & covMatrix) const virtual
Covariance matrix of the underlying random variable.
Reimplemented from QUESO::BaseJointPdf< V, M >.
Definition at line 117 of file InverseGammaJointPdf.C.
References queso_assert_equal_to, and queso_assert_greater.
 {
   queso_assert_equal_to(m_alpha.sizeLocal(), m_beta.sizeLocal());
   queso_assert_equal_to(m_alpha.sizeLocal(), covMatrix.numCols());
   queso_assert_equal_to (covMatrix.numCols(), covMatrix.numRowsGlobal());
   covMatrix.zeroLower();
   covMatrix.zeroUpper();
   for (unsigned int i = 0; i < m_alpha.sizeLocal(); ++i) {
     queso_assert_greater(m_alpha[i], 2);
     covMatrix(i,i) = m_beta[i]*m_beta[i] / (m_alpha[i] - 1) /
                      (m_alpha[i] - 1) / (m_alpha[i] - 2);
   }
 }
template<class V , class M > double QUESO::InverseGammaJointPdf< V, M >::lnValue (const V & domainVector, const V * domainDirection, V * gradVector, M * hessianMatrix, V * hessianEffect) const virtual
TODO: Logarithm of the value of the Gamma PDF.
Todo:
: implement me!
Implements QUESO::BaseJointPdf< V, M >.
Definition at line 80 of file InverseGammaJointPdf.C.
References queso_require_msg.
 {
   queso_require_msg(!(domainDirection || gradVector || hessianMatrix || hessianEffect), "incomplete code for gradVector, hessianMatrix and hessianEffect calculations");
   double result = 0.;
   for (unsigned int i = 0; i < domainVector.sizeLocal(); ++i) {
     result -= (m_alpha[i]+1.)*log(domainVector[i]);
     result -= m_beta[i]/domainVector[i];
     if (m_normalizationStyle == 0) {
       // Code needs to be done yet
     }
   }
   result += m_logOfNormalizationFactor; // [PDF-07]
   return result;
 }
Member Data Documentation
template<class V = GslVector, class M = GslMatrix> V QUESO::InverseGammaJointPdf< V, M >::m_alpha protected
Definition at line 93 of file InverseGammaJointPdf.h.
template<class V = GslVector, class M = GslMatrix> V QUESO::InverseGammaJointPdf< V, M >::m_beta protected
Definition at line 94 of file InverseGammaJointPdf.h.
The documentation for this class was generated from the following files:
src/stats/inc/InverseGammaJointPdf.h
src/stats/src/InverseGammaJointPdf.C