queso-0.52.0: QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M > Class Template Reference
QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M > Class Template Reference
A class for exponential covariance matrices.
#include <ExponentialMatrixCovarianceFunction.h>
Public Member Functions
Constructor/Destructor methods
ExponentialMatrixCovarianceFunction (const char *prefix, const VectorSet< P_V, P_M > &basicDomainSet, const VectorSet< Q_V, Q_M > &imageSet, const Q_M &sigmas, const Q_M &as)
Default constructor.
virtual ~ExponentialMatrixCovarianceFunction ()
Virtual destructor.
Math methods
@
void covMatrix (const P_V &domainVector1, const P_V &domainVector2, Q_M &imageMatrix) const
Calculates the covariance matrix, given two parameter domains.
Public Member Functions inherited from QUESO::BaseMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >
BaseMatrixCovarianceFunction (const char *prefix, const VectorSet< P_V, P_M > &basicDomainSet, const VectorSet< Q_V, Q_M > &imageSet)
Default constructor.
virtual ~BaseMatrixCovarianceFunction ()
Virtual destructor.
const VectorSet< P_V, P_M > & basicDomainSet () const
Domain set; access to private attribute m_basicDomainSet.
Protected Attributes
Q_M * m_sigmas
Q_M * m_as
Protected Attributes inherited from QUESO::BaseMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >
const BaseEnvironment & m_env
std::string m_prefix
const VectorSet< P_V, P_M > & m_basicDomainSet
const VectorSet< Q_V, Q_M > & m_imageSet
Detailed Description
template<class P_V, class P_M, class Q_V, class Q_M>
class QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >
A class for exponential covariance matrices.
This class implements squared exponential covariance matrices of the form:
, where is the distance between two vectors, is the variance matrix and is the length scale ().
Definition at line 47 of file ExponentialMatrixCovarianceFunction.h.
Constructor & Destructor Documentation
template<class P_V , class P_M , class Q_V , class Q_M > QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::ExponentialMatrixCovarianceFunction (const char * prefix, const VectorSet< P_V, P_M > & basicDomainSet, const VectorSet< Q_V, Q_M > & imageSet, const Q_M & sigmas, const Q_M & as)
Default constructor.
Instantiates an object of the class given a prefix, the domain and image sets, the variances scale factors.
Definition at line 31 of file ExponentialMatrixCovarianceFunction.C.
References QUESO::VectorSpace< V, M >::dimLocal(), QUESO::BaseEnvironment::displayVerbosity(), QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::m_as, QUESO::BaseMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::m_env, QUESO::BaseMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::m_imageSet, QUESO::BaseMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::m_prefix, QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::m_sigmas, QUESO::BaseEnvironment::subDisplayFile(), UQ_FATAL_TEST_MACRO, QUESO::VectorSet< V, M >::vectorSpace(), and QUESO::BaseEnvironment::worldRank().
   :
   BaseMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>(prefix,basicDomainSet,imageSet),
   m_sigmas(NULL),
   m_as    (NULL)
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   m_sigmas = new Q_M(sigmas);
   m_as     = new Q_M(as);
   unsigned int matrixOrder = m_imageSet.vectorSpace().dimLocal();
   UQ_FATAL_TEST_MACRO(m_sigmas->numRowsLocal() != matrixOrder,
                       m_env.worldRank(),
                       "ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::Constructor()",
                       "m_sigmas has invalid number of rows");
   UQ_FATAL_TEST_MACRO(m_sigmas->numCols() != matrixOrder,
                       m_env.worldRank(),
                       "ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::Constructor()",
                       "m_sigmas has invalid number of columns");
   UQ_FATAL_TEST_MACRO(m_as->numRowsLocal() != matrixOrder,
                       m_env.worldRank(),
                       "ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::Constructor()",
                       "m_as has invalid number of rows");
   UQ_FATAL_TEST_MACRO(m_as->numCols() != matrixOrder,
                       m_env.worldRank(),
                       "ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::Constructor()",
                       "m_as has invalid number of columns");
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::constructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
template<class P_V , class P_M , class Q_V , class Q_M > QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::~ExponentialMatrixCovarianceFunction () virtual
Virtual destructor.
Definition at line 81 of file ExponentialMatrixCovarianceFunction.C.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::destructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
   delete m_as;
   delete m_sigmas;
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::destructor()"
                             << ": prefix = " << m_prefix
                             << std::endl;
   }
 }
Member Function Documentation
template<class P_V , class P_M , class Q_V , class Q_M > void QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::covMatrix (const P_V & domainVector1, const P_V & domainVector2, Q_M & imageMatrix) const virtual
Calculates the covariance matrix, given two parameter domains.
Implements QUESO::BaseMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >.
Definition at line 101 of file ExponentialMatrixCovarianceFunction.C.
References UQ_FATAL_TEST_MACRO.
 {
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Entering ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::covMatrix()"
                           << std::endl;
   }
   unsigned int matrixOrder = m_imageSet.vectorSpace().dimLocal();
   UQ_FATAL_TEST_MACRO(imageMatrix.numRowsLocal() != matrixOrder,
                       m_env.worldRank(),
                       "ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::covMatrix()",
                       "imageMatrix has invalid number of rows");
   UQ_FATAL_TEST_MACRO(imageMatrix.numCols() != matrixOrder,
                       m_env.worldRank(),
                       "ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::covMatrix()",
                       "imageMatrix has invalid number of columns");
   double tmpSq = -(domainVector1 - domainVector2).norm2Sq();
   for (unsigned int i = 0; i < matrixOrder; ++i) {
     for (unsigned int j = 0; j < matrixOrder; ++j) {
       double tmp = tmpSq/( (*m_sigmas)(i,j) * (*m_sigmas)(i,j) );
       imageMatrix(i,j) = (*m_as)(i,j) * std::exp(tmp);
     }
   }
   if ((m_env.subDisplayFile()) && (m_env.displayVerbosity() >= 54)) {
     *m_env.subDisplayFile() << "Leaving ExponentialMatrixCovarianceFunction<P_V,P_M,Q_V,Q_M>::covMatrix()"
                           << std::endl;
   }
   return;
 }
Member Data Documentation
template<class P_V , class P_M , class Q_V , class Q_M > Q_M* QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::m_as protected
Definition at line 76 of file ExponentialMatrixCovarianceFunction.h.
Referenced by QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::ExponentialMatrixCovarianceFunction().
template<class P_V , class P_M , class Q_V , class Q_M > Q_M* QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::m_sigmas protected
Definition at line 75 of file ExponentialMatrixCovarianceFunction.h.
Referenced by QUESO::ExponentialMatrixCovarianceFunction< P_V, P_M, Q_V, Q_M >::ExponentialMatrixCovarianceFunction().
The documentation for this class was generated from the following files:
src/stats/inc/ExponentialMatrixCovarianceFunction.h
src/stats/src/ExponentialMatrixCovarianceFunction.C